<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>42&nbsp; Two-way analysis of variance – Probabilistic Data Science for Psychology</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../_part_5/510-Partial-Correlation.html" rel="next">
<link href="../_part_5/508-One-Way-Analysis-of-Variance.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d6825770f4e37b80aa8621686b79c10e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Probabilistic Data Science for Psychology</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dirk-ostwald.github.io/"> 
<span class="menu-text">Deutsch</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Probabilistic-Data-Science-for-Psychology.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_part_5/500-General-Linear-Model.html">General linear model</a></li><li class="breadcrumb-item"><a href="../_part_5/509-Two-Way-Analysis-of-Variance.html"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Two-way analysis of variance</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_1/100-Mathematical-Foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mathematical foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/101-Language-and-Logic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Language and logic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/102-Sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Sets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/103-Sums-Products-Powers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sums, products, powers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/104-Functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/105-Sequences-Limits-Continuity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sequences, limits, continuity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/106-Differential-Calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Differential calculus</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/107-Integral-Calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Integral calculus</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/108-Vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/109-Matrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Matrices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/110-Descriptive-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_2/200-Imperative-Programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Imperative programming</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/201-Basic-Concepts-of-Computer-Science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Basic concepts of computer science</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/202-Arithmetic-and-Variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Arithmetic and variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/203-Data-Structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Data structures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/204-Vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/205-Matrices-and-Arrays.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Matrices and arrays</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/206-Lists-Dataframes-and-Tibbles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Lists, dataframes, and tibbles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/207-Data-Management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Data management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/208-Control-Structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Control structures</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_3/300-Probability-Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/301-Probability-Spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Probability spaces</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/302-Elementary-Probabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Elementary probabilities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/303-Random-Variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Random variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/304-Random-Vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Random vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/305-Expectations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Expectations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/306-Variances.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Variances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/307-Covariances.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Covariances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/308-Inequalities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inequalities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/309-Limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Limits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/310-Transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Transformations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/311-Normal-Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Normal distributions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_4/400-Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/401-Frequentist-Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Frequentist inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/402-Point-Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Point estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/403-Confidence-Intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/404-Hypothesis-Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Hypothesis tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_5/500-General-Linear-Model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General linear model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/501-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/502-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/503-Model-Formulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Model formulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/504-Parameter-Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Parameter estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/505-T-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">T-statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/506-F-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">F-statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/507-T-Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">T-tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/508-One-Way-Analysis-of-Variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">One-way analysis of variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/509-Two-Way-Analysis-of-Variance.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Two-way analysis of variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/510-Partial-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Partial correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/511-Multiple-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_7/700-Multivariate-Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multivariate inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_7/701-Multivariate-Descriptive-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Multivariate descriptive statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#application-scenario" id="toc-application-scenario" class="nav-link active" data-scroll-target="#application-scenario"><span class="header-section-number">42.1</span> Application scenario</a>
  <ul class="collapse">
  <li><a href="#main-effects-and-interactions" id="toc-main-effects-and-interactions" class="nav-link" data-scroll-target="#main-effects-and-interactions">Main effects and interactions</a></li>
  <li><a href="#application-example" id="toc-application-example" class="nav-link" data-scroll-target="#application-example">Application example</a></li>
  </ul></li>
  <li><a href="#model-formulation" id="toc-model-formulation" class="nav-link" data-scroll-target="#model-formulation"><span class="header-section-number">42.2</span> Model formulation</a>
  <ul class="collapse">
  <li><a href="#additive-two-way-anova-model" id="toc-additive-two-way-anova-model" class="nav-link" data-scroll-target="#additive-two-way-anova-model"><span class="header-section-number">42.2.1</span> Additive two-way ANOVA model</a></li>
  <li><a href="#two-way-anova-model-with-interaction" id="toc-two-way-anova-model-with-interaction" class="nav-link" data-scroll-target="#two-way-anova-model-with-interaction"><span class="header-section-number">42.2.2</span> Two-way ANOVA model with interaction</a></li>
  </ul></li>
  <li><a href="#model-estimation" id="toc-model-estimation" class="nav-link" data-scroll-target="#model-estimation"><span class="header-section-number">42.3</span> Model estimation</a></li>
  <li><a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation"><span class="header-section-number">42.4</span> Model evaluation</a>
  <ul class="collapse">
  <li><a href="#evaluation-of-main-effects-in-the-additive-2-times-2-two-way-anova-model" id="toc-evaluation-of-main-effects-in-the-additive-2-times-2-two-way-anova-model" class="nav-link" data-scroll-target="#evaluation-of-main-effects-in-the-additive-2-times-2-two-way-anova-model">Evaluation of main effects in the additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model</a></li>
  <li><a href="#evaluation-of-the-interaction-in-the-2-times-2-two-way-anova-model-with-interaction" id="toc-evaluation-of-the-interaction-in-the-2-times-2-two-way-anova-model-with-interaction" class="nav-link" data-scroll-target="#evaluation-of-the-interaction-in-the-2-times-2-two-way-anova-model-with-interaction">Evaluation of the interaction in the <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction</a></li>
  </ul></li>
  <li><a href="#literature-notes" id="toc-literature-notes" class="nav-link" data-scroll-target="#literature-notes"><span class="header-section-number">42.5</span> Literature notes</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages/edit/main/_part_5/509-Two-Way-Analysis-of-Variance.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_part_5/500-General-Linear-Model.html">General linear model</a></li><li class="breadcrumb-item"><a href="../_part_5/509-Two-Way-Analysis-of-Variance.html"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Two-way analysis of variance</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-two-way-analysis-of-variance" class="quarto-section-identifier"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Two-way analysis of variance</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="application-scenario" class="level2" data-number="42.1">
<h2 data-number="42.1" class="anchored" data-anchor-id="application-scenario"><span class="header-section-number">42.1</span> Application scenario</h2>
<p>The classical application scenario of a two-way analysis of variance (two-way ANOVA) is a randomized, fully crossed two-factor study design consisting of a univariate dependent variable measured on randomized experimental units and two independent variables, which usually each have at least two levels. In the context of analysis of variance, the independent variables are also called factors, and their values are called factor levels. In a fully crossed design, each level of one factor is combined with all levels of the other factor. The combination of two specific factor levels is called a cell of the design. Because groups of experimental units are usually assigned to the cells of a two-way ANOVA design, these cells are also often called groups or experimental conditions.</p>
<p>Specific two-factor study designs are usually named by their factor levels. An <span class="math inline">\(I \times J\)</span> study design, and its corresponding <span class="math inline">\(I \times J\)</span> two-way ANOVA, therefore implies that <span class="math inline">\(I\)</span> factor levels of the first factor, called factor A in the following, are crossed with <span class="math inline">\(J\)</span> factor levels of the second factor, called factor B in the following. The following table gives names and factor levels for some possible two-way ANOVA designs.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 15%">
<col style="width: 31%">
<col style="width: 29%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(2 \times 2\)</span> two-way ANOVA</td>
<td><span class="math inline">\(\Rightarrow\)</span></td>
<td>factor A with levels 1, 2</td>
<td>factor B with levels 1, 2</td>
</tr>
<tr class="even">
<td><span class="math inline">\(2 \times 3\)</span> two-way ANOVA</td>
<td><span class="math inline">\(\Rightarrow\)</span></td>
<td>factor A with levels 1, 2</td>
<td>factor B with levels 1, 2, 3</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(4 \times 2\)</span> two-way ANOVA</td>
<td><span class="math inline">\(\Rightarrow\)</span></td>
<td>factor A with levels 1, 2, 3, 4</td>
<td>factor B with levels 1, 2</td>
</tr>
<tr class="even">
<td><span class="math inline">\(3 \times 1\)</span> two-way ANOVA</td>
<td><span class="math inline">\(\Rightarrow\)</span></td>
<td>factor A with levels 1, 2, 3</td>
<td>factor B with level 1</td>
</tr>
</tbody>
</table>
<p>In general, <span class="math inline">\(2 \times 2\)</span> two-way ANOVA designs are very popular and make it possible to discuss the essential characteristics of two-way analysis-of-variance designs. We therefore focus largely on this case in the following. In <a href="#fig-two-way-anova-concept-and-notation" class="quarto-xref">Figure&nbsp;<span>42.1</span></a> A, we visualize the conceptual design of a <span class="math inline">\(2 \times 2\)</span> two-way ANOVA, where we denote the design cells by A1B1, A1B2, A2B1, and A2B2.</p>
<p><a href="#fig-two-way-anova-concept-and-notation" class="quarto-xref">Figure&nbsp;<span>42.1</span></a> B visualizes that a group of data points corresponds to each cell of the design. We use the following index convention: <span class="math inline">\(y_{ijk}\)</span> denotes the data value of the <span class="math inline">\(k\)</span>th experimental unit in the <span class="math inline">\(i\)</span>th level of factor A and the <span class="math inline">\(j\)</span>th level of factor B, where <span class="math inline">\(k=1,\ldots,n_{ij}\)</span> and, in the present case, <span class="math inline">\(i=1,2\)</span> and <span class="math inline">\(j=1,2\)</span>. If the number of data values <span class="math inline">\(n_{ij}\)</span> is identical in each cell, the design is again called a balanced design.</p>
<section id="main-effects-and-interactions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="main-effects-and-interactions">Main effects and interactions</h3>
<p>In two-way ANOVA designs, one is intuitively interested in main effects and interactions, which initially refer purely descriptively to the pattern of cell-specific group means.</p>
<div id="fig-two-way-anova-concept-and-notation" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-way-anova-concept-and-notation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/509-two-way-anova-concept-and-notation.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-way-anova-concept-and-notation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;42.1: Conceptual design and data notation of a <span class="math inline">\(2 \times 2\)</span> two-way ANOVA.
</figcaption>
</figure>
</div>
<p>For the case of a <span class="math inline">\(2 \times 2\)</span> two-way ANOVA, one intuitively speaks of a <em>main effect of factor A</em> if the group means differ between level 1 and level 2 of factor A, averaged across the two levels of factor B. Similarly, one speaks of a <em>main effect of factor B</em> if the group means differ between level 1 and level 2 of factor B, averaged across the two levels of factor A.</p>
<p>An <em>interaction of factors A and B</em> is present if the difference between the group means for factor A between levels 1 and 2 differs depending on level 1 or level 2 of factor B, or equivalently if the difference between the group means for factor B between levels 1 and 2 differs depending on level 1 or level 2 of factor A.</p>
<p>Main effects thus intuitively concern marginal differences, whereas interactions concern differences of differences. The presence of an interaction only says that differences between the group means for the levels of one experimental factor change as a function of the levels of the other experimental factor; it does not explain why this is the case. In other words, main effects and interactions in analysis of variance are data patterns, not scientific theories. The frequentist inferential safeguarding of these data patterns is the topic of this chapter.</p>
</section>
<section id="application-example" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="application-example">Application example</h3>
<p>As a concrete application example from intervention evaluation, we consider an analysis of BDI pre-post intervention difference values for two settings, face-to-face and online, and two variants, mindfulness and exercise, of cognitive behavioral therapy (<code>CBT</code>; <a href="#fig-two-way-anova-application-example" class="quarto-xref">Figure&nbsp;<span>42.2</span></a>). Setting is factor A with levels (1) face-to-face (<code>F2F</code>) and (2) online (<code>ONL</code>), and variant is factor B with levels (1) mindfulness (<code>MND</code>) and (2) exercise (<code>EXC</code>). Each intervention condition arising from crossing the factor levels is assigned a group of <span class="math inline">\(n_{ij}:=12\)</span> patients, and for each patient the difference between the pre-intervention and post-intervention BDI value is determined and denoted by dBDI.</p>
<div id="fig-two-way-anova-application-example" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-way-anova-application-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/509-two-way-anova-application-example.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-way-anova-application-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;42.2: Conceptual design of the application example.
</figcaption>
</figure>
</div>
<div class="cell">
<div id="tbl-two-way-anova-dbdi" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-two-way-anova-dbdi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;42.1: Pre-post BDI difference values for the factor-level combinations
</figcaption>
<div aria-describedby="tbl-two-way-anova-dbdi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Setting</th>
<th style="text-align: center;">Variant</th>
<th style="text-align: center;">dBDI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">MND</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">EXC</td>
<td style="text-align: center;">13</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-two-way-anova-dbdi" class="quarto-xref">Table&nbsp;<span>42.1</span></a> shows an example data set. Each row represents a patient, the column <code>Setting</code> denotes the level of the therapy-setting factor corresponding to this patient, and the column <code>Variant</code> denotes the corresponding level of the therapy-variant factor. The corresponding dBDI row value represents the pre-post intervention BDI difference value of the respective patient. High values indicate a strong improvement, low values indicate a rather slight improvement in depressive symptoms.</p>
<p><a href="#fig-two-way-anova-example-data-set" class="quarto-xref">Figure&nbsp;<span>42.3</span></a> shows two frequently used visualization forms for descriptive statistics, here group means and standard deviations, in <span class="math inline">\(2 \times 2\)</span> two-way ANOVA scenarios. Panel A shows the factor-level combination-specific group means and their standard deviations as a bar chart. Panel B shows the same data as a line plot with error bars. The two lines correspond to the two levels of the setting factor, F2F (dark gray line) and ONL (light gray line). The values on the x-axis correspond to the two levels of the variant factor, MND and EXC.</p>
<div id="fig-two-way-anova-example-data-set" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-way-anova-example-data-set-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/509-two-way-anova-example-data-set.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-way-anova-example-data-set-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;42.3: Visualization of the example data set as bar and line plots.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="model-formulation" class="level2" data-number="42.2">
<h2 data-number="42.2" class="anchored" data-anchor-id="model-formulation"><span class="header-section-number">42.2</span> Model formulation</h2>
<p>To discuss the special case of the GLM for the two-way ANOVA scenario, we proceed in two steps. First, we introduce the <em>additive two-way ANOVA model</em>, which can model only the main effects of the factors, but not their interaction. Correspondingly, main-effect parameters can be estimated and inferentially evaluated on the basis of this model. Second, we introduce the two-way ANOVA model with interaction, which models both the main effects of the factors and their interaction and on whose basis both main-effect and interaction parameters can be estimated and inferentially evaluated. In both cases, the central topic of model formulation, as in one-way ANOVA, is to move from an intuition for modeling the expectation parameters of the cells of the two-way ANOVA scenario to a non-overparameterized representation using effect parameters.</p>
<section id="additive-two-way-anova-model" class="level3" data-number="42.2.1">
<h3 data-number="42.2.1" class="anchored" data-anchor-id="additive-two-way-anova-model"><span class="header-section-number">42.2.1</span> Additive two-way ANOVA model</h3>
<p>In analogy to one-way ANOVA, in the additive two-way ANOVA model one wants to model the group expectation values <span class="math inline">\(\mu_{ij}\)</span>, with <span class="math inline">\(i=1,\ldots,I\)</span> for the levels of factor A and <span class="math inline">\(j=1,\ldots,J\)</span> for the levels of factor B, as the sum of a group-unspecific expectation value and the effects of the levels of factor A and factor B.</p>
<p>We denote the group-unspecific expectation parameter by <span class="math inline">\(\mu_0\)</span>, the effect of level <span class="math inline">\(i\)</span> of factor A by <span class="math inline">\(\alpha_i\)</span>, and the effect of level <span class="math inline">\(j\)</span> of factor B by <span class="math inline">\(\beta_j\)</span>; here <span class="math inline">\(\beta_j\)</span> therefore does denote the <span class="math inline">\(j\)</span>th entry of the beta-parameter vector. For example, for <span class="math inline">\(I:=J:=2\)</span> this gives <span class="math display">\[\begin{equation}
\begin{array}{l|l}
\mu_{11}:=\mu_{0}+\alpha_{1}+\beta_{1}  &amp; \mu_{12}:=\mu_{0}+\alpha_{1}+\beta_{2} \\\hline
\mu_{21}:=\mu_{0}+\alpha_{2}+\beta_{1}  &amp; \mu_{22}:=\mu_{0}+\alpha_{2}+\beta_{2}.
\end{array}
\end{equation}\]</span></p>
<p>As in one-way ANOVA, this representation of the group expectation values <span class="math inline">\(\mu_{ij}\)</span> is overparameterized. Specifically, the four expectation parameters <span class="math inline">\(\mu_{11},\mu_{12},\mu_{21},\mu_{22}\)</span> are represented by the five parameters <span class="math inline">\(\mu_0,\alpha_1,\alpha_2,\beta_1,\beta_2\)</span>. To guarantee a unique representation of the <span class="math inline">\(\mu_{ij}\)</span>, it is again natural to define the effect of the first level of each factor as zero, <span class="math display">\[\begin{equation}
\alpha_{1}:=\beta_{1}:=0,
\end{equation}\]</span> thereby establishing the factor-level combination A1B1 as the reference group. For <span class="math inline">\(I:=J:=2\)</span> this yields <span class="math display">\[\begin{equation}
\begin{array}{l|l}
\mu_{11} := \mu_{0}             &amp; \mu_{12} := \mu_{0}+\beta_{2}         \\\hline
\mu_{21} :=\mu_{0}+\alpha_{2}   &amp; \mu_{22}:=\mu_{0}+\alpha_{2}+\beta_{2}.
\end{array}
\end{equation}\]</span></p>
<p>Thus the four expectation parameters are represented by only three effect parameters, <span class="math inline">\(\mu_0,\alpha_2,\beta_2\)</span>. In this sense, the additive two-way ANOVA model is even underparameterized, which allows the introduction of an interaction parameter in the next section. As in one-way ANOVA, however, the interpretations of <span class="math inline">\(\mu_0,\alpha_2,\beta_2\)</span> change in this effect representation with reference group: <span class="math inline">\(\mu_0\)</span> is the expectation value of the factor-level combination A1B1, <span class="math inline">\(\alpha_2\)</span> is the difference when moving from level 1 to level 2 of factor A, and <span class="math inline">\(\beta_2\)</span> is the difference when moving from level 1 to level 2 of factor B.</p>
<div id="def-additive-two-way-anova-model-with-reference-group" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 42.1 (Additive two-way ANOVA model with reference group)</strong></span> Let <span class="math inline">\(y_{ijk}\)</span>, with <span class="math inline">\(i=1,\ldots,I\)</span>, <span class="math inline">\(j=1,\ldots,J\)</span>, and <span class="math inline">\(k=1,\ldots,n_{ij}\)</span>, be the random variable that models the <span class="math inline">\(k\)</span>th data point at the <span class="math inline">\(i\)</span>th level of factor A and the <span class="math inline">\(j\)</span>th level of factor B in a two-way ANOVA application scenario. Then the additive two-way ANOVA model with reference group has the structural form <span class="math display">\[\begin{equation}
y_{ijk} = \mu_{ij}+\varepsilon_{ijk} \mbox{ with }
\varepsilon_{ijk} \sim N\left(0, \sigma^{2}\right) \mbox{ i.i.d. for } i=1,\ldots,I,\ j=1,\ldots,J,\ k=1,\ldots,n_{ij},
\end{equation}\]</span> and the data distribution form <span class="math display">\[\begin{equation}
y_{ijk} \sim N\left(\mu_{ij}, \sigma^{2}\right) \mbox{ independent for } i=1,\ldots,I,\ j=1,\ldots,J,\ k=1,\ldots,n_{ij}.
\end{equation}\]</span> Within each factor-level combination <span class="math inline">\((i,j)\)</span>, the <span class="math inline">\(y_{ijk}\)</span>, <span class="math inline">\(k=1,\ldots,n_{ij}\)</span>, are identically distributed, with <span class="math display">\[\begin{equation}
\mu_{ij}:=\mu_{0}+\alpha_{i}+\beta_{j} \mbox{ for } i=1,\ldots,I,\ j=1,\ldots,J
\mbox{ and } \alpha_{1}:=\beta_{1}:=0,
\end{equation}\]</span> and <span class="math inline">\(\sigma^{2}&gt;0\)</span>.</p>
</div>
<p>We omit a general design-matrix form in <a href="#def-additive-two-way-anova-model-with-reference-group" class="quarto-xref">Definition&nbsp;<span>42.1</span></a> and consider it below only for the <span class="math inline">\(2 \times 2\)</span> special case.</p>
<p>The expressivity of the additive two-way ANOVA model is, as emphasized above, limited to representing main effects. The following parameter examples and <a href="#fig-two-way-anova-additive-examples" class="quarto-xref">Figure&nbsp;<span>42.4</span></a> illustrate this.</p>
<p><strong>Example (1).</strong> Let <span class="math inline">\(\mu_0:=1,\alpha_2:=1,\beta_2:=0\)</span>. The effect parameter for the main effect of factor A is different from zero, whereas the effect parameter for the main effect of factor B is zero. The group expectation values are <span class="math display">\[\begin{equation}
\begin{array}{l|l}
\mu_{11}=1 &amp; \mu_{12}=1 \\\hline
\mu_{21}=2 &amp; \mu_{22}=2.
\end{array}
\end{equation}\]</span></p>
<p><strong>Example (2).</strong> Let <span class="math inline">\(\mu_0:=1,\alpha_2:=0,\beta_2:=1\)</span>. The main-effect parameter for factor A is zero, whereas the main-effect parameter for factor B is different from zero. The group expectation values are <span class="math display">\[\begin{equation}
\begin{array}{l|l}
\mu_{11}=1 &amp; \mu_{12}=2 \\\hline
\mu_{21}=1 &amp; \mu_{22}=2.
\end{array}
\end{equation}\]</span></p>
<p><strong>Example (3).</strong> Let <span class="math inline">\(\mu_0:=1,\alpha_2:=1,\beta_2:=1\)</span>. The effect parameters for the main effects of both factors are different from zero. The group expectation values are <span class="math display">\[\begin{equation}
\begin{array}{l|l}
\mu_{11}=1 &amp; \mu_{12}=2 \\\hline
\mu_{21}=2 &amp; \mu_{22}=3.
\end{array}
\end{equation}\]</span></p>
<p>With respect to the line-plot form of the group expectation values of the additive two-way ANOVA, the lines corresponding to the levels of factor A are always parallel.</p>
<div id="fig-two-way-anova-additive-examples" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-way-anova-additive-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/509-two-way-anova-additive-examples.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-way-anova-additive-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;42.4: Group expectation values of example parameter scenarios in bar- and line-plot form in the additive two-way ANOVA model.
</figcaption>
</figure>
</div>
<p>For the case of a <span class="math inline">\(2 \times 2\)</span> two-way ANOVA, <a href="#def-additive-2x2-two-way-anova-model-with-reference-group" class="quarto-xref">Definition&nbsp;<span>42.2</span></a> gives the additive model with reference group including its design-matrix form.</p>
<div id="def-additive-2x2-two-way-anova-model-with-reference-group" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 42.2 (Additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with reference group)</strong></span> Let <span class="math inline">\(y_{ijk}\)</span>, with <span class="math inline">\(i=1,2\)</span>, <span class="math inline">\(j=1,2\)</span>, and <span class="math inline">\(k=1,\ldots,n_{ij}\)</span>, be the random variable that models the <span class="math inline">\(k\)</span>th data point at the <span class="math inline">\(i\)</span>th level of factor A and the <span class="math inline">\(j\)</span>th level of factor B in a <span class="math inline">\(2 \times 2\)</span> two-way ANOVA application scenario. Then, with <span class="math inline">\(\sigma^2&gt;0\)</span>, the additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with reference group has the structural form <span class="math display">\[\begin{equation}
y_{ijk} = \mu_{ij}+\varepsilon_{ijk}
\mbox{ with }
\varepsilon_{ijk} \sim N\left(0, \sigma^{2}\right)
\mbox{ i.i.d. for } i=1,2,\ j=1,2,\ k=1,\ldots,n_{ij},
\end{equation}\]</span> the data distribution form <span class="math display">\[\begin{equation}
y_{ijk} \sim N\left(\mu_{ij}, \sigma^{2}\right) \mbox{ independent for } i=1,2,\ j=1,2,\ k=1,\ldots,n_{ij},
\end{equation}\]</span> with <span class="math display">\[\begin{equation}
\mu_{ij}:=\mu_{0}+\alpha_{i}+\beta_{j} \mbox{ for } i=1,2,\ j=1,2
\mbox{ and } \alpha_{1}:=\beta_{1}:=0,
\end{equation}\]</span> as well as the design-matrix form <span class="math display">\[\begin{equation}
y \sim N\left(X\beta,\sigma^{2}I_n\right),
\end{equation}\]</span> where <span class="math display">\[\begin{equation}
y :=
\begin{pmatrix}
y_{111} \\ \vdots \\ y_{11 n_{11}} \\
y_{121} \\ \vdots \\ y_{12 n_{12}} \\
y_{211} \\ \vdots \\ y_{21 n_{21}} \\
y_{221} \\ \vdots \\ y_{22 n_{22}}
\end{pmatrix},
X =
\begin{pmatrix}
1 &amp; 0 &amp; 0 \\
\vdots &amp; \vdots &amp; \vdots \\
1 &amp; 0 &amp; 0 \\
1 &amp; 0 &amp; 1 \\
\vdots &amp; \vdots &amp; \vdots \\
1 &amp; 0 &amp; 1 \\
1 &amp; 1 &amp; 0 \\
\vdots &amp; \vdots &amp; \vdots \\
1 &amp; 1 &amp; 0 \\
1 &amp; 1 &amp; 1 \\
\vdots &amp; \vdots &amp; \vdots \\
1 &amp; 1 &amp; 1
\end{pmatrix} \in \mathbb{R}^{n \times 3},
\beta:=
\begin{pmatrix}
\mu_{0} \\
\alpha_{2} \\
\beta_{2}
\end{pmatrix} \in \mathbb{R}^{3} \mbox{ and } \sigma^{2}&gt;0.
\end{equation}\]</span></p>
</div>
</section>
<section id="two-way-anova-model-with-interaction" class="level3" data-number="42.2.2">
<h3 data-number="42.2.2" class="anchored" data-anchor-id="two-way-anova-model-with-interaction"><span class="header-section-number">42.2.2</span> Two-way ANOVA model with interaction</h3>
<p>In two-way ANOVA with interaction, one wants to model the group expectation values <span class="math inline">\(\mu_{ij}\)</span> as the sum of a group-unspecific expectation value, the effects of the levels of factor A and factor B, and the interaction of the factor levels. We denote the group-unspecific expectation parameter by <span class="math inline">\(\mu_0\)</span>, the effect of level <span class="math inline">\(i\)</span> of factor A by <span class="math inline">\(\alpha_i\)</span>, the effect of level <span class="math inline">\(j\)</span> of factor B by <span class="math inline">\(\beta_j\)</span>, and the interaction of level <span class="math inline">\(i\)</span> of factor A with level <span class="math inline">\(j\)</span> of factor B by <span class="math inline">\(\gamma_{ij}\)</span>. For <span class="math inline">\(I:=J:=2\)</span>, <span class="math display">\[\begin{equation}
\begin{array}{l|l}
\mu_{11}:=\mu_{0}+\alpha_{1}+\beta_{1}+\gamma_{11} &amp; \mu_{12}:=\mu_{0}+\alpha_{1}+\beta_{2}+\gamma_{12} \\\hline
\mu_{21}:=\mu_{0}+\alpha_{2}+\beta_{1}+\gamma_{21} &amp; \mu_{22}:=\mu_{0}+\alpha_{2}+\beta_{2}+\gamma_{22}.
\end{array}
\end{equation}\]</span></p>
<p>This representation is multiply overparameterized. To guarantee a unique representation, we define the effect of the first level of each factor and each interaction involving a first level as zero, <span class="math display">\[\begin{equation}
\alpha_{1}:=\beta_{1}:=\gamma_{i1}:=\gamma_{1j}:=0
\mbox{ for } i=1,\ldots,I,\ j=1,\ldots,J,
\end{equation}\]</span> thereby establishing A1B1 as the reference group. For <span class="math inline">\(I:=J:=2\)</span> this yields <span class="math display">\[\begin{equation}
\begin{array}{l|l}
\mu_{11}:=\mu_{0}              &amp; \mu_{12}:=\mu_{0}+\beta_{2} \\\hline
\mu_{21}:=\mu_{0}+\alpha_{2}   &amp; \mu_{22}:=\mu_{0}+\alpha_{2}+\beta_{2}+\gamma_{22}.
\end{array}
\end{equation}\]</span> The four expectation parameters are now represented by the four effect parameters <span class="math inline">\(\mu_0,\alpha_2,\beta_2,\gamma_{22}\)</span>. Here <span class="math inline">\(\gamma_{22}\)</span> is a difference of differences: it quantifies how the transition from level 1 to level 2 of factor B changes when moving from level 1 to level 2 of factor A.</p>
<div id="def-two-way-anova-model-with-interaction-and-reference-group" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 42.3 (Two-way ANOVA model with interaction and reference group)</strong></span> Let <span class="math inline">\(y_{ijk}\)</span>, with <span class="math inline">\(i=1,\ldots,I\)</span>, <span class="math inline">\(j=1,\ldots,J\)</span>, and <span class="math inline">\(k=1,\ldots,n_{ij}\)</span>, be the random variable that models the <span class="math inline">\(k\)</span>th data point at the <span class="math inline">\(i\)</span>th level of factor A and the <span class="math inline">\(j\)</span>th level of factor B in a two-way ANOVA application scenario. Then the two-way ANOVA model with interaction and reference group has the structural form <span class="math display">\[\begin{equation}
y_{ijk}=\mu_{ij}+\varepsilon_{ijk}
\mbox{ with }
\varepsilon_{ijk} \sim N\left(0,\sigma^{2}\right)
\mbox{ i.i.d. for } i=1,\ldots,I,\ j=1,\ldots,J,\ k=1,\ldots,n_{ij},
\end{equation}\]</span> the data distribution form <span class="math display">\[\begin{equation}
y_{ijk} \sim N\left(\mu_{ij},\sigma^{2}\right)
\mbox{ independent for } i=1,\ldots,I,\ j=1,\ldots,J,\ k=1,\ldots,n_{ij},
\end{equation}\]</span> with <span class="math display">\[\begin{equation}
\mu_{ij}:=\mu_{0}+\alpha_{i}+\beta_{j}+\gamma_{ij},
\end{equation}\]</span> <span class="math display">\[\begin{equation}
\alpha_{1}:=\beta_{1}:=\gamma_{i1}:=\gamma_{1j}:=0
\mbox{ for } i=1,\ldots,I,\ j=1,\ldots,J,
\end{equation}\]</span> and <span class="math inline">\(\sigma^{2}&gt;0\)</span>.</p>
</div>
<p>The expressivity of the two-way ANOVA model with interaction corresponds to the consideration of main effects and interaction as discussed in the introduction. The following parameter examples and <a href="#fig-two-way-anova-interaction-examples" class="quarto-xref">Figure&nbsp;<span>42.5</span></a> illustrate this.</p>
<p><strong>Example (1).</strong> Let <span class="math inline">\(\mu_0:=1,\alpha_2:=0,\beta_2:=0,\gamma_{22}=2\)</span>. The main effects are zero, but the interaction effect is positive. The group expectation values are <span class="math inline">\((1,1,1,3)\)</span>.</p>
<p><strong>Example (2).</strong> Let <span class="math inline">\(\mu_0:=1,\alpha_2:=1,\beta_2:=1,\gamma_{22}=-2\)</span>. Both main effects are positive and the interaction effect is negative. The group expectation values are <span class="math inline">\((1,2,2,1)\)</span>.</p>
<p><strong>Example (3).</strong> Let <span class="math inline">\(\mu_0:=1,\alpha_2:=1,\beta_2:=0,\gamma_{22}=1\)</span>. The effect parameter for factor A is positive, the one for factor B is zero, and the interaction effect is positive. The group expectation values are <span class="math inline">\((1,1,2,3)\)</span>.</p>
<p><strong>Example (4).</strong> Let <span class="math inline">\(\mu_0:=1,\alpha_2:=0,\beta_2:=1,\gamma_{22}=1\)</span>. The effect parameter for factor A is zero, the one for factor B is positive, and the interaction effect is positive. The group expectation values are <span class="math inline">\((1,2,1,3)\)</span>.</p>
<p>The examples show that the expressivity of two-way ANOVA with interaction is much higher than the expressivity of the purely additive model. In the line-plot visualization, a nonzero interaction term implies nonparallel lines.</p>
<div id="fig-two-way-anova-interaction-examples" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-way-anova-interaction-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/509-two-way-anova-interaction-examples.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-way-anova-interaction-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;42.5: Group expectation values of example parameter scenarios in bar- and line-plot form in the two-way ANOVA model with interaction.
</figcaption>
</figure>
</div>
<div id="def-2x2-two-way-anova-model-with-interaction-and-reference-group" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 42.4 (<span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction and reference group)</strong></span> Let <span class="math inline">\(y_{ijk}\)</span>, with <span class="math inline">\(i=1,2\)</span>, <span class="math inline">\(j=1,2\)</span>, and <span class="math inline">\(k=1,\ldots,n_{ij}\)</span>, be the random variable that models the <span class="math inline">\(k\)</span>th data point at the <span class="math inline">\(i\)</span>th level of factor A and the <span class="math inline">\(j\)</span>th level of factor B in a <span class="math inline">\(2 \times 2\)</span> two-way ANOVA application scenario. Then the <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction and reference group has the structural and data distribution forms stated above, and, for <span class="math inline">\(n:=\sum_{i=1}^{2}\sum_{j=1}^{2} n_{ij}\)</span>, the design-matrix form <span class="math display">\[\begin{equation}
y \sim N\left(X\beta,\sigma^{2}I_n\right),
\end{equation}\]</span> with <span class="math display">\[\begin{equation}
X =
\begin{pmatrix}
1 &amp; 0 &amp; 0 &amp; 0 \\
\vdots &amp; \vdots &amp; \vdots &amp; \vdots \\
1 &amp; 0 &amp; 0 &amp; 0 \\
1 &amp; 0 &amp; 1 &amp; 0 \\
\vdots &amp; \vdots &amp; \vdots &amp; \vdots \\
1 &amp; 0 &amp; 1 &amp; 0 \\
1 &amp; 1 &amp; 0 &amp; 0 \\
\vdots &amp; \vdots &amp; \vdots &amp; \vdots \\
1 &amp; 1 &amp; 0 &amp; 0 \\
1 &amp; 1 &amp; 1 &amp; 1 \\
\vdots &amp; \vdots &amp; \vdots &amp; \vdots \\
1 &amp; 1 &amp; 1 &amp; 1
\end{pmatrix} \in \mathbb{R}^{n \times 4},
\beta :=
\begin{pmatrix}
\mu_{0} \\
\alpha_{2} \\
\beta_{2} \\
\gamma_{22}
\end{pmatrix} \in \mathbb{R}^{4},\quad \sigma^{2}&gt;0.
\end{equation}\]</span></p>
</div>
<p>For <span class="math inline">\(n_{ij}:=4\)</span>, the design matrix has 16 rows and the four columns shown in <a href="#def-2x2-two-way-anova-model-with-interaction-and-reference-group" class="quarto-xref">Definition&nbsp;<span>42.4</span></a>. The following <strong>R</strong> code realizes data in this example.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(MASS)                                                                    <span class="co"># multivariate normal distribution</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>I      <span class="ot">=</span> <span class="dv">2</span>                                                                       <span class="co"># number of levels of factor A</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>J      <span class="ot">=</span> <span class="dv">2</span>                                                                       <span class="co"># number of levels of factor B</span></span>
<span id="cb1-4"><a href="#cb1-4"></a>n_ij   <span class="ot">=</span> <span class="dv">4</span>                                                                       <span class="co"># number of data points in each cell</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>n      <span class="ot">=</span> I<span class="sc">*</span>J<span class="sc">*</span>n_ij                                                                <span class="co"># number of data points</span></span>
<span id="cb1-6"><a href="#cb1-6"></a>p      <span class="ot">=</span> <span class="dv">1</span> <span class="sc">+</span> (I<span class="dv">-1</span>)<span class="sc">+</span>(J<span class="dv">-1</span>)<span class="sc">+</span>(I<span class="sc">*</span>J<span class="dv">-3</span>)                                                 <span class="co"># number of parameters</span></span>
<span id="cb1-7"><a href="#cb1-7"></a>Dmat   <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,                                                       <span class="co"># prototypical design matrix for balanced designs</span></span>
<span id="cb1-8"><a href="#cb1-8"></a>                  <span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb1-9"><a href="#cb1-9"></a>                  <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,</span>
<span id="cb1-10"><a href="#cb1-10"></a>                  <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb1-11"><a href="#cb1-11"></a>                <span class="at">nrow  =</span> p,</span>
<span id="cb1-12"><a href="#cb1-12"></a>                <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-13"><a href="#cb1-13"></a>C      <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n_ij),<span class="at">nrow =</span> n_ij)                                         <span class="co"># prototypical cell vector</span></span>
<span id="cb1-14"><a href="#cb1-14"></a>X      <span class="ot">=</span> <span class="fu">kronecker</span>(Dmat,C)                                                       <span class="co"># Kronecker-product design matrix</span></span>
<span id="cb1-15"><a href="#cb1-15"></a>I_n    <span class="ot">=</span> <span class="fu">diag</span>(n)                                                                 <span class="co"># n x n identity matrix</span></span>
<span id="cb1-16"><a href="#cb1-16"></a>beta   <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">nrow =</span> p)                                            <span class="co"># beta = (mu_0,alpha_2,beta_2,gamma_22)</span></span>
<span id="cb1-17"><a href="#cb1-17"></a>sigsqr <span class="ot">=</span> <span class="dv">10</span>                                                                      <span class="co"># sigma^2</span></span>
<span id="cb1-18"><a href="#cb1-18"></a>y      <span class="ot">=</span> <span class="fu">mvrnorm</span>(<span class="dv">1</span>, X <span class="sc">%*%</span> beta, sigsqr<span class="sc">*</span>I_n)                                      <span class="co"># one realization</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="model-estimation" class="level2" data-number="42.3">
<h2 data-number="42.3" class="anchored" data-anchor-id="model-estimation"><span class="header-section-number">42.3</span> Model estimation</h2>
<p>We now consider beta-parameter estimators in the additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with reference group and in the <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction and reference group. The estimators for the beta-parameter components turn out to be weighted sums of the group-specific sample means. For simplicity, we assume balanced designs.</p>
<div id="thm-beta-parameter-estimation-in-additive-2x2-two-way-anova-model-with-reference-group" class="theorem">
<p><span class="theorem-title"><strong>Theorem 42.1 (Beta-parameter estimation in the additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with reference group)</strong></span> Let the design-matrix form of a balanced additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with reference group be given. Then the beta-parameter estimator is <span class="math display">\[\begin{equation}
\hat{\beta} :=
\begin{pmatrix}
\hat{\mu}_{0} \\
\hat{\alpha}_{2} \\
\hat{\beta}_{2}
\end{pmatrix}
=
\begin{pmatrix}
\frac{3}{4} \bar{y}_{11}+\frac{1}{4}\left(\bar{y}_{12}+\bar{y}_{21}\right)-\frac{1}{4} \bar{y}_{22} \\
\frac{1}{2}\left(\bar{y}_{21}+\bar{y}_{22}\right)-\frac{1}{2}\left(\bar{y}_{11}+\bar{y}_{12}\right) \\
\frac{1}{2}\left(\bar{y}_{12}+\bar{y}_{22}\right)-\frac{1}{2}\left(\bar{y}_{11}+\bar{y}_{21}\right)
\end{pmatrix},
\end{equation}\]</span> where <span class="math display">\[\begin{equation}
\bar{y}_{ij}:=\frac{1}{n_{ij}} \sum_{k=1}^{n_{ij}} y_{ijk}
\end{equation}\]</span> denotes the sample mean of the <span class="math inline">\((i,j)\)</span>th group of the <span class="math inline">\(2 \times 2\)</span> design.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>The result follows from the GLM beta-parameter estimator <span class="math inline">\(\hat{\beta}=(X^TX)^{-1}X^Ty\)</span>. For the balanced additive <span class="math inline">\(2 \times 2\)</span> design, <span class="math display">\[\begin{equation}
X^{T}X =
n_{ij}
\begin{pmatrix}
4 &amp; 2 &amp; 2 \\
2 &amp; 2 &amp; 1 \\
2 &amp; 1 &amp; 2
\end{pmatrix},
\quad
\left(X^{T}X\right)^{-1}
=
\frac{1}{n_{ij}}
\begin{pmatrix}
\frac{3}{4} &amp; -\frac{1}{2} &amp; -\frac{1}{2} \\
-\frac{1}{2} &amp; 1 &amp; 0 \\
-\frac{1}{2} &amp; 0 &amp; 1
\end{pmatrix},
\end{equation}\]</span> and multiplication with <span class="math inline">\(X^Ty\)</span> yields the stated weighted sums of cell means.</p>
</div>
<p><strong>Example.</strong> The following <strong>R</strong> code illustrates the relation between beta-parameter estimator components and group-specific sample means in the example data set.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># data reformatting</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>D          <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/509-two-way-analysis-of-variance.csv"</span>)            <span class="co"># data set</span></span>
<span id="cb2-3"><a href="#cb2-3"></a>A1B1       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"F2F"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"MND"</span> ]                    <span class="co"># face-to-face, mindfulness</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>A1B2       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"F2F"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"EXC"</span> ]                    <span class="co"># face-to-face, exercise</span></span>
<span id="cb2-5"><a href="#cb2-5"></a>A2B1       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"ONL"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"MND"</span> ]                    <span class="co"># online, mindfulness</span></span>
<span id="cb2-6"><a href="#cb2-6"></a>A2B2       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"ONL"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"EXC"</span> ]                    <span class="co"># online, exercise</span></span>
<span id="cb2-7"><a href="#cb2-7"></a></span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="co"># data matrix for group means</span></span>
<span id="cb2-9"><a href="#cb2-9"></a>n_ij       <span class="ot">=</span> <span class="fu">length</span>(A1B1)                                                        <span class="co"># number of data points per group</span></span>
<span id="cb2-10"><a href="#cb2-10"></a>Y          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(A1B1,A1B2,A2B1,A2B2), <span class="at">nrow =</span> n_ij)                         <span class="co"># data matrix</span></span>
<span id="cb2-11"><a href="#cb2-11"></a>bar_y      <span class="ot">=</span> <span class="fu">colMeans</span>(Y)                                                         <span class="co"># cell means</span></span>
<span id="cb2-12"><a href="#cb2-12"></a></span>
<span id="cb2-13"><a href="#cb2-13"></a><span class="co"># model estimation</span></span>
<span id="cb2-14"><a href="#cb2-14"></a>I          <span class="ot">=</span> <span class="dv">2</span>                                                                   <span class="co"># number of levels of factor A</span></span>
<span id="cb2-15"><a href="#cb2-15"></a>J          <span class="ot">=</span> <span class="dv">2</span>                                                                   <span class="co"># number of levels of factor B</span></span>
<span id="cb2-16"><a href="#cb2-16"></a>n          <span class="ot">=</span> I<span class="sc">*</span>J<span class="sc">*</span>n_ij                                                            <span class="co"># number of data points</span></span>
<span id="cb2-17"><a href="#cb2-17"></a>p          <span class="ot">=</span> <span class="dv">1</span> <span class="sc">+</span> (I<span class="dv">-1</span>)<span class="sc">+</span>(J<span class="dv">-1</span>)<span class="sc">+</span>(I<span class="sc">*</span>J<span class="dv">-3</span>)                                             <span class="co"># number of parameters</span></span>
<span id="cb2-18"><a href="#cb2-18"></a>Dmat       <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,                                                     <span class="co"># prototypical design matrix</span></span>
<span id="cb2-19"><a href="#cb2-19"></a>                      <span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,</span>
<span id="cb2-20"><a href="#cb2-20"></a>                      <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb2-21"><a href="#cb2-21"></a>                      <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">nrow =</span> p, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-22"><a href="#cb2-22"></a>C          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n_ij),<span class="at">nrow =</span> n_ij)                                     <span class="co"># prototypical cell vector</span></span>
<span id="cb2-23"><a href="#cb2-23"></a>X          <span class="ot">=</span> <span class="fu">kronecker</span>(Dmat,C)                                                   <span class="co"># Kronecker-product design matrix</span></span>
<span id="cb2-24"><a href="#cb2-24"></a>y          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(A1B1,A1B2,A2B1,A2B2), <span class="at">nrow =</span> n)                            <span class="co"># data vector</span></span>
<span id="cb2-25"><a href="#cb2-25"></a>beta_hat   <span class="ot">=</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y                                    <span class="co"># beta-parameter estimator</span></span>
<span id="cb2-26"><a href="#cb2-26"></a>eps_hat    <span class="ot">=</span> y <span class="sc">-</span> X <span class="sc">%*%</span> beta_hat                                                  <span class="co"># residual vector</span></span>
<span id="cb2-27"><a href="#cb2-27"></a>sigsqr_hat <span class="ot">=</span> (<span class="fu">t</span>(eps_hat) <span class="sc">%*%</span> eps_hat) <span class="sc">/</span>(n<span class="sc">-</span>p)                                     <span class="co"># variance-parameter estimator</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>hat{beta}                                                :  10.15 5.29 0.04 
hat{sigsqr}                                              :  6.07 
bar{y}_11,bar{y}_12,bar{y}_21,bar{y}_22                  :  10.5 9.83 15.08 15.83 
3/4bar{y}_11 + 1/4(bar{y}_12 + bar{y}_21) - 1/4bar{y}_22 :  10.15 
1/2(bar{y}_21 + bar{y}_22) - 1/2(bar{y}_11 + bar{y}_12)  :  5.29 
1/2(bar{y}_12 + bar{y}_22) - 1/2(bar{y}_11 + bar{y}_21)  :  0.04</code></pre>
</div>
</div>
<div id="thm-beta-parameter-estimation-in-2x2-two-way-anova-model-with-interaction-and-reference-group" class="theorem">
<p><span class="theorem-title"><strong>Theorem 42.2 (Beta-parameter estimation in the <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction and reference group)</strong></span> Let the design-matrix form of a balanced <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction and reference group be given. Then the beta-parameter estimator is <span class="math display">\[\begin{equation}
\hat{\beta}:=
\begin{pmatrix}
\hat{\mu}_{0} \\
\hat{\alpha}_{2} \\
\hat{\beta}_{2} \\
\hat{\gamma}_{22}
\end{pmatrix}
=
\begin{pmatrix}
\bar{y}_{11} \\
\bar{y}_{21}-\bar{y}_{11} \\
\bar{y}_{12}-\bar{y}_{11} \\
(\bar{y}_{11}-\bar{y}_{12})-(\bar{y}_{21}-\bar{y}_{22})
\end{pmatrix}.
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>For the balanced <span class="math inline">\(2 \times 2\)</span> design with interaction, <span class="math display">\[\begin{equation}
X^{T}X =
n_{ij}
\begin{pmatrix}
4 &amp; 2 &amp; 2 &amp; 1 \\
2 &amp; 2 &amp; 1 &amp; 1 \\
2 &amp; 1 &amp; 2 &amp; 1 \\
1 &amp; 1 &amp; 1 &amp; 1
\end{pmatrix},
\quad
\left(X^{T}X\right)^{-1}
=
\frac{1}{n_{ij}}
\begin{pmatrix}
1 &amp; -1 &amp; -1 &amp; 1 \\
-1 &amp; 2 &amp; 1 &amp; -2 \\
-1 &amp; 1 &amp; 2 &amp; -2 \\
1 &amp; -2 &amp; -2 &amp; 4
\end{pmatrix}.
\end{equation}\]</span> Multiplying this inverse with <span class="math inline">\(X^Ty\)</span> yields the cell-mean expressions in the theorem.</p>
</div>
<p>The following <strong>R</strong> code illustrates the relation in the example data set.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># data reformatting</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>D          <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/509-two-way-analysis-of-variance.csv"</span>)            <span class="co"># data set</span></span>
<span id="cb4-3"><a href="#cb4-3"></a>A1B1       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"F2F"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"MND"</span> ]                    <span class="co"># face-to-face, mindfulness</span></span>
<span id="cb4-4"><a href="#cb4-4"></a>A1B2       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"F2F"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"EXC"</span> ]                    <span class="co"># face-to-face, exercise</span></span>
<span id="cb4-5"><a href="#cb4-5"></a>A2B1       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"ONL"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"MND"</span> ]                    <span class="co"># online, mindfulness</span></span>
<span id="cb4-6"><a href="#cb4-6"></a>A2B2       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"ONL"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"EXC"</span> ]                    <span class="co"># online, exercise</span></span>
<span id="cb4-7"><a href="#cb4-7"></a></span>
<span id="cb4-8"><a href="#cb4-8"></a><span class="co"># data matrix for group means</span></span>
<span id="cb4-9"><a href="#cb4-9"></a>n_ij       <span class="ot">=</span> <span class="fu">length</span>(A1B1)                                                        <span class="co"># number of data points per group</span></span>
<span id="cb4-10"><a href="#cb4-10"></a>Y          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(A1B1,A1B2,A2B1,A2B2), <span class="at">nrow =</span> n_ij)                         <span class="co"># data matrix</span></span>
<span id="cb4-11"><a href="#cb4-11"></a>bar_y      <span class="ot">=</span> <span class="fu">colMeans</span>(Y)                                                         <span class="co"># cell means</span></span>
<span id="cb4-12"><a href="#cb4-12"></a></span>
<span id="cb4-13"><a href="#cb4-13"></a><span class="co"># model estimation</span></span>
<span id="cb4-14"><a href="#cb4-14"></a>I          <span class="ot">=</span> <span class="dv">2</span>                                                                   <span class="co"># number of levels of factor A</span></span>
<span id="cb4-15"><a href="#cb4-15"></a>J          <span class="ot">=</span> <span class="dv">2</span>                                                                   <span class="co"># number of levels of factor B</span></span>
<span id="cb4-16"><a href="#cb4-16"></a>n          <span class="ot">=</span> I<span class="sc">*</span>J<span class="sc">*</span>n_ij                                                            <span class="co"># number of data points</span></span>
<span id="cb4-17"><a href="#cb4-17"></a>p          <span class="ot">=</span> <span class="dv">1</span> <span class="sc">+</span> (I<span class="dv">-1</span>)<span class="sc">+</span>(J<span class="dv">-1</span>)<span class="sc">+</span>(I<span class="sc">*</span>J<span class="dv">-3</span>)                                             <span class="co"># number of parameters</span></span>
<span id="cb4-18"><a href="#cb4-18"></a>Dmat       <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,                                                   <span class="co"># prototypical design matrix</span></span>
<span id="cb4-19"><a href="#cb4-19"></a>                      <span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,</span>
<span id="cb4-20"><a href="#cb4-20"></a>                      <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,</span>
<span id="cb4-21"><a href="#cb4-21"></a>                      <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">nrow =</span> p, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-22"><a href="#cb4-22"></a>C          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n_ij),<span class="at">nrow =</span> n_ij)                                     <span class="co"># prototypical cell vector</span></span>
<span id="cb4-23"><a href="#cb4-23"></a>X          <span class="ot">=</span> <span class="fu">kronecker</span>(Dmat,C)                                                   <span class="co"># Kronecker-product design matrix</span></span>
<span id="cb4-24"><a href="#cb4-24"></a>y          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(A1B1,A1B2,A2B1,A2B2), <span class="at">nrow =</span> n)                            <span class="co"># data vector</span></span>
<span id="cb4-25"><a href="#cb4-25"></a>beta_hat   <span class="ot">=</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y                                    <span class="co"># beta-parameter estimator</span></span>
<span id="cb4-26"><a href="#cb4-26"></a>eps_hat    <span class="ot">=</span> y <span class="sc">-</span> X <span class="sc">%*%</span> beta_hat                                                  <span class="co"># residual vector</span></span>
<span id="cb4-27"><a href="#cb4-27"></a>sigsqr_hat <span class="ot">=</span> (<span class="fu">t</span>(eps_hat) <span class="sc">%*%</span> eps_hat) <span class="sc">/</span>(n<span class="sc">-</span>p)                                     <span class="co"># variance-parameter estimator</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>hat{beta}                                        :  10.5 4.58 -0.67 1.42 
hat{sigsqr}                                      :  5.94 
bar{y}_11,bar{y}_12,bar{y}_21,bar{y}_22          :  10.5 9.83 15.08 15.83 
bar{y}_11                                        :  10.5 
bar{y}_21 - bar{y}_11                            :  4.58 
bar{y}_12 - bar{y}_11                            :  -0.67 
bar{y}_11 + bar{y}_22 - bar{y}_12 - bar{y}_21    :  1.42</code></pre>
</div>
</div>
</section>
<section id="model-evaluation" class="level2" data-number="42.4">
<h2 data-number="42.4" class="anchored" data-anchor-id="model-evaluation"><span class="header-section-number">42.4</span> Model evaluation</h2>
<p>The inferential evaluation of main-effect and interaction parameters in two-way ANOVA models can be viewed from several perspectives. Analogously to one-way ANOVA, sum-of-squares decompositions can be developed and used to define corresponding F-statistics. Here we follow the alternative approach of formulating F-statistics for main effects and interactions against the background of model comparisons in the corresponding two-way ANOVA models. We restrict ourselves to (1) evaluation of main effects in the additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with reference group and (2) evaluation of the interaction in the <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction and reference group.</p>
<section id="evaluation-of-main-effects-in-the-additive-2-times-2-two-way-anova-model" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="evaluation-of-main-effects-in-the-additive-2-times-2-two-way-anova-model">Evaluation of main effects in the additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model</h3>
<div id="thm-test-statistics-for-main-effects" class="theorem">
<p><span class="theorem-title"><strong>Theorem 42.3 (Test statistics for main effects)</strong></span> Let <span class="math display">\[\begin{equation}
y = X\beta+\varepsilon \mbox{ with } \varepsilon \sim N\left(0_{n}, \sigma^{2} I_{n}\right)
\end{equation}\]</span> be the design-matrix form of the additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with reference group, where the <span class="math inline">\(n \times 1\)</span> columns of <span class="math inline">\(X\)</span> are denoted by <span class="math display">\[\begin{equation}
X:=
\begin{pmatrix}
X_{\mu_{0}} &amp; X_{\alpha_{2}} &amp; X_{\beta_{2}}
\end{pmatrix}
\in \mathbb{R}^{n \times 3}.
\end{equation}\]</span> Then:</p>
<ol type="A">
<li><p>An F-test statistic for the main effect of factor A is the F-statistic of the GLM with <span class="math display">\[\begin{equation}
X_{A}:=
\begin{pmatrix}
X_{\mu_{0}} &amp; X_{\beta_{2}} &amp; X_{\alpha_{2}}
\end{pmatrix},\quad
\beta_A :=
\begin{pmatrix}
\mu_0 \\
\beta_2 \\
\alpha_2
\end{pmatrix},
\quad p_0:=2,\ p_1:=1.
\end{equation}\]</span></p></li>
<li><p>An F-test statistic for the main effect of factor B is the F-statistic of the GLM with <span class="math display">\[\begin{equation}
X_{B}:=
\begin{pmatrix}
X_{\mu_{0}} &amp; X_{\alpha_{2}} &amp; X_{\beta_{2}}
\end{pmatrix},\quad
\beta_B :=
\begin{pmatrix}
\mu_0 \\
\alpha_2 \\
\beta_2
\end{pmatrix},
\quad p_0:=2,\ p_1:=1.
\end{equation}\]</span></p></li>
</ol>
</div>
<div id="def-test-hypotheses-and-tests-for-main-effects" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 42.5 (Test hypotheses and tests for main effects)</strong></span> Let the additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model be given, and let the F-test statistics for the main effects of factors A and B be denoted by <span class="math inline">\(F_A\)</span> and <span class="math inline">\(F_B\)</span>. Then:</p>
<ol type="A">
<li><p>The critical-value-based test <span class="math display">\[\begin{equation}
\phi_A(y):=1_{\{F_A \geq k\}} \mbox{ with null hypothesis } H_0^A:\alpha_2=0
\end{equation}\]</span> defines the F-test of the main effect of factor A in the model with <span class="math inline">\(X_A,\beta_A\)</span>.</p></li>
<li><p>The critical-value-based test <span class="math display">\[\begin{equation}
\phi_B(y):=1_{\{F_B \geq k\}} \mbox{ with null hypothesis } H_0^B:\beta_2=0
\end{equation}\]</span> defines the F-test of the main effect of factor B in the model with <span class="math inline">\(X_B,\beta_B\)</span>.</p></li>
</ol>
</div>
<div id="thm-test-size-control-and-p-values-for-main-effects" class="theorem">
<p><span class="theorem-title"><strong>Theorem 42.4 (Test-size control and p-values for main effects)</strong></span> With the above definitions and the CDF <span class="math inline">\(\varphi\)</span> of the <span class="math inline">\(f\)</span> distribution:</p>
<ol type="A">
<li><p><span class="math inline">\(\phi_A\)</span> is a level-<span class="math inline">\(\alpha_0\)</span> test with test size <span class="math inline">\(\alpha_0\)</span> if the critical value is <span class="math display">\[\begin{equation}
k_{\alpha_0}^{A}:=\varphi^{-1}\left(1-\alpha_0;1,n-3\right).
\end{equation}\]</span> The p-value associated with an observed value <span class="math inline">\(f_A\)</span> of <span class="math inline">\(F_A\)</span> is <span class="math display">\[\begin{equation}
p_A\mbox{-value}:=1-\varphi\left(f_A;1,n-3\right).
\end{equation}\]</span></p></li>
<li><p><span class="math inline">\(\phi_B\)</span> is a level-<span class="math inline">\(\alpha_0\)</span> test with test size <span class="math inline">\(\alpha_0\)</span> if the critical value is <span class="math display">\[\begin{equation}
k_{\alpha_0}^{B}:=\varphi^{-1}\left(1-\alpha_0;1,n-3\right).
\end{equation}\]</span> The p-value associated with an observed value <span class="math inline">\(f_B\)</span> of <span class="math inline">\(F_B\)</span> is <span class="math display">\[\begin{equation}
p_B\mbox{-value}:=1-\varphi\left(f_B;1,n-3\right).
\end{equation}\]</span></p></li>
</ol>
</div>
<p><strong>Application example</strong></p>
<p>The following <strong>R</strong> code demonstrates the evaluation procedure for main effects in the additive <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with reference group.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>D          <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/509-two-way-analysis-of-variance.csv"</span>)            <span class="co"># data set</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>A1B1       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"F2F"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"MND"</span> ]                    <span class="co"># face-to-face, mindfulness</span></span>
<span id="cb6-3"><a href="#cb6-3"></a>A1B2       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"F2F"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"EXC"</span> ]                    <span class="co"># face-to-face, exercise</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>A2B1       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"ONL"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"MND"</span> ]                    <span class="co"># online, mindfulness</span></span>
<span id="cb6-5"><a href="#cb6-5"></a>A2B2       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"ONL"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"EXC"</span> ]                    <span class="co"># online, exercise</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>I          <span class="ot">=</span> <span class="dv">2</span>                                                                   <span class="co"># number of levels of factor setting</span></span>
<span id="cb6-7"><a href="#cb6-7"></a>J          <span class="ot">=</span> <span class="dv">2</span>                                                                   <span class="co"># number of levels of factor variant</span></span>
<span id="cb6-8"><a href="#cb6-8"></a>n_ij       <span class="ot">=</span> <span class="fu">length</span>(A1B1)                                                        <span class="co"># balanced ANOVA design</span></span>
<span id="cb6-9"><a href="#cb6-9"></a>n          <span class="ot">=</span> I<span class="sc">*</span>J<span class="sc">*</span>n_ij                                                            <span class="co"># number of data points</span></span>
<span id="cb6-10"><a href="#cb6-10"></a>y          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(A1B1,A1B2,A2B1,A2B2), <span class="at">nrow =</span> n)                            <span class="co"># data vector</span></span>
<span id="cb6-11"><a href="#cb6-11"></a>Dmat       <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),                                  <span class="co"># prototypical design matrix</span></span>
<span id="cb6-12"><a href="#cb6-12"></a>                     <span class="at">nrow =</span> I<span class="sc">*</span>J, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-13"><a href="#cb6-13"></a>C          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n_ij),<span class="at">nrow =</span> n_ij)                                     <span class="co"># prototypical cell vector</span></span>
<span id="cb6-14"><a href="#cb6-14"></a>X          <span class="ot">=</span> <span class="fu">kronecker</span>(Dmat,C)                                                   <span class="co"># Kronecker-product design matrix</span></span>
<span id="cb6-15"><a href="#cb6-15"></a>XH         <span class="ot">=</span> <span class="fu">list</span>(X[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">2</span>)], X)                                               <span class="co"># model variants</span></span>
<span id="cb6-16"><a href="#cb6-16"></a>alpha_0    <span class="ot">=</span> <span class="fl">0.05</span>                                                                <span class="co"># significance level</span></span>
<span id="cb6-17"><a href="#cb6-17"></a>Eff        <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,<span class="dv">2</span>)                                                          <span class="co"># F-test statistic</span></span>
<span id="cb6-18"><a href="#cb6-18"></a>k_alpha_0  <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,<span class="dv">2</span>)                                                          <span class="co"># critical value</span></span>
<span id="cb6-19"><a href="#cb6-19"></a>phi        <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,<span class="dv">2</span>)                                                          <span class="co"># test value</span></span>
<span id="cb6-20"><a href="#cb6-20"></a>p_vals     <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,<span class="dv">2</span>)                                                          <span class="co"># p-value</span></span>
<span id="cb6-21"><a href="#cb6-21"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>) {</span>
<span id="cb6-22"><a href="#cb6-22"></a>    X            <span class="ot">=</span> XH[[i]]                                                       <span class="co"># full-model design matrix</span></span>
<span id="cb6-23"><a href="#cb6-23"></a>    X_0          <span class="ot">=</span> X[,<span class="sc">-</span><span class="dv">3</span>]                                                        <span class="co"># reduced-model design matrix</span></span>
<span id="cb6-24"><a href="#cb6-24"></a>    p            <span class="ot">=</span> <span class="fu">ncol</span>(X)                                                       <span class="co"># number of full-model parameters</span></span>
<span id="cb6-25"><a href="#cb6-25"></a>    p_0          <span class="ot">=</span> <span class="fu">ncol</span>(X_0)                                                     <span class="co"># number of reduced-model parameters</span></span>
<span id="cb6-26"><a href="#cb6-26"></a>    p_1          <span class="ot">=</span> p <span class="sc">-</span> p_0                                                       <span class="co"># number of additional parameters</span></span>
<span id="cb6-27"><a href="#cb6-27"></a>    beta_hat_0   <span class="ot">=</span> <span class="fu">solve</span>(<span class="fu">t</span>(X_0)<span class="sc">%*%</span>X_0)<span class="sc">%*%</span><span class="fu">t</span>(X_0)<span class="sc">%*%</span>y                              <span class="co"># reduced-model beta estimator</span></span>
<span id="cb6-28"><a href="#cb6-28"></a>    beta_hat     <span class="ot">=</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span>X )<span class="sc">%*%</span><span class="fu">t</span>(X) <span class="sc">%*%</span>y                                 <span class="co"># full-model beta estimator</span></span>
<span id="cb6-29"><a href="#cb6-29"></a>    eps_hat_0    <span class="ot">=</span> y<span class="sc">-</span>X_0<span class="sc">%*%</span>beta_hat_0                                            <span class="co"># reduced-model residual vector</span></span>
<span id="cb6-30"><a href="#cb6-30"></a>    eps_hat      <span class="ot">=</span> y <span class="sc">-</span> X<span class="sc">%*%</span>beta_hat                                              <span class="co"># full-model residual vector</span></span>
<span id="cb6-31"><a href="#cb6-31"></a>    eh0_eh0      <span class="ot">=</span> <span class="fu">t</span>(eps_hat_0) <span class="sc">%*%</span> eps_hat_0                                    <span class="co"># reduced-model RSS</span></span>
<span id="cb6-32"><a href="#cb6-32"></a>    eh_eh        <span class="ot">=</span> <span class="fu">t</span>(eps_hat) <span class="sc">%*%</span> eps_hat                                        <span class="co"># full-model RSS</span></span>
<span id="cb6-33"><a href="#cb6-33"></a>    sigsqr_hat   <span class="ot">=</span> eh_eh<span class="sc">/</span>(n<span class="sc">-</span>p)                                                   <span class="co"># full-model variance estimator</span></span>
<span id="cb6-34"><a href="#cb6-34"></a>    Eff[i]       <span class="ot">=</span> ((eh0_eh0<span class="sc">-</span>eh_eh)<span class="sc">/</span>p_1)<span class="sc">/</span>sigsqr_hat                              <span class="co"># F-statistic</span></span>
<span id="cb6-35"><a href="#cb6-35"></a>    k_alpha_0[i] <span class="ot">=</span> <span class="fu">qf</span>(<span class="dv">1</span><span class="sc">-</span>alpha_0, p_1, n<span class="sc">-</span>p)                                       <span class="co"># critical value</span></span>
<span id="cb6-36"><a href="#cb6-36"></a>    <span class="cf">if</span>(Eff[i] <span class="sc">&gt;=</span> k_alpha_0[i]){ phi[i] <span class="ot">=</span> <span class="dv">1</span> } <span class="cf">else</span> { phi[i] <span class="ot">=</span> <span class="dv">0</span> }                 <span class="co"># test value</span></span>
<span id="cb6-37"><a href="#cb6-37"></a>    p_vals[i]    <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(Eff[i], p_1,n<span class="sc">-</span>p)                                       <span class="co"># p-value</span></span>
<span id="cb6-38"><a href="#cb6-38"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             f     k phi p.value
Setting 56.575 4.057   1   0.000
Variant  0.004 4.057   0   0.953</code></pre>
</div>
</div>
<p>For the main effect of factor Setting, the F-statistic is <span class="math inline">\(F_A=0.17\)</span> with a critical value of <span class="math inline">\(k_{0.05}=4.06\)</span>. The null hypothesis of a true, but unknown, effect parameter value of zero for factor Setting would therefore not be rejected in light of the data visualized in <a href="#fig-two-way-anova-example-data-set" class="quarto-xref">Figure&nbsp;<span>42.3</span></a>. For the main effect of factor Variant, the F-statistic is <span class="math inline">\(F_B=51.36\)</span> with the same critical value. The null hypothesis of a true, but unknown, effect parameter value of zero for factor Variant would therefore be rejected at <span class="math inline">\(\alpha_0:=0.05\)</span>.</p>
<p>The following <strong>R</strong> code demonstrates the same analysis using the <strong>R</strong> function <code>aov()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>D          <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/509-two-way-analysis-of-variance.csv"</span>)            <span class="co"># data set</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>res.aov    <span class="ot">=</span> <span class="fu">aov</span>(dBDI <span class="sc">~</span> Setting <span class="sc">+</span> Variant, <span class="at">data =</span> D)                             <span class="co"># model formulation and model estimation</span></span>
<span id="cb8-3"><a href="#cb8-3"></a><span class="fu">summary</span>(res.aov)                                                                 <span class="co"># model evaluation</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Setting      1  336.0   336.0  56.575 1.73e-09 ***
Variant      1    0.0     0.0   0.004    0.953    
Residuals   45  267.3     5.9                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The following <strong>R</strong> code demonstrates the same analysis using the <strong>R</strong> functions <code>lm()</code> and <code>anova()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>D          <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/509-two-way-analysis-of-variance.csv"</span>)            <span class="co"># data set</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>glm        <span class="ot">=</span> <span class="fu">lm</span>(dBDI <span class="sc">~</span> Setting <span class="sc">+</span> Variant, <span class="at">data =</span> D)                              <span class="co"># model formulation and model estimation</span></span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="fu">anova</span>(glm)                                                                       <span class="co"># model evaluation</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: dBDI
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Setting    1 336.02  336.02 56.5753 1.728e-09 ***
Variant    1   0.02    0.02  0.0035     0.953    
Residuals 45 267.27    5.94                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="evaluation-of-the-interaction-in-the-2-times-2-two-way-anova-model-with-interaction" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="evaluation-of-the-interaction-in-the-2-times-2-two-way-anova-model-with-interaction">Evaluation of the interaction in the <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction</h3>
<div id="thm-test-statistic-for-the-interaction" class="theorem">
<p><span class="theorem-title"><strong>Theorem 42.5 (Test statistic for the interaction)</strong></span> Let <span class="math display">\[\begin{equation}
y = X\beta+\varepsilon \mbox{ with } \varepsilon \sim N\left(0_{n}, \sigma^{2} I_{n}\right)
\end{equation}\]</span> be the design-matrix form of the <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction and reference group. Then the F-statistic with <span class="math inline">\(p_0:=3\)</span> and <span class="math inline">\(p_1:=1\)</span> is an F-test statistic for the interaction of factor A and factor B.</p>
</div>
<div id="def-test-hypothesis-and-test-for-the-interaction" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 42.6 (Test hypothesis and test for the interaction)</strong></span> Let the F-test statistic for the interaction of factor A and factor B be denoted by <span class="math inline">\(F_{A \times B}\)</span>. Then the critical-value-based test <span class="math display">\[\begin{equation}
\phi_{A \times B}(y):=1_{\{F_{A \times B} \geq k\}}
\mbox{ with null hypothesis } H_0^{A \times B}:\gamma_{22}=0
\end{equation}\]</span> defines the F-test of the interaction of factor A and factor B.</p>
</div>
<div id="thm-test-size-control-and-p-value-for-the-interaction" class="theorem">
<p><span class="theorem-title"><strong>Theorem 42.6 (Test-size control and p-value for the interaction)</strong></span> With the above definition and the CDF <span class="math inline">\(\varphi\)</span> of the <span class="math inline">\(f\)</span> distribution, <span class="math inline">\(\phi_{A \times B}\)</span> is a level-<span class="math inline">\(\alpha_0\)</span> test with test size <span class="math inline">\(\alpha_0\)</span> if the critical value is <span class="math display">\[\begin{equation}
k_{\alpha_0}^{A \times B}:=\varphi^{-1}\left(1-\alpha_0;1,n-4\right).
\end{equation}\]</span> The p-value associated with an observed value <span class="math inline">\(f_{A \times B}\)</span> of <span class="math inline">\(F_{A \times B}\)</span> is <span class="math display">\[\begin{equation}
p_{A \times B}\mbox{-value}:=1-\varphi\left(f_{A \times B};1,n-4\right).
\end{equation}\]</span></p>
</div>
<p><strong>Application example</strong></p>
<p>The following <strong>R</strong> code demonstrates the evaluation procedure for the interaction of the factors in the <span class="math inline">\(2 \times 2\)</span> two-way ANOVA model with interaction and reference group.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>D          <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/509-two-way-analysis-of-variance.csv"</span>)            <span class="co"># data set</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>A1B1       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"F2F"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"MND"</span> ]                    <span class="co"># face-to-face, mindfulness</span></span>
<span id="cb12-3"><a href="#cb12-3"></a>A1B2       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"F2F"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"EXC"</span> ]                    <span class="co"># face-to-face, exercise</span></span>
<span id="cb12-4"><a href="#cb12-4"></a>A2B1       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"ONL"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"MND"</span> ]                    <span class="co"># online, mindfulness</span></span>
<span id="cb12-5"><a href="#cb12-5"></a>A2B2       <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>Setting <span class="sc">==</span> <span class="st">"ONL"</span> <span class="sc">&amp;</span> D<span class="sc">$</span>Variant <span class="sc">==</span> <span class="st">"EXC"</span> ]                    <span class="co"># online, exercise</span></span>
<span id="cb12-6"><a href="#cb12-6"></a>I          <span class="ot">=</span> <span class="dv">2</span>                                                                   <span class="co"># number of levels of factor setting</span></span>
<span id="cb12-7"><a href="#cb12-7"></a>J          <span class="ot">=</span> <span class="dv">2</span>                                                                   <span class="co"># number of levels of factor variant</span></span>
<span id="cb12-8"><a href="#cb12-8"></a>n_ij       <span class="ot">=</span> <span class="fu">length</span>(A1B1)                                                        <span class="co"># balanced ANOVA design</span></span>
<span id="cb12-9"><a href="#cb12-9"></a>n          <span class="ot">=</span> I<span class="sc">*</span>J<span class="sc">*</span>n_ij                                                            <span class="co"># number of data points</span></span>
<span id="cb12-10"><a href="#cb12-10"></a>y          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(A1B1,A1B2,A2B1,A2B2), <span class="at">nrow =</span> n)                            <span class="co"># data vector</span></span>
<span id="cb12-11"><a href="#cb12-11"></a>Dmat       <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">nrow =</span> I<span class="sc">*</span>J, <span class="at">byrow =</span> <span class="cn">TRUE</span>) <span class="co"># prototypical design matrix</span></span>
<span id="cb12-12"><a href="#cb12-12"></a>C          <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n_ij),<span class="at">nrow =</span> n_ij)                                     <span class="co"># prototypical cell vector</span></span>
<span id="cb12-13"><a href="#cb12-13"></a>X          <span class="ot">=</span> <span class="fu">kronecker</span>(Dmat,C)                                                   <span class="co"># Kronecker-product design matrix</span></span>
<span id="cb12-14"><a href="#cb12-14"></a>alpha_0    <span class="ot">=</span> <span class="fl">0.05</span>                                                                <span class="co"># significance level</span></span>
<span id="cb12-15"><a href="#cb12-15"></a>X_0        <span class="ot">=</span> X[,<span class="sc">-</span><span class="dv">4</span>]                                                              <span class="co"># reduced-model design matrix</span></span>
<span id="cb12-16"><a href="#cb12-16"></a>p          <span class="ot">=</span> <span class="fu">ncol</span>(X)                                                             <span class="co"># number of full-model parameters</span></span>
<span id="cb12-17"><a href="#cb12-17"></a>p_0        <span class="ot">=</span> <span class="fu">ncol</span>(X_0)                                                           <span class="co"># number of reduced-model parameters</span></span>
<span id="cb12-18"><a href="#cb12-18"></a>p_1        <span class="ot">=</span> p <span class="sc">-</span> p_0                                                             <span class="co"># number of additional parameters</span></span>
<span id="cb12-19"><a href="#cb12-19"></a>beta_hat_0 <span class="ot">=</span> <span class="fu">solve</span>(<span class="fu">t</span>(X_0)<span class="sc">%*%</span>X_0)<span class="sc">%*%</span><span class="fu">t</span>(X_0)<span class="sc">%*%</span>y                                    <span class="co"># reduced-model beta estimator</span></span>
<span id="cb12-20"><a href="#cb12-20"></a>beta_hat   <span class="ot">=</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span>X )<span class="sc">%*%</span><span class="fu">t</span>(X) <span class="sc">%*%</span>y                                       <span class="co"># full-model beta estimator</span></span>
<span id="cb12-21"><a href="#cb12-21"></a>eps_hat_0  <span class="ot">=</span> y<span class="sc">-</span>X_0<span class="sc">%*%</span>beta_hat_0                                                  <span class="co"># reduced-model residual vector</span></span>
<span id="cb12-22"><a href="#cb12-22"></a>eps_hat    <span class="ot">=</span> y <span class="sc">-</span> X<span class="sc">%*%</span>beta_hat                                                    <span class="co"># full-model residual vector</span></span>
<span id="cb12-23"><a href="#cb12-23"></a>eh0_eh0    <span class="ot">=</span> <span class="fu">t</span>(eps_hat_0) <span class="sc">%*%</span> eps_hat_0                                          <span class="co"># reduced-model RSS</span></span>
<span id="cb12-24"><a href="#cb12-24"></a>eh_eh      <span class="ot">=</span> <span class="fu">t</span>(eps_hat) <span class="sc">%*%</span> eps_hat                                              <span class="co"># full-model RSS</span></span>
<span id="cb12-25"><a href="#cb12-25"></a>sigsqr_hat <span class="ot">=</span> eh_eh<span class="sc">/</span>(n<span class="sc">-</span>p)                                                         <span class="co"># full-model variance estimator</span></span>
<span id="cb12-26"><a href="#cb12-26"></a>f          <span class="ot">=</span> ((eh0_eh0<span class="sc">-</span>eh_eh)<span class="sc">/</span>p_1)<span class="sc">/</span>sigsqr_hat                                    <span class="co"># F-statistic</span></span>
<span id="cb12-27"><a href="#cb12-27"></a>k_alpha_0  <span class="ot">=</span> <span class="fu">qf</span>(<span class="dv">1</span><span class="sc">-</span>alpha_0, p_1, n<span class="sc">-</span>p)                                             <span class="co"># critical value</span></span>
<span id="cb12-28"><a href="#cb12-28"></a><span class="cf">if</span>(f <span class="sc">&gt;=</span> k_alpha_0){phi <span class="ot">=</span> <span class="dv">1</span>} <span class="cf">else</span> {phi <span class="ot">=</span> <span class="dv">0</span>}                                       <span class="co"># test value</span></span>
<span id="cb12-29"><a href="#cb12-29"></a>p_val      <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(f, p_1,n<span class="sc">-</span>p)                                                  <span class="co"># p-value</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                      f     k phi p.value
Setting x Variant 1.014 4.062   0   0.319</code></pre>
</div>
</div>
<p>The F-statistic is <span class="math inline">\(F_{A \times B}=1.01\)</span> with a critical value <span class="math inline">\(k_{0.05}=4.06\)</span>. The null hypothesis of a true, but unknown, effect parameter value of zero for the interaction effect would therefore not be rejected in light of the data visualized in <a href="#fig-two-way-anova-example-data-set" class="quarto-xref">Figure&nbsp;<span>42.3</span></a>.</p>
<p>The following <strong>R</strong> code demonstrates the same analysis using the <strong>R</strong> function <code>aov()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>D          <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/509-two-way-analysis-of-variance.csv"</span>)            <span class="co"># data set</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>res.aov    <span class="ot">=</span> <span class="fu">aov</span>(dBDI <span class="sc">~</span> Setting <span class="sc">+</span> Variant <span class="sc">+</span> Setting<span class="sc">:</span>Variant, <span class="at">data =</span> D)           <span class="co"># model formulation and model estimation</span></span>
<span id="cb14-3"><a href="#cb14-3"></a><span class="fu">summary</span>(res.aov)                                                                 <span class="co"># model evaluation</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Setting          1  336.0   336.0  56.593 1.97e-09 ***
Variant          1    0.0     0.0   0.004    0.953    
Setting:Variant  1    6.0     6.0   1.014    0.319    
Residuals       44  261.2     5.9                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The following <strong>R</strong> code demonstrates the same analysis using the <strong>R</strong> functions <code>lm()</code> and <code>anova()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>D          <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/509-two-way-analysis-of-variance.csv"</span>)            <span class="co"># data set</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>glm        <span class="ot">=</span> <span class="fu">lm</span>(dBDI <span class="sc">~</span> Setting <span class="sc">+</span> Variant <span class="sc">+</span> Setting<span class="sc">:</span>Variant, <span class="at">data =</span> D)            <span class="co"># model formulation and model estimation</span></span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="fu">anova</span>(glm)                                                                       <span class="co"># model evaluation</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: dBDI
                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Setting          1 336.02  336.02 56.5930 1.973e-09 ***
Variant          1   0.02    0.02  0.0035    0.9530    
Setting:Variant  1   6.02    6.02  1.0140    0.3194    
Residuals       44 261.25    5.94                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
<section id="literature-notes" class="level2" data-number="42.5">
<h2 data-number="42.5" class="anchored" data-anchor-id="literature-notes"><span class="header-section-number">42.5</span> Literature notes</h2>
<p>The popularity of analysis-of-variance procedures is generally traced back to <span class="citation" data-cites="fisher1925b">Fisher (<a href="#ref-fisher1925b" role="doc-biblioref">1925</a>)</span> and <span class="citation" data-cites="fisher1935">Fisher (<a href="#ref-fisher1935" role="doc-biblioref">1935</a>)</span>. <span class="citation" data-cites="everitt2005">Everitt &amp; Howell (<a href="#ref-everitt2005" role="doc-biblioref">2005</a>)</span> and <span class="citation" data-cites="stigler1986">Stigler (<a href="#ref-stigler1986" role="doc-biblioref">1986</a>)</span> provide a brief and a detailed historical overview, respectively.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-everitt2005" class="csl-entry" role="listitem">
Everitt, B., &amp; Howell, D. C. (Eds.). (2005). <em>Encyclopedia of statistics in behavioral science</em>. John Wiley &amp; Sons.
</div>
<div id="ref-fisher1925b" class="csl-entry" role="listitem">
Fisher, R. A. (1925). Applications of "<span>Student</span>’s" distribution. <em>Metron</em>, <em>5</em>, 90–104.
</div>
<div id="ref-fisher1935" class="csl-entry" role="listitem">
Fisher, R. A. (1935). <em>The design of experiments</em> (1. ed). Hafner Press.
</div>
<div id="ref-stigler1986" class="csl-entry" role="listitem">
Stigler, S. M. (1986). <em>The history of statistics: The measurement of uncertainty before 1900</em>. Belknap Press of Harvard University Press.
</div>
</div>
</section>

</main> <!-- /main -->
<script>
(function () {
  var base = "https://dirk-ostwald.github.io";
  var pageMap = {
    "/": "/en/",
    "/index.html": "/en/",
    "/Referenzen.html": "/en/References.html",
    "/_part_1/100-Mathematische-Grundlagen.html": "/en/_part_1/100-Mathematical-Foundations.html",
    "/_part_1/101-Sprache-und-Logik.html": "/en/_part_1/101-Language-and-Logic.html",
    "/_part_1/102-Mengen.html": "/en/_part_1/102-Sets.html",
    "/_part_1/103-Summen-Produkte-Potenzen.html": "/en/_part_1/103-Sums-Products-Powers.html",
    "/_part_1/104-Funktionen.html": "/en/_part_1/104-Functions.html",
    "/_part_1/105-Folgen-Grenzwerte-Stetigkeit.html": "/en/_part_1/105-Sequences-Limits-Continuity.html",
    "/_part_1/106-Differenzialrechnung.html": "/en/_part_1/106-Differential-Calculus.html",
    "/_part_1/107-Integralrechnung.html": "/en/_part_1/107-Integral-Calculus.html",
    "/_part_1/108-Vektoren.html": "/en/_part_1/108-Vectors.html",
    "/_part_1/109-Matrizen.html": "/en/_part_1/109-Matrices.html",
    "/_part_1/110-Deskriptivstatistiken.html": "/en/_part_1/110-Descriptive-Statistics.html",
    "/_part_2/200-Imperative-Programmierung.html": "/en/_part_2/200-Imperative-Programming.html",
    "/_part_2/201-Informatische-Grundbegriffe.html": "/en/_part_2/201-Basic-Concepts-of-Computer-Science.html",
    "/_part_2/202-Arithmetik-und-Variablen.html": "/en/_part_2/202-Arithmetic-and-Variables.html",
    "/_part_2/203-Datenstrukturen.html": "/en/_part_2/203-Data-Structures.html",
    "/_part_2/204-Vektoren.html": "/en/_part_2/204-Vectors.html",
    "/_part_2/205-Matrizen-und-Arrays.html": "/en/_part_2/205-Matrices-and-Arrays.html",
    "/_part_2/206-Listen-Dataframes-und-Tibbles.html": "/en/_part_2/206-Lists-Dataframes-and-Tibbles.html",
    "/_part_2/207-Datenmanagement.html": "/en/_part_2/207-Data-Management.html",
    "/_part_2/208-Kontrollstrukturen.html": "/en/_part_2/208-Control-Structures.html",
    "/_part_3/300-Wahrscheinlichkeitstheorie.html": "/en/_part_3/300-Probability-Theory.html",
    "/_part_3/301-Wahrscheinlichkeitsräume.html": "/en/_part_3/301-Probability-Spaces.html",
    "/_part_3/302-Elementare-Wahrscheinlichkeiten.html": "/en/_part_3/302-Elementary-Probabilities.html",
    "/_part_3/303-Zufallsvariablen.html": "/en/_part_3/303-Random-Variables.html",
    "/_part_3/304-Zufallsvektoren.html": "/en/_part_3/304-Random-Vectors.html",
    "/_part_3/305-Erwartungswerte.html": "/en/_part_3/305-Expectations.html",
    "/_part_3/306-Varianzen.html": "/en/_part_3/306-Variances.html",
    "/_part_3/307-Kovarianzen.html": "/en/_part_3/307-Covariances.html",
    "/_part_3/308-Ungleichungen.html": "/en/_part_3/308-Inequalities.html",
    "/_part_3/309-Grenzwerte.html": "/en/_part_3/309-Limits.html",
    "/_part_3/310-Transformationen.html": "/en/_part_3/310-Transformations.html",
    "/_part_3/311-Normalverteilungen.html": "/en/_part_3/311-Normal-Distributions.html",
    "/_part_4/400-Inferenz.html": "/en/_part_4/400-Inference.html",
    "/_part_4/401-Frequentistische-Inferenz.html": "/en/_part_4/401-Frequentist-Inference.html",
    "/_part_4/402-Punktschätzung.html": "/en/_part_4/402-Point-Estimation.html",
    "/_part_4/403-Konfidenzintervalle.html": "/en/_part_4/403-Confidence-Intervals.html",
    "/_part_4/404-Hypothesentests.html": "/en/_part_4/404-Hypothesis-Tests.html",
    "/_part_5/500-Allgemeines-Lineares-Modell.html": "/en/_part_5/500-General-Linear-Model.html",
    "/_part_5/501-Regression.html": "/en/_part_5/501-Regression.html",
    "/_part_5/502-Korrelation.html": "/en/_part_5/502-Correlation.html",
    "/_part_5/503-Modellformulierung.html": "/en/_part_5/503-Model-Formulation.html",
    "/_part_5/504-Parameterschätzung.html": "/en/_part_5/504-Parameter-Estimation.html",
    "/_part_5/505-T-Statistiken.html": "/en/_part_5/505-T-Statistics.html",
    "/_part_5/506-F-Statistiken.html": "/en/_part_5/506-F-Statistics.html",
    "/_part_5/507-T-Tests.html": "/en/_part_5/507-T-Tests.html",
    "/_part_5/508-Einfaktorielle-Varianzanalyse.html": "/en/_part_5/508-One-Way-Analysis-of-Variance.html",
    "/_part_5/509-Zweifaktorielle-Varianzanalyse.html": "/en/_part_5/509-Two-Way-Analysis-of-Variance.html",
    "/_part_5/510-Partielle-Korrelation.html": "/en/_part_5/510-Partial-Correlation.html",
    "/_part_5/511-Multiple-Regression.html": "/en/_part_5/511-Multiple-Regression.html",
    "/_part_7/700-Multivariate-Inferenz.html": "/en/_part_7/700-Multivariate-Inference.html",
    "/_part_7/701-Multivariate-Deskriptivstatistiken.html": "/en/_part_7/701-Multivariate-Descriptive-Statistics.html"
  };
  var reversePageMap = {};
  Object.keys(pageMap).forEach(function (key) {
    reversePageMap[pageMap[key]] = key;
  });
  function headings() {
    return Array.prototype.slice.call(document.querySelectorAll("main.content h1[id], main.content h2[id], main.content h3[id], main.content h4[id]"));
  }
  function currentHeadingIndex() {
    var hash = window.location.hash;
    if (!hash) return "";
    var id = hash.slice(1);
    try {
      id = decodeURIComponent(id);
    } catch (error) {}
    var list = headings();
    for (var i = 0; i < list.length; i++) {
      if (list[i].id === id) return String(i);
    }
    return "";
  }
  function scrollToHeadingIndex() {
    var params = new URLSearchParams(window.location.search);
    var value = params.get("h");
    if (value === null) return;
    var index = Number(value);
    var list = headings();
    if (Number.isInteger(index) && index >= 0 && index < list.length) {
      list[index].scrollIntoView();
      if (history.replaceState) {
        history.replaceState(null, "", window.location.pathname + "#" + list[index].id);
      }
    }
  }
  var path = window.location.pathname;
  var target = pageMap[path] || reversePageMap[path];
  if (target) {
    document.querySelectorAll("a.nav-link").forEach(function (link) {
      var text = link.textContent.trim();
      if (text === "English" || text === "Deutsch") {
        var index = currentHeadingIndex();
        link.href = base + target + (index ? "?h=" + index : "");
      }
    });
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", scrollToHeadingIndex);
  } else {
    scrollToHeadingIndex();
  }
}());
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../_part_5/508-One-Way-Analysis-of-Variance.html" class="pagination-link" aria-label="One-way analysis of variance">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">One-way analysis of variance</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../_part_5/510-Partial-Correlation.html" class="pagination-link" aria-label="Partial correlation">
        <span class="nav-page-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Partial correlation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages/edit/main/_part_5/509-Two-Way-Analysis-of-Variance.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>