# Mathematische Grundlagen
\normalsize
### Vorbemerkungen {-}


Die Mathematik ist die zentrale Sprache der probabilistischen Datenwissenschaft.
Ihre Funktion ist dabei die einer Vermittlerin zwischen intuitiver 
Wissenschaftssprache und der Vielfalt von Programmiersprachen, die zur Implementation 
datenwissenschaftlicher Analysen eingesetzt werden. Mathematische Begriffsbildungen 
erlauben es dabei, Konzepte sehr genau und allgemein verständlich zu greifen und 
unabhängig von den Ungenauigkeiten der wissenschaftlichen Alltagsprache oder 
den Idiosynkratien verschiedener Programmiersprachen zu kommunizieren. 
Natürlich kann die mathematische Sprache diese Rolle nicht unabhängig von 
wissenschaftssprachlicher Intuition oder praktischer programmiertechnischer 
Anwendung einnehmen. Die Mathematik ist in der probabilistischen Datenanalyse 
nie Selbstzweck, sondern immer als angewandte Mathematik zu verstehen.

In diesem Teil stellen wir nach einigen Gedanken zu den grundlegenden Konzepten
der Mathematik (@sec-sprache-und-logik) mit den Mengen und den Funktionen 
(@def-mengen und @sec-funktionen) die beiden Grundpfeiler der modernen Mathematik 
in komprimierter Form dar. Wir ergänzen diese Darstellung durch einige im notationelle
Aspekte in @sec-summen-produkte-potenzen. Eng verwoben mit dem Begriff der
Funktion sind bekanntlich die Differential- und Integralrechnung (@sec-differentialrechnung
und @sec-integralrechnung). Auch hier geht es uns natürlich nicht um eine 
erschöpfende Darstellung, sondern insbesondere um die Erläuterung einiger Grundlagen, 
die für die im Kontext der probabilistischen Datenwissenschaft zentralen Konzepte der
Optimierung von Funktionen sowie dem Umgang mit Wahrscheinlichkeitsfunktionen 
zentral sind. Wir ergänzen diese Abschnitte mit einigen oberflächlichen Gedanken 
zu den analytischen Grundlagen der Differential- und Integralrechnung in 
@sec-folgen-grenzwerte-stetigkeit. Im Umgang mit den großen Datenmengen der
zeitgenössischen Wissenschaft hat sich die Matrixschreibweise als hilfreich 
erwiesen. Wir widmen uns diesem Teilbereich der Linearen Algebra in @sec-vektoren,
@sec-matrizen und @sec-eigenanalyse, wiederrum mit dem einzigen Ziel, notationelle
und rechnerische Grundlagen für spätere Abschnitte bereitzustellen.

Insgesamt dient dieser Teil also vor allem der Kurzeinführung von Grundlagen,
die in allen anderen Teilen von PDWP wieder aufgegriffen werden und dient dabei
vor allem auch der Einführung einer einheitlichen Notation über die verschiedenen
Teilbereiche. Je nach Bedarf und Interesse ist hier natürlich ein
vertieftes Studium der verschiedenen Inhalte angezeigt. In den folgenden Literaturhinweisen
führen wir überblicksartig Quellen und Leseempfehlungen zu den Inhalten dieses Teils an.  

### Literaturhinweise {-}

@baerwolff2017 und @arens2018 bilden die primäre Grundlage für viele in diesem
Teil dargestellen Themen und bieten einen exzellenten und umfassenden Einstieg 
in die behandelte Materie. Auf internationaler Ebene bilden @spivak2008
und @strang2009 sehr gut lesbare Einführungen in die Differentialrechnung und 
die Lineare Algebra, respektive. Ein tieferes Verständnis insbesondere analytischer Konzepte 
liefern zum Beispiel @abbott2015 und @chiossi2021. @searle1982 bietet eine kompakte
Darstellung derjenigen Aspekte der Matrizenrechnung und Linearen Algebra, die
im Bereich der probabilistischen Datenanalyse hauptsächlich zum Einsatz kommen.
@deisenroth2020 bietet einen Überblick über viele der hier behandelten Themen 
unter dem Moniker des Maschinellen Lernens.







