# Mengen {#sec-mengen}
\normalsize

## Grundlegende Definitionen

Mengen fassen mathematische Objekte wie beispielsweise Zahlen zusammen und bilden
die Grundlage der modernen Mathematik. Wir beginnen mit folgender Definition.

:::{#def-mengen}
## Mengen
Nach @cantor1895 ist eine *Menge* definiert als 
"eine Zusammenfassung $M$ von bestimmten wohlunterschiedenen Objekten $m$ unsere
Anschauung oder unseres Denken (welche die Elemente der Menge genannt werden) 
zu einem Ganzen". Wir schreiben
\begin{equation}
m \in M \mbox{ bzw. } m \notin M
\end{equation}
um auszudrücken, dass $m$ ein Element bzw. kein Element von $M$ ist. 
::: 

Zur  Definition von Mengen gibt es mindestens folgende Möglichkeiten:

* Auflisten der Elemente in geschweiften Klammern, z.B. $M := \{1,2,3\}$. 
* Angabe der Eigenschaften der Elemente, z.B. $M := \{x \in \mathbb{N}|x < 4\}$. 
* Gleichsetzen mit einer anderen eindeutig definieren Menge, z.B. $M := \mathbb{N}_3$. 

Die Schreibweise $\{x \in \mathbb{N}|x < 4\}$ wird gelesen als "$x \in \mathbb{N}$,
für die gilt, dass $x < 4$ ist", wobei die Bedeutung von $\mathbb{N}$ im Folgenden 
noch zu erläutern sein wird. Es ist wichtig zu erkennen, dass Mengen *ungeordnete* 
mathematische Objekte sind, dass heißt die Reihenfolge der Auflistung der Elemente 
einer Menge spielt keine Rolle. Zum Beispiel bezeichnen $\{1,2,3\}$, $\{1,3,2\}$ und $\{2,3,1\}$ 
dieselbe Menge, nämlich die Menge der ersten drei natürlichen Zahlen.

Grundlegende Beziehungen zwischen mehreren Mengen werden in der nächsten Definition
festgelegt.


:::{#def-teilmengen-und-mengengleichheit}
## Teilmengen und Mengengleichheit
$A$ und $B$ seien zwei Mengen.

* Eine Menge $A$ heißt *Teilmenge* einer Menge $B$, wenn für jedes Element
$a \in A$ gilt, dass auch $a\in B$. Ist $A$ eine Teilmenge von $B$, so schreibt
man
\begin{equation}
A \subseteq B
\end{equation}
und nennt $A$ *Untermenge* von $B$ und $B$ *Obermenge* von $A$.
* Eine Menge $A$ heißt *echte Teilmenge* einer Menge $B$, wenn für jedes Element
$a \in A$ gilt, dass auch $a\in B$, es aber zumindest ein Element $b \in B$ gibt,
für das gilt $b \notin A$. Ist $A$ eine echte Teilmenge von $B$, so schreibt man
\begin{equation}
A \subset B.
\end{equation}
* Zwei Mengen $A$ und $B$ heißen *gleich*, wenn für jedes Element $a \in A$ gilt,
dass auch $a \in B$, und wenn für jedes Element $b \in B$ gilt, dass auch $b
\in A$. Sind die Mengen $A$ und $B$ gleich, so schreibt man
\begin{equation}
A = B.
\end{equation}
:::

Betrachten wir zum Beispiel die Mengen $A := \{1\}$, $B := \{1,2\}$, und
$C := \{1,2\}$. Dann gilt mit obigen Definitionen, dass  $A \subset B$, weil $1 \in A$
und $1 \in B$, aber $2 \in B$ und $2 \notin A$. Weiterhin gilt, dass $B \subseteq C$,
weil $1 \in B$ und $1 \in C$ sowie $2 \in B$ und $2 \in C$ und es kein Element von 
$C$ gibt, welches nicht in $B$ ist. Ebenso gilt  $C \subseteq B$, weil $1 \in C$ 
und $1 \in B$ sowie $2 \in C$ und $2 \in B$ und es kein Element von $B$ gibt, 
welches nicht in $C$ ist. Schließlich gilt sogar $B = C$,  weil für jedes Element 
$b \in B$ gilt, dass auch $b \in C$, und gleichzeitig für jedes Element 
$c \in C$ gilt, dass auch $c\in B$.

Eine wichtige Eigenschaft einer Menge ist die Anzahl der in ihr enthaltenen Elemente.
Diese wird als *Kardinalität* der Menge bezeichnet.

:::{#def-kardinalität}
## Kardinalität
Die Anzahl der Elemente einer Menge $M$ heißt *Kardinalität* und wird mit $|M|$ bezeichnet. 
:::

Eine besondere Menge ist die Menge ohne Elemente.

:::{#def-leere-menge}
Eine Menge mit Kardinalität Null heißt *leere Menge* und wird mit $\emptyset$ bezeichnet.
:::

Als Beispiele seien $A := \{1,2,3\}$, $B = \{a,b,c,d\}$ und $C := \{\,\}$. Dann gelten
$|A| = 3$, $B = 4$ und $|C| = 0$.

Zu jeder Menge kann man die Menge aller Teilmengen dieser Menge betrachten. Dies
führt auf den wichtigen Begriff der *Potenzmenge*.


:::{#def-potenzmenge}
## Potenzmenge
Die Menge aller Teilmengen einer Menge $M$ heißt *Potenzmenge von $M$* und wird mit $\mathcal{P}(M)$ bezeichnet. 
:::

Man beachte, dass die leere Untermenge von $M$ und $M$ selbst auch immer Elemente 
von $\mathcal{P}(M)$ sind. Wir betrachten vier Beispiele zum Begriff der Potenzmenge.

* $M_0 := \emptyset$ sei die leere Menge. Dann gilt
\begin{equation}
\mathcal{P}(M_0) = \emptyset.
\end{equation}

* $M_1$ sei die einelementige Menge $M_1 := \{a\}$. Dann gilt
\begin{equation}
\mathcal{P}(M_1) = \{\emptyset,\{a\}\}.
\end{equation}

* Es sei $M_2 := \{a,b\}$. Dann hat $M_2$ sowohl ein- als auch zweielementige Teilmengen
und es gilt
\begin{equation}
\mathcal{P}(M_2) = \{\emptyset,\{a\}\, \{b\}, \{a,b\}\}.
\end{equation}

* Schließlich sei $M_3 := \{a,b,c\}$. Dann hat  $M$ ein-, zwei-, als auch
dreielementige Teilmengen und es gilt
\begin{equation}
\mathcal{P}(M_3) = \{\emptyset, \{a\},\{b\},\{c\},\{a,b\},\{a,c\},\{b,c\},\{a,b,c\}\}.
\end{equation}

Hinsichtlich der Kardinalitäten einer Menge und ihrer Potenzmenge kann man beweisen,
dass aus $|M| = n$ mit $n>0$ folgt, dass die Kardinalität der Potenzmenge
$|\mathcal{P}(M)| = 2^n$ ist. In den obigen Beispielen haben wir die Fälle
$|M_1| = 1$ und somit $|\mathcal{P}(M_1)| = 2^1 = 2$, $|M_2| = 2$ und somit
$|\mathcal{P}(M_3)| = 2^2 = 4$ und schließlich $|M_3| = 3$ und somit
$|\mathcal{P}(M_3)| = 2^3 = 8$, wovon man sich durch Nachzählen schnell überzeugt.


## Verknüpfungen von Mengen {#sec-verknuepfung-von-mengen}
Zwei Mengen können auf unterschiedliche Weise miteinander verknüpft werden. Das
Ergebnis einer solchen Verknüpfung ist eine weitere Menge. Wir bezeichnen die
Verknüpfung zweier Mengen als *Mengenoperation* und geben folgende Definitionen.

:::{#def-mengenoperationen}
## Mengenoperationen

$M$ und $N$ seien zwei Mengen.

* Die *Vereinigung von $M$ und $N$* ist definiert als die Menge
\begin{equation}
M \cup N := \{x | x \in M \lor x \in N\},
\end{equation}
wobei $\lor$ wie immer im inklusiven Sinne als und/oder zu verstehen ist.

* Der *Durchschnitt von $M$ und $N$* ist definiert als die Menge
\begin{equation}
M \cap N := \{x | x \in M \land x \in N\}.
\end{equation}
Wenn für $M$ und $N$ gilt, dass $M \cap N= \emptyset$, dann heißen $M$ und $N$ *disjunkt*.

* Die *Differenz von $M$ und $N$* ist definiert als die Menge
\begin{equation}
M\setminus N := \{x | x \in M \land x \notin N\}.
\end{equation}
Die Differenz  $M$ und $N$ heißt, insbesondere bei $M \subseteq N$, auch das
*Komplement von $N$ bezüglich $M$* und wird mit $N^c$ bezeichnet.

* Die *symmetrische Differenz von $M$ und $N$* ist definiert als die Menge
\begin{equation}
M \Delta N := \{x|(x \in M \lor x \in N ) \land x \notin M \cap N\},
\end{equation}
Die symmetrische Differenz kann also als *exklusives oder* verstanden werden.

:::

Als Beispiel betrachten wir die Mengen $M := \{1,2,3\}$und $N := \{2,3,4,5\}$. Dann gelten

* $M \cup N = \{1,2,3,4,5\}$, weil $1 \in M$, $2 \in M$, $3 \in M$, $4 \in N$ und $5 \in N$.
* $M \cap N = \{2,3\}$, weil nur für $2$ und $3$ gilt, dass $2\in M, 3 \in M$ und auch $2\in N, 3 \in N$.
Für $1$ gilt lediglich, dass $1 \in M$ und für $4$ und $5$ gelten lediglich, dass $4 \in N$ und $5 \in N$.
* $M \setminus N = \{1\}$, weil $1 \in M$, aber $1 \notin N$ und $2 \in M$, aber auch $2 \in N$.
* $N \setminus M = \{4,5\}$, weil $2 \in N$ und $3 \in N$, aber auch $2\in M$ und $3 \in M$. Dies zeigt insbesondere,
dass die Differenz von $M$ Und $N$ *nicht* symmetrisch ist, also dass *nicht* zwangsläufig gilt, dass $M\setminus N$ gleich $N \setminus M$ ist.
* $M \Delta N = \{1,4,5\}$, weil $1 \in M$, aber $1 \notin \{2,3\}$, $2 \in M$, aber $2 \in \{2,3\}$, $3 \in M$, aber $3 \in \{2,3\}$, $4 \in N$, aber $4 \notin \{2,3\}$
und $5 \in N$, aber $5 \notin \{2,3\}$.

Schließlich wollen wir noch den Begriff der Partition einer Menge einführen. 


:::{#def-partition}
## Partition
$M$ sei eine Menge und $P := \{N_i\}$ sei eine Menge von Mengen $N_i$ mit $i = 1,...,n$,
so dass gilt
\begin{equation}
M = \cup_{i=1}^n N_i \land N_i \cap N_j = \emptyset \mbox{ für } i = 1,...,n, j = 1,...,n, i \neq j.
\end{equation}
Dann heißt $P$ eine \textit{Partition von $M$}.
:::

Intuitiv entspricht die Partition einer Menge also dem Aufteilen der Menge in disjunkte 
Teilmengen. Partitionen sind generell nicht eindeutig, d.h. es gibt meist verschiedene
Möglichkeiten eine gegebene Menge zu partitionieren. Betrachten wir zum Beispiel
die Menge $M := \{1,2,3,4,5,6\}$. Dann sind $P_1 := \{\{1\}, \{2,3,4,5,6\}\}$,
$P_2 := \{\{1,2,3\}, \{4,5,6\}\}$ und $P_3 := \{\{1,2\},\{3,4\}, \{5,6\}\}$
drei mögliche Partitionen von $M$.

## Spezielle Mengen

In der Naturwissenschaft versucht man, Phänomene der Welt mit Zahlen zu 
beschreiben. Je nach Phänomen bieten sich dazu *diskrete* oder *kontinuierliche* 
Zahlenmengen an. Die Mathematik stellt dazu unter anderem die in folgender 
Definition gegebenen Zahlenmengen bereit.

:::{#def-zahlenmengen}
## Zahlenmengen

Es bezeichnen

* $\mathbb{N}\,\,\, := \{1,2,3,...\}$ die *natürlichen Zahlen*,
* $\mathbb{N}_n     := \{1,2,3,...,n\}$ die *natürlichen Zahlen der Ordnung $n$*,
* $\mathbb{N}^0     := \mathbb{N} \cup \{0\}$ die *natürlichen Zahlen* und Null,
* $\mathbb{Z}\,\,\, := \{...,-3,-2,-1,0,1,2,3...\}$ die *ganzen Zahlen*,
* $\mathbb{Q}\,\,\, := \{\frac{p}{q}|p,q \in \mathbb{Z}, q \neq 0\}$ die *rationalen Zahlen*,
* $\mathbb{R}\,\,\,$ die *reellen Zahlen*, und
* $\mathbb{C}\,\,\, := \{a + ib|a,b\in \mathbb{R}, i := \sqrt{-1} \}$ die *komplexen Zahlen*.
:::

Die natürlichen und ganzen Zahlen eignen sich insbesondere zum Quantifizieren
diskreter Phänomene. Die rationalen und insbesondere die reellen Zahlen eignen
sich zum Quantifizieren kontinuierlicher Phänomene. $\mathbb{R}$ umfasst dabei
die rationalen Zahlen und die sogenannten *irrationalen Zahlen* $\mathbb{R}\setminus
\mathbb{Q}$. Rationale Zahlen sind Zahlen, die sich, wie oben definiert, durch
Brüche ganzer Zahlen ausdrücken lassen. Dies sind alle ganzen Zahlen sowie die negativen
und positiven Dezimalzahlen wie z.B. $-\frac{9}{10} = -0.9$, $\frac{1}{3} = 1.3\bar{3}$,
und $\frac{196}{100} = 1.96$. Irrationale Zahlen sind Zahlen, die sich nicht als
rationale Zahlen ausdrücken lassen. Beispiele für irrationale Zahlen sind die 
*Eulersche Zahl* $e \approx 2.71$, die *Kreiszahl* $\pi \approx 3.14$ und die 
Quadratwurzel von $2$, $\sqrt{2} \approx 1.41$. 

Die reellen Zahlen enthalten als Teilmengen die natürlichen, ganzen, und die 
rationalen Zahlen. Es gibt also sehr viele reelle Zahlen. Tatsächlich kann man 
beweisen (@cantor1892), dass es mehr reelle Zahlen als natürliche Zahlen gibt, 
obwohl es sowohl unendlich viele reelle Zahlen als auch unendlich viele natürliche 
Zahlen gibt. Diese Eigenschaft der reellen Zahlen bezeichnet man als die *Überabzählbarkeit* 
der reellen Zahlen. Insbesondere gilt
\begin{equation}
\mathbb{N} \subset \mathbb{Z} \subset \mathbb{Q} \subset \mathbb{R}.
\end{equation}
Zwischen zwei reellen Zahlen gibt es unendlich viele weitere reelle Zahlen.
Positiv-Unendlich ($\infty$) und Negativ-Unendlich ($-\infty$) sind keine Zahlen, mit denen
in der Standardmathematik gerechnet werden kann. Sie gehören auch nicht zu den
in obiger Definition gegebenen Zahlenmengen, es gilt also sowohl $\infty \notin \mathbb{R}$
als auch $-\infty \notin \mathbb{R}$.

Komplexe Zahlen eignen sich zur Beschreibung zweidimensionaler kontinuierlicher
Phänomene. Dabei werden die Werte der ersten Dimension im reellen Teil $a$ und 
die Werte der zweiten Dimension im komplexen Teil $b$ einer komplexen Zahl repräsentiert. 
Komplexe Zahlen kommen insbesondere bei der Modellierung physikalischer Phänomene 
und im Bereich der Fourieranalyse zum Einsatz. Wir vertiefen die Theorie 
komplexer Zahlen an dieser Stelle nicht.

Wichtige Teilmengen der reellen Zahlen sind die sogenannten *Intervalle*. Wir
geben folgende Definitionen.

:::{#def-intervalle}
Zusammenhängende Teilmengen der reellen Zahlen heißen *Intervalle*. 
Für $a,b\in \mathbb{R}$ unterscheidet man

* das *abgeschlossene Intervall*
\begin{equation}
[a,b] := \{x \in \mathbb{R}|a \le x \le b\},
\end{equation}
* das *offene Interval*
\begin{equation}
]a,b[ := \{x \in \mathbb{R}|a < x < b\},
\end{equation}
* und die *halboffenen Intervalle*
\begin{equation}
]a,b] := \{x \in \mathbb{R}| a < x \le b\} \mbox{ und }
[a,b[ := \{x \in \mathbb{R}| a \le x < b\}.
\end{equation}
:::

Wie oben erwähnt sind Positiv-Unendlich ($\infty$) und Negativ-Unendlich ($-\infty$)
keine Elemente von $\mathbb{R}$. Es gilt also immer $]-\infty,b]$ oder $]-\infty,b[$ bzw.
$]a,\infty[$ oder $[a,\infty[$, sowie $\mathbb{R} = ]-\infty, \infty[$.

Oft möchte man mehrere Eigenschaften eines Phänomens gleichzeitig quantitativ beschreiben. 
Zu diesem Zweck können die oben definierten eindimensionalen Zahlenmenge durch 
Bildung *Kartesischer Produkte* auf mehrdimensionale Zahlenmengen erweitert werden. 
Die Elemente Kartesischer Produkte nennt man *geordnete Tupel* oder auch *Vektoren*. 

:::{#def-kartesische-produkte}
## Kartesische Produkte

$M$ und $N$ seien zwei Mengen. Dann ist das *Kartesische Produkt der Mengen $M$
und $N$* die Menge aller geordneten Tupel $(m,n)$ mit $m \in M$ und $n \in N$,
formal
\begin{equation}
M \times N := \{(m,n)|m\in M, n \in N \}.
\end{equation}

Das Kartesische Produkt einer Menge $M$ mit sich selbst wird bezeichnet mit
\begin{equation}
M^2 := M \times M.
\end{equation}
Seien weiterhin $M_1, M_2, ..., M_n$ Mengen. Dann ist das *Kartesische Produkt
der Mengen $M_1,...,M_n$* die Menge aller geordneten $n$-Tupel $(m_1,...,m_n)$
mit $m_i \in M_i$ für $i = 1,...,n$, formal
\begin{equation}
\prod_{i=1}^n M_i := M_1 \times \cdots \times M_n := \{(m_1,...,m_n)
                |m_i \in M_i \mbox{ für } i = 1,...,n\}.
\end{equation}
Das $n$-fache Kartesische Produkt einer Menge $M$ mit sich selbst wird bezeichnet mit
\begin{equation}
M^n := \prod_{i=1}^n M := \{(m_1,,...,m_n)|m_i \in M\}.
\end{equation}
:::

Im Gegensatz zu Mengen sind die in @def-kartesische-produkte eingeführten 
Tupel *geordnet*. Das heißt, für Mengen gilt zum Beispiel $\{1,2\} = \{2,1\}$, 
aber für Tupel gilt $(1,2) \neq (2,1)$.

Wie oben beschrieben eignen sich insbesondere die reellen Zahlen zur Beschreibung
kontinuierlicher Phänomene. Zur simultanen Beschreibung mehrere Aspekte eines 
kontinuierlichen  Phänomens bietet sich entsprechend die *Menge der reellen Tupel 
$n$-ter Ordnung* an.

:::{#def-menge-der-reellen-tupel-nter-ordnung}
## Menge der reellen Tupel $n$-ter Ordnung
Das $n$-fache Kartesische Produkt der reellen Zahlen mit sich selbst wird bezeichnet mit
\begin{equation}
\mathbb{R}^n := \prod_{i=1}^n \mathbb{R} := \{x := (x_1,,...,x_n)|x_i \in \mathbb{R}\}
\end{equation}
und wird "$\mathbb{R}$ hoch $n$" gesprochen. Wir schreiben die Elemente von
$\mathbb{R}^n$ als Spalten
\begin{equation}
x :=
\begin{pmatrix}
x_1
\\
\vdots
\\
x_n
\end{pmatrix}
\end{equation}
und nennen sie *$n$-dimensionale Vektoren*. Zu Abgrenzung nennen wir die
Elemente von $\mathbb{R}^1 = \mathbb{R}$ auch *Skalare*.
:::

Ein Beispiel für $x \in \mathbb{R}^4$ ist
\begin{equation}
x = \begin{pmatrix} 0.16 \\ 1.76 \\ 0.23 \\ 7.11 \end{pmatrix}.
\end{equation}

## Selbstkontrollfragen {#sec-selbstkontrollfragen-mengen}
\footnotesize
1. Geben Sie die Definition einer Menge nach Cantor (1895) wieder.
1. Nennen Sie drei Möglichkeiten zur Definition einer Menge.
1. Erläutern Sie die Ausdrücke $m \in M, m \notin N, M \subseteq N, M \subset N$ für zwei Mengen $M$ und $N$. 
1. Geben Sie die Definition der Kardinalität einer Menge wieder.
1. Geben Sie die Definition der Potenzmenge einer Menge wieder.
1. Es sei $M := \{1,2\}$. Bestimmen Sie $\mathcal{P}(M)$.
1. Es seien $M := \{1,2\}, N := \{1,4,5\}$. Bestimmen Sie $M \cup N, M \cap N, M\setminus N, M \Delta N$.
1. Erläutern Sie die Symbole $\mathbb{N}$, $\mathbb{N}_n$, und $\mathbb{N}^0$.
1. Erläutern Sie die Unterschiede zwischen $\mathbb{N}$ und $\mathbb{Z}$ und zwischen $\mathbb{R}$ und $\mathbb{Q}$.
1. Geben Sie die Definition abgeschlossener, offener, und halboffener Intervalle wieder.
1. Es seien $M$ und $N$ Mengen. Erläutern Sie die Notation $M \times N$.
1. Geben Sie die Definition von $\mathbb{R}^n$ wieder.


