# Summen, Produkte, Potenzen {#sec-summen-produkte-potenzen}
\normalsize

Diese Einheit führt Schreibweisen für die Grundrechenarten ein.

## Summen {#sec-summen}

:::{#def-summenzeichen}
## Summenzeichen

Es bezeichnet
\begin{equation}
\sum_{i=1}^{n} x_i = x_1 + x_{2} + \cdots + x_{n}.
\end{equation}
Dabei stehen

* $\Sigma$ für das griechische *S*igma, mnemonisch für *S*umme,
* das Subskript $i = 1$ für den *Laufindex* und den *Startindex*,
* das Superskript $n$ für den *Endindex* und
* $x_1, x_2, ..., x_n$ für die *Summanden*.
:::

Für eine sinnvolle Benutzung des Summenzeichens ist es essentiell, mithilfe 
des Subskripts und des Superskripts den Anfang und das Ende der Summation festzulegen. 
Die genaue Bezeichnung des Laufindexes ist dagegen für den Wert der Summe irrelevant, es gilt
\begin{equation}
\sum_{i=1}^n x_i = \sum_{j=1}^n x_j.
\end{equation}
Manchmal  wird der Laufindex auch als Element einer *Indexmenge*
angegeben. Ist z.B. die Indexmenge $I := \{1,5,7\}$ definiert, so ist
\begin{equation}
\sum_{i \in I}x_i := x_1 + x_5 + x_7.
\end{equation}
Im Folgenden wollen wir kurz einige Beispiele für die Benutzung des Summenzeichens betrachten.

* *Summation vordefinierter Summanden.* Es seien $x_1 := 2$, $x_2 := 10$, $x_3 := -4$. Dann gilt
\begin{equation}
\sum_{i=1}^3 x_i = x_1 + x_2 + x_3 = 2 + 10 - 4 = 8. 
\end{equation}
* *Summation gewichteter vordefinierter Summanden.* Es seien wiederum $x_1 := 2$,
 $x_2 := 10$, $x_3 := -4$. Weiterhin seien die *Wichtungskoeffizienten* 
 $a_1 := \frac{1}{2}$, $a_2 := \frac{1}{5}$, $a_3 := 2$ definiert. 
Dann gilt
\begin{equation}
\sum_{i=1}^3 a_i x_i = a_1x_1 + a_2x_2 + a_2x_3 =  \frac{1}{2}\cdot 2 + \frac{1}{5}\cdot 10 + 2\cdot (-4) = 1 + 2 - 8 = -5. 
\end{equation}
Ausdrücke der Form $\sum_{i=1}^n a_i x_i$ werden auch als *Linearkombinationen* 
der $x_1,...,x_n$ mit den *Koeffizienten* oder *Wichtungsparametern* $a_1,...,a_n$ bezeichnet.
* *Summation natürlicher Zahlen.* Es gilt
\begin{equation}
\sum_{i=1}^5 i = 1 + 2 + 3 + 4 + 5 = 15.  
\end{equation}
* *Summation gerader natürlicher Zahlen.* Es gilt
\begin{equation}
\sum_{i=1}^5 2i = 2\cdot 1  + 2\cdot 2 + 2\cdot 3 + 2\cdot 4 + 2\cdot 5 = 2 + 4 + 6 + 8 + 10 = 30.
\end{equation}
* *Summation ungerader natürlicher Zahlen.* Es gilt
\begin{equation}
\sum_{i=1}^5 (2i - 1) = 2\cdot 1 - 1  + 2\cdot 2 - 1 + 2\cdot 3 - 1 + 2\cdot 4 - 1 + 2\cdot 5 - 1 = 1 + 3 + 5 + 7 + 9 = 25.
\end{equation}

Der Umgang mit dem Summenzeichen kann oft durch die Anwendung folgender Rechenregeln vereinfacht werden.

:::{#thm-rechenregeln-für-summen}
## Rechenregeln für Summen

(1) Summen gleicher Summanden
\begin{equation}
\sum_{i=1}^n x = nx
\end{equation}
(2) Assoziativität bei Summen gleicher Länge
\begin{equation}
\sum_{i=1}^n x_i + \sum_{i=1}^n y_i = \sum_{i=1}^n (x_i + y_i)
\end{equation}
(3) Distributivität bei Multiplikation mit einer Konstante
\begin{equation}
\sum_{i=1}^n ax_i = a\sum_{i=1}^n x_i
\end{equation}
(4) Aufspalten von Summen mit $1 < m < n$
\begin{equation}
\sum_{i = 1}^n x_i = \sum_{i=1}^m x_i + \sum_{i=m+1}^n x_i
\end{equation}
(5) Umindizierung
\begin{equation}
\sum_{i=0}^n x_i = \sum_{j = m}^{n+m} x_{j - m}
\end{equation}
:::

:::{.proof}
Man überzeugt sich von diesen Rechenregeln durch Ausschreiben der Summen und 
Anwenden der Rechenregeln von Addition und Multiplikation. Wir zeigen hier 
exemplarisch die Assoziativität bei Summen gleicher Länge und die Distributivität
bei Multiplikation mit einer Konstante. Hinsichtlich ersterer haben wir
\begin{align}
\begin{split}
\sum_{i=1}^n x_i + \sum_{i=1}^n y_i
& = x_1 + x_2 + \cdots + x_n +  y_1 + y_2 + \cdots + y_n    \\
& = x_1 + y_1 + x_2 + y_2 + \cdots + x_n + y_n               \\
& = \sum_{i=1}^n (x_i + y_i).
\end{split}
\end{align}
Hinsichtlich letzterer gilt
\begin{align}
\begin{split}
\sum_{i=1}^n ax_i
& = ax_1 + ax_2 + \cdots + ax_n                             \\ 
& = a(x_1 + x_2 + \cdots + x_n)                             \\
& = a\sum_{i=1}^n x_i.
\end{split}
\end{align}
:::

**Beispiele**

Als erstes Beispiel für die Anwendung der in @thm-rechenregeln-für-summen 
festgehaltenen Rechenregeln betrachten wir die Auswertung eines *Mittelwertes* 
(manchmal auch *Durchschnitt* genannt). Dazu seien $x_1, x_2,...,x_n$ reelle Zahlen. 
Der Mittelwert dieser Zahlen entspricht der Summe von $x_1, x_2,...,x_n$ geteilt 
durch die Anzahl der Zahlen $n$. Dabei ist es nach Aussage (3) von 
@thm-rechenregeln-für-summen irrelevant, ob zunächst die Zahlen aufaddiert werden 
und dann die resultierende Summe durch $n$ geteilt wird, oder die Zahlen jeweils 
einzeln durch $n$ geteilt werden und die entsprechenden Ergebenisse dann aufaddiert 
werden. Genauer gilt durch Anwendung @thm-rechenregeln-für-summen (3) mit $a =1/n$, dass
\begin{equation}
\frac{1}{n}\sum_{i=1}^n x_i = \sum_{i=1}^n \frac{x_i}{n}.
\end{equation}
So ist zum Beispiel der Mittelwert von  $x_1 := 1, x_2 := 4, x_3 := 2$ $x_4 := 1$ gegeben
durch
\begin{equation} 
\frac{1}{4}\sum_{i=1}^4 x_i 
= \frac{1}{4}(1 + 4 + 2 + 1) 
= \frac{8}{4} 
= 2 
= \frac{8}{4} 
= \frac{1}{4} + \frac{4}{4} + \frac{2}{4} + \frac{1}{4}
= \sum_{i=1}^4 \frac{x_i}{4}.
\end{equation}

Als zweites Beispiel betrachten wir die in @thm-rechenregeln-für-summen (5) festgehaltene
Umindizierungsregel. Dazu seien $n := 3$ und $m := 2$, sowie $x_0 := 2$, $x_1 := 3$, $x_2 := 5$ 
und $x_3 := 10$. Dann gilt offenbar
\begin{align}
\begin{split}
\sum_{i=0}^3 x_i
& = x_0 + x_1 + x_2 + x_3   \\
& = 2 + 3 + 5 + 10          \\
& = 20.
\end{split}
\end{align}
Ebenso gilt aber auch
\begin{align}
\begin{split}
\sum_{j = m}^{n + m} x_{j-m}
& = \sum_{j = 2}^{3 + 2} x_{j-2}            \\
& = \sum_{j = 2}^{5} x_{j-2}                \\
& = x_{2-2} + x_{3-2} + x_{4-2} + x_{5-2}   \\
& = x_{0} + x_{1} + x_{2} + x_{3}           \\
& = 2 + 3 + 5 + 10                          \\
& = 20.
\end{split}
\end{align}

**Doppelsummen**

Nicht selten trifft man in der Anwendung auf Ausdrücke, die mehrere Summationen
hintereinander ausführen. Dabei gelten für jede der Summen die oben gelisteten
Definitionen und Rechenregeln. Man macht sich die Bedeutung von Doppelsummen am
besten dadurch klar, dass man sie von innen nach außen ausschreibt und dabei beachtet, 
dass für jede Iteration der inneren Summe der Laufindex der äußeren Summe konstant 
bleibt. Folgendes Beispiel mag dies verdeutlichen. Es gilt
\begin{align}
\begin{split}
\sum_{i=1}^2 \sum_{j = 1}^3 (x_i + y_j)
& = \sum_{i=1}^2 (x_i + y_1 + x_i + y_2 + x_i + y_3)                            \\
& = (x_1 + y_1 + x_1 + y_2 + x_1 + y_3) + (x_2 + y_1 + x_2 + y_2 + x_2 + y_3).  \\
\end{split}
\end{align}


## Produkte {#sec-produkte}
Eine analoge Schreibweise zum Summenzeichen bietet das Produktzeichen für Produkte.

:::{#def-produktzeichen}
## Produktzeichen
Es bezeichnet 
\begin{equation}
\prod_{i=1}^{n} x_i = x_1 \cdot x_{2} \cdot \cdots \cdot x_{n}.
\end{equation}
Dabei stehen

* $\prod$ für das griechische *P*i, mnemonisch für *P*rodukt,
* das Subskript $i = 1$ für den *Laufindex* und den *Startindex*,
* das Superskript $n$ für den *Endindex*,
* $x_1, x_2, ..., x_n$ für die *Produktterme*
:::

Analog zum Summenzeichen gilt, dass das Produktzeichen nur mit Subskript und 
Superskripten zu Lauf- und Endindex Sinn ergibt. Die genaue Bezeichnung des
Laufindizes ist wiederum irrelevant, es gilt
\begin{equation}
\prod_{i=1}^n x_i = \prod_{j=1}^n x_j.
\end{equation}
Auch hier wird in seltenen Fällen der Laufindex als Element einer Indexmenge
angegeben. Ist z.B. die Indexmenge $J := \mathbb{N}_2^0$ definiert, so ist
\begin{equation}
\prod_{j \in J}x_j := x_0 \cdot x_1 \cdot x_2.
\end{equation}

Ein Beispiel für die Benutzung des Produktzeichens ist etwa die Definition der
*Fakultät* einer natürlichen Zahl $n$ durch
\begin{equation}
n! := \prod_{i=1}^n i.
\end{equation}
So ist etwa
\begin{equation}
3! := \prod_{i=1}^3 i = 1 \cdot 2 \cdot 3 = 6.
\end{equation}

Auch für Produkte gibt es eine Reihe von Rechenregeln, die den Umgang mit ihnen
oft vereinfachen. Wir listen einige in folgendem Theorem. Dabei machen wir vorgreifend 
Gebrauch der in @sec-potenzen definierten Schreibweise von *Potenzen*.

:::{#thm-rechenregeln-für-produkte}
## Rechenregeln für Produkte

(1) Produkte gleicher Faktoren
\begin{equation}
\prod_{i=1}^n x = x^n
\end{equation}
(2) Potenzierung von Konstanten
\begin{equation}
\prod_{i=1}^n ax_i = a^n\prod_{i=1}^n x_i
\end{equation}
(3) Aufspalten von Produkten mit $1 < m < n$
\begin{equation}
\prod_{i=1}^n x_i = \prod_{i=1}^m x_i \prod_{j=m+1}^n x_j
\end{equation}
(4) Produkt von Produkten
\begin{equation}
\prod_{i=1}^n x_iy_i = \prod_{i=1}^n x_i \prod_{i=1}^n y_i
\end{equation}

:::

## Potenzen {#sec-potenzen}
Produkte von Zahlen mit sich selbst können mithilfe der Potenzschreibweise 
abgekürzt werden.

:::{#def-potenz}
## Potenz

Für $a \in \mathbb{R}$ und $n \in \mathbb{N}^0$ ist die *$n$-te Potenz von $a$* definiert durch
\begin{equation}
a^0 := 1 \mbox{ und } a^{n+1} := a^n \cdot a.
\end{equation}
Weiterhin ist für $a\in \mathbb{R} \setminus 0$ und  $n \in \mathbb{N}^0$ die
*negative $n$-te Potenz von $a$* definiert durch
\begin{equation}
a^{-n} := (a^n)^{-1} := \frac{1}{a^n}.
\end{equation}
$a$ wird dabei *Basis* und $n$ wird *Exponent* genannt.
:::

Die Art der Definition von $a^{n+1}$ mit Rückbezug auf die Potenz $a^n$ in obiger
Definition nennt man *rekursiv*. Die Definition $a^0 := 1$ nennt man dabei den
*Rekursionsanfang*; er macht die rekursive Definition von $a^{n+1}$ erst möglich.
Die Definition $a^{n+1} := a^n \cdot a$ nennt man auch *Rekursionsschritt*. 
Folgende Rechenregeln vereinfachen das Rechnen mit Potenzen.

:::{#thm-rechenregeln-für-potenzen}
## Rechenregeln für Potenzen

Für $a,b\in \mathbb{R}$  und $n,m \in \mathbb{Z}$ mit $a\neq 0$ bei negativen
Exponenten gelten folgende Rechenregeln:
\begin{align}
a^n a^m & = a^{n+m} \\
(a^n)^m & = a^{nm}  \\
(ab)^n 	& = a^nb^n
\end{align}
:::
Anstelle eines Beweises betrachten wir folgende Beispiele

Beispiel (1)
\begin{equation}
2^2 \cdot 2^3 = (2\cdot 2) \cdot (2 \cdot 2 \cdot 2) = 2^5 = 2^{2 + 3},
\end{equation}

Beispiel (2)
\begin{equation}
(3^2)^3 = (3\cdot 3)^3 = (3\cdot 3)\cdot(3\cdot 3)\cdot(3\cdot 3)= 3^6 = 3^{2\cdot3},
\end{equation}

Beispiel (3)
\begin{equation}
(2 \cdot 4)^2 = (2\cdot 4)\cdot (2 \cdot 4) = (2 \cdot 2)\cdot(4\cdot 4) = 2^2 \cdot 4^2.
\end{equation}

In enger Beziehung zur Potenz steht die Definition der $n$ten Wurzel:

:::{#def-nte-wurzel}
## $n$-te Wurzel
Für $a \in \mathbb{R}$ und $n \in \mathbb{N}$ ist die *$n$-te Wurzel von $a$*
definiert als die reelle Zahl $r$ mit
\begin{equation}
r^n = a.
\end{equation}
:::

Beim Rechnen mit Wurzeln ist die Potenzschreibweise von Wurzeln oft hilfreich,
da sie die direkte Anwendung der Rechenregeln für Potenzen ermöglicht.

:::{#thm-potenzschreibweise-der-nten-wurzel}
## Potenzschreibweise der $n$-ten Wurzel
Es sei $a \in \mathbb{R}$, $n \in \mathbb{N}$ und $r$ die $n$-te Wurzel von $a$. Dann gilt
\begin{equation}
r = a^{\frac{1}{n}}
\end{equation}
:::

:::{.proof}
Es gilt
\begin{equation}
\left(a^{\frac{1}{n}}\right)^n
= a^{\frac{1}{n}}\cdot a^{\frac{1}{n}}\cdot \cdots \cdot a^{\frac{1}{n}}
= a^{\sum_{i=1}^n \frac{1}{n}}
= a^1
= a.
\end{equation}
Also gilt mit @def-nte-wurzel, dass $r = a^\frac{1}{n}$.
:::

Das Rechnen mit Quadratwurzeln wird durch die Potenzschreibweise
\begin{equation}
\sqrt{x} = x^{\frac{1}{2}}
\end{equation}
sehr erleichtert. So gilt zum Beispiel
\begin{equation}
\frac{2\pi}{\sqrt{2\pi}}
= \frac{2\pi}{(2\pi)^{\frac{1}{2}}} 
= (2\pi)^{1} \cdot (2\pi)^{-\frac{1}{2}}
= (2\pi)^{1-\frac{1}{2}}
= (2\pi)^{\frac{1}{2}}
= \sqrt{2\pi}.
\end{equation}

Folgender Zusammenhang zwischen Quadrat, Wurzel und Betrag wird des öfteren genutzt.

:::{#thm-wurzel-und-betrag}
## Wurzel und Betrag
Es sei $x \in \mathbb{R}$. Dann gilt
\begin{equation}
\sqrt{x^2} = |x|.
\end{equation}
:::

:::{.proof}
Wir betrachten die Fälle $x \ge 0$ und $x < 0$. Sei zunächst $x \ge 0$. Dann gilt
\begin{equation}
x \ge 0 \Rightarrow x^2 \ge 0 \Rightarrow \sqrt{x^2} = x  = |x|.
\end{equation}
Sei nun $x < 0$. Dann gilt
\begin{equation}
x <  0 \Rightarrow x^2 > 0 \Rightarrow \sqrt{x^2} = -x = |x|.
\end{equation}
:::



## Selbstkontrollfragen {#sec-selbstkontrollfragen-summen-produkte-potenzen}
\footnotesize
1. Geben Sie die Definition des Summenzeichens wieder.
1. Berechnen Sie die Summen $\sum_{i=1}^3 2$, $\sum_{i=1}^3 i^2$, und $\sum_{i=1}^3 \frac{2}{3}i$.
1. Schreiben Sie die Summe $1 + 3 + 5 + 7 + 9 + 11$ mithilfe des Summenzeichens.
1. Schreiben Sie die Summe $0 + 2 + 4 + 6 + 8 + 10$ mithilfe des Summenzeichens.
1. Geben Sie die Definition des Produktzeichens wieder.
1. Geben Sie die Definition der $n$-ten Potenz von $a \in \mathbb{R}$ wieder.
1. Berechnen Sie $2^2\cdot 2^3$ und $2^5$ und geben Sie die zugehörige Potenzregel wieder.
1. Berechnen Sie $6^2$ und $2^2\cdot 3^2$ und geben Sie die zugehörige Potenzregel wieder.
1. Begründen Sie, warum die $n$-te Wurzel von $a$ als $a^{\frac{1}{n}}$ geschrieben werden kann.
1. Berechnen Sie $(\sqrt{2})^{\frac{2}{3}}, 9^{\frac{1}{2}}$, und $4^{-\frac{1}{2}}$.


