# Wahrscheinlichkeitstheorie
\normalsize
### Vorbemerkungen {-}

Die Wahrscheinlichkeitstheorie ist ein mathematisches Modell zur Beschreibung 
von und zum quantitativen Schlussfolgern über *Zufallsvorgänge* der Wirklichkeit 
(@fig-wahrscheinlichkeitstheorie). Unter Zufallsvorgängen verstehen wir dabei 
alle Phänomene, die von uns nicht mit absoluter Sicherheit vorhergesagt werden können, 
deren Ergebnis also mit Unsicherheit behaftet ist. Offensichtliche und vertraute 
Beispiele für Zufallsvorgänge sind das Werfen eines Würfels oder einer Münze. 
Allerdings ist der Begriff des Zufallsvorgangs und damit der Anwendungsbereich 
der Wahrscheinlichkeitstheorie als sehr viel weiter gefasst zu verstehen. Nicht 
mit vollständiger Sicherheit vorhersagbar und damit mit Unsicherheit behaftet 
sind zum Beispiel auch der Ausgang einer Wahl, das morgige Wetter, der Messwert 
einer EEG-Elektrode zu einem bestimmten Zeitpunkt nach Applikation eines Reizes 
oder der Effekt einer Psychotherapieintervention auf den Gesundheitszustand 
einer Patient:in. Beginnt man darüber nachzudenken, welche Phänomene der Wirklichkeit 
mit Unsicherheit behaftet sind, so fällt es schwer, nichttriviale Phänomene anzugeben 
hinsichtlich deren Ergebnis man vollständige Sicherheit besitzt.

![*Wahrscheinlichkeitstheorie als Modell von Zufallsvorgängen.* Ausgangspunkt der
Wahrscheinlichkeitstheorie ist die Absicht, über einen Zufallsvorgang, also ein mit
Unsicherheit behaftetes Phänomen der Wirklichkeit, logisch-quantitative Schlüsse zu ziehen.
Die Repräsentation zentraler Aspekte des Zufallsvorgang mithilfe wahrscheinlichkeitstheoretischer
Begrifflichkeiten bezeichnet man als Modellierung. Das wahrscheinlichkeitstheoretische
Modell selbst garantiert dann im Sinne der Wahrscheinlichkeitsrechnung die Korrektheit 
logisch-quantitativer Schlussfolgerungen, welche zur Vorhersage von Aspekten des 
Zufallsvorgangs genutzt werden können.](./_figures/300-wahrscheinlichkeitstheorie){#fig-wahrscheinlichkeitstheorie fig-align="center"}

Als mathematisches Modell von Zufallsvorgängen erlaubt die 
Wahrscheinlichkeitstheorie insbesondere das vernunftbasierte, quantitative
Schlussfolgern über Zufallsvorgänge. Dies schlägt sich primär in der sogenannten 
*Wahrscheinlichkeitsrechnung* nieder. Quantitative Schlussfolgerungen der 
Wahrscheinlichkeitsrechnung haben beispielsweise folgende Form: Wenn ich 
annehme, dass das Ereignis $A$ mit Wahrscheinlichkeit $x$ und das Ereignis $B$ 
mit Wahrscheinlichkeit $y$ eintritt, dann ergibt sich für die Wahrscheinlichkeit 
von Ereignis $C$ eine Wahrscheinlichkeit von $z$. Dabei ist der Schluss auf die 
Wahrscheinlichkeit von $C$ logisch-mathematisch abgesichert, in dem Sinne, wie 
zum Beispiel logisch-mathematisch abgesichert ist, dass $1+1=2$ ist. Ob die 
Annahmen hinsichtlich der Wahrscheinlichkeiten von $A$ und $B$ aber den Gegebenheiten 
des Zufallsvorgangs in der Wirklichkeit entsprechen, darüber macht 
die Wahrscheinlichkeitstheorie keine Aussagen. 

Die Wahrscheinlichkeitstheorie selbst bedient sich dabei der mathematischen 
Theorie der Mengen und Funktionen. Spätestens seit @kolmogoroff1933 herrscht 
dabei ein axiomatischer Zugang vor: Man fragt in der Wahrscheinlichkeitstheorie 
selbst nicht, was denn eine Wahrscheinlichkeit sei oder inwieweit die Vorhersagen 
der Wahrscheinlichkeitstheorie mit der Wirklichkeit übereinstimmen, sondern 
versucht, ein in sich schlüssiges formal-mathematisches System von unbegründeten, 
aber intuitiv plausiblen, Grundannahmen und ihren Folgerungen zu entwickeln. 
Ausgangspunkt dieser Entwicklung ist das *Wahrscheinlichkeitsraummodell* eines
Zufallsvorgangs, das wir in @sec-wahrscheinlichkeitsraeume einführen werden.
In der Tat gibt es neben dem formal-mathematischen System der 
Wahrscheinlichkeitstheorie bis heute mathematisch-philosophische Diskussionen darüber, 
was genau denn unter dem Begriff der "Wahrscheinlichkeit eines Ereignisses" zu 
verstehen ist (vgl. @hajek2019). Dabei sind grob gesagt zwei etwas gegensätzliche 
Interpretationen vorherrschend, die sogenannte *Frequentistische Interpretation* 
und die sogenannte *Bayesianische Interpretation*.

Nach der *Frequentistischen Interpretation* ist die Wahrscheinlichkeit eines 
Ereignisses  die idealisierte relative Häufigkeit, mit der ein Ereignis unter 
den gleichen äußeren Bedingungen einzutreten pflegt. Zum Beispiel ist die 
Frequentistische Interpretation der Aussage "Mit einer Wahrscheinlichkeit von
1/6 zeigt der Würfel im nächsten Wurf eine 2" die folgende: "Wenn man einen Würfel 
unendlich oft werfen würde und dabei die relative Häufigkeit des Ereignisses, dass 
der Würfel eine 2 zeigt, bestimmen würde, dann wäre diese relative Häufigkeit 
gleich 1/6". Man beachte bei dieser Interpretation, dass man de-facto die 
Wahrscheinlichkeit eines Ereignisses nicht empirisch bestimmen kann, da man 
einen Würfel nicht unendlich oft werfen kann. Natürlich kann man die 
Wahrscheinlichkeit in dieser Interpretation aber empirisch schätzen. 
Schätzvorgänge selbst wiederrum sind allerdings kein Teil der Wahrscheinlichkeitstheorie, 
sondern der *Frequentistischen* oder *Bayesianischen Inferenz*.  

Nach der *Bayesianischen Interpretation* ist die Wahrscheinlichkeit eines 
Ereignisses  der Grad der Sicherheit, den eine Beobachter:in aufgrund ihrer 
subjektiven Einschätzung der Lage dem Eintreten des Ereignisses zumisst. 
Zum Beispiel ist die Bayesianische Interpretation der Aussage "Mit einer 
Wahrscheinlichkeit von 1/6 zeigt der Würfel im nächsten Wurf eine Zwei" dann etwa die
folgende: "Basierend auf meiner eigenen und der tradierten Erfahrung mit dem 
Werfen eines Würfels bin ich mir zu 16.6% sicher, dass der Würfel beim nächsten 
Wurf eine Zwei zeigt." 

In Modellen von tatsächlich zumindest unter ähnlichen Umständen wiederholbaren 
Zufallsvorgängen wie dem Werfen eines Würfels ist der Unterschied zwischen 
Frequentistischer und Bayesianischer Interpretation oft eher subtil. Es gibt 
aber wie oben angedeutet viele Zufallsvorgänge, die mit Wahrscheinlichkeiten 
beschrieben werden können, bei denen aufgrund ihrer Einmaligkeit eine 
Frequentistische Interpretation nicht angemessen ist. Zum Beispiel machen 
Aussagen der Form "Die Wahrscheinlichkeit dafür, dass die weltweiten Hitzerekorde 
im Jahr 2023 nicht auf den Klimawandel zurückzuführen sind, ist kleiner als 0.01" (vgl.
@philip2020) nur unter der Bayesianischen Interpretation Sinn, da es sich bei den 
Wetteraufzeichnungen des Jahres 2023 um ein einmaliges, nicht wiederholbares Ereignis handelt.  

Obwohl also die Interpretation des Begriffes der Wahrscheinlichkeit durchaus 
nicht eindeutig ist, unterscheiden sich die formalen Definitionen und Rechenregeln 
für Wahrscheinlichkeiten nicht. Sowohl die Frequentistische als auch die 
Bayesianische Inferenz, auf die wir an späterer Stelle eingehen, haben mit der 
Wahrscheinlichkeitstheorie also ein identisches mathematisches Bezugssystem 
und gemeinsames Fundament. Im Wesentlichen unterscheidet sich dies nicht so sehr
von vielen anderen Formen der mathematischen Modellierung. Beispielsweise kann
die Ableitung einer Funktion als die Geschwindigkeit eines Objekts oder als die 
Wachstumsrate einer Bakterienpopulation interpretiert werden. Obwohl sich diese
Phänomene intuitiv sehr stark in Bezug auf die Realität unterscheiden, ist das 
logische Schlussfolgern über beide Phänomene im Bereich der Mathematik identisch.  

