project:
  type: book
lang: de
csl: https://www.zotero.org/styles/apa
pdf-engine: xelatex
book:
  title: "Probabilistische Datenwissenschaft für die Psychologie"
  author:
  - name: Dirk Ostwald 
    affiliation: Otto-von-Guericke-Universität Magdeburg
  date: today
  doi: 10.5281/zenodo.10730200
  navbar:   
    title: Probabilistische Datenwissenschaft für die Psychologie
  repo-url: https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - index.qmd
    # - part: 000-Einführung.qmd
    #   chapters:
    #     - 001-Wissenschaft.qmd
    #     - 002-Psychologische-Forschung.qmd
    #     - 003-Quantifizierung.qmd
    #     - 004-Studiendesign.qmd
    #     - 005-Ethik.qmd
    #     - 006-Dokumentation.qmd
    - part: 100-Mathematische-Grundlagen.qmd
      chapters: 
        - 101-Sprache-und-Logik.qmd
    #     - 102-Mengen.qmd
    #     - 103-Summen-Produkte-Potenzen.qmd
    #     - 104-Funktionen.qmd
    #     - 105-Differentialrechnung.qmd
    #     - 106-Folgen-Grenzwerte-Stetigkeit.qmd
    #     - 107-Integralrechnung.qmd
    #     - 108-Vektoren.qmd
    #     - 109-Matrizen.qmd
    #     - 110-Eigenanalyse.qmd
    #     - 111-Deskriptivstatistiken.qmd
    #     - 112-Repräsentationstheorie.qmd
    # - part: 200-Imperative-Programmierung.qmd
    #   chapters:
    #   #   - 201-Informatische-Grundbegriffe.qmd
    #     - 202-Arithmetik-und-Variablen.qmd
    #   #   - 203-Datenstrukturen-und-Datenmanagement.qmd
    #   #   - 204-Kontrollstrukturen-und-Funktionen.qmd
    # - part: 300-Wahrscheinlichkeitstheorie.qmd
    #   chapters:
    #     - 301-Wahrscheinlichkeitsräume.qmd
    #     - 302-Elementare-Wahrscheinlichkeiten.qmd
    #     - 303-Zufallsvariablen.qmd
    #     - 304-Zufallsvektoren.qmd
    #     - 305-Erwartungswerte.qmd
    #     - 306-Ungleichungen.qmd
    #     - 307-Grenzwerte.qmd
    #     - 308-Transformationstheoreme.qmd
    #     - 309-Normalverteilungstransformationen.qmd
    #     - 310-Multivariate-Normalverteilungen.qmd
    # - part: 400-Inferenz.qmd
    #   chapters:
    #     - 401-Grundbegriffe.qmd
    #     - 402-Punktschätzung.qmd
    #     - 403-Konfidenzintervalle.qmd
    #     - 404-Hypothesentests.qmd
    # - part: 500-Allgemeines-Lineares-Modell.qmd
    #   chapters:
    #     - 501-Regression.qmd
    #     - 502-Korrelation.qmd
    #     - 503-Modellformulierung.qmd
    #     - 504-Parameterschätzung.qmd
    #     - 505-T-Statistiken.qmd
    #     - 506-F-Statistiken.qmd
    #     - 507-T-Tests.qmd
    #     - 508-Einfaktorielle-Varianzanalyse.qmd
    #     - 509-Zweifaktorielle-Varianzanalyse.qmd
    #     - 510-Partielle-Korrelation.qmd
    #     - 511-Multiple-Regression.qmd
    #     - 512-Kovarianzanalyse.qmd
    #     - 513-Die-lm-Funktion.qmd
    # - part: 600-Multivariate-Inferenz.qmd
    #   chapters:
    #     - 601-Multivariate-Deskriptivstatistiken.qmd
    #     - 602-Einstichproben-T2-Tests.qmd
    #     - 603-Einfaktorielle-Varianzanalyse.qmd
    #     - 604-Kanonische-Korrelationsanalyse.qmd
    # - part: 700-Prädiktive-Modellierung
    #   chapters:
    # - part: 800-Psychometrische-Verfahren.qmd
    #   chapters:
      # - 801-Klassische-Testtheorie.qmd
      # - 802-Item-Response-Theorie.qmd
        # - 803-Explorative-Faktorenanalyse.qmd
        # - 804-Konfirmatorische-Faktorenanalyse.qmd
    - Referenzen.qmd
bibliography: Referenzen.bib
format:
  html:
    theme: 
      - yeti
    fontsize: 0.9em
    fig-format: png
    toc-location: left
    code-line-numbers: true
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    keep-tex: false
    code-line-numbers: false
    latex-tinytex: false
    include-in-header:
      - _texheader.tex







