project:
  type: book
lang: de
csl: https://www.zotero.org/styles/apa
book:
  title: "Probabilistische Datenwissenschaft für die Psychologie"
  author:
  - name: Dirk Ostwald 
    affiliation: Otto-von-Guericke-Universität Magdeburg
  date: today
  doi: 10.5281/zenodo.10730200
  navbar:   
    title: Probabilistische Datenwissenschaft für die Psychologie
  repo-url: https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: 100-Mathematische-Grundlagen.qmd
      chapters: 
        - 101-Sprache-und-Logik.qmd
        - 102-Mengen.qmd
        - 103-Summen-Produkte-Potenzen.qmd
        - 104-Funktionen.qmd
        - 105-Differentialrechnung.qmd
        - 106-Folgen-Grenzwerte-Stetigkeit.qmd
        - 107-Integralrechnung.qmd
        - 108-Vektoren.qmd
        - 109-Matrizen.qmd
        - 110-Eigenanalyse.qmd
    - part: 200-Wahrscheinlichkeitstheorie.qmd
      chapters:
        - 201-Wahrscheinlichkeitsräume.qmd
        - 202-Elementare-Wahrscheinlichkeiten.qmd
        - 203-Zufallsvariablen.qmd
        - 204-Zufallsvektoren.qmd
        - 205-Erwartungswerte.qmd
        - 206-Ungleichungen.qmd
        - 207-Grenzwerte.qmd
        - 208-Transformationstheoreme.qmd
        - 209-Normalverteilungstransformationen.qmd
        - 210-Multivariate-Normalverteilungen.qmd
    - part: Frequentistische Inferenz
      chapters:
        - 301-Grundbegriffe.qmd
        - 302-Punktschätzung.qmd
        - 303-Konfidenzintervalle.qmd
        - 304-Hypothesentests.qmd
    - part: Das Allgemeine Lineare Modell
      chapters:
        - 401-Regression.qmd
        - 402-Korrelation.qmd
        - 403-Modellformulierung.qmd
        - 404-Parameterschätzung.qmd
        - 405-T-Statistiken.qmd
        - 406-F-Statistiken.qmd
        - 407-T-Tests.qmd
        - 408-Einfaktorielle-Varianzanalyse.qmd
        - 409-Zweifaktorielle-Varianzanalyse.qmd
        - 410-Partielle-Korrelation.qmd
        - 411-Multiple-Regression.qmd
    - part: Multivariate Inferenz
      chapters:
        - 501-Datendeskription.qmd
        - 502-Einstichproben-T2-Tests.qmd
        - 503-Einfaktorielle-Varianzanalyse.qmd
        - 504-Kanonische-Korrelationsanalyse.qmd
    - Referenzen.qmd
bibliography: Referenzen.bib
format:
  html:
    theme: 
      - yeti
    fontsize: 0.9em
    fig-format: png
    toc-location: left
    code-line-numbers: true
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    keep-tex: false
    code-line-numbers: false
    include-in-header:
      - _texheader.tex





