project:
  type: book
lang: de
csl: https://www.zotero.org/styles/apa
pdf-engine: xelatex
book:
  title: "Probabilistische Datenwissenschaft für die Psychologie"
  author:
  - name: Dirk Ostwald 
    affiliation: Otto-von-Guericke-Universität Magdeburg
  date: today
  doi: 10.5281/zenodo.10730200
  navbar:   
    title: Probabilistische Datenwissenschaft für die Psychologie
  repo-url: https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: _part_1/100-Mathematische-Grundlagen.qmd
      chapters: 
        - _part_1/101-Sprache-und-Logik.qmd
        - _part_1/102-Mengen.qmd 
        - _part_1/103-Summen-Produkte-Potenzen.qmd
        - _part_1/104-Funktionen.qmd
        - _part_1/105-Folgen-Grenzwerte-Stetigkeit.qmd
        - _part_1/106-Differenzialrechnung.qmd      
        - _part_1/107-Integralrechnung.qmd
        - _part_1/108-Vektoren.qmd
        - _part_1/109-Matrizen.qmd
        - _part_1/110-Deskriptivstatistiken.qmd
    - part: _part_2/200-Imperative-Programmierung.qmd
      chapters:
        - _part_2/201-Informatische-Grundbegriffe.qmd
        - _part_2/202-Arithmetik-und-Variablen.qmd
        - _part_2/203-Datenstrukturen.qmd
        - _part_2/204-Vektoren.qmd
        - _part_2/205-Matrizen-und-Arrays.qmd
        - _part_2/206-Listen-Dataframes-und-Tibbles.qmd
        - _part_2/207-Datenmanagement.qmd
        - _part_2/208-Kontrollstrukturen.qmd
    - part: _part_3/300-Wahrscheinlichkeitstheorie.qmd
      chapters:
        - _part_3/301-Wahrscheinlichkeitsräume.qmd
        - _part_3/302-Elementare-Wahrscheinlichkeiten.qmd
        - _part_3/303-Zufallsvariablen.qmd
        - _part_3/304-Zufallsvektoren.qmd
        - _part_3/305-Erwartungswerte.qmd
        - _part_3/306-Varianzen.qmd
        - _part_3/307-Kovarianzen.qmd
        - _part_3/308-Ungleichungen.qmd
        - _part_3/309-Grenzwerte.qmd
        - _part_3/310-Transformationen.qmd
        - _part_3/311-Normalverteilungen.qmd
    - part: _part_4/400-Inferenz.qmd
      chapters:
        - _part_4/401-Frequentistische-Inferenz.qmd
        - _part_4/402-Punktschätzung.qmd
        - _part_4/403-Konfidenzintervalle.qmd
        - _part_4/404-Hypothesentests.qmd
    - part: _part_5/500-Allgemeines-Lineares-Modell.qmd
      chapters:
        - _part_5/501-Regression.qmd
        - _part_5/502-Korrelation.qmd
        - _part_5/503-Modellformulierung.qmd
        - _part_5/504-Parameterschätzung.qmd
        - _part_5/505-T-Statistiken.qmd
        - _part_5/506-F-Statistiken.qmd
        - _part_5/507-T-Tests.qmd
        - _part_5/508-Einfaktorielle-Varianzanalyse.qmd
        - _part_5/509-Zweifaktorielle-Varianzanalyse.qmd
        - _part_5/510-Partielle-Korrelation.qmd
        - _part_5/511-Multiple-Regression.qmd
    - part: _part_7/700-Multivariate-Inferenz.qmd
      chapters:
        - _part_7/701-Multivariate-Deskriptivstatistiken.qmd
        - _part_7/702-Einstichproben-T2-Tests.qmd
        - _part_7/703-Einfaktorielle-Varianzanalyse.qmd
        - _part_7/704-Kanonische-Korrelationsanalyse.qmd
    - part: _part_9/900-Psychometrische-Verfahren.qmd
      chapters:
        - _part_9/901-Psychologische-Tests.qmd
        - _part_9/902-Klassische-Testtheorie.qmd
        - _part_9/903-Faktoranalyse.qmd
    - Referenzen.qmd
bibliography: Referenzen.bib
format:
  html:
    theme: yeti
    fontsize: 0.9em
    fig-format: png
    toc-location: left
    code-line-numbers: true
    grid:
      sidebar-width: 275px
      body-width: 800px
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    keep-tex: false
    code-line-numbers: false
    latex-tinytex: false
    include-in-header:
      - _texheader.tex







