# Mathematische Grundlagen

Als Sprache der naturwissenschaftlichen Modellbildung ist die Mathematik auch die 
Sprache der probabilistischen Datenwissenschaft der Psychologie. Die Funktion der Mathematik 
ist dabei die einer Vermittlerin zwischen intuitiver Wissenschaftssprache und der Vielfalt 
von Programmiersprachen, die zur Implementation datenwissenschaftlicher Analysen 
eingesetzt werden. Mathematische Begriffsbildungen erlauben es, Konzepte sehr 
genau und allgemein verständlich zu greifen und unabhängig von den Ungenauigkeiten 
der naturwissenschaftlichen Alltagsprache oder den Idiosynkratien verschiedener 
Programmiersprachen zu kommunizieren. Natürlich kann die mathematische Sprache 
diese Rolle nicht losgelöst von wissenschaftssprachlicher Intuition oder praktischer 
Anwendung einnehmen. Die Mathematik ist in der probabilistischen Datenanalyse also 
nie Selbstzweck, sondern immer als angewandte Mathematik zu verstehen.

In diesem Teil stellen wir nach einigen Gedanken zu den grundlegenden Konzepten
der Mathematik (@sec-sprache-und-logik) mit den Mengen und den Funktionen 
(@def-mengen und @sec-funktionen) die beiden Grundpfeiler der modernen Mathematik 
in komprimierter Form dar. Wir ergänzen diese Darstellung durch einige im notationelle
Aspekte in @sec-summen-produkte-potenzen. Eng verwoben mit dem Begriff der
Funktion sind die Differentialrechnung und die Integralrechnung (@sec-differenzialrechnung
und @sec-integralrechnung). Auch hier geht es nicht um eine 
erschöpfende Darstellung, sondern insbesondere um die Erläuterung einiger Grundlagen, 
die für die datenwissenschaftlich zentralen Konzepte der Optimierung sowie dem Umgang 
mit Wahrscheinlichkeitsfunktionen zentral sind. Wir ergänzen diese Abschnitte mit 
einigen oberflächlichen Gedanken zu den analytischen Grundlagen der Differenzialrechnung 
und Integralrechnung in @sec-folgen-grenzwerte-stetigkeit. Im Umgang mit den 
großen Datenmengen der zeitgenössischen Wissenschaft hat sich die Matrixschreibweise 
als hilfreich erwiesen. Wir widmen uns diesem Teilbereich der linearen Algebra zunächst
für einspaltige Matrizen in @sec-vektoren und dann ausführlich in @sec-matrizen, 
wiederrum mit dem Ziel, notationelle und rechnerische Grundlagen für spätere Abschnitte bereitzustellen.

Insgesamt dient dieser Teil also vor allem der Kurzeinführung von Grundlagen,
die in anderen Teilen wieder aufgegriffen werden, und dabei vor allem auch der 
Einführung einer einheitlichen Notation. Je nach Bedarf und Interesse ist 
natürlich ein vertieftes Selbststudium der verschiedenen Inhalte angezeigt. In 
den folgenden Literaturhinweisen führen wir überblicksartig Quellen und 
Leseempfehlungen zu den hier betrachteten Inhalten.  

### Literaturhinweise {-}

@baerwolff2017 und @arens2018 bilden die primäre Grundlage für viele hier 
dargestellen Themen und bieten einen exzellenten und umfassenden Einstieg 
in die behandelte Materie. Auf internationaler Ebene geben @spivak2008
und @strang2009 sehr gut lesbare Einführungen in die Differenzialrechnung bzw.
die lineare Algebra. Ein tieferes Verständnis insbesondere analytischer Konzepte 
liefern zum Beispiel @abbott2015 und @chiossi2021. @searle1982 bietet eine kompakte
Darstellung derjenigen Aspekte der Matrizenrechnung und linearen Algebra, die
im Bereich der probabilistischen Datenanalyse hauptsächlich zum Einsatz kommen.
@deisenroth2020 bietet einen Überblick über viele der hier behandelten Themen 
unter dem Moniker des maschinellen Lernens.







