<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>31&nbsp; Point estimation – Probabilistic Data Science for Psychology</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../_part_4/403-Confidence-Intervals.html" rel="next">
<link href="../_part_4/401-Frequentist-Inference.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d6825770f4e37b80aa8621686b79c10e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Probabilistic Data Science for Psychology</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dirk-ostwald.github.io/"> 
<span class="menu-text">Deutsch</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Probabilistic-Data-Science-for-Psychology.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_part_4/400-Inference.html">Inference</a></li><li class="breadcrumb-item"><a href="../_part_4/402-Point-Estimation.html"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Point estimation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_1/100-Mathematical-Foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mathematical foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/101-Language-and-Logic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Language and logic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/102-Sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Sets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/103-Sums-Products-Powers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sums, products, powers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/104-Functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/105-Sequences-Limits-Continuity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sequences, limits, continuity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/106-Differential-Calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Differential calculus</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/107-Integral-Calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Integral calculus</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/108-Vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/109-Matrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Matrices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/110-Descriptive-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_2/200-Imperative-Programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Imperative programming</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/201-Basic-Concepts-of-Computer-Science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Basic concepts of computer science</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/202-Arithmetic-and-Variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Arithmetic and variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/203-Data-Structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Data structures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/204-Vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/205-Matrices-and-Arrays.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Matrices and arrays</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/206-Lists-Dataframes-and-Tibbles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Lists, dataframes, and tibbles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/207-Data-Management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Data management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/208-Control-Structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Control structures</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_3/300-Probability-Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/301-Probability-Spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Probability spaces</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/302-Elementary-Probabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Elementary probabilities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/303-Random-Variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Random variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/304-Random-Vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Random vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/305-Expectations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Expectations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/306-Variances.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Variances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/307-Covariances.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Covariances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/308-Inequalities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inequalities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/309-Limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Limits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/310-Transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Transformations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/311-Normal-Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Normal distributions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_4/400-Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/401-Frequentist-Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Frequentist inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/402-Point-Estimation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Point estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/403-Confidence-Intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/404-Hypothesis-Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Hypothesis tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_5/500-General-Linear-Model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General linear model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/501-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/502-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/503-Model-Formulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Model formulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/504-Parameter-Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Parameter estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/505-T-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">T-statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/506-F-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">F-statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-maximum-likelihood-estimation" id="toc-sec-maximum-likelihood-estimation" class="nav-link active" data-scroll-target="#sec-maximum-likelihood-estimation"><span class="header-section-number">31.1</span> Maximum likelihood estimation</a>
  <ul class="collapse">
  <li><a href="#examples" id="toc-examples" class="nav-link" data-scroll-target="#examples">Examples</a></li>
  <li><a href="#sec-mean-squared-error" id="toc-sec-mean-squared-error" class="nav-link" data-scroll-target="#sec-mean-squared-error"><span class="header-section-number">31.2.3</span> Mean squared error</a></li>
  <li><a href="#sec-cramer-rao-inequality" id="toc-sec-cramer-rao-inequality" class="nav-link" data-scroll-target="#sec-cramer-rao-inequality"><span class="header-section-number">31.2.4</span> Cramér-Rao inequality</a></li>
  </ul></li>
  <li><a href="#sec-asymptotic-estimator-properties" id="toc-sec-asymptotic-estimator-properties" class="nav-link" data-scroll-target="#sec-asymptotic-estimator-properties"><span class="header-section-number">31.3</span> Asymptotic estimator properties</a>
  <ul class="collapse">
  <li><a href="#sec-asymptotic-unbiasedness" id="toc-sec-asymptotic-unbiasedness" class="nav-link" data-scroll-target="#sec-asymptotic-unbiasedness"><span class="header-section-number">31.3.1</span> Asymptotic unbiasedness</a></li>
  <li><a href="#sec-consistency" id="toc-sec-consistency" class="nav-link" data-scroll-target="#sec-consistency"><span class="header-section-number">31.3.2</span> Consistency</a></li>
  <li><a href="#sec-asymptotic-normality" id="toc-sec-asymptotic-normality" class="nav-link" data-scroll-target="#sec-asymptotic-normality"><span class="header-section-number">31.3.3</span> Asymptotic normality</a></li>
  <li><a href="#sec-asymptotic-efficiency" id="toc-sec-asymptotic-efficiency" class="nav-link" data-scroll-target="#sec-asymptotic-efficiency"><span class="header-section-number">31.3.4</span> Asymptotic efficiency</a></li>
  </ul></li>
  <li><a href="#sec-properties-of-maximum-likelihood-estimators" id="toc-sec-properties-of-maximum-likelihood-estimators" class="nav-link" data-scroll-target="#sec-properties-of-maximum-likelihood-estimators"><span class="header-section-number">31.4</span> Properties of maximum likelihood estimators</a></li>
  <li><a href="#bibliographic-remarks" id="toc-bibliographic-remarks" class="nav-link" data-scroll-target="#bibliographic-remarks"><span class="header-section-number">31.5</span> Bibliographic remarks</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages/edit/main/_part_4/402-Point-Estimation.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_part_4/400-Inference.html">Inference</a></li><li class="breadcrumb-item"><a href="../_part_4/402-Point-Estimation.html"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Point estimation</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-point-estimation" class="quarto-section-identifier"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Point estimation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this chapter, in the sense of the terminology introduced in <a href="401-Frequentist-Inference.html" class="quarto-xref"><span>Chapter 30</span></a>, we always assume a parametric product model <span class="math display">\[\begin{equation}
\mathcal{M} := \{\mathcal{Y},\mathcal{A}, \{\mathbb{P}_\theta| \theta \in \Theta\}\}
\end{equation}\]</span> with <span class="math inline">\(n\)</span>-dimensional sample space (e.g.&nbsp;<span class="math inline">\(\mathcal{Y} := \mathbb{R}^n\)</span>), <span class="math inline">\(d\)</span>-dimensional parameter space <span class="math inline">\(\Theta \subset \mathbb{R}^d\)</span>, and given PMF or PDF <span class="math inline">\(p_\theta\)</span> for all <span class="math inline">\(\theta \in \Theta\)</span>. <span class="math inline">\(y := (y_1,...,y_n)\)</span> denotes the sample of independent and identically distributed random variables belonging to <span class="math inline">\(\mathcal{M}\)</span>; throughout, therefore, <span class="math display">\[\begin{equation}
y_1,...,y_n \sim \mathbb{P}_\theta.
\end{equation}\]</span> The nature and aim of the <em>point estimation</em> treated here is to give, based on the sample, a guess that is as good as possible for a characteristic quantity of the distribution <span class="math inline">\(\mathbb{P}_\theta\)</span> of a sample variable. The guess has the same mathematical nature as the corresponding characteristic quantity, for example a scalar value for a scalar parameter. This is not the only possibility for estimation; with confidence intervals we will encounter one way of estimating scalar values by intervals. The characteristic quantities of <span class="math inline">\(\mathbb{P}_\theta\)</span> to be estimated are often simply the true, but unknown, parameters themselves. We treat this case in detail in <a href="#sec-maximum-likelihood-estimation" class="quarto-xref"><span>Section 31.1</span></a>. However, many basic results of frequentist point estimation also remain valid when the quantities to be estimated are not the parameters themselves, but functions of them. Examples are the estimation of the expectation, variance, or standard deviation of <span class="math inline">\(\mathbb{P}_\theta\)</span>. We begin, however, with <em>parameter estimation</em>. To estimate the true, but unknown, parameter of an inference model, frequentist inference uses so-called <em>parameter point estimators</em>.</p>
<div id="def-parameter-point-estimator" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.1</strong></span> <span class="math inline">\(\mathcal{M} := (\mathcal{Y}, \mathcal{A}, \{\mathbb{P}_\theta|\theta \in \Theta\})\)</span> be a frequentist inference model, let <span class="math inline">\((\Theta,\mathcal{S})\)</span> be a measurable space, and let <span class="math inline">\(\hat{\theta} : \mathcal{Y} \to \Theta\)</span> be a mapping. Then <span class="math inline">\(\hat{\theta}\)</span> is called a <em>parameter point estimator</em> for <span class="math inline">\(\theta\)</span>.</p>
</div>
<p>Parameter point estimators are usually also simply called <em>parameter estimators</em>. In the sense of <a href="401-Frequentist-Inference.html#def-estimator" class="quarto-xref">Definition&nbsp;<span>30.3</span></a>, parameter point estimators are estimators with <span class="math inline">\(\tau := \mbox{id}_\Theta\)</span>. Parameter point estimators are therefore functions of data and take numerical values in the parameter space. As functions of random variables, parameter estimators are of course also random variables. Often, notation does not distinguish between <span class="math inline">\(\hat{\theta}\)</span> as a random variable and <span class="math inline">\(\hat{\theta}(y)\)</span> as the value of this random variable.</p>
<p><a href="#def-parameter-point-estimator" class="quarto-xref">Definition&nbsp;<span>31.1</span></a> evidently does not specify how a parameter point estimator is to be constructed or to what extent it may then be a sensible estimator. In what follows, with <em>maximum likelihood estimation</em>, we first discuss a general principle that allows parameter estimators to be determined for a given frequentist inference model and that, as we will see later, guarantees certain desirable properties (<a href="#sec-properties-of-maximum-likelihood-estimators" class="quarto-xref"><span>Section 31.4</span></a>). These properties generally concern its qualitative distributional behavior for a fixed sample size or in the limit of an infinitely large sample size. We introduce these properties in <a href="#sec-estimator-properties-in-finite-samples" class="quarto-xref"><span>Section 31.2</span></a> and <a href="#sec-asymptotic-estimator-properties" class="quarto-xref"><span>Section 31.3</span></a>.</p>
<section id="sec-maximum-likelihood-estimation" class="level2" data-number="31.1">
<h2 data-number="31.1" class="anchored" data-anchor-id="sec-maximum-likelihood-estimation"><span class="header-section-number">31.1</span> Maximum likelihood estimation</h2>
<p>The basic idea of maximum likelihood estimation is to choose, as a guess for a true, but unknown, parameter value, that parameter value for which the probability of the observed data is maximal. For this, it is first necessary to consider the probability of observed data in a frequentist inference model as a function of the parameter in question. This is enabled and formalized by the <em>likelihood function</em> and its logarithm, the <em>log-likelihood function</em>. We define these terms here for parametric product models.</p>
<div id="def-likelihood-function-and-log-likelihood-function" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.2 (Likelihood function and log-likelihood function)</strong></span> Let <span class="math inline">\(\mathcal{M}\)</span> be a parametric product model with PMF or PDF <span class="math inline">\(p_\theta\)</span>. Then the <em>likelihood function</em> is defined as <span class="math display">\[\begin{equation}
L : \Theta \to [0,\infty[, \theta \mapsto L(\theta) := \prod_{i=1}^n p_\theta(y_i)
\end{equation}\]</span> and the <em>log-likelihood function</em> is defined as <span class="math display">\[\begin{equation}
\ell_n : \Theta \to \mathbb{R}, \theta \mapsto \ell(\theta) := \ln L(\theta).
\end{equation}\]</span></p>
</div>
<p>The likelihood function is thus a function of the parameter, and its function values are the values of the joint PMF or PDF of observed data values <span class="math inline">\(y_1,...,y_n\)</span>. In general, there is no reason to assume that a likelihood function integrates to 1 over the parameter space; the likelihood function is therefore generally not a PMF or PDF. The log-likelihood function is simply the logarithm of the likelihood function. A parameter estimator obtained according to the principle of maximum likelihood estimation is now intended to maximize the likelihood function or the log-likelihood function. This leads to the following definition of a <em>maximum likelihood estimator</em>.</p>
<div id="def-maximum-likelihood-estimator" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.3 (Maximum likelihood estimator)</strong></span> Let <span class="math inline">\(\mathcal{M}\)</span> be a parametric product model with parameter <span class="math inline">\(\theta \in \Theta\)</span>. A <em>maximum likelihood estimator</em> of <span class="math inline">\(\theta\)</span> is defined as <span class="math display">\[\begin{equation}
\hat{\theta}^{\mbox{\tiny ML}} : \mathcal{Y} \to \Theta,
y \mapsto \hat{\theta}^{\mbox{\tiny ML}}(y)
:= \mbox{argmax}_{\theta \in \Theta} L(\theta)
= \mbox{argmax}_{\theta \in \Theta} \ell(\theta)
\end{equation}\]</span></p>
</div>
<p>Note in <a href="#def-maximum-likelihood-estimator" class="quarto-xref">Definition&nbsp;<span>31.3</span></a> that a maximum point of the log-likelihood function corresponds to the maximum point of the likelihood function, because the logarithm function is monotonically increasing. Working with the log-likelihood function is often easier than working directly with the likelihood function, for example when exponential functions occur in the PMF or PDF of the model. Furthermore, note that <a href="#def-likelihood-function-and-log-likelihood-function" class="quarto-xref">Definition&nbsp;<span>31.2</span></a> implies <span class="math display">\[\begin{equation}
\hat{\theta}^{\mbox{\tiny ML}}(y)
= \mbox{argmax}_{\theta \in \Theta} \prod_{i=1}^n p_\theta(y_i)
= \mbox{argmax}_{\theta \in \Theta} \sum_{i=1}^n \ln p_\theta(y_i)
\end{equation}\]</span> which makes the dependence of a maximum likelihood estimator on the data clear.</p>
<p>With <a href="#def-maximum-likelihood-estimator" class="quarto-xref">Definition&nbsp;<span>31.3</span></a>, maximum likelihood estimation is therefore the problem of determining extrema of a function. For these extrema, differential calculus provides, as is well known, necessary and sufficient conditions (cf. <a href="../_part_1/106-Differential-Calculus.html#sec-analytic-optimization" class="quarto-xref"><span>Section 6.2</span></a>). In its application to obtaining maximum likelihood estimators, one usually contents oneself, due to the functional form of the functions considered, with the fulfillment of the necessary condition. Depending on the nature of the log-likelihood function, methods of analytic or numerical optimization then suggest themselves. In the following classical examples we use an analytic approach. We proceed in the following steps:</p>
<ol type="1">
<li>Formulation of the log-likelihood function.</li>
<li>Determination of the first derivative of the log-likelihood function and setting it to zero.</li>
<li>Solving for potential maximum points.</li>
</ol>
<p>In <a href="#thm-maximum-likelihood-estimator-of-bernoulli-model" class="quarto-xref">Theorem&nbsp;<span>31.1</span></a> we show that the maximum likelihood estimator for the parameter of the Bernoulli model from <a href="401-Frequentist-Inference.html#exm-bernoulli-model" class="quarto-xref">Example&nbsp;<span>30.2</span></a> is given by the corresponding sample mean, and in <a href="#thm-maximum-likelihood-estimators-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>31.2</span></a> we show that the maximum likelihood estimators for the expectation and variance parameters of the normal distribution model from <a href="401-Frequentist-Inference.html#exm-normal-distribution-model" class="quarto-xref">Example&nbsp;<span>30.1</span></a> are given by the sample mean and a modified sample variance, respectively.</p>
<section id="examples" class="level3 unnumbered">
<h3 class="unnumbered anchored">Examples</h3>
<div id="thm-maximum-likelihood-estimator-of-bernoulli-model" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.1 (Maximum likelihood estimator of the Bernoulli model)</strong></span> Let <span class="math inline">\(\mathcal{M}\)</span> be the Bernoulli model, that is, <span class="math inline">\(y_1,...,y_n \sim \mbox{Bern}(\mu)\)</span>. Then <span class="math display">\[\begin{equation}
\hat{\mu}^{\mbox{\tiny ML}} : \{0,1\}^n \to [0,1],
y \mapsto \hat{\mu}^{\mbox{\tiny ML}}(y):= \frac{1}{n}\sum_{i=1}^n y_i
\end{equation}\]</span> is a maximum likelihood estimator of <span class="math inline">\(\mu\)</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>We first formulate the log-likelihood function. For the likelihood function, <span class="math display">\[\begin{equation}
L: ]0,1[ \to ]0,1[,
\mu \mapsto L(\mu)
:= \prod_{i=1}^n \mu^{y_i}(1 - \mu)^{1-y_i}
= \mu^{\sum_{i=1}^n y_i}(1 - \mu)^{n - \sum_{i=1}^n y_i}.
\end{equation}\]</span> Taking logarithms gives <span class="math display">\[\begin{equation}
\ell: ]0,1[ \to \mathbb{R}, \mu \mapsto \ell(\mu)
= \ln \mu \sum_{i=1}^n y_i + \ln (1- \mu) \left(n - \sum_{i=1}^n y_i \right).
\end{equation}\]</span> We then evaluate the derivative of the log-likelihood function. We have <span class="math display">\[\begin{align}
\begin{split}
\frac{d}{d\mu} \ell(\mu)
&amp; = \frac{d}{d\mu}\left(\ln \mu \sum_{i=1}^n y_i + \ln (1- \mu) \left(n - \sum_{i=1}^n y_i \right)\right)  \\
&amp; = \frac{d}{d\mu} \ln \mu \sum_{i=1}^n y_i  + \frac{d}{d\mu} \ln (1 - \mu) \left(n - \sum_{i=1}^n y_i \right)  \\
&amp; = \frac{1}{\mu}\sum_{i=1}^n y_i - \frac{1}{1-\mu} \left(n - \sum_{i=1}^n y_i \right).
\end{split}
\end{align}\]</span> Setting this to zero then gives the following as a necessary condition for a maximum likelihood estimator in the Bernoulli model: <span class="math display">\[\begin{equation}
\frac{1}{\hat{\mu}^{\mbox{\tiny ML}}}\sum_{i=1}^n y_i - \frac{1}{1-\hat{\mu}^{\mbox{\tiny ML}}} \left(n - \sum_{i=1}^n y_i \right) = 0.
\end{equation}\]</span> Solving the maximum likelihood equation for <span class="math inline">\(\hat{\mu}^{\mbox{\tiny ML}}\)</span> gives <span class="math display">\[\begin{align}
\begin{split}
\frac{1}{\hat{\mu}^{\mbox{\tiny ML}}}\sum_{i=1}^n y_i - \frac{1}{1-\hat{\mu}^{\mbox{\tiny ML}}} \left(n - \sum_{i=1}^n y_i \right) &amp; = 0 \\
\Leftrightarrow
\hat{\mu}^{\mbox{\tiny ML}}(1 - \hat{\mu}^{\mbox{\tiny ML}})\left(\frac{1}{\hat{\mu}^{\mbox{\tiny ML}}}\sum_{i=1}^n y_i - \frac{1}{1-\hat{\mu}^{\mbox{\tiny ML}}} \left(n - \sum_{i=1}^n y_i \right) \right) &amp; = 0 \\
\Leftrightarrow
\sum_{i=1}^n y_i - \hat{\mu}^{\mbox{\tiny ML}} \sum_{i=1}^n y_i - n \hat{\mu}^{\mbox{\tiny ML}}  + \hat{\mu}^{\mbox{\tiny ML}}\sum_{i=1}^n y_i &amp; = 0 \\
\Leftrightarrow
n \hat{\mu}^{\mbox{\tiny ML}}  &amp; = \sum_{i=1}^n y_i \\
\Leftrightarrow
\hat{\mu}^{\mbox{\tiny ML}}  &amp; = \frac{1}{n} \sum_{i=1}^n y_i. \\
\end{split}
\end{align}\]</span> Thus, <span class="math inline">\(\hat{\mu}^{\mbox{\tiny ML}} = \frac{1}{n}\sum_{i=1}^n y_i\)</span> is a candidate for a maximum likelihood estimator of <span class="math inline">\(\mu\)</span>. This could be verified by considering the second derivative of <span class="math inline">\(\ell\)</span>, but we refrain from doing so here.</p>
</div>
<div id="thm-maximum-likelihood-estimators-of-normal-distribution-model" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.2 (Maximum likelihood estimators of the normal distribution model)</strong></span> Let <span class="math inline">\(\mathcal{M}\)</span> be the normal distribution model, that is, <span class="math inline">\(y_1,...,y_n \sim N\left(\mu,\sigma^2\right)\)</span>. Then <span class="math display">\[\begin{equation}
\hat{\mu}^{\mbox{\tiny ML}} :
\mathbb{R}^n \to \mathbb{R}, y \mapsto \hat{\mu}^{\mbox{\tiny ML}}(y)
:= \frac{1}{n}\sum_{i=1}^n y_i
\end{equation}\]</span> and <span class="math display">\[\begin{equation}
\hat{\sigma}^{2^{\mbox{\tiny ML}}} :
\mathbb{R}^n \to \mathbb{R}_{\ge 0},
y \mapsto \hat{\sigma}^{2^{\mbox{\tiny ML}}}(y)
:= \frac{1}{n}\sum_{i=1}^n \left(y_i - \hat{\mu}^{\mbox{\tiny ML}}\right)^2.
\end{equation}\]</span> are maximum likelihood estimators for <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span>, respectively.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>We first formulate the log-likelihood function. For the likelihood function we obtain <span class="math display">\[\begin{align}
\begin{split}
L: \mathbb{R} \times \mathbb{R}_{&gt;0} \to \mathbb{R}_{&gt;0},
(\mu,\sigma^2) \mapsto L(\mu,\sigma^2)
:= &amp; \prod_{i=1}^n \frac{1}{\sqrt{2\pi \sigma^2}}\exp\left(-\frac{1}{2\sigma^2}(y_i-\mu)^2\right) \\
= &amp; \left(2 \pi \sigma^2\right)^{-\frac{n}{2}}\exp\left(-\frac{1}{2\sigma^2}\sum_{i=1}^n(y_i-\mu)^2\right). \\
\end{split}
\end{align}\]</span> Taking logarithms gives <span class="math display">\[\begin{equation}
\ell: \mathbb{R} \times \mathbb{R}_{&gt;0} \to \mathbb{R},
(\mu,\sigma^2) \mapsto \mathcal{\ell}_n(\mu,\sigma^2)
= -\frac{n}{2} \ln 2\pi - \frac{n}{2} \ln \sigma^2-\frac{1}{2\sigma^2}\sum_{i=1}^n(y_i-\mu)^2.
\end{equation}\]</span> Evaluation of the partial derivatives of the log-likelihood function gives <span class="math display">\[\begin{equation}
\frac{\partial}{\partial{\mu}} \ell(\mu,\sigma^2)
= - \frac{\partial}{\partial{\mu}} \frac{1}{2\sigma^2}\sum_{i=1}^n(y_i-\mu)^2
= - \frac{1}{2\sigma^2}\sum_{i=1}^n \frac{\partial}{\partial{\mu}} (y_i-\mu)^2
= \frac{1}{\sigma^2}\sum_{i=1}^n (y_i-\mu)
\end{equation}\]</span> and <span class="math display">\[\begin{align}
\begin{split}
\frac{\partial}{\partial\sigma^2} \ell(\mu,\sigma^2)
= - \frac{n}{2} \frac{\partial}{\partial\sigma^2} \ln \sigma^2  - \frac{\partial}{\partial\sigma^2} \frac{1}{2\sigma^2}\sum_{i=1}^n(y_i-\mu)^2
= - \frac{n}{2 \sigma^2} + \frac{1}{2\sigma^4}\sum_{i=1}^n(y_i-\mu)^2.
\end{split}
\end{align}\]</span> The system of maximum likelihood equations as an expression of the necessary conditions for extrema of the log-likelihood function therefore has the form <span class="math display">\[\begin{equation}
\sum_{i=1}^n (y_i-\hat{\mu}^{\mbox{\tiny ML}}) = 0
\mbox{ and }
- \frac{n}{2 \hat{\sigma}^{2^{\mbox{\tiny ML}}}} + \frac{1}{2\hat{\sigma}^{4^{\mbox{\tiny ML}}}}\sum_{i=1}^n(y_i-\mu)^2  = 0.
\end{equation}\]</span> Solving the system of maximum likelihood equations first gives <span class="math display">\[\begin{equation}
\sum_{i=1}^n (y_i-\hat{\mu}^{\mbox{\tiny ML}})  = 0
\Leftrightarrow \sum_{i=1}^n y_i  = n\hat{\mu}^{\mbox{\tiny ML}}
\Leftrightarrow \hat{\mu}^{\mbox{\tiny ML}} = \frac{1}{n}\sum_{i=1}^n y_i.
\end{equation}\]</span> Thus, <span class="math display">\[\begin{equation}
\hat{\mu}^{\mbox{\tiny ML}} = \frac{1}{n}\sum_{i=1}^n y_i
\end{equation}\]</span> is a potential maximum likelihood estimator of <span class="math inline">\(\mu\)</span>. Substituting this estimator into the second maximum likelihood equation then gives <span class="math display">\[\begin{align}
\begin{split}
- \frac{n}{2 \hat{\sigma}^{2^{\mbox{\tiny ML}}}} + \frac{1}{2\hat{\sigma}^{4^{\mbox{\tiny ML}}}}\sum_{i=1}^n(y_i-\hat{\mu}^{\mbox{\tiny ML}})^2 &amp; = 0 \\
\Leftrightarrow
- n\hat{\sigma}^{2^{\mbox{\tiny ML}}} + \sum_{i=1}^n(y_i-\hat{\mu}^{\mbox{\tiny ML}})^2 &amp; = 0 \\
\Leftrightarrow
\hat{\sigma}^{2^{\mbox{\tiny ML}}} &amp; = \frac{1}{n} \sum_{i=1}^n(y_i-\hat{\mu}^{\mbox{\tiny ML}})^2.
\end{split}
\end{align}\]</span> Thus, <span class="math display">\[\begin{equation}
\hat{\sigma}^{2^{\mbox{\tiny ML}}} = \frac{1}{n}\sum_{i=1}^n\left(y_i-\hat{\mu}^{\mbox{\tiny ML}}\right)^2
\end{equation}\]</span> is a potential maximum likelihood estimator of <span class="math inline">\(\sigma^2\)</span>. Both potential maximum likelihood estimators can be verified by considering the second derivative of <span class="math inline">\(\ell\)</span>, but we refrain from doing so here.</p>
</div>
<p>Note in <a href="#thm-maximum-likelihood-estimators-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>31.2</span></a> that <span class="math inline">\(\hat{\mu}^{\mbox{\tiny ML}}\)</span> is identical to the sample mean <span class="math inline">\(\bar{y}\)</span>, but <span class="math inline">\(\hat{\sigma}^{2^{\mbox{\tiny ML}}}\)</span> does not coincide with the sample variance <span class="math inline">\(S^2\)</span>. In contrast to the sample variance, the maximum likelihood estimator of <span class="math inline">\(\sigma^2\)</span> contains the multiplicative factor <span class="math inline">\(\frac{1}{n}\)</span>, not, as in the sample variance, the multiplicative factor <span class="math inline">\(\frac{1}{n-1}\)</span>. We will return to this difference in the context of estimator properties.</p>
<div id="exm-application-example-parameter-estimation" class="theorem example">
<p><span class="theorem-title"><strong>Example 31.3 (Application example)</strong></span> To conclude this section, we consider <a href="#thm-maximum-likelihood-estimators-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>31.2</span></a> in the context of the application example from <a href="401-Frequentist-Inference.html#exm-application-example" class="quarto-xref">Example&nbsp;<span>30.5</span></a>. There we based the observed <code>dBDI</code> values on the normal distribution model <span class="math display">\[\begin{equation}
y_1,...,y_n \sim N(\mu,\sigma^2)
\end{equation}\]</span> The maximum likelihood estimators for the parameters of this model can then be evaluated, using <a href="#thm-maximum-likelihood-estimators-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>31.2</span></a>, with the <strong>R</strong> sample mean and sample variance functions <code>mean()</code> and <code>var()</code>, and taking into account the identity <span class="math display">\[\begin{equation}
\frac{n-1}{n}s^2
= \frac{n-1}{n}\cdot\frac{1}{n-1}\sum_{i=1}^n (y_i - \bar{y})^2
= \frac{1}{n}\sum_{i=1}^n \left(y_i - \hat{\mu}^{\mbox{\tiny ML}}\right)^2
= \hat{\sigma}^{2^{\mbox{\tiny ML}}}
\end{equation}\]</span> as in the following <strong>R</strong> code.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>D           <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/bdi-ii-dataset.csv"</span>)       <span class="co"># read dataset</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>y           <span class="ot">=</span> D<span class="sc">$</span>dBDI                                        <span class="co"># select data</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>mu_hat      <span class="ot">=</span> <span class="fu">mean</span>(y)                                       <span class="co"># maximum likelihood estimate of expectation parameter</span></span>
<span id="cb1-4"><a href="#cb1-4"></a>n           <span class="ot">=</span> <span class="fu">length</span>(y)                                     <span class="co"># number of data points</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>sigsqr_hat  <span class="ot">=</span> ((n<span class="dv">-1</span>)<span class="sc">/</span>n)<span class="sc">*</span><span class="fu">var</span>(y)                              <span class="co"># maximum likelihood estimate of variance parameter</span></span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="fu">cat</span>(<span class="st">"mu_hat     :"</span>, mu_hat,<span class="st">"</span><span class="sc">\n</span><span class="st">sigsqr_hat :"</span>, sigsqr_hat)    <span class="co"># output</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>mu_hat     : 3.166667 
sigsqr_hat : 12.63889</code></pre>
</div>
</div>
<p>Based on the principle of maximum likelihood estimation and the available <span class="math inline">\(n = 12\)</span> data points, <span class="math display">\[\begin{equation}
\hat{\mu}^{\mbox{\tiny ML}} = 3.17
\mbox{ and }
\hat{\sigma}^{2^{\mbox{\tiny ML}}} = 12.6
\end{equation}\]</span> are therefore guesses for the true, but unknown, parameters of the model.</p>
<section id="sec-estimator-properties-in-finite-samples" class="level2" data-number="31.2">
<h2 data-number="31.2" class="anchored" data-anchor-id="sec-estimator-properties-in-finite-samples"><span class="header-section-number">31.2</span> Estimator properties in finite samples</h2>
<p>In general, frequentist estimator properties concern the distribution of estimators as a function of the distribution of the data on which they are based. Because data are random in frequentist inference, estimators are random as well. In particular, observed data values are interpreted as realizations of random variables. Estimators as functions of random variables are therefore also random variables, even though, of course, they take only one concrete value when a concrete dataset is available. We distinguish between <em>estimator properties in finite samples</em> and <em>asymptotic estimator properties</em>. The former are the content of this section and concern the properties of an estimator for a fixed sample size <span class="math inline">\(n\)</span>; the latter are the content of <a href="#sec-asymptotic-estimator-properties" class="quarto-xref"><span>Section 31.3</span></a> and concern the properties of an estimator in the limiting case <span class="math inline">\(n \to \infty\)</span> of large sample sizes.</p>
<p>Let <span class="math inline">\((\Sigma,S)\)</span> first be a measurable space and <span class="math inline">\(\hat{\tau} : \mathcal{Y} \to \Sigma\)</span> an estimator of <span class="math inline">\(\tau : \Theta \to \Sigma\)</span> (cf. <a href="401-Frequentist-Inference.html#def-estimator" class="quarto-xref">Definition&nbsp;<span>30.3</span></a>). In what follows, in addition to parameter estimators of the form <span class="math display">\[\begin{equation}
\tau: \Theta \to \Sigma, \tau(\theta) := \theta
\end{equation}\]</span> we will repeatedly consider estimators that, in parametric product models, estimate only functions of the parameters, such as the expectation, variance, or standard deviation of the sample variables. Since, by assumption, the distributions of the sample variables <span class="math inline">\(y_1,...,y_n\)</span> are identical, these are estimators of the form <span class="math display">\[\begin{align}
\begin{split}
\tau: \Theta \to \Sigma,\,
\theta \mapsto \tau(\theta)
\mbox{ with }
\tau(\theta) := \mathbb{E}_\theta(y_1),
\tau(\theta) := \mathbb{V}_\theta(y_1) \mbox{ and }
\tau(\theta) := \mathbb{S}_\theta(y_1).
\end{split}
\end{align}\]</span></p>
<p>In this section we specifically illuminate four aspects of estimator properties in finite samples. In <a href="#sec-unbiasedness" class="quarto-xref"><span>Section 31.2.1</span></a> we first deal with the <em>unbiasedness</em> of an estimator. An estimator is called <em>unbiased</em> if its expectation is identical to the true, but unknown, value <span class="math inline">\(\tau(\theta)\)</span> for all <span class="math inline">\(\theta \in \Theta\)</span>. In <a href="#sec-variance-and-standard-error" class="quarto-xref"><span>Section 31.2.2</span></a> we introduce, with the <em>variance</em> and the <em>standard error</em> of an estimator, two measures of the frequentist variability of estimators. With the <em>mean squared error</em> of an estimator <span class="math inline">\(\hat{\tau}\)</span> as the expectation of the squared deviation of <span class="math inline">\(\hat{\tau}(y)\)</span> from <span class="math inline">\(\tau(\theta)\)</span>, in <a href="#sec-mean-squared-error" class="quarto-xref"><span>Section 31.2.3</span></a> we then introduce an estimator property that allows the accuracy and variability of an estimator to be related in the sense of a so-called <em>bias-variance tradeoff</em>. Finally, the <em>Cramér-Rao inequality</em> discussed in <a href="#sec-cramer-rao-inequality" class="quarto-xref"><span>Section 31.2.4</span></a> gives a lower bound for the variance of unbiased estimators. An unbiased estimator with variance equal to the lower bound given by the Cramér-Rao inequality has the smallest possible variance of all unbiased estimators and is in this sense an optimal estimator.</p>
<section id="sec-unbiasedness" class="level3" data-number="31.2.1">
<h3 data-number="31.2.1" class="anchored" data-anchor-id="sec-unbiasedness"><span class="header-section-number">31.2.1</span> Unbiasedness</h3>
<p>The concept of unbiasedness of an estimator arises in the context of the <em>error</em> and the <em>bias</em> of an estimator as follows.</p>
<div id="def-error-bias-and-unbiasedness" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.4 (Error, bias, and unbiasedness)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be a sample of a frequentist inference model and let <span class="math inline">\(\hat{\tau}\)</span> be an estimator for <span class="math inline">\(\tau\)</span>.</p>
<ul>
<li>The <em>error</em> of <span class="math inline">\(\hat{\tau}\)</span> is defined as <span class="math display">\[\begin{equation}
\hat{\tau}(y) - \tau(\theta).
\end{equation}\]</span></li>
<li>The <em>bias</em> of <span class="math inline">\(\hat{\tau}\)</span> is defined as <span class="math display">\[\begin{equation}
\mbox{B}(\hat{\tau} ) := \mathbb{E}_{\theta}(\hat{\tau} (y)) - \tau(\theta).
\end{equation}\]</span></li>
<li>The estimator <span class="math inline">\(\hat{\tau}\)</span> is called <em>unbiased</em> if <span class="math display">\[\begin{equation}
\mbox{B}(\hat{\tau} ) = 0\Leftrightarrow
\mathbb{E}_{\theta}(\hat{\tau} (y)) = \tau(\theta) \mbox{ for all } \theta \in \Theta \mbox{ and all } n \in \mathbb{N}.
\end{equation}\]</span> Otherwise, <span class="math inline">\(\hat{\tau}\)</span> is called <em>biased</em>.</li>
</ul>
</div>
<p>Note that in <a href="#def-error-bias-and-unbiasedness" class="quarto-xref">Definition&nbsp;<span>31.4</span></a> the error of an estimator depends on the specific realization of the sample <span class="math inline">\(y\)</span>. The bias, in contrast, is the expected error over sample realizations and is therefore independent of a specific realization. For the special case of a parameter point estimator, <a href="#def-error-bias-and-unbiasedness" class="quarto-xref">Definition&nbsp;<span>31.4</span></a> says that it is unbiased if <span class="math display">\[\begin{equation}
\mathbb{E}_{\theta}(\hat{\theta}) = \theta.
\end{equation}\]</span></p>
<p>As first examples of unbiased estimators, the following theorem considers the sample mean and the sample variance as estimators of the expectation and the variance of a sample variable.</p>
<div id="thm-unbiasedness-of-sample-mean-and-sample-variance" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.3 (Unbiasedness of sample mean and sample variance)</strong></span> Let <span class="math inline">\(y := (y_1,...,y_n)\)</span> be the sample of a parametric product model. Then:</p>
<ol type="1">
<li>The sample mean <span class="math display">\[\begin{equation}
\bar{y} := \frac{1}{n}\sum_{i=1}^n y_i
\end{equation}\]</span> is an unbiased estimator of the expectation <span class="math inline">\(\mathbb{E}_\theta(y_1)\)</span>.</li>
<li>The sample variance <span class="math display">\[\begin{equation}
S^2 := \frac{1}{n-1}\sum_{i=1}^n (y_i - \bar{y})^2
\end{equation}\]</span> is an unbiased estimator of the variance <span class="math inline">\(\mathbb{V}_\theta(y_1)\)</span>.</li>
</ol>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>(1) The unbiasedness of the sample mean follows with <a href="../_part_3/305-Expectations.html#thm-expectation-under-linear-affine-combination-of-random-variables" class="quarto-xref">Theorem&nbsp;<span>23.2</span></a> from <span class="math display">\[\begin{align}
\mathbb{E}_\theta(\bar{y})
= \mathbb{E}_\theta \left(\frac{1}{n}\sum_{i=1}^n y_i \right)
= \frac{1}{n}\sum_{i=1}^n \mathbb{E}_\theta\left(y_i \right)
= \frac{1}{n}\sum_{i=1}^n \mathbb{E}_\theta\left(y_1 \right)
= \frac{1}{n} n \mathbb{E}_\theta\left(y_1 \right)
= \mathbb{E}_\theta\left(y_1 \right).
\end{align}\]</span></p>
<p>(2) To show the unbiasedness of the sample variance, we first note that with <a href="../_part_3/307-Covariances.html#thm-variance-of-a-linear-combination-of-random-variables" class="quarto-xref">Theorem&nbsp;<span>25.6</span></a> and independence of the random variables considered, <span class="math display">\[\begin{equation}
\mathbb{V}_\theta(\bar{y})
= \mathbb{V}_\theta\left(\frac{1}{n} \sum_{i=1}^n y_i \right)
= \frac{1}{n^2} \sum_{i=1}^n \mathbb{V}_\theta\left(y_i \right)
= \frac{1}{n^2} \sum_{i=1}^n \mathbb{V}_\theta\left(y_1 \right)
= \frac{1}{n^2} n \mathbb{V}_\theta\left(y_1 \right)
= \frac{\mathbb{V}_\theta\left(y_1 \right)}{n}.
\end{equation}\]</span> Furthermore, for the term of summed squared deviations in the sample variance, <span class="math display">\[\begin{align}
\sum_{i=1}^n \left(y_i - \bar{y}\right)^2 = \sum_{i=1}^n (y_i - \mathbb{E}_\theta(y_1))^2 - n(\bar{y} - \mathbb{E}_\theta(y_1))^2,
\end{align}\]</span> because <span class="math display">\[\begin{align}
\begin{split}
\sum_{i=1}^n \left(y_i - \bar{y}\right)^2
&amp; = \sum_{i=1}^n \left(y_i - \mathbb{E}_\theta(y_1) - \bar{y} + \mathbb{E}_\theta(y_1) \right)^2 \\
&amp; = \sum_{i=1}^n \left((y_i - \mathbb{E}_\theta(y_1)) - (\bar{y} - \mathbb{E}_\theta(y_1)) \right)^2 \\
&amp; = \sum_{i=1}^n (y_i-\mathbb{E}_\theta(y_1))^2 - 2(\bar{y}-\mathbb{E}_\theta(y_1))\left(\sum_{i=1}^n(y_i-\mathbb{E}_\theta(y_1))\right) + \sum_{i=1}^n (\bar{y}-\mathbb{E}_\theta(y_1))^2 \\
&amp; = \sum_{i=1}^n (y_i-\mathbb{E}_\theta(y_1))^2 - 2(\bar{y}-\mathbb{E}_\theta(y_1))\left(\sum_{i=1}^ny_i- n\mathbb{E}_\theta(y_1)\right) + n(\bar{y}-\mathbb{E}_\theta(y_1))^2 \\
&amp; = \sum_{i=1}^n (y_i-\mathbb{E}_\theta(y_1))^2 - 2(\bar{y}-\mathbb{E}_\theta(y_1))\left(n\left(\frac{1}{n}\sum_{i=1}^ny_i\right)- n\mathbb{E}_\theta(y_1)\right) + n(\bar{y}-\mathbb{E}_\theta(y_1))^2 \\
&amp; = \sum_{i=1}^n (y_i-\mathbb{E}_\theta(y_1))^2 - 2n(\bar{y}-\mathbb{E}_\theta(y_1))^2 + n(\bar{y}-\mathbb{E}_\theta(y_1))^2 \\
&amp; = \sum_{i=1}^n (y_i - \mathbb{E}_\theta(y_1))^2 - n(\bar{y} - \mathbb{E}_\theta(y_1))^2.
\end{split}
\end{align}\]</span> Together, this gives <span class="math display">\[\begin{align}
\mathbb{E}_\theta\left((n-1)S^2\right)
&amp; = \mathbb{E}_\theta\left(\sum_{i=1}^n \left(y_i - \bar{y}\right)^2 \right) \\
&amp; = \mathbb{E}_\theta\left(\sum_{i=1}^n (y_i - \mathbb{E}_\theta(y_1))^2 - n(\bar{y} - \mathbb{E}_\theta(y_1))^2 \right) \\
&amp; = \sum_{i=1}^n \mathbb{E}_\theta\left((y_i - \mathbb{E}_\theta(y_1))^2\right) - n \mathbb{E}_\theta\left((\bar{y} - \mathbb{E}_\theta(y_1))^2 \right) \\
&amp; = n \mathbb{V}_\theta(y_1) - n \mathbb{V}_\theta(\bar{y}) \\
&amp; = n \mathbb{V}_\theta(y_1) - n \frac{\mathbb{V}_\theta(y_1)}{n} \\
&amp; = n \mathbb{V}_\theta(y_1) - \mathbb{V}_\theta(y_1) \\
&amp; = (n - 1) \mathbb{V}_\theta(y_1).
\end{align}\]</span> Finally, <span class="math display">\[\begin{equation}
\mathbb{E}_\theta\left(S^2\right)
= \mathbb{E}_\theta\left(\frac{1}{n-1}(n-1)S^2 \right)
= \frac{1}{n-1}\mathbb{E}_\theta\left((n-1)S^2 \right)
= \frac{1}{n-1}(n - 1)  \mathbb{V}_\theta(y_1)
= \mathbb{V}_\theta(y_1)
\end{equation}\]</span> and thus the unbiasedness of the sample variance as an estimator of the variance.</p>
</div>
<p>Of course, in <a href="#thm-unbiasedness-of-sample-mean-and-sample-variance" class="quarto-xref">Theorem&nbsp;<span>31.3</span></a>, due to the identical distribution of the sample variables of a parametric product model, the sample mean and the sample variance are also unbiased estimators of the expectation and variance of any sample variable <span class="math inline">\(y_i\)</span> with <span class="math inline">\(1 \le i \le n\)</span>. Note that in the proof of the unbiasedness of the sample variance, the denominator <span class="math inline">\(n-1\)</span> in the definition of the sample variance plays a decisive role.</p>
<p>Although the sample variance is an unbiased estimator of the variance of a sample variable of a parametric product model, this does not hold for the sample standard deviation as an estimator of the standard deviation. This is the content of the following theorem.</p>
<div id="thm-bias-of-sample-standard-deviation" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.4 (Bias of the sample standard deviation)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model. Then the sample standard deviation <span class="math display">\[\begin{equation}
S := \sqrt{S^2}
\end{equation}\]</span> is a biased estimator of the standard deviation <span class="math inline">\(\mathbb{S}_\theta(y_1)\)</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>We first note that <span class="math inline">\(\sqrt{\cdot}\)</span> is a strictly concave function and <span class="math inline">\(\sigma^2 &gt; 0\)</span>. With Jensen’s inequality <span class="math inline">\(\mathbb{E}(f(\xi)) &lt; f(\mathbb{E}(\xi))\)</span> for strictly concave functions (cf. <a href="../_part_3/308-Inequalities.html#thm-jensens-inequality" class="quarto-xref">Theorem&nbsp;<span>26.5</span></a>), it follows that <span class="math display">\[\begin{equation}
\mathbb{E}_\theta(S)
= \mathbb{E}_\theta\left(\sqrt{S^2}\right)
&lt; \sqrt{\mathbb{E}_\theta(S^2)}
= \sqrt{\mathbb{V}_\theta(y_1)}
= \mathbb{S}_\theta(y_1).
\end{equation}\]</span></p>
</div>
<p>In general, nonlinear transformations of unbiased estimators often lead to biased estimators, but we will not deepen this point further here.</p>
<div id="exm-simulation-example-unbiasedness" class="theorem example">
<p><span class="theorem-title"><strong>Example 31.1 (Simulation example)</strong></span> The following <strong>R</strong> code illustrates the concepts of unbiasedness and bias of the sample mean, sample variance, and sample standard deviation using the example of a parametric product model with sample distribution <span class="math display">\[\begin{equation}
y_1,...,y_{12} \sim N(1.7,2)
\end{equation}\]</span> The expectations of the estimators are estimated by their sample means across many realizations of <span class="math inline">\(y_1,...,y_{12}\)</span> as a function of the number of realizations (simulations).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># model formulation</span></span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">set.seed</span>(<span class="dv">0</span>)                          <span class="co"># random number generator</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>mu      <span class="ot">=</span> <span class="fl">1.7</span>                         <span class="co"># true, but unknown, expectation parameter</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>sigsqr  <span class="ot">=</span> <span class="dv">2</span>                           <span class="co"># true, but unknown, variance parameter</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>n       <span class="ot">=</span> <span class="dv">12</span>                          <span class="co"># sample size n</span></span>
<span id="cb3-6"><a href="#cb3-6"></a>nsim    <span class="ot">=</span> <span class="fl">5e4</span>                         <span class="co"># number of simulations</span></span>
<span id="cb3-7"><a href="#cb3-7"></a>y_bar   <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,nsim)               <span class="co"># sample mean array</span></span>
<span id="cb3-8"><a href="#cb3-8"></a>s_sqr   <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,nsim)               <span class="co"># sample variance array</span></span>
<span id="cb3-9"><a href="#cb3-9"></a>s       <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,nsim)               <span class="co"># sample standard deviation array</span></span>
<span id="cb3-10"><a href="#cb3-10"></a></span>
<span id="cb3-11"><a href="#cb3-11"></a><span class="co"># simulation iterations</span></span>
<span id="cb3-12"><a href="#cb3-12"></a><span class="cf">for</span>(sim <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nsim){</span>
<span id="cb3-13"><a href="#cb3-13"></a></span>
<span id="cb3-14"><a href="#cb3-14"></a>    <span class="co"># sample realization of y_1,...,y_{12}</span></span>
<span id="cb3-15"><a href="#cb3-15"></a>    y          <span class="ot">=</span> <span class="fu">rnorm</span>(n,mu,<span class="fu">sqrt</span>(sigsqr))</span>
<span id="cb3-16"><a href="#cb3-16"></a></span>
<span id="cb3-17"><a href="#cb3-17"></a>    <span class="co"># expectation, variance, and standard deviation estimators</span></span>
<span id="cb3-18"><a href="#cb3-18"></a>    y_bar[sim] <span class="ot">=</span> <span class="fu">mean</span>(y)              <span class="co"># sample mean</span></span>
<span id="cb3-19"><a href="#cb3-19"></a>    s_sqr[sim] <span class="ot">=</span> <span class="fu">var</span>(y)               <span class="co"># sample variance</span></span>
<span id="cb3-20"><a href="#cb3-20"></a>    s[sim]     <span class="ot">=</span> <span class="fu">sd</span>(y)                <span class="co"># sample standard deviation</span></span>
<span id="cb3-21"><a href="#cb3-21"></a>}</span>
<span id="cb3-22"><a href="#cb3-22"></a></span>
<span id="cb3-23"><a href="#cb3-23"></a><span class="co"># expectation estimation</span></span>
<span id="cb3-24"><a href="#cb3-24"></a>E_hat_y_bar <span class="ot">=</span> <span class="fu">cumsum</span>(y_bar)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">:</span>nsim)  <span class="co"># \mathbb{E}(\bar{y}) estimates</span></span>
<span id="cb3-25"><a href="#cb3-25"></a>E_hat_s_sqr <span class="ot">=</span> <span class="fu">cumsum</span>(s_sqr)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">:</span>nsim)  <span class="co"># \mathbb{E}(S^2) estimates</span></span>
<span id="cb3-26"><a href="#cb3-26"></a>E_hat_s     <span class="ot">=</span> <span class="fu">cumsum</span>(s)    <span class="sc">/</span>(<span class="dv">1</span><span class="sc">:</span>nsim)  <span class="co"># \mathbb{E}(S) estimates</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><a href="#fig-unbiasedness" class="quarto-xref">Figure&nbsp;<span>31.1</span></a> visualizes the results of the above simulation. Shown are estimates of the expectations of the sample mean, sample variance, and sample standard deviation as a function of the number of realizations of the sample variables <span class="math inline">\(y_1,...,y_{12}\)</span>, as well as the true, but unknown, values of the expectation, variance, and standard deviation of <span class="math inline">\(y_1,...,y_{12}\)</span>. It is noticeable that these estimates are more variable for a small number of realizations. From an estimate based on about 10,000 realizations of <span class="math inline">\(y_1,...,y_{12}\)</span> onward, the sample means of <span class="math inline">\(\bar{y}\)</span> and <span class="math inline">\(S^2\)</span> correspond to their true, but unknown, values in accordance with their unbiasedness. The sample standard deviation, in contrast, in accordance with its bias, still shows a consistently too low estimate of the true, but unknown, standard deviation even as the number of realizations of <span class="math inline">\(y_1,...,y_{12}\)</span> continues to increase.</p>
</div>
<div id="fig-unbiasedness" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-unbiasedness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/402-unbiasedness.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-unbiasedness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;31.1: Simulation of the unbiasedness of the sample mean and sample variance as estimators of the expectation and variance under normally distributed sample variables, and simulation of the bias of the sample standard deviation as an estimator of the standard deviation under normally distributed sample variables.
</figcaption>
</figure>
</div>
</section>
<section id="sec-variance-and-standard-error" class="level3" data-number="31.2.2">
<h3 data-number="31.2.2" class="anchored" data-anchor-id="sec-variance-and-standard-error"><span class="header-section-number">31.2.2</span> Variance and standard error</h3>
<p>In the previous section we considered the expectation of an estimator. In this section we consider its variance and its standard deviation. We use the following definition.</p>
<div id="def-variance-and-standard-error" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.5 (Variance and standard error)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a frequentist inference model and let <span class="math inline">\(\hat{\tau}\)</span> be an estimator of <span class="math inline">\(\tau\)</span>.</p>
<ul>
<li>The <em>variance</em> of <span class="math inline">\(\hat{\tau}\)</span> is defined as <span class="math display">\[\begin{equation}
\mathbb{V}_\theta(\hat{\tau} ) :=
\mathbb{E}_\theta
\left((\hat{\tau} (y) - \mathbb{E}_\theta(\hat{\tau} (y)))^2\right).
\end{equation}\]</span></li>
<li>The <em>standard error</em> of <span class="math inline">\(\hat{\tau}\)</span> is defined as <span class="math display">\[\begin{equation}
\mbox{SE}(\hat{\tau} ) := \sqrt{\mathbb{V}_\theta(\hat{\tau})}.
\end{equation}\]</span></li>
</ul>
</div>
<p>The variance of an estimator <span class="math inline">\(\hat{\tau}\)</span> is thus defined as the variance of the random variable <span class="math inline">\(\hat{\tau}(y)\)</span>. The standard error of an estimator <span class="math inline">\(\hat{\tau}\)</span> is defined as the standard deviation of <span class="math inline">\(\hat{\tau}(y)\)</span>. As a first example of a standard error, we consider the <em>standard error of the sample mean</em>.</p>
<div id="thm-standard-error-of-sample-mean" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.5 (Standard error of the sample mean)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model. Then the is given by <span class="math display">\[\begin{equation}
\mbox{SE}(\bar{y}) = \frac{\mathbb{S}_\theta(y_1)}{\sqrt{n}}.
\end{equation}\]</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>With the variance of the sample mean, we obtain <span class="math display">\[\begin{equation}
\mbox{SE}(\bar{y})
= \sqrt{\mathbb{V}_\theta(\bar{y})}
= \sqrt{\frac{\mathbb{V}_\theta(y_1)}{n}}
= \frac{\mathbb{S}_\theta(y_1)}{\sqrt{n}}.
\end{equation}\]</span></p>
</div>
<p>The standard error of the mean describes the variability of the sample mean. Since the standard deviation <span class="math inline">\(\mathbb{S}_\theta(y_1)\)</span> is unknown, the standard error <span class="math inline">\(\mbox{SE}(\bar{y})\)</span> is also unknown and can therefore only be estimated. With the sample standard deviation as a biased estimator of the standard deviation <span class="math inline">\(\mathbb{S}_\theta(y_1)\)</span>, an also biased estimator for the standard error of the sample mean is <span class="math display">\[\begin{equation}
\hat{\mbox{SE}}(\bar{y}) = \frac{S}{\sqrt{n}}.
\end{equation}\]</span></p>
<p>As a second example, we consider the standard error of the maximum likelihood estimator for the parameter of a Bernoulli model.</p>
<div id="thm-standard-error-of-bernoulli-ml-parameter-estimator" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.6 (Standard error of the maximum likelihood estimator of the Bernoulli model parameter)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a Bernoulli model and let <span class="math inline">\(\hat{\mu}^{\mbox{\tiny ML}}\)</span> be the maximum likelihood estimator for the Bernoulli model parameter <span class="math inline">\(\mu\)</span>. Then the standard error of <span class="math inline">\(\hat{\mu}^{\mbox{\tiny ML}}\)</span> is given by <span class="math display">\[\begin{equation}
\mbox{SE}\left(\hat{\mu}^{\mbox{\tiny ML}}\right) = \sqrt{\frac{\mu(1-\mu)}{n}}.
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>We have <span class="math display">\[\begin{align}
\begin{split}
\mbox{SE}\left(\hat{\mu}^{\mbox{\tiny ML}}\right)
= \sqrt{\mathbb{V}_\mu\left(\hat{\mu}^{\mbox{\tiny ML}}\right)}
= \sqrt{\mathbb{V}_\mu\left(\frac{1}{n}\sum_{i=1}^n y_i \right)}
= \sqrt{\frac{1}{n^2}\sum_{i=1}^n \mathbb{V}_\mu(y_i)}
= \sqrt{\frac{n \mu(1-\mu)}{n^2}}
= \sqrt{\frac{\mu(1-\mu)}{n}},
\end{split}
\end{align}\]</span> where the third equality follows from the independence of the <span class="math inline">\(y_i\)</span> and the fourth equality from the variance <span class="math display">\[\begin{equation}
\mathbb{V}_\mu(y_1) = \mathbb{V}_\mu(y_i) = \mu(1-\mu)
\end{equation}\]</span> of the sample variables.</p>
</div>
<p>As in the case of the standard error of the sample mean, the standard error of the maximum likelihood estimator of the Bernoulli model parameter is a true, but unknown, value. An estimator for <span class="math inline">\(\mbox{SE}\left(\hat{\mu}^{\mbox{\tiny ML}}\right)\)</span> is obtained with the maximum likelihood estimator for the Bernoulli model parameter as <span class="math display">\[\begin{equation}
\hat{\mbox{SE}}\left(\hat{\mu}^{\mbox{\tiny ML}}\right)
= \sqrt{\frac{\hat{\mu}^{\mbox{\tiny ML}}(1-\hat{\mu}^{\mbox{\tiny ML}})}{n}}.
\end{equation}\]</span></p>
<div id="exm-simulation-example-standard-error" class="theorem example">
<p><span class="theorem-title"><strong>Example 31.2 (Simulation example)</strong></span> The following <strong>R</strong> code simulates the distribution of the maximum likelihood estimator for the parameter of a Bernoulli model with true, but unknown, parameter value <span class="math inline">\(\mu := 0.4\)</span> for the sample sizes <span class="math inline">\(n = 20\)</span>, <span class="math inline">\(n = 100\)</span>, and <span class="math inline">\(n = 200\)</span>. <a href="#fig-standard-error" class="quarto-xref">Figure&nbsp;<span>31.2</span></a> visualizes the resulting distributions using histograms. The variability of the estimates, that is, the width of the histogram distributions, evidently depends on the sample size. Larger sample sizes result in lower variability of the estimator. We will deepen this idea in <a href="#sec-asymptotic-estimator-properties" class="quarto-xref"><span>Section 31.3</span></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># model formulation</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>mu       <span class="ot">=</span> <span class="fl">0.4</span>                                                      <span class="co"># true, but unknown, parameter value</span></span>
<span id="cb4-3"><a href="#cb4-3"></a>n_all    <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">20</span>,<span class="dv">100</span>,<span class="dv">200</span>)                                            <span class="co"># sample sizes n</span></span>
<span id="cb4-4"><a href="#cb4-4"></a>ns       <span class="ot">=</span> <span class="fl">1e4</span>                                                      <span class="co"># number of simulations</span></span>
<span id="cb4-5"><a href="#cb4-5"></a>mu_hat   <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NaN</span>, <span class="fu">length</span>(n_all)<span class="sc">*</span>ns), <span class="at">nrow =</span> <span class="fu">length</span>(n_all)) <span class="co"># maximum likelihood estimator array</span></span>
<span id="cb4-6"><a href="#cb4-6"></a></span>
<span id="cb4-7"><a href="#cb4-7"></a><span class="co"># sample size iterations</span></span>
<span id="cb4-8"><a href="#cb4-8"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq_along</span>(n_all)){</span>
<span id="cb4-9"><a href="#cb4-9"></a></span>
<span id="cb4-10"><a href="#cb4-10"></a>    <span class="co"># simulation iterations</span></span>
<span id="cb4-11"><a href="#cb4-11"></a>    <span class="cf">for</span>(s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ns){</span>
<span id="cb4-12"><a href="#cb4-12"></a>        y            <span class="ot">=</span> <span class="fu">rbinom</span>(n_all[i],<span class="dv">1</span>,mu)                        <span class="co"># sample realization of y_1,...,y_n</span></span>
<span id="cb4-13"><a href="#cb4-13"></a>        mu_hat[i,s]  <span class="ot">=</span> <span class="fu">mean</span>(y)                                      <span class="co"># sample mean</span></span>
<span id="cb4-14"><a href="#cb4-14"></a>    }</span>
<span id="cb4-15"><a href="#cb4-15"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
</section>
</div>
<div id="fig-standard-error" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-standard-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/402-standard-error.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-standard-error-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;31.2: Simulation of the distribution of the maximum likelihood estimator of a Bernoulli model. The variability of the estimator evidently depends on the sample size <span class="math inline">\(n\)</span>.
</figcaption>
</figure>
</div>
</section>
<section id="sec-mean-squared-error" class="level3" data-number="31.2.3">
<h3 data-number="31.2.3" class="anchored" data-anchor-id="sec-mean-squared-error"><span class="header-section-number">31.2.3</span> Mean squared error</h3>
<p>With the unbiasedness and variance of an estimator, we have encountered in the previous two sections two independent criteria for the quality of estimators. The <em>mean squared error</em> of an estimator introduced in this section enables an integrated consideration of the accuracy (unbiasedness) and variability (variance) of an estimator in the sense of its so-called <em>bias-variance decomposition</em>. We first define the mean squared error of an estimator as follows.</p>
<div id="def-mean-squared-error" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.6 (Mean squared error)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model and <span class="math inline">\(\hat{\tau}\)</span> an estimator for <span class="math inline">\(\tau\)</span>. Then the <em>mean squared error</em> of <span class="math inline">\(\hat{\tau}\)</span> is defined as <span class="math display">\[\begin{equation}
\mbox{MSE}(\hat{\tau})
:= \mathbb{E}_\theta\left((\hat{\tau}(y) - \tau(\theta))^2\right).
\end{equation}\]</span></p>
</div>
<p>The mean squared error of <span class="math inline">\(\hat{\tau}\)</span> is thus the expected squared deviation of <span class="math inline">\(\hat{\tau}(y)\)</span> from <span class="math inline">\(\tau(\theta)\)</span>. Note that, by contrast, the variance of <span class="math inline">\(\hat{\tau}\)</span> is the expected squared deviation of <span class="math inline">\(\hat{\tau}\)</span> from <span class="math inline">\(\mathbb{E}_\theta(\hat{\tau}(y))\)</span>. As seen in <a href="#sec-unbiasedness" class="quarto-xref"><span>Section 31.2.1</span></a>, <span class="math inline">\(\mathbb{E}_\theta(\hat{\tau}(y))\)</span> may coincide with <span class="math inline">\(\tau(\theta)\)</span>, so an estimator may be unbiased, but need not be. If one uses the mean squared error as a quality criterion for an estimator, for example by trying to construct an estimator with the smallest possible mean squared error, then one may accept possible slight deviations from unbiasedness in favor of a small estimator variance. For the mean squared error, the following theorem holds.</p>
<div id="thm-decomposition-of-mean-squared-error" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.7 (Decomposition of the mean squared error)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model, let <span class="math inline">\(\hat{\tau}\)</span> be an estimator for <span class="math inline">\(\tau\)</span>, and let <span class="math inline">\(\mbox{MSE}(\hat{\tau})\)</span> be the mean squared error of <span class="math inline">\(\hat{\tau}\)</span>. Then <span class="math display">\[\begin{equation}
\mbox{MSE}(\hat{\tau}) = \mbox{B}(\hat{\tau})^2 + \mathbb{V}_\theta(\hat{\tau}).
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>To simplify notation, let <span class="math inline">\(\tau := \tau(\theta)\)</span>, <span class="math inline">\(\hat{\tau} := \hat{\tau}(y)\)</span>, and <span class="math inline">\(\bar{\tau}_n := \mathbb{E}_\theta(\hat{\tau}(y))\)</span>. Then: <span class="math display">\[\begin{align}
\begin{split}
\mathbb{E}_\theta\left((\hat{\tau} - \tau)^2\right)
&amp; = \mathbb{E}_\theta\left((\hat{\tau} - \bar{\tau}_n + \bar{\tau}_n - \tau)^2\right) \\
&amp; = \mathbb{E}_\theta
\left(
(\hat{\tau} - \bar{\tau}_n)^2 + 2(\hat{\tau} - \bar{\tau}_n)(\bar{\tau}_n - \tau) + (\bar{\tau}_n - \tau)^2
\right)
\\
&amp; = \mathbb{E}_\theta\left((\hat{\tau} - \bar{\tau}_n)^2\right) + 2\mathbb{E}_\theta\left((\hat{\tau} - \bar{\tau}_n)(\bar{\tau}_n - \tau)\right) + \mathbb{E}_\theta\left((\bar{\tau}_n - \tau)^2\right) \\
&amp; = \mathbb{E}_\theta\left((\hat{\tau} - \bar{\tau}_n)^2\right) + 2\mathbb{E}_\theta\left(
\hat{\tau}\bar{\tau}_n - \hat{\tau}\tau - \bar{\tau}_n\bar{\tau}_n + \bar{\tau}_n\tau
\right) + \mathbb{E}_\theta\left((\bar{\tau}_n - \tau)^2\right)
\\
&amp; =
\mathbb{E}_\theta\left((\hat{\tau} - \bar{\tau}_n)^2\right) + 2\left(
\bar{\tau}_n\bar{\tau}_n - \bar{\tau}_n\tau
\right) + \mathbb{E}_\theta\left((\bar{\tau}_n - \tau)^2\right) \\
&amp; =
\mathbb{E}_\theta\left((\hat{\tau} - \bar{\tau}_n)^2\right) + 0 + \mathbb{E}_\theta\left((\bar{\tau}_n - \tau)^2\right) \\
&amp; =
\mathbb{E}_\theta\left((\bar{\tau}_n - \tau)^2\right) + \mathbb{E}_\theta\left((\hat{\tau} - \bar{\tau}_n)^2\right) \\
&amp; =
\mathbb{E}_\theta\left((\mathbb{E}_\theta(\hat{\tau}) - \tau)^2\right) + \mathbb{E}_\theta\left((\hat{\tau} - \mathbb{E}_\theta(\hat{\tau}))^2\right) \\
&amp; =
(\mathbb{E}_\theta(\hat{\tau}) - \tau)^2 + \mathbb{V}_\theta(\hat{\tau}) \\
&amp; =
\mbox{B}(\hat{\tau})^2 + \mathbb{V}_\theta(\hat{\tau}).
\end{split}
\end{align}\]</span></p>
</div>
</section>
<section id="sec-cramer-rao-inequality" class="level3" data-number="31.2.4">
<h3 data-number="31.2.4" class="anchored" data-anchor-id="sec-cramer-rao-inequality"><span class="header-section-number">31.2.4</span> Cramér-Rao inequality</h3>
<p>If several unbiased estimators are available, the estimator with the smallest variance most reliably serves its purpose. But because sample realizations of frequentist inference models are generally variable, the variability of unbiased estimators cannot be arbitrarily small either. The <em>Cramér-Rao inequality</em> gives a lower bound for the variance of unbiased estimators. An unbiased estimator with variance equal to this lower bound therefore has the smallest possible variance of all unbiased estimators and is, in this sense, an optimal estimator.</p>
<p>The Cramér-Rao inequality is based on the concept of the so-called <em>Fisher information</em>, which in turn is based on the concept of the <em>score function</em> of a frequentist inference model. We therefore first introduce these two concepts before formulating and proving the Cramér-Rao inequality.</p>
<p>The results presented generally hold only under a series of mathematical assumptions, the so-called <em>Fisher regularity conditions</em>. For a frequentist inference model with PMF or PDF <span class="math inline">\(p_\theta\)</span> and parameter space <span class="math inline">\(\Theta\)</span>, these consist in assuming that (1) <span class="math inline">\(\Theta\)</span> is an open set, so the true, but unknown, parameter value cannot lie on a boundary of the parameter space, (2) the subset of <span class="math inline">\(\Theta\)</span> on which <span class="math inline">\(p_\theta\)</span> takes nonzero values does not depend on <span class="math inline">\(\theta\)</span>, (3) the model itself is identifiable, that is, PMFs or PDFs with different parameter values are different functions and therefore imply different sample distributions, (4) the likelihood function of the model is twice continuously differentiable, and (5) for the likelihood function integration and differentiation may be interchanged. We thus assume the Fisher regularity conditions to be fulfilled and consider only models with one-dimensional parameter spaces <span class="math inline">\(\Theta \subseteq \mathbb{R}\)</span>. We first define the terms <em>score function</em> and <em>Fisher information</em> as follows.</p>
<div id="def-score-function-and-fisher-information" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.7 (Score function and Fisher information)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model with one-dimensional parameter <span class="math inline">\(\theta \in \Theta \subseteq \mathbb{R}\)</span>, and let <span class="math inline">\(\ell\)</span> be the associated log-likelihood function. Then:</p>
<ul>
<li>The first derivative of <span class="math inline">\(\ell\)</span> is called the <em>score function of the sample</em> and is denoted by <span class="math display">\[\begin{equation}
S(\theta) := \frac{d}{d\theta}\ell(\theta)
\end{equation}\]</span> For <span class="math inline">\(n = 1\)</span> we write <span class="math inline">\(S(\theta) := S_1(\theta)\)</span> and call <span class="math inline">\(S(\theta)\)</span> the <em>score function of a random variable</em>.</li>
<li>The negative second derivative of <span class="math inline">\(\ell\)</span> is called the <em>Fisher information of the sample</em> and is denoted by <span class="math display">\[\begin{equation}
I(\theta) := -\frac{d^2}{d\theta^2}\ell(\theta)
\end{equation}\]</span> For <span class="math inline">\(n  = 1\)</span> we write <span class="math inline">\(I(\theta) := I_1(\theta)\)</span> and call <span class="math inline">\(I(\theta)\)</span> the <em>Fisher information of a random variable</em>.</li>
</ul>
</div>
<p>Because likelihood and log-likelihood functions depend on the realization of a sample, they are random functions against the background of a frequentist inference model. Since Fisher information, as a function of the log-likelihood function, is therefore also a random variable, one must distinguish between the <em>observed</em> and the <em>expected</em> values of the Fisher information.</p>
<div id="def-observed-and-expected-fisher-information" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.8 (Observed and expected Fisher information)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model with one-dimensional parameter <span class="math inline">\(\theta \in \Theta \subseteq \mathbb{R}\)</span>, let <span class="math inline">\(\ell\)</span> be the associated log-likelihood function, and let <span class="math inline">\(\hat{\theta}^{\mbox{\tiny ML}}\)</span> be a maximum likelihood estimator of <span class="math inline">\(\theta\)</span>. Then:</p>
<ul>
<li>The <em>observed Fisher information of the sample</em> is defined as <span class="math display">\[\begin{equation}
I\left(\hat{\theta}^{\mbox{\tiny ML}}\right)
:= -\frac{d^2}{d\theta^2}\ell\left(\hat{\theta}^{\mbox{\tiny ML}}\right),
\end{equation}\]</span> that is, the observed Fisher information of the sample is the Fisher information at the point of the maximum likelihood estimator <span class="math inline">\(\hat{\theta}^{\mbox{\tiny ML}}\)</span>.</li>
<li>The <em>expected Fisher information of the sample</em> is defined as <span class="math display">\[\begin{equation}
J(\theta) := \mathbb{E}_\theta(I(\theta)).
\end{equation}\]</span> For <span class="math inline">\(n = 1\)</span> we write <span class="math inline">\(J(\theta) := J_1(\theta)\)</span> and call <span class="math inline">\(J(\theta)\)</span> the </li>
</ul>
</div>
<p>Before illustrating these concepts using the Bernoulli model (<a href="#thm-score-function-and-fisher-information-of-bernoulli-model" class="quarto-xref">Theorem&nbsp;<span>31.10</span></a>) and the normal distribution model (<a href="#thm-score-function-and-fisher-information-of-normal-distribution-model-with-known-expectation-parameter" class="quarto-xref">Theorem&nbsp;<span>31.12</span></a> and <a href="#thm-score-function-and-fisher-information-of-normal-distribution-model-with-known-variance-parameter" class="quarto-xref">Theorem&nbsp;<span>31.11</span></a>), we introduce, with the <em>additivity of Fisher information</em> in parametric product models (<a href="#thm-additivity-of-fisher-information" class="quarto-xref">Theorem&nbsp;<span>31.8</span></a>) and the expectation and variance of the score function (<a href="#thm-expectation-and-variance-of-score-function" class="quarto-xref">Theorem&nbsp;<span>31.9</span></a>), important properties of these concepts that simplify the following discussion.</p>
<div id="thm-additivity-of-fisher-information" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.8 (Additivity of Fisher information)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model with parameter <span class="math inline">\(\theta \in \Theta \subseteq \mathbb{R}\)</span>, let <span class="math inline">\(\ell\)</span> be the associated log-likelihood function, and let <span class="math inline">\(I(\theta)\)</span> and <span class="math inline">\(J(\theta)\)</span> be the Fisher information and the expected Fisher information of the sample, respectively. Then <span class="math display">\[\begin{equation}
I(\theta) = nI_1(\theta) \mbox{ and } J(\theta) = nJ_1(\theta).
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>We show the result for the expected Fisher information; the result for the observed Fisher information then holds implicitly. With the linearity of derivatives and expectations, <span class="math display">\[\begin{align}
\begin{split}
J(\theta)
&amp; = \mathbb{E}_\theta\left(-\frac{d^2}{d\theta^2} \ell(\theta)\right) \\
&amp; = \mathbb{E}_\theta\left(-\frac{d^2}{d\theta^2} \ln \left(\prod_{i=1}^n p_\theta(y_i)\right)\right) \\
&amp; = \mathbb{E}_\theta\left(-\frac{d^2}{d\theta^2} \sum_{i=1}^n \ln p_\theta(y_i)\right) \\
&amp; = \mathbb{E}_\theta\left(-\frac{d^2}{d\theta^2} \sum_{i=1}^n \ln p_\theta(y_1)\right) \\
&amp; = \mathbb{E}_\theta\left(-\frac{d^2}{d\theta^2} \ell_1(\theta)n\right) \\
&amp; = n \mathbb{E}_\theta\left(-\frac{d^2}{d\theta^2}\ell_1(\theta))\right) \\
&amp; = n J_1(\theta).
\end{split}
\end{align}\]</span></p>
</div>
<p>According to <a href="#thm-additivity-of-fisher-information" class="quarto-xref">Theorem&nbsp;<span>31.8</span></a>, to compute the observed or expected Fisher information of a sample in parametric product models, it is sufficient to compute the observed or expected Fisher information of one of the random variables in the sample. Further simplifications in determining Fisher information and justifying the Cramér-Rao inequality follow from the identities formulated in the following theorem.</p>
<div id="thm-expectation-and-variance-of-score-function" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.9 (Expectation and variance of the score function)</strong></span> The expectation of the score function of a random variable is <span class="math display">\[\begin{equation}
\mathbb{E}_\theta(S(\theta)) = 0
\end{equation}\]</span> and the variance of the score function of a random variable is <span class="math display">\[\begin{equation}
\mathbb{V}_\theta(S(\theta)) = J(\theta).
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>We consider only the case in which <span class="math inline">\(p_\theta\)</span> is a PDF and first show that <span class="math inline">\(\mathbb{E}_\theta(S(\theta)) = 0\)</span>. <span class="math display">\[\begin{align}
\begin{split}
\mathbb{E}_\theta(S(\theta))
&amp; = \int S(\theta)p_\theta(x) \,dx \\
&amp; = \int \frac{d}{d\theta}\ell(\theta)p_\theta(x) \,dx \\
&amp; = \int \frac{d}{d\theta} \ln L(\theta) p_\theta(x) \,dx \\
&amp; = \int \frac{1}{L(\theta)}\frac{d}{d\theta}L(\theta) p_\theta(x) \,dx  \\
&amp; = \int \frac{1}{p_\theta(x)}\frac{d}{d\theta}L(\theta) p_\theta(x) \,dx  \\
&amp; = \int \frac{d}{d\theta}L(\theta) \,dx  \\
&amp; = \frac{d}{d\theta} \int p_\theta(x)\,dx \\
&amp; = \frac{d}{d\theta} 1 \\
&amp; = 0.
\end{split}
\end{align}\]</span> With the definition of variance, it follows immediately that <span class="math inline">\(\mathbb{V}_\theta(S(\theta)) = \mathbb{E}_\theta(S(\theta)^2)\)</span>. Next we show that <span class="math inline">\(J(\theta) =  \mathbb{E}_\theta(S(\theta)^2)\)</span> and hence <span class="math inline">\(\mathbb{V}_\theta(S(\theta)) = J(\theta)\)</span>. <span class="math display">\[\begin{align}
\begin{split}
J(\theta)
&amp; = \mathbb{E}_\theta\left(-\frac{d^2}{d\theta^2} \ln L(\theta)\right) \\
&amp; = \mathbb{E}_\theta\left(-\frac{d}{d\theta} \frac{\frac{d}{d\theta}L(\theta)}{L(\theta)}\right) \\
&amp; = \mathbb{E}_\theta\left(-\frac{\frac{d^2}{d\theta^2} L(\theta) L(\theta) - \frac{d}{d\theta}L(\theta)\frac{d}{d\theta}L(\theta)}{L(\theta)L(\theta)}\right) \\
&amp; = - \mathbb{E}_\theta\left(\frac{\frac{d^2}{d\theta^2} L(\theta)}{L(\theta)}\right) +
\mathbb{E}_\theta\left(\frac{\left(\frac{d}{d\theta}L(\theta)\right)^2}{(L(\theta))^2}\right) \\
&amp; = - \int \frac{\frac{d^2}{d\theta^2} L(\theta)}{L(\theta)} p_\theta(x) \,dx +
      \int \frac{\left(\frac{d}{d\theta}L(\theta)\right)^2}{(L(\theta))^2} p_\theta(x) \,dx \\
&amp; = - \frac{d^2}{d\theta^2} \int p_\theta(x) \,dx +
      \int \left(\frac{1}{L(\theta)}\frac{d}{d\theta}L(\theta)\right)^2 p_\theta(x) \,dx \\
&amp; = - \frac{d^2}{d\theta^2} 1 +
\int \left(\frac{d}{d\theta} \ln L(\theta) \right)^2 p_\theta(x) \,dx \\
&amp; = \mathbb{E}_\theta\left(S(\theta)^2\right).
\end{split}
\end{align}\]</span></p>
</div>
<p>The expectation of the derivative of the log-likelihood function is thus always zero, and the expected Fisher information is always equal to the variance of the score function. We now compute the score function and the different forms of Fisher information concretely for the familiar frequentist inference models. The following theorem first summarizes the results for the Bernoulli model.</p>
<div id="thm-score-function-and-fisher-information-of-bernoulli-model" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.10 (Score function and Fisher information of the Bernoulli model)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a Bernoulli model with parameter <span class="math inline">\(\mu \in ]0,1[\)</span>. Then:</p>
<ul>
<li>The score function of the sample is <span class="math display">\[\begin{equation}
S : ]0,1[ \to \mathbb{R}, \mu \mapsto S(\mu) := \frac{1}{\mu}\sum_{i=1}^n y_i  -  \frac{1}{1-\mu} \left(n - \sum_{i=1}^n y_i \right).
\end{equation}\]</span></li>
<li>The Fisher information of the sample is <span class="math display">\[\begin{equation}
I : ]0,1[ \to \mathbb{R}, \mu \mapsto I(\mu) := I(\mu) =  \frac{ny}{\mu^2} + \frac{n(1 - y)}{1-\mu}^{2}.
\end{equation}\]</span></li>
<li>The observed Fisher information of the sample is <span class="math display">\[\begin{equation}
I: ]0,1[ \to \mathbb{R}, \hat{\mu}^{\mbox{\tiny ML}} \mapsto
I\left(\hat{\mu}^{\mbox{\tiny ML}}\right)
:= \frac{ny}{\hat{\mu}_{n}^{{\mbox{\tiny ML}}^2}} + \frac{n(1 - y)}{1-\hat{\mu}^{\mbox{\tiny ML}}}.
\end{equation}\]</span></li>
<li>The expected Fisher information of the sample is <span class="math display">\[\begin{equation}
J: ]0,1[ \to \mathbb{R}, \mu \mapsto J(\mu)
:= \frac{n}{\mu(1-\mu)}.
\end{equation}\]</span></li>
</ul>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>The score function was already derived in the context of maximum likelihood estimation of <span class="math inline">\(\mu\)</span>. We consider the Fisher information of a single Bernoulli random variable <span class="math inline">\(y\)</span>. <span class="math display">\[\begin{align}
\begin{split}
I(\mu)
&amp; := -\frac{d^2}{d\mu^2} \ell_1(\mu)                                                                                        \\
&amp;  = -\frac{d^2}{d\mu^2} \ln p_\mu(y)                                                                                       \\
&amp;  = -\frac{d^2}{d\mu^2}\left(y \ln \mu + (1 - y) \ln (1-\mu)\right)                                                        \\
&amp;  = -\frac{\partial}{\partial{\mu}}\left(\frac{\partial}{\partial{\mu}}\left(y \ln \mu + (1 - y) \ln (1-\mu)\right)\right) \\
&amp;  = -\frac{\partial}{\partial{\mu}}\left(\frac{y}{\mu} + \frac{(1 - y)}{1-\mu}\right)                                      \\
&amp;  = -\left(-\frac{y}{\mu^2} - \frac{(1 - y)}{1-\mu}^{2}\right)                                                             \\
&amp;  =  \frac{y}{\mu^2} + \frac{(1 - y)}{1-\mu}^{2}.                                                                          \\
\end{split}
\end{align}\]</span> Thus the expected Fisher information of the random variable <span class="math inline">\(y\)</span> is <span class="math display">\[\begin{align}
\begin{split}
J(\mu)
&amp; = \mathbb{E}_\mu(I(\mu))                                                                  \\
&amp; = \mathbb{E}_\mu \left(\frac{y}{\mu^2} + \frac{(1 - y)}{1-\mu}^{2} \right)            \\
&amp; = \frac{\mathbb{E}_\mu(y)}{\mu^2} + \frac{(1 - \mathbb{E}_\mu(y))}{1-\mu}^{2}         \\
&amp; = \frac{\mu}{\mu^2} + \frac{(1 - \mu)}{1-\mu}^{2}                                         \\
&amp; = \frac{1}{\mu(1-\mu)}.                                                                   \\
\end{split}
\end{align}\]</span> With the additivity property of Fisher information and the definition of observed Fisher information, it follows immediately that <span class="math display">\[\begin{equation}
I(\mu)
=  \frac{ny}{\mu^2} + \frac{n(1 - y)}{1-\mu}^{2}
\mbox{ and }
J(\mu) = \frac{n}{\mu(1-\mu)}.
\end{equation}\]</span></p>
</div>
<p>We consider the score function and Fisher information of the normal distribution model only under the additional assumption of a known variance parameter (<a href="#thm-score-function-and-fisher-information-of-normal-distribution-model-with-known-variance-parameter" class="quarto-xref">Theorem&nbsp;<span>31.11</span></a>) or a known expectation parameter (<a href="#thm-score-function-and-fisher-information-of-normal-distribution-model-with-known-expectation-parameter" class="quarto-xref">Theorem&nbsp;<span>31.12</span></a>).</p>
<div id="thm-score-function-and-fisher-information-of-normal-distribution-model-with-known-variance-parameter" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.11 (Score function and Fisher information of the normal distribution model with known variance parameter)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a normal distribution model and assume that the variance parameter <span class="math inline">\(\sigma^2\)</span> is known. Then:</p>
<ul>
<li>The score function of the sample is <span class="math display">\[\begin{equation}
S: \mathbb{R} \to \mathbb{R}, \mu \mapsto S(\mu) := \frac{1}{\sigma^2}\sum_{i=1}^n(y_i-\mu).
\end{equation}\]</span></li>
<li>The Fisher information of the sample is <span class="math display">\[\begin{equation}
I: \mathbb{R} \to \mathbb{R}, \mu \mapsto I(\mu) := \frac{n}{\sigma^2}.
\end{equation}\]</span></li>
<li>The observed Fisher information of the sample is <span class="math display">\[\begin{equation}
I(\hat{\mu}^{\mbox{\tiny ML}}_n) = \frac{n}{\sigma^2}.
\end{equation}\]</span></li>
<li>The expected Fisher information of the sample is <span class="math display">\[\begin{equation}
J : \mathbb{R} \to \mathbb{R}, \mu \mapsto J(\mu) := \frac{n}{\sigma^2}.
\end{equation}\]</span></li>
</ul>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Recall that the log-likelihood function of a normal distribution model with known variance parameter <span class="math inline">\(\sigma^2\)</span> is given by <span class="math display">\[\begin{equation}
\ell: \mathbb{R} \to \mathbb{R},
\mu \mapsto \ell(\mu)
:= -\frac{n}{2} \ln 2\pi - \frac{n}{2} \ln \sigma^2 - \frac{1}{2\sigma^2}\sum_{i=1}^n(y_i-\mu)^2
\end{equation}\]</span> Thus the score function is <span class="math display">\[\begin{align}
\begin{split}
S(\mu)
= \frac{\partial}{\partial{\mu}}\ell(\mu)
= \frac{1}{\sigma^2}\sum_{i=1}^n(y_i-\mu)
\end{split}
\end{align}\]</span> The Fisher information of the sample is <span class="math display">\[\begin{align}
\begin{split}
I(\mu)
= -\frac{d^2}{d\mu^2}\ell(\mu)
= -\frac{\partial}{\partial{\mu}}S(\mu)
= -\frac{1}{\sigma^2}\frac{\partial}{\partial{\mu}}\left(\sum_{i=1}^n y_i -  n\mu \right)
= \frac{n}{\sigma^2}.
\end{split}
\end{align}\]</span> The observed Fisher information is the Fisher information at the point of the maximum likelihood estimator <span class="math inline">\(\hat{\mu}^{\mbox{\tiny ML}}_n\)</span>. The expected Fisher information finally is <span class="math display">\[\begin{align}
\begin{split}
J(\mu)
= \mathbb{E}_\mu(I(\mu))
= \mathbb{E}_\mu\left(\frac{n}{\sigma^2}\right)
= \frac{n}{\sigma^2}.
\end{split}
\end{align}\]</span></p>
</div>
<div id="thm-score-function-and-fisher-information-of-normal-distribution-model-with-known-expectation-parameter" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.12 (Score function and Fisher information of the normal distribution model with known expectation parameter)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a normal distribution model and assume that the expectation parameter <span class="math inline">\(\mu\)</span> is known. Then:</p>
<ul>
<li>The score function of the sample is given by <span class="math display">\[\begin{equation}
S: \mathbb{R}_{&gt;0} \to \mathbb{R}, \sigma^2 \mapsto S(\sigma^2) := - \frac{n}{2 \sigma^2} + \frac{1}{2\sigma^4}\sum_{i=1}^n(y_i-\mu)^2
\end{equation}\]</span></li>
<li>The Fisher information of the sample is given by <span class="math display">\[\begin{equation}
I: \mathbb{R}_{&gt;0} \to \mathbb{R}, \sigma^2 \mapsto I(\sigma^2) :=
\frac{1}{\sigma^6}\sum_{i=1}^n (y_i - \mu)^2 - \frac{n}{2\sigma^4}
\end{equation}\]</span></li>
<li>The observed Fisher information of the sample is given by <span class="math display">\[\begin{equation}
I(\hat{\sigma}^{2\,\mbox{\tiny ML}}_n) =  \frac{n}{2\hat{\sigma}_{\mbox{\tiny ML}}^4}
\end{equation}\]</span></li>
<li>The expected Fisher information of the sample is given by <span class="math display">\[\begin{equation}
J: \mathbb{R}_{&gt;0} \to \mathbb{R}, \sigma^2 \mapsto J(\sigma^2) := \frac{n}{2\sigma^4}.
\end{equation}\]</span></li>
</ul>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Recall that the log-likelihood function of the sample of a normal distribution model with known expectation parameter <span class="math inline">\(\mu\)</span> is given by <span class="math display">\[\begin{equation}
\ell: \mathbb{R}_{&gt;0} \to \mathbb{R},
\sigma^2 \mapsto \ell(\sigma^2)
:= -\frac{n}{2} \ln 2\pi - \frac{n}{2} \ln \sigma^2  - \frac{1}{2\sigma^2}\sum_{i=1}^n(y_i-\mu)^2.
\end{equation}\]</span> The score function is therefore <span class="math display">\[\begin{align}
\begin{split}
S(\sigma^2)
= \frac{\partial}{\partial\sigma^2}\ell(\sigma^2)
= - \frac{n}{2 \sigma^2} + \frac{1}{2\sigma^4}\sum_{i=1}^n(y_i-\mu)^2.
\end{split}
\end{align}\]</span> The Fisher information of the sample is <span class="math display">\[\begin{align}
\begin{split}
I(\sigma^2)
&amp; = -\frac{\partial}{\partial\sigma^2}S(\sigma^2) \\
&amp; = - \frac{\partial}{\partial\sigma^2}\left(\frac{n}{2\sigma^4} - \frac{1}{\sigma^6}\sum_{i=1}^n (y_i - \mu)^2\right) \\
&amp; = \frac{1}{\sigma^6}\sum_{i=1}^n (y_i - \mu)^2 - \frac{n}{2\sigma^4}.
\end{split}
\end{align}\]</span> The observed Fisher information is the Fisher information at the point of the maximum likelihood estimator <span class="math inline">\(\hat{\sigma}^{2^{\mbox{\tiny ML}}}\)</span>, <span class="math display">\[\begin{align}
\begin{split}
I(\hat{\sigma}^{2\,\mbox{\tiny ML}}_n)
&amp; =   \frac{\sum_{i=1}^n (y_i - \mu)^2}{\left(\hat{\sigma}^{2\,\mbox{\tiny ML}}_n \right)^3} -
      \frac{n}{2\left(\hat{\sigma}^{2\,\mbox{\tiny ML}}_n \right)^2}                                    \\
&amp; =   \frac{\sum_{i=1}^n (y_i - \mu)^2}{\frac{1}{n^3}\left(\sum_{i=1}^n (y_i - \mu)^2 \right)^3} -
      \frac{n}{2\left(\hat{\sigma}^{2\,\mbox{\tiny ML}}_n \right)^2}                                    \\
&amp; =   \frac{1}{\frac{1}{n^3}\left(\sum_{i=1}^n (y_i - \mu)^2 \right)^2} -
      \frac{n}{2\left(\hat{\sigma}^{2\,\mbox{\tiny ML}}_n \right)^2}                                    \\
&amp; =   \frac{n}{\left(\hat{\sigma}^{2\,\mbox{\tiny ML}}_n \right)^2} -
      \frac{n}{2\left(\hat{\sigma}^{2\,\mbox{\tiny ML}}_n \right)^2}                                \\
&amp; =  \frac{n}{2\left(\hat{\sigma}^{2\,\mbox{\tiny ML}}_n \right)^2}                                     \\
&amp; =  \frac{n}{2\hat{\sigma}^{4\,\mbox{\tiny ML}}_n}.
\end{split}
\end{align}\]</span> The expected Fisher information finally is <span class="math display">\[\begin{align}
\begin{split}
J(\sigma^2)
&amp; = \mathbb{E}_{\sigma^2}(I(\sigma^2))  \\
&amp; = \mathbb{E}_{\sigma^2}\left(\frac{1}{\sigma^6}\sum_{i=1}^n (y_i - \mu)^2  - \frac{n}{2\sigma^4}\right)   \\
&amp; = \frac{1}{\sigma^6}\sum_{i=1}^n \mathbb{E}_{\sigma^2}\left((y_i - \mu)^2 \right)   - \frac{n}{2\sigma^4} \\
&amp; = \frac{1}{\sigma^6}\sum_{i=1}^n \sigma^2 - \frac{n}{2\sigma^4}   \\
&amp; = \frac{n\sigma^2}{\sigma^6} - \frac{n}{2\sigma^4}    \\
&amp; = \frac{n}{\sigma^4} - \frac{n}{2\sigma^4}    \\
&amp; = \frac{n}{2\sigma^4}.    \\
\end{split}
\end{align}\]</span></p>
</div>
<p>With the properties of the score function discussed above, we can now formulate and prove the Cramér-Rao inequality.</p>
<div id="thm-cramer-rao-inequality" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.13 (Cramér-Rao inequality)</strong></span> Let a frequentist inference model with one-dimensional parameter <span class="math inline">\(\theta \in \Theta \subseteq \mathbb{R}\)</span>, PMF or PDF <span class="math inline">\(p_\theta\)</span>, be given, and let <span class="math inline">\(\hat{\tau}\)</span> be an unbiased estimator of <span class="math inline">\(\tau(\theta)\)</span>. Then <span class="math display">\[\begin{equation}
\mathbb{V}_\theta(\hat{\tau}) \ge \frac{\left(\frac{d}{d\theta}\tau(\theta)\right)^2}{J(\theta)}.
\end{equation}\]</span> In particular, for a parameter estimator with <span class="math inline">\(\tau(\theta) := \theta\)</span> and thus <span class="math display">\[\begin{equation}
\hat{\tau} = \hat{\theta} \mbox{ and } \left(\frac{d}{d\theta}\tau(\theta)\right)^2 = 1,
\end{equation}\]</span> we have <span class="math display">\[\begin{equation}
\mathbb{V}_\theta(\hat{\theta}) \ge \frac{1}{J(\theta)}.
\end{equation}\]</span> The right-hand side of the above inequalities is called the <em>Cramér-Rao bound</em>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>We first note that for the random variables <span class="math inline">\(S(\theta)\)</span> and <span class="math inline">\(\hat{\tau}\)</span>, with the correlation inequality (<a href="../_part_3/308-Inequalities.html#thm-correlation-inequality" class="quarto-xref">Theorem&nbsp;<span>26.4</span></a>) and the identity of <span class="math inline">\(\mathbb{V}_\theta(S(\theta))\)</span> and <span class="math inline">\(J(\theta)\)</span> (<a href="#thm-expectation-and-variance-of-score-function" class="quarto-xref">Theorem&nbsp;<span>31.9</span></a>), <span class="math display">\[\begin{equation}
\frac{\mathbb{C}_\theta(S(\theta), \hat{\tau})^2}{\mathbb{V}_\theta(S(\theta))\mathbb{V}_\theta(\hat{\tau})}
\le 1
\Leftrightarrow \mathbb{V}_\theta(\hat{\tau})
\ge \frac{\mathbb{C}_\theta(S(\theta),\hat{\tau})^2}{J(\theta)}.
\end{equation}\]</span> With the covariance shift theorem (<a href="../_part_3/307-Covariances.html#thm-covariance-shift-theorem" class="quarto-xref">Theorem&nbsp;<span>25.2</span></a>), the fact that the expectation of the score function is always zero (<a href="#thm-expectation-and-variance-of-score-function" class="quarto-xref">Theorem&nbsp;<span>31.9</span></a>), and the assumed unbiasedness of <span class="math inline">\(\hat{\tau}\)</span>, we first obtain <span class="math display">\[\begin{align}
\begin{split}
\mathbb{C}_\theta(S(\theta),\hat{\tau})
&amp; = \mathbb{E}_\theta(S(\theta)\hat{\tau})  - \mathbb{E}_\theta(S(\theta))\mathbb{E}_\theta(\hat{\tau}) \\
&amp; = \mathbb{E}_\theta(S(\theta)\hat{\tau})                                                              \\
&amp; = \int S(\theta)\,\hat{\tau}\,p_\theta(x) \,dx                                                        \\
&amp; = \int \frac{d}{d\theta} \ln L(\theta)\,\hat{\tau}\,p_\theta(x) \,dx                                  \\
&amp; = \int \frac{\frac{d}{d\theta} L(\theta)}{L(\theta)}\,\hat{\tau}\,p_\theta(x) \,dx                    \\
&amp; = \int \frac{\frac{d}{d\theta} L(\theta)}{p_\theta(x)}\,\hat{\tau}\,p_\theta(x) \,dx                  \\
&amp; = \int \frac{d}{d\theta} L(\theta)\, \hat{\tau}  \,dx                                                 \\
&amp; = \frac{d}{d\theta} \int L(\theta)\, \hat{\tau}  \,dx                                                 \\
&amp; = \frac{d}{d\theta} \int \hat{\tau}\, p_\theta(x) \,dx                                                \\
&amp; = \frac{d}{d\theta} \mathbb{E}_\theta(\hat{\tau})                                                     \\
&amp; = \frac{d}{d\theta} \tau(\theta).
\end{split}
\end{align}\]</span> Thus it follows directly that <span class="math display">\[\begin{equation}
\mathbb{V}_\theta(\hat{\tau}) \ge \frac{\left(\frac{d}{d\theta}\tau(\theta) \right)^2}{J(\theta)}.
\end{equation}\]</span></p>
</div>
<p>For parameter estimators, in particular, the variance of an unbiased parameter estimator <span class="math inline">\(\hat{\theta}\)</span> is therefore always greater than or equal to the reciprocal expected Fisher information <span class="math inline">\(J(\theta)\)</span>. If even <span class="math display">\[\begin{equation}
\mathbb{V}_\theta(\hat{\theta}) = \frac{1}{J(\theta)}
\end{equation}\]</span> holds, then the variance of the parameter estimator is minimal and the estimator is thus shown to be an optimal estimator in the sense of the Cramér-Rao inequality. We return to this idea in <a href="#sec-properties-of-maximum-likelihood-estimators" class="quarto-xref"><span>Section 31.4</span></a>.</p>
</section>
</section>
<section id="sec-asymptotic-estimator-properties" class="level2" data-number="31.3">
<h2 data-number="31.3" class="anchored" data-anchor-id="sec-asymptotic-estimator-properties"><span class="header-section-number">31.3</span> Asymptotic estimator properties</h2>
<p>In this section we give a brief introduction to <em>asymptotic statistics</em> (<span class="citation" data-cites="vaart1998">Vaart (<a href="#ref-vaart1998" role="doc-biblioref">1998</a>)</span>). Asymptotic statistics is the area of frequentist inference that deals with the behavior of statistics and estimators at large sample sizes. The methods of asymptotic statistics are used, on the one hand, to study qualitative estimator properties, as here, and, on the other hand, to approximate estimator properties at large sample sizes. Since sample sizes can nowadays be quite large, the methods of asymptotic statistics are therefore well motivated for application and can be used in many ways there.</p>
<p>Continuing <a href="#sec-estimator-properties-in-finite-samples" class="quarto-xref"><span>Section 31.2</span></a>, in this section we illuminate four asymptotic estimator properties. To emphasize that in this section the properties of an estimator <span class="math inline">\(\hat{\tau}\)</span> depend on the sample size <span class="math inline">\(n\)</span>, we write <span class="math inline">\(\hat{\tau}_n\)</span> for an estimator in this section. In <a href="#sec-asymptotic-unbiasedness" class="quarto-xref"><span>Section 31.3.1</span></a> we consider the <em>asymptotic unbiasedness</em> of an estimator. An estimator <span class="math inline">\(\hat{\tau}_n\)</span> for <span class="math inline">\(\tau\)</span> is called <em>asymptotically unbiased</em> if the expectation of <span class="math inline">\(\hat{\tau}_n\)</span> for large sample sizes <span class="math inline">\(n \to \infty\)</span> is identical to the true, but unknown, value <span class="math inline">\(\tau(\theta)\)</span>. In <a href="#sec-consistency" class="quarto-xref"><span>Section 31.3.2</span></a> we introduce the concept of <em>consistency</em> of an estimator. Intuitively, an estimator <span class="math inline">\(\hat{\tau}_n\)</span> for <span class="math inline">\(\tau\)</span> is called <em>consistent</em> if, for large sample sizes <span class="math inline">\(n \to \infty\)</span>, the probability that <span class="math inline">\(\hat{\tau}_n(y)\)</span> deviates from the true, but unknown, value <span class="math inline">\(\tau(\theta)\)</span> becomes arbitrarily small. For large sample sizes, the distributions of estimators often result in normal distributions. In <a href="#sec-asymptotic-normality" class="quarto-xref"><span>Section 31.3.3</span></a> we introduce a corresponding formalization with the concept of an <em>asymptotic normal distribution</em>. An estimator <span class="math inline">\(\hat{\tau}_n\)</span> for <span class="math inline">\(\tau\)</span> is then called <em>asymptotically normally distributed</em> if, for large sample sizes <span class="math inline">\(n \to \infty\)</span>, the distribution of <span class="math inline">\(\hat{\tau}_n\)</span> is given by a normal distribution. Finally, in <a href="#sec-asymptotic-efficiency" class="quarto-xref"><span>Section 31.3.4</span></a>, with <em>asymptotic efficiency</em>, we consider an optimality criterion for estimators at sample sizes tending to infinity. An estimator <span class="math inline">\(\hat{\tau}_n\)</span> for <span class="math inline">\(\tau\)</span> is then called <em>asymptotically efficient</em> if, for large sample sizes <span class="math inline">\(n \to \infty\)</span>, the distribution of <span class="math inline">\(\hat{\tau}_n\)</span> is given by a normal distribution with expectation parameter <span class="math inline">\(\tau(\theta)\)</span> and variance parameter equal to the Cramér-Rao bound.</p>
<section id="sec-asymptotic-unbiasedness" class="level3" data-number="31.3.1">
<h3 data-number="31.3.1" class="anchored" data-anchor-id="sec-asymptotic-unbiasedness"><span class="header-section-number">31.3.1</span> Asymptotic unbiasedness</h3>
<p>Asymptotic unbiasedness of an estimator refines the concept of an unbiased estimator as follows.</p>
<div id="def-asymptotic-unbiasedness" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.9 (Asymptotic unbiasedness)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model and let <span class="math inline">\(\hat{\tau}_n\)</span> be an estimator for <span class="math inline">\(\tau\)</span>. <span class="math inline">\(\hat{\tau}_n\)</span> is called <em>asymptotically unbiased</em> if <span class="math display">\[\begin{equation}
\lim_{n\to\infty} \mathbb{E}_\theta(\hat{\tau}_n(y)) = \tau(\theta) \mbox{ for all } \theta \in \Theta.
\end{equation}\]</span></p>
</div>
<p>Asymptotically unbiased estimators are therefore unbiased only when the sample size tends to infinity. Unbiased estimators are always also asymptotically unbiased, because their unbiasedness is independent of the sample size. As an example of an estimator that is only asymptotically unbiased, we consider the maximum likelihood estimator of the variance parameter of the normal distribution model.</p>
<div id="thm-asymptotic-unbiasedness-of-variance-parameter-estimator" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.14 (Asymptotic unbiasedness of the variance parameter estimator)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a normal distribution model with variance parameter <span class="math inline">\(\sigma^2\)</span>. Then the maximum likelihood estimator of <span class="math inline">\(\sigma^2\)</span>, <span class="math display">\[\begin{equation}
\hat{\sigma}_n^{2^{\mbox{\tiny ML}}}
:= \frac{1}{n}\sum_{i=1}^n \left(y_i - \bar{y}_n \right)^2,
\end{equation}\]</span> is not unbiased, but asymptotically unbiased.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>With the unbiasedness of the sample variance we first obtain (cf. <a href="#thm-unbiasedness-of-sample-mean-and-sample-variance" class="quarto-xref">Theorem&nbsp;<span>31.3</span></a>) <span class="math display">\[\begin{equation}
\mathbb{E}_{\mu,\sigma^2}\left(\hat{\sigma}_n^{2^{\mbox{\tiny ML}}} \right)
= \mathbb{E}_{\mu,\sigma^2}\left(\frac{1}{n}\sum_{i=1}^n \left(y_i - \bar{y}_n \right)^2 \right)
= \frac{1}{n}\mathbb{E}_{\mu,\sigma^2}\left(\sum_{i=1}^n \left(y_i - \bar{y}_n \right)^2 \right)
= \frac{n-1}{n}\sigma^2.
\end{equation}\]</span> Thus <span class="math display">\[\begin{equation}
\mathbb{E}_{\mu,\sigma^2}\left(\hat{\sigma}_n^{2^{\mbox{\tiny ML}}} \right) \neq \sigma^2
\end{equation}\]</span> and <span class="math inline">\(\hat{\sigma}_n^{2^{\mbox{\tiny ML}}}\)</span> is not an unbiased estimator of <span class="math inline">\(\sigma^2\)</span>. However, <span class="math display">\[\begin{equation}
\frac{n-1}{n} \to 1 \mbox{ for } n \to \infty,
\end{equation}\]</span> so that <span class="math display">\[\begin{equation}
\lim_{n \to \infty} \mathbb{E}_{\mu,\sigma^2}\left(\hat{\sigma}_n^{2^{\mbox{\tiny ML}}}\right) =
\lim_{n \to \infty}  \frac{n-1}{n}\sigma^2 =
\sigma^2 \lim_{n \to \infty}  \frac{n-1}{n} =
\sigma^2
\end{equation}\]</span> and the maximum likelihood estimator of <span class="math inline">\(\sigma^2\)</span> is therefore asymptotically unbiased.</p>
</div>
<div id="exm-simulation-example-asymptotic-unbiasedness" class="theorem example">
<p><span class="theorem-title"><strong>Example 31.4 (Simulation example)</strong></span> The following <strong>R</strong> code simulates the behavior of the maximum likelihood estimator for the variance parameter of a normal distribution model with true, but unknown, parameters <span class="math inline">\(\mu = 1\)</span> and <span class="math inline">\(\sigma^2 = 2\)</span> as a function of the sample size.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># model formulation</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>mu        <span class="ot">=</span> <span class="dv">1</span>                                               <span class="co"># true, but unknown, expectation parameter</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>sigsqr    <span class="ot">=</span> <span class="dv">2</span>                                               <span class="co"># true, but unknown, variance parameter</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>n         <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">100</span>, <span class="at">by =</span> <span class="dv">2</span>)                              <span class="co"># sample sizes</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>ns        <span class="ot">=</span> <span class="fl">1e3</span>                                             <span class="co"># number of simulations per sample size</span></span>
<span id="cb5-6"><a href="#cb5-6"></a>sigsqr_ml <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NaN</span>, <span class="fu">length</span>(n)<span class="sc">*</span>ns),<span class="at">ncol =</span> <span class="fu">length</span>(n)) <span class="co"># \hat{\sigma^2}^{ML} array</span></span>
<span id="cb5-7"><a href="#cb5-7"></a></span>
<span id="cb5-8"><a href="#cb5-8"></a><span class="co"># simulation</span></span>
<span id="cb5-9"><a href="#cb5-9"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq_along</span>(n)){                                     <span class="co"># sample size iterations</span></span>
<span id="cb5-10"><a href="#cb5-10"></a>    <span class="cf">for</span>(s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ns){                                         <span class="co"># sample realization iterations</span></span>
<span id="cb5-11"><a href="#cb5-11"></a>        y               <span class="ot">=</span> <span class="fu">rnorm</span>(n[i], mu, <span class="fu">sqrt</span>(sigsqr))     <span class="co"># sample realization</span></span>
<span id="cb5-12"><a href="#cb5-12"></a>        sigsqr_ml[s,i]  <span class="ot">=</span> ((n[i]<span class="sc">-</span><span class="dv">1</span>)<span class="sc">/</span>n[i])<span class="sc">*</span><span class="fu">var</span>(y)            <span class="co"># \hat{\sigma^2}^{ML}</span></span>
<span id="cb5-13"><a href="#cb5-13"></a>    }</span>
<span id="cb5-14"><a href="#cb5-14"></a>}</span>
<span id="cb5-15"><a href="#cb5-15"></a>E_sigsqr_ml <span class="ot">=</span> <span class="fu">colMeans</span>(sigsqr_ml)                           <span class="co"># estimator expectation estimate</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We visualize the expectation of the estimator estimated on the basis of the above simulations as a function of sample size in <a href="#fig-sigsqr-ml" class="quarto-xref">Figure&nbsp;<span>31.3</span></a>. For small sample sizes, the estimator clearly underestimates the true, but unknown, variance parameter; for larger sample sizes, it does not.</p>
</div>
<div id="fig-sigsqr-ml" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sigsqr-ml-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/402-sigsqr-ml.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sigsqr-ml-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;31.3: Simulation of the expectation of the maximum likelihood estimator for the variance parameter of a normal distribution model. For small sample sizes, the maximum likelihood estimator systematically underestimates the true, but unknown, variance parameter; for larger sample sizes, the estimator is approximately unbiased.
</figcaption>
</figure>
</div>
</section>
<section id="sec-consistency" class="level3" data-number="31.3.2">
<h3 data-number="31.3.2" class="anchored" data-anchor-id="sec-consistency"><span class="header-section-number">31.3.2</span> Consistency</h3>
<p>The concept of consistency of an estimator generalizes the weak law of large numbers from sample means and expectations (cf. <a href="../_part_3/309-Limits.html#thm-weak-law-of-large-numbers" class="quarto-xref">Theorem&nbsp;<span>27.1</span></a>) to arbitrary estimators and true, but unknown, parameter values.</p>
<div id="def-consistency" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.10 (Consistency)</strong></span> Let <span class="math inline">\(y := (y_1,...,y_n)\)</span> be the sample of a parametric product model and let <span class="math inline">\(\hat{\tau}_n\)</span> be an estimator of <span class="math inline">\(\tau\)</span>. Then a sequence of estimators <span class="math inline">\(\hat{\tau}_1, \hat{\tau}_2, ...\)</span> is called a <em>consistent sequence of estimators</em> if, for every arbitrarily small <span class="math inline">\(\epsilon &gt; 0\)</span> and every <span class="math inline">\(\theta \in \Theta\)</span>, <span class="math display">\[\begin{equation}
\lim_{n\to \infty}
\mathbb{P}_\theta\left(|\hat{\tau}_n(y) - \tau(\theta)| \ge \epsilon \right) = 0.
\end{equation}\]</span> If <span class="math inline">\(\hat{\tau}_1,\hat{\tau}_2,...\)</span> is a consistent sequence of estimators, then <span class="math inline">\(\hat{\tau}_n\)</span> is called a <em>consistent estimator</em>.</p>
</div>
<p>The intuition behind <a href="#def-consistency" class="quarto-xref">Definition&nbsp;<span>31.10</span></a> corresponds to the law of large numbers. For sample sizes with <span class="math inline">\(n \to \infty\)</span>, the probability that <span class="math inline">\(\hat{\tau}_n(y)\)</span> is arbitrarily close to <span class="math inline">\(\tau(\theta)\)</span>, or equivalently that <span class="math inline">\(\hat{\tau}_n(y)\)</span> deviates far from <span class="math inline">\(\tau(\theta)\)</span>, becomes small. However, these properties must hold for all possible true, but unknown, parameter values. As will be shown below, the sample mean is a consistent estimator for the expectation parameter of a normal distribution model.</p>
<div id="exm-simulation-example-consistency" class="theorem example">
<p><span class="theorem-title"><strong>Example 31.5</strong></span> Analogously to <a href="../_part_3/309-Limits.html#sec-laws-of-large-numbers" class="quarto-xref"><span>Section 27.1</span></a>, we demonstrate the meaning of consistency by simulation for <span class="math inline">\(\mu = 1\)</span> and <span class="math inline">\(\sigma^2 = 2\)</span> using the following <strong>R</strong> code.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># model formulation</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>mu      <span class="ot">=</span> <span class="dv">1</span>                                           <span class="co"># true, but unknown, value of \mu</span></span>
<span id="cb6-3"><a href="#cb6-3"></a>sigsqr  <span class="ot">=</span> <span class="dv">2</span>                                           <span class="co"># true, but unknown, value of \sigma^2</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>n       <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="fl">1e3</span>,<span class="at">by =</span> <span class="dv">10</span>)                          <span class="co"># sample size n</span></span>
<span id="cb6-5"><a href="#cb6-5"></a>eps     <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">0.15</span>, <span class="fl">0.10</span>, <span class="fl">0.05</span>)                         <span class="co"># \epsilon values</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>ne      <span class="ot">=</span> <span class="fu">length</span>(eps)                                 <span class="co"># number of \epsilon values</span></span>
<span id="cb6-7"><a href="#cb6-7"></a>nn      <span class="ot">=</span> <span class="fu">length</span>(n)                                   <span class="co"># number of sample sizes</span></span>
<span id="cb6-8"><a href="#cb6-8"></a>ns      <span class="ot">=</span> <span class="dv">1000</span>                                        <span class="co"># number of simulations</span></span>
<span id="cb6-9"><a href="#cb6-9"></a>E       <span class="ot">=</span> <span class="fu">array</span>(<span class="fu">rep</span>(<span class="cn">NaN</span>,nn<span class="sc">*</span>ne<span class="sc">*</span>ns),<span class="at">dim =</span> <span class="fu">c</span>(nn,ne,ns))  <span class="co"># event indicator array</span></span>
<span id="cb6-10"><a href="#cb6-10"></a></span>
<span id="cb6-11"><a href="#cb6-11"></a><span class="co"># simulation</span></span>
<span id="cb6-12"><a href="#cb6-12"></a><span class="cf">for</span>(e <span class="cf">in</span> <span class="fu">seq_along</span>(eps)){                             <span class="co"># \epsilon iterations</span></span>
<span id="cb6-13"><a href="#cb6-13"></a>    <span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq_along</span>(n)){                           <span class="co"># n iterations</span></span>
<span id="cb6-14"><a href="#cb6-14"></a>        <span class="cf">for</span>(s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ns){                               <span class="co"># simulation iterations</span></span>
<span id="cb6-15"><a href="#cb6-15"></a></span>
<span id="cb6-16"><a href="#cb6-16"></a>            <span class="co"># sample realizations</span></span>
<span id="cb6-17"><a href="#cb6-17"></a>            y   <span class="ot">=</span> <span class="fu">rnorm</span>(n[i], mu, <span class="fu">sqrt</span>(sigsqr))</span>
<span id="cb6-18"><a href="#cb6-18"></a>            <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">mean</span>(y) <span class="sc">-</span> mu) <span class="sc">&gt;=</span> eps[e]){          <span class="co"># |y_bar - \mu)| \ge \epsilon</span></span>
<span id="cb6-19"><a href="#cb6-19"></a>                E[i,e,s] <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb6-20"><a href="#cb6-20"></a>            } <span class="cf">else</span> {                                  <span class="co"># |y_bar - \mu)| &lt; \epsilon</span></span>
<span id="cb6-21"><a href="#cb6-21"></a>                E[i,e,s] <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb6-22"><a href="#cb6-22"></a>            }</span>
<span id="cb6-23"><a href="#cb6-23"></a>        }</span>
<span id="cb6-24"><a href="#cb6-24"></a>    }</span>
<span id="cb6-25"><a href="#cb6-25"></a>}</span>
<span id="cb6-26"><a href="#cb6-26"></a></span>
<span id="cb6-27"><a href="#cb6-27"></a><span class="co"># estimate of \mathbb{P}(|\hat{\tau}_n(y)-\tau(\theta)| \ge \epsilon)</span></span>
<span id="cb6-28"><a href="#cb6-28"></a>P_hat       <span class="ot">=</span> <span class="fu">apply</span>(E, <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We visualize the estimate of the probability <span class="math inline">\(\mathbb{P}(|\hat{\tau}_n(y)-\tau(\theta)| \ge \epsilon)\)</span> for this example in <a href="#fig-consistency" class="quarto-xref">Figure&nbsp;<span>31.4</span></a> as a function of sample size and criterion value <span class="math inline">\(\epsilon\)</span>. For larger values of <span class="math inline">\(\epsilon\)</span>, small sample sizes suffice for a small probability of deviation of the estimator from the true, but unknown, parameter value; for smaller values of <span class="math inline">\(\epsilon\)</span>, larger sample sizes are necessary.</p>
</div>
<div id="fig-consistency" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-consistency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/402-consistency.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-consistency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;31.4: Simulation of the consistency of the sample mean as an estimator for the expectation parameter of the normal distribution model.
</figcaption>
</figure>
</div>
<p>The criteria for consistency of estimators stated in <a href="#thm-mean-squared-error-criterion-for-consistency" class="quarto-xref">Theorem&nbsp;<span>31.15</span></a> and <a href="#thm-bias-variance-criterion-for-consistency" class="quarto-xref">Theorem&nbsp;<span>31.16</span></a> simplify the proof of consistency of an estimator with the help of the mean squared error (<a href="#def-mean-squared-error" class="quarto-xref">Definition&nbsp;<span>31.6</span></a>).</p>
<div id="thm-mean-squared-error-criterion-for-consistency" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.15 (Mean squared error criterion for consistency)</strong></span> Let <span class="math inline">\(y := (y_1,...,y_n)\)</span> be the sample of a parametric product model and let <span class="math inline">\(\hat{\tau}_n\)</span> be an estimator of <span class="math inline">\(\tau\)</span>. If <span class="math display">\[\begin{equation}
\lim_{n\to \infty} \mbox{MSE}(\hat{\tau}_n) = 0,
\end{equation}\]</span> then <span class="math inline">\(\hat{\tau}_n\)</span> is a consistent estimator.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>With Chebyshev’s inequality, <span class="math display">\[\begin{equation}
\mathbb{P}_\theta\left(|\hat{\tau}_n(y) - \tau(\theta)| \ge \epsilon \right) \le
\frac{\mathbb{E}_\theta\left((\hat{\tau}_n(y) -  \tau(\theta))^2\right)}{\epsilon^2}
\end{equation}\]</span> Taking limits gives <span class="math display">\[\begin{equation}
\lim_{n\to \infty}\mathbb{P}_\theta\left(|\hat{\tau}_n(y) - \tau(\theta)| \ge \epsilon \right) \le
\frac{1}{\epsilon^2}\lim_{n\to\infty}\mathbb{E}_\theta\left((\hat{\tau}_n(y) - \tau(\theta))^2\right).
\end{equation}\]</span> If therefore <span class="math inline">\(\lim_{n\to\infty}\mathbb{E}_\theta\left((\hat{\tau}_n(y) - \tau(\theta))^2\right) = 0\)</span>, then, with <span class="math inline">\(\mathbb{P}_\theta(|\hat{\tau}_n(y) - \tau(\theta)| \ge \epsilon)\ge 0\)</span>, <span class="math display">\[\begin{equation}
\lim_{n\to \infty}\mathbb{P}_\theta\left(|\hat{\tau}_n(y) - \tau(\theta)| \ge \epsilon \right) = 0.
\end{equation}\]</span> Thus <span class="math inline">\(\hat{\tau}_n\)</span> is a consistent estimator.</p>
</div>
<div id="thm-bias-variance-criterion-for-consistency" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.16 (Bias-variance criterion for consistency)</strong></span> Let <span class="math inline">\(y := (y_1,...,y_n)\)</span> be the sample of a parametric product model and let <span class="math inline">\(\hat{\tau}_n\)</span> be an estimator of <span class="math inline">\(\tau\)</span>. If <span class="math display">\[\begin{equation}
\lim_{n\to \infty} \mbox{B}(\hat{\tau}_n) = 0
\mbox{ and }
\lim_{n\to \infty} \mathbb{V}_\theta(\hat{\tau}_n) = 0
\end{equation}\]</span> hold, then <span class="math inline">\(\hat{\tau}_n\)</span> is a consistent estimator.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>If <span class="math inline">\(n \to \infty\)</span>, then <span class="math inline">\(\mbox{B}(\hat{\tau}_n) \to 0\)</span>, and thus also <span class="math inline">\(\mbox{B}(\hat{\tau}_n)^2 \to 0\)</span>. If for <span class="math inline">\(n \to \infty\)</span> both <span class="math inline">\(\mbox{B}(\hat{\tau}_n)^2 \to 0\)</span> and <span class="math inline">\(\mathbb{V}_\theta(\hat{\tau}_n) \to 0\)</span>, then also <span class="math inline">\(\lim_{n\to \infty} \mbox{MSE}(\hat{\theta}_n) = 0\)</span>. Hence, by <a href="#thm-mean-squared-error-criterion-for-consistency" class="quarto-xref">Theorem&nbsp;<span>31.15</span></a>, <span class="math inline">\(\hat{\tau}_n\)</span> is consistent.</p>
</div>
<p>As an application of <a href="#thm-bias-variance-criterion-for-consistency" class="quarto-xref">Theorem&nbsp;<span>31.16</span></a>, the following theorem proves consistency of the sample mean as an estimator of the expectation under normality.</p>
<div id="thm-consistency-of-expectation-estimator-under-normality" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.17 (Consistency of the expectation estimator under normality)</strong></span> Let <span class="math inline">\(y\)</span> be the sample of a normal distribution model. Then <span class="math inline">\(\bar{y}_n\)</span> is a consistent estimator of <span class="math inline">\(\mathbb{E}(y_1)\)</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>With the unbiasedness of the sample mean as an estimator of the expectation, we first have <span class="math display">\[\begin{equation}
\lim_{n \to \infty} \mbox{B}(\bar{y}_n) =  0.
\end{equation}\]</span> Furthermore, with the variance of the sample mean, <span class="math display">\[\begin{equation}
\lim_{n \to \infty} \mathbb{V}_\theta(\bar{y}_n) = \lim_{n\to \infty} \frac{1}{n}\mathbb{V}(y_1) = 0.
\end{equation}\]</span> By the bias-variance criterion, the consistency of <span class="math inline">\(\bar{y}_n\)</span> as an estimator of <span class="math inline">\(\mathbb{E}(y_1)\)</span> follows.</p>
</div>
<p>Note that <a href="#thm-consistency-of-expectation-estimator-under-normality" class="quarto-xref">Theorem&nbsp;<span>31.17</span></a> is of course already implied by the weak law of large numbers (cf. <a href="../_part_3/309-Limits.html#thm-weak-law-of-large-numbers" class="quarto-xref">Theorem&nbsp;<span>27.1</span></a>).</p>
</section>
<section id="sec-asymptotic-normality" class="level3" data-number="31.3.3">
<h3 data-number="31.3.3" class="anchored" data-anchor-id="sec-asymptotic-normality"><span class="header-section-number">31.3.3</span> Asymptotic normality</h3>
<p>In some cases, the frequentist distribution of an estimator approaches a normal distribution at large sample sizes. Such an estimator is called <em>asymptotically normally distributed</em>.</p>
<div id="def-asymptotically-normally-distributed-estimator" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.11 (Asymptotically normally distributed estimator)</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model and let <span class="math inline">\(\hat{\theta}_n\)</span> be a parameter estimator for <span class="math inline">\(\theta\)</span>. Furthermore, let <span class="math display">\[\begin{equation}
\tilde{\theta} \sim N(\mu,\sigma^2)
\end{equation}\]</span> be a normally distributed random variable with expectation parameter <span class="math inline">\(\mu\)</span> and variance parameter <span class="math inline">\(\sigma^2\)</span>. If <span class="math inline">\(\hat{\theta}_n\)</span> converges in distribution to <span class="math inline">\(\tilde{\theta}\)</span>, that is, if for the CDFs <span class="math inline">\(P_n\)</span> and <span class="math inline">\(P\)</span> of <span class="math inline">\(\hat{\theta}_n\)</span> and <span class="math inline">\(\tilde{\theta}\)</span>, respectively, <span class="math display">\[\begin{equation}
\lim_{n\to \infty} P_n(\hat{\theta}_n) = P(\tilde{\theta}),
\end{equation}\]</span> then <span class="math inline">\(\hat{\theta}_n\)</span> is called <em>asymptotically normally distributed</em> and we write <span class="math display">\[\begin{equation}
\hat{\theta}_n  \stackrel{a}{\sim}  N(\mu,\sigma^2).
\end{equation}\]</span></p>
</div>
<p>As an example of an asymptotically normally distributed estimator, in <a href="#sec-asymptotic-efficiency" class="quarto-xref"><span>Section 31.3.4</span></a> we consider the maximum likelihood estimator of the Bernoulli model parameter. It is remarkable that this estimator is asymptotically normally distributed, since the sample variables of the Bernoulli model take only the values zero and one.</p>
</section>
<section id="sec-asymptotic-efficiency" class="level3" data-number="31.3.4">
<h3 data-number="31.3.4" class="anchored" data-anchor-id="sec-asymptotic-efficiency"><span class="header-section-number">31.3.4</span> Asymptotic efficiency</h3>
<p>In some cases, in addition to asymptotic normality of an estimator, statements about the expectation parameter and variance parameter of this asymptotic normal distribution can also be justified by the form of the frequentist model. The concept of an <em>efficient estimator</em> formulates such a special case.</p>
<div id="def-asymptotic-efficiency" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.12</strong></span> Let <span class="math inline">\(y = (y_1,...,y_n)\)</span> be the sample of a parametric product model and let <span class="math inline">\(\hat{\theta}_n\)</span> be a parameter estimator for <span class="math inline">\(\theta\)</span>. Furthermore, let <span class="math inline">\(J(\theta)\)</span> be the expected Fisher information of the sample <span class="math inline">\(y\)</span>. If <span class="math display">\[\begin{equation}
\hat{\theta}_n \stackrel{a}{\sim} N\left(\theta, J(\theta)^{-1}\right),
\end{equation}\]</span> then <span class="math inline">\(\hat{\theta}_n\)</span> is called .</p>
</div>
<p>An asymptotically efficient estimator is evidently always also asymptotically normally distributed and unbiased. The variance of the asymptotic distribution of an estimator is also called the <em>asymptotic variance</em>. For an asymptotically efficient estimator, the asymptotic variance is identical to the Cramér-Rao bound and is therefore minimal in the set of unbiased asymptotically normally distributed estimators.</p>
<div id="exm-simulation-example-asymptotic-efficiency" class="theorem example">
<p><span class="theorem-title"><strong>Example 31.6</strong></span> As an example of an asymptotically efficient estimator, we consider the maximum likelihood estimator of the Bernoulli model parameter. The following <strong>R</strong> code simulates the frequentist distribution of this estimator and determines the PDF of its asymptotic distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># model formulation</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>mu          <span class="ot">=</span> <span class="fl">0.4</span>                                                       <span class="co"># true, but unknown, parameter value</span></span>
<span id="cb7-3"><a href="#cb7-3"></a>n_all       <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">1e1</span>,<span class="fl">5e1</span>,<span class="fl">1e2</span>)                                            <span class="co"># sample size</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>ns          <span class="ot">=</span> <span class="fl">1e4</span>                                                       <span class="co"># number of sample realizations</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>mu_hat      <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NaN</span>, <span class="fu">length</span>(n_all)<span class="sc">*</span>ns), <span class="at">nrow =</span> <span class="fu">length</span>(n_all))  <span class="co"># maximum likelihood estimator array</span></span>
<span id="cb7-6"><a href="#cb7-6"></a>mu_hat_r    <span class="ot">=</span> <span class="fl">1e3</span>                                                       <span class="co"># maximum likelihood estimator-space resolution</span></span>
<span id="cb7-7"><a href="#cb7-7"></a>mu_hat_y    <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">len =</span> mu_hat_r)                                   <span class="co"># maximum likelihood estimator space</span></span>
<span id="cb7-8"><a href="#cb7-8"></a>mu_hat_p    <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NaN</span>, <span class="fu">length</span>(n_all)<span class="sc">*</span>mu_hat_r), <span class="at">nrow =</span> <span class="fu">length</span>(n_all)) <span class="co"># maximum likelihood PDF array</span></span>
<span id="cb7-9"><a href="#cb7-9"></a></span>
<span id="cb7-10"><a href="#cb7-10"></a><span class="co"># sample size iterations</span></span>
<span id="cb7-11"><a href="#cb7-11"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq_along</span>(n_all)){</span>
<span id="cb7-12"><a href="#cb7-12"></a></span>
<span id="cb7-13"><a href="#cb7-13"></a>    <span class="co"># simulation iterations</span></span>
<span id="cb7-14"><a href="#cb7-14"></a>    <span class="cf">for</span>(s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ns){</span>
<span id="cb7-15"><a href="#cb7-15"></a>        y           <span class="ot">=</span> <span class="fu">rbinom</span>(n_all[i],<span class="dv">1</span>,mu)                             <span class="co"># sample realization</span></span>
<span id="cb7-16"><a href="#cb7-16"></a>        mu_hat[i,s] <span class="ot">=</span> <span class="fu">mean</span>(y)                                           <span class="co"># maximum likelihood estimator realization</span></span>
<span id="cb7-17"><a href="#cb7-17"></a>    }</span>
<span id="cb7-18"><a href="#cb7-18"></a>    mu_hat_p[i,] <span class="ot">=</span> <span class="fu">dnorm</span>(mu_hat_y, mu, <span class="fu">sqrt</span>(mu<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>mu)<span class="sc">/</span>n_all[i]))        <span class="co"># PDF of asymptotic distribution</span></span>
<span id="cb7-19"><a href="#cb7-19"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div id="fig-efficiency" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-efficiency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/402-efficiency.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-efficiency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;31.5: Simulation of the asymptotic efficiency of the maximum likelihood parameter estimator for the parameter of a Bernoulli model. With increasing sample size, the distribution of the simulated estimator values shown by a histogram becomes similar to the normal distribution formulated in <a href="#def-asymptotic-efficiency" class="quarto-xref">Definition&nbsp;<span>31.12</span></a>.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="sec-properties-of-maximum-likelihood-estimators" class="level2" data-number="31.4">
<h2 data-number="31.4" class="anchored" data-anchor-id="sec-properties-of-maximum-likelihood-estimators"><span class="header-section-number">31.4</span> Properties of maximum likelihood estimators</h2>
<p>The maximum likelihood principle for obtaining estimators for parameters of frequentist inference models is justified by the following theorem on the properties of maximum likelihood estimators.</p>
<div id="thm-properties-of-maximum-likelihood-estimators" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.18 (Properties of maximum likelihood estimators)</strong></span> Let <span class="math inline">\(y\)</span> be the sample of a parametric product model and let <span class="math inline">\(\hat{\theta}_n^{\mbox{\tiny{ML}}}\)</span> be a maximum likelihood estimator for <span class="math inline">\(\theta\)</span>. Then <span class="math inline">\(\hat{\theta}_n^{\mbox{\tiny{ML}}}\)</span></p>
<ol type="1">
<li>is not necessarily unbiased, but</li>
<li>is asymptotically unbiased,</li>
<li>is consistent,</li>
<li>is asymptotically normally distributed, and</li>
<li>is asymptotically efficient.</li>
</ol>
</div>
<p>For a proof of <a href="#thm-properties-of-maximum-likelihood-estimators" class="quarto-xref">Theorem&nbsp;<span>31.18</span></a> we refer to <span class="citation" data-cites="held2014">Held &amp; Sabanés Bové (<a href="#ref-held2014" role="doc-biblioref">2014</a>)</span>, Section 3.4. Thus, if one uses the maximum likelihood principle to obtain an estimator, the estimator obtained is guaranteed to satisfy the estimator quality criteria summarized in <a href="#thm-properties-of-maximum-likelihood-estimators" class="quarto-xref">Theorem&nbsp;<span>31.18</span></a>.</p>
</section>
<section id="bibliographic-remarks" class="level2" data-number="31.5">
<h2 data-number="31.5" class="anchored" data-anchor-id="bibliographic-remarks"><span class="header-section-number">31.5</span> Bibliographic remarks</h2>
<p>The results presented in this chapter go back in a very substantial way to <span class="citation" data-cites="fisher1922">Fisher (<a href="#ref-fisher1922" role="doc-biblioref">1922</a>)</span>. <span class="citation" data-cites="aldrich1997">Aldrich (<a href="#ref-aldrich1997" role="doc-biblioref">1997</a>)</span> provides historical context.</p>
</section>
<section id="study-questions" class="level2 unnumbered unlisted">
<h2 class="unnumbered unlisted anchored" data-anchor-id="study-questions">Study questions</h2>
<ol type="1">
<li>State the definition of a parameter point estimator.</li>
<li>Explain the concept of a parameter point estimator.</li>
<li>State the definition of the likelihood function and the log-likelihood function.</li>
<li>State the definition of a maximum likelihood estimator.</li>
<li>Explain the procedure for obtaining maximum likelihood estimators.</li>
<li>State the theorem on the maximum likelihood estimator of the Bernoulli model parameter.</li>
<li>State the theorem on the maximum likelihood estimators of the normal distribution model parameters.</li>
<li>State the definition of unbiasedness of an estimator.</li>
<li>Explain the concept of unbiasedness of an estimator.</li>
<li>State the definition of the variance and standard error of an estimator.</li>
<li>State the definition of asymptotic unbiasedness of an estimator.</li>
<li>Explain the concept of asymptotic unbiasedness of an estimator.</li>
<li>State the definition of consistency of an estimator.</li>
<li>Explain the concept of consistency of an estimator.</li>
<li>State the first three statements of the theorem on the properties of maximum likelihood estimators.</li>
</ol>
</section>
<section id="study-question-answers" class="level2 unnumbered unlisted">
<h2 class="unnumbered unlisted anchored" data-anchor-id="study-question-answers">Study question answers</h2>
<ol type="1">
<li>See <a href="#def-parameter-point-estimator" class="quarto-xref">Definition&nbsp;<span>31.1</span></a>.</li>
<li>A parameter point estimator gives, based on a sample, a guess for the corresponding true, but unknown, parameter.</li>
<li>See <a href="#def-likelihood-function-and-log-likelihood-function" class="quarto-xref">Definition&nbsp;<span>31.2</span></a>.</li>
<li>See <a href="#def-maximum-likelihood-estimator" class="quarto-xref">Definition&nbsp;<span>31.3</span></a>.</li>
<li>To obtain a maximum likelihood estimator, one first formulates the log-likelihood function and then determines the zeros of its derivative as potential maximum points. In classical examples one usually uses analytic optimization for this; in applications to more complex models, numerical optimization is usually used.</li>
<li>See <a href="#thm-maximum-likelihood-estimator-of-bernoulli-model" class="quarto-xref">Theorem&nbsp;<span>31.1</span></a>.</li>
<li>See <a href="#thm-maximum-likelihood-estimators-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>31.2</span></a>.</li>
<li>See <a href="#def-error-bias-and-unbiasedness" class="quarto-xref">Definition&nbsp;<span>31.4</span></a>.</li>
<li>An estimator is called unbiased if its expectation is identical to the true, but unknown, value it estimates.</li>
<li>See <a href="#def-variance-and-standard-error" class="quarto-xref">Definition&nbsp;<span>31.5</span></a>.</li>
<li>See <a href="#def-asymptotic-unbiasedness" class="quarto-xref">Definition&nbsp;<span>31.9</span></a>.</li>
<li>An estimator is called asymptotically unbiased if, for sample sizes tending to infinity, its expectation is identical to the true, but unknown, value it estimates.</li>
<li>See <a href="#def-consistency" class="quarto-xref">Definition&nbsp;<span>31.10</span></a>.</li>
<li>An estimator is called consistent if, for large sample sizes, the probability that the estimator value deviates from the true, but unknown, value becomes arbitrarily small.</li>
<li>See <a href="#thm-properties-of-maximum-likelihood-estimators" class="quarto-xref">Theorem&nbsp;<span>31.18</span></a>, statements (1), (2), and (3).</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-aldrich1997" class="csl-entry" role="listitem">
Aldrich, J. (1997). R.<span>A</span>. <span>Fisher</span> and the making of maximum likelihood 1912-1922. <em>Statistical Science</em>, <em>12</em>(3), 162–176. <a href="https://doi.org/10.1214/ss/1030037906">https://doi.org/10.1214/ss/1030037906</a>
</div>
<div id="ref-fisher1922" class="csl-entry" role="listitem">
Fisher, R. A. (1922). On the mathematical foundations of theoretical statistics. <em>Philosophical Transactions of the Royal Society of London. Series A, Containing Papers of a Mathematical or Physical Character</em>, <em>222</em>(594-604), 309–368. <a href="https://doi.org/10.1098/rsta.1922.0009">https://doi.org/10.1098/rsta.1922.0009</a>
</div>
<div id="ref-held2014" class="csl-entry" role="listitem">
Held, L., &amp; Sabanés Bové, D. (2014). <em>Applied <span>Statistical Inference</span></em>. Springer Berlin Heidelberg. <a href="https://doi.org/10.1007/978-3-642-37887-4">https://doi.org/10.1007/978-3-642-37887-4</a>
</div>
<div id="ref-vaart1998" class="csl-entry" role="listitem">
Vaart, A. W. van der. (1998). <em>Asymptotic statistics</em>. Cambridge University Press.
</div>
</div>
</section>

</main> <!-- /main -->
<script>
(function () {
  var base = "https://dirk-ostwald.github.io";
  var pageMap = {
    "/": "/en/",
    "/index.html": "/en/",
    "/Referenzen.html": "/en/References.html",
    "/_part_1/100-Mathematische-Grundlagen.html": "/en/_part_1/100-Mathematical-Foundations.html",
    "/_part_1/101-Sprache-und-Logik.html": "/en/_part_1/101-Language-and-Logic.html",
    "/_part_1/102-Mengen.html": "/en/_part_1/102-Sets.html",
    "/_part_1/103-Summen-Produkte-Potenzen.html": "/en/_part_1/103-Sums-Products-Powers.html",
    "/_part_1/104-Funktionen.html": "/en/_part_1/104-Functions.html",
    "/_part_1/105-Folgen-Grenzwerte-Stetigkeit.html": "/en/_part_1/105-Sequences-Limits-Continuity.html",
    "/_part_1/106-Differenzialrechnung.html": "/en/_part_1/106-Differential-Calculus.html",
    "/_part_1/107-Integralrechnung.html": "/en/_part_1/107-Integral-Calculus.html",
    "/_part_1/108-Vektoren.html": "/en/_part_1/108-Vectors.html",
    "/_part_1/109-Matrizen.html": "/en/_part_1/109-Matrices.html",
    "/_part_1/110-Deskriptivstatistiken.html": "/en/_part_1/110-Descriptive-Statistics.html",
    "/_part_2/200-Imperative-Programmierung.html": "/en/_part_2/200-Imperative-Programming.html",
    "/_part_2/201-Informatische-Grundbegriffe.html": "/en/_part_2/201-Basic-Concepts-of-Computer-Science.html",
    "/_part_2/202-Arithmetik-und-Variablen.html": "/en/_part_2/202-Arithmetic-and-Variables.html",
    "/_part_2/203-Datenstrukturen.html": "/en/_part_2/203-Data-Structures.html",
    "/_part_2/204-Vektoren.html": "/en/_part_2/204-Vectors.html",
    "/_part_2/205-Matrizen-und-Arrays.html": "/en/_part_2/205-Matrices-and-Arrays.html",
    "/_part_2/206-Listen-Dataframes-und-Tibbles.html": "/en/_part_2/206-Lists-Dataframes-and-Tibbles.html",
    "/_part_2/207-Datenmanagement.html": "/en/_part_2/207-Data-Management.html",
    "/_part_2/208-Kontrollstrukturen.html": "/en/_part_2/208-Control-Structures.html",
    "/_part_3/300-Wahrscheinlichkeitstheorie.html": "/en/_part_3/300-Probability-Theory.html",
    "/_part_3/301-Wahrscheinlichkeitsräume.html": "/en/_part_3/301-Probability-Spaces.html",
    "/_part_3/302-Elementare-Wahrscheinlichkeiten.html": "/en/_part_3/302-Elementary-Probabilities.html",
    "/_part_3/303-Zufallsvariablen.html": "/en/_part_3/303-Random-Variables.html",
    "/_part_3/304-Zufallsvektoren.html": "/en/_part_3/304-Random-Vectors.html",
    "/_part_3/305-Erwartungswerte.html": "/en/_part_3/305-Expectations.html",
    "/_part_3/306-Varianzen.html": "/en/_part_3/306-Variances.html",
    "/_part_3/307-Kovarianzen.html": "/en/_part_3/307-Covariances.html",
    "/_part_3/308-Ungleichungen.html": "/en/_part_3/308-Inequalities.html",
    "/_part_3/309-Grenzwerte.html": "/en/_part_3/309-Limits.html",
    "/_part_3/310-Transformationen.html": "/en/_part_3/310-Transformations.html",
    "/_part_3/311-Normalverteilungen.html": "/en/_part_3/311-Normal-Distributions.html",
    "/_part_4/400-Inferenz.html": "/en/_part_4/400-Inference.html",
    "/_part_4/401-Frequentistische-Inferenz.html": "/en/_part_4/401-Frequentist-Inference.html",
    "/_part_4/402-Punktschätzung.html": "/en/_part_4/402-Point-Estimation.html",
    "/_part_4/403-Konfidenzintervalle.html": "/en/_part_4/403-Confidence-Intervals.html",
    "/_part_4/404-Hypothesentests.html": "/en/_part_4/404-Hypothesis-Tests.html",
    "/_part_5/500-Allgemeines-Lineares-Modell.html": "/en/_part_5/500-General-Linear-Model.html",
    "/_part_5/501-Regression.html": "/en/_part_5/501-Regression.html",
    "/_part_5/502-Korrelation.html": "/en/_part_5/502-Correlation.html",
    "/_part_5/503-Modellformulierung.html": "/en/_part_5/503-Model-Formulation.html",
    "/_part_5/504-Parameterschätzung.html": "/en/_part_5/504-Parameter-Estimation.html",
    "/_part_5/505-T-Statistiken.html": "/en/_part_5/505-T-Statistics.html",
    "/_part_5/506-F-Statistiken.html": "/en/_part_5/506-F-Statistics.html"
  };
  var reversePageMap = {};
  Object.keys(pageMap).forEach(function (key) {
    reversePageMap[pageMap[key]] = key;
  });
  function headings() {
    return Array.prototype.slice.call(document.querySelectorAll("main.content h1[id], main.content h2[id], main.content h3[id], main.content h4[id]"));
  }
  function currentHeadingIndex() {
    var hash = window.location.hash;
    if (!hash) return "";
    var id = hash.slice(1);
    try {
      id = decodeURIComponent(id);
    } catch (error) {}
    var list = headings();
    for (var i = 0; i < list.length; i++) {
      if (list[i].id === id) return String(i);
    }
    return "";
  }
  function scrollToHeadingIndex() {
    var params = new URLSearchParams(window.location.search);
    var value = params.get("h");
    if (value === null) return;
    var index = Number(value);
    var list = headings();
    if (Number.isInteger(index) && index >= 0 && index < list.length) {
      list[index].scrollIntoView();
      if (history.replaceState) {
        history.replaceState(null, "", window.location.pathname + "#" + list[index].id);
      }
    }
  }
  var path = window.location.pathname;
  var target = pageMap[path] || reversePageMap[path];
  if (target) {
    document.querySelectorAll("a.nav-link").forEach(function (link) {
      var text = link.textContent.trim();
      if (text === "English" || text === "Deutsch") {
        var index = currentHeadingIndex();
        link.href = base + target + (index ? "?h=" + index : "");
      }
    });
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", scrollToHeadingIndex);
  } else {
    scrollToHeadingIndex();
  }
}());
</script>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../_part_4/401-Frequentist-Inference.html" class="pagination-link" aria-label="Frequentist inference">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Frequentist inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../_part_4/403-Confidence-Intervals.html" class="pagination-link" aria-label="Confidence intervals">
        <span class="nav-page-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages/edit/main/_part_4/402-Point-Estimation.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>