<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Probabilistische Datenwissenschaft für die Psychologie - 31&nbsp; T-Tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./408-Einfaktorielle-Varianzanalyse.html" rel="next">
<link href="./406-F-Statistiken.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./401-Regression.html">Das Allgemeine Lineare Modell</a></li><li class="breadcrumb-item"><a href="./407-T-Tests.html"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">T-Tests</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Probabilistische Datenwissenschaft für die Psychologie</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages" title="Quellcode" class="quarto-navigation-tool px-1" aria-label="Quellcode"><i class="bi bi-github"></i></a>
    <a href="./Probabilistische-Datenwissenschaft-für-die-Psychologie.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Willkommen</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Mathematische Grundlagen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./101-Sprache-und-Logik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Sprache und Logik</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./102-Mengen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Mengen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./103-Summen-Produkte-Potenzen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summen, Produkte, Potenzen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./104-Funktionen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Funktionen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./105-Differentialrechnung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Differentialrechnung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./106-Folgen-Grenzwerte-Stetigkeit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Folgen, Grenzwerte, Stetigkeit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./107-Integralrechnung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Integralrechnung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./108-Vektoren.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Vektoren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./109-Matrizen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Matrizen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./110-Eigenanalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Eigenanalyse</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./200-Wahrscheinlichkeitstheorie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wahrscheinlichkeitstheorie</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./201-Wahrscheinlichkeitsräume.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Wahrscheinlichkeitsräume</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./202-Elementare-Wahrscheinlichkeiten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Elementare Wahrscheinlichkeiten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./203-Zufallsvariablen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Zufallsvariablen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./204-Zufallsvektoren.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Zufallsvektoren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./205-Erwartungswerte.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Erwartungswerte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./206-Ungleichungen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ungleichungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./207-Grenzwerte.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Grenzwerte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./208-Transformationstheoreme.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Transformationstheoreme</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./209-Normalverteilungstransformationen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Normalverteilungstransformationen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./210-Multivariate-Normalverteilungen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multivariate Normalverteilungen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Frequentistische Inferenz</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./301-Grundbegriffe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Grundbegriffe</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./302-Punktschätzung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Punktschätzung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./303-Konfidenzintervalle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Konfidenzintervalle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./304-Hypothesentests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Hypothesentests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Das Allgemeine Lineare Modell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./401-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./402-Korrelation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Korrelation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./403-Modellformulierung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modellformulierung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./404-Parameterschätzung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Parameterschätzung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./405-T-Statistiken.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">T-Statistiken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./406-F-Statistiken.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">F-Statistiken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./407-T-Tests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">T-Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./408-Einfaktorielle-Varianzanalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Einfaktorielle Varianzanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./409-Zweifaktorielle-Varianzanalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Zweifaktorielle Varianzanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./410-Partielle-Korrelation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Partielle Korrelation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./411-Multiple-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Multivariate Inferenz</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./501-Datendeskription.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Datendeskription</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./502-Einstichproben-T2-Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Einstichproben-T<span class="math inline">\(^2\)</span>-Tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./503-Einfaktorielle-Varianzanalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Einfaktorielle Varianzanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./504-Kanonische-Korrelationsanalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Kanonische Korrelationsanalyse</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Referenzen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referenzen</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#einstichproben-t-tests" id="toc-einstichproben-t-tests" class="nav-link active" data-scroll-target="#einstichproben-t-tests"><span class="header-section-number">31.1</span> Einstichproben-T-Tests</a>
  <ul class="collapse">
  <li><a href="#anwendungsszenario" id="toc-anwendungsszenario" class="nav-link" data-scroll-target="#anwendungsszenario">Anwendungsszenario</a></li>
  <li><a href="#anwendungsbeispiel" id="toc-anwendungsbeispiel" class="nav-link" data-scroll-target="#anwendungsbeispiel">Anwendungsbeispiel</a></li>
  <li><a href="#modellformulierung" id="toc-modellformulierung" class="nav-link" data-scroll-target="#modellformulierung">Modellformulierung</a></li>
  <li><a href="#modellschätzung" id="toc-modellschätzung" class="nav-link" data-scroll-target="#modellschätzung">Modellschätzung</a></li>
  </ul></li>
  <li><a href="#modellevaluation" id="toc-modellevaluation" class="nav-link" data-scroll-target="#modellevaluation"><span class="header-section-number">31.2</span> Modellevaluation</a>
  <ul class="collapse">
  <li><a href="#anwendungsbeispiel-1" id="toc-anwendungsbeispiel-1" class="nav-link" data-scroll-target="#anwendungsbeispiel-1">Anwendungsbeispiel</a></li>
  </ul></li>
  <li><a href="#zweistichproben-t-tests" id="toc-zweistichproben-t-tests" class="nav-link" data-scroll-target="#zweistichproben-t-tests"><span class="header-section-number">31.3</span> Zweistichproben-T-Tests</a>
  <ul class="collapse">
  <li><a href="#anwendungsszenario-1" id="toc-anwendungsszenario-1" class="nav-link" data-scroll-target="#anwendungsszenario-1">Anwendungsszenario</a></li>
  <li><a href="#anwendungsbeispiel-2" id="toc-anwendungsbeispiel-2" class="nav-link" data-scroll-target="#anwendungsbeispiel-2">Anwendungsbeispiel</a></li>
  <li><a href="#modellformulierung-1" id="toc-modellformulierung-1" class="nav-link" data-scroll-target="#modellformulierung-1">Modellformulierung</a></li>
  <li><a href="#modellschätzung-1" id="toc-modellschätzung-1" class="nav-link" data-scroll-target="#modellschätzung-1">Modellschätzung</a></li>
  <li><a href="#modellevaluation-1" id="toc-modellevaluation-1" class="nav-link" data-scroll-target="#modellevaluation-1">Modellevaluation</a></li>
  <li><a href="#anwendungsbeispiel-3" id="toc-anwendungsbeispiel-3" class="nav-link" data-scroll-target="#anwendungsbeispiel-3">Anwendungsbeispiel</a></li>
  </ul></li>
  <li><a href="#literaturhinweise" id="toc-literaturhinweise" class="nav-link" data-scroll-target="#literaturhinweise"><span class="header-section-number">31.4</span> Literaturhinweise</a></li>
  <li><a href="#selbstkontrollfragen" id="toc-selbstkontrollfragen" class="nav-link" data-scroll-target="#selbstkontrollfragen"><span class="header-section-number">31.5</span> Selbstkontrollfragen</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages/edit/main/407-T-Tests.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./401-Regression.html">Das Allgemeine Lineare Modell</a></li><li class="breadcrumb-item"><a href="./407-T-Tests.html"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">T-Tests</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-t-tests" class="quarto-section-identifier"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">T-Tests</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="einstichproben-t-tests" class="level2" data-number="31.1">
<h2 data-number="31.1" class="anchored" data-anchor-id="einstichproben-t-tests"><span class="header-section-number">31.1</span> Einstichproben-T-Tests</h2>
<section id="anwendungsszenario" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="anwendungsszenario">Anwendungsszenario</h3>
<p>Das Anwendungsszenario eines Einstichproben-T-Test ist bekanntlich dadurch gekennzeichnet, dass <span class="math inline">\(n\)</span> univariate Datenpunkte einer Stichprobe (Gruppe) randomisierter experimenteller Einheiten betrachtet werden, von denen angenommen wird, dass sie Realisierungen von <span class="math inline">\(n\)</span> unabhängigen und identisch normalverteilten Zufallsvariablen sind. Hinsichtlich der identischen univariaten Normalverteilungen <span class="math inline">\(N\left(\mu, \sigma^{2}\right)\)</span> dieser Zufallsvariablen wird angenommen, dass sowohl der Erwartungswertparameter <span class="math inline">\(\mu\)</span> als auch der Varianzparameter <span class="math inline">\(\sigma^{2}\)</span> unbekannt sind. Schließlich wird vorausgesetzt, dass ein Interesse an einem inferentiellen Vergleich des unbekannten Erwartungswertparameters <span class="math inline">\(\mu\)</span> mit einen vorgebenenen Wert <span class="math inline">\(\mu_{0}\)</span> (z.B. <span class="math inline">\(\mu_{0}:=0\)</span> ) besteht.</p>
</section>
<section id="anwendungsbeispiel" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="anwendungsbeispiel">Anwendungsbeispiel</h3>
<p>Für ein konkretes Anwendungsbeispiel betrachten wir die Analyse von Pre-PostInterventions-BDI-Differenzwerten einer Gruppe von <span class="math inline">\(n=12\)</span> Patient:innen wie in <a href="#tbl-ett-daten" class="quarto-xref">Tabelle&nbsp;<span>31.1</span></a> dargestellt. Die ersten beiden Spalten dieser Tabelle listen die patientenspezifische BDI Werte vor (PreBDI) und nach (PosBDI) der psychotherapeutischen Intervention, die dritte Spalte dBDI zeigt die entsprechenden PreBDI-PosBDI Differenzwerte. Ein positiver Wert entspricht hier einer Verbesserung der Depressionssymptomatik und ein negativer Wert einer Verschlechterung der Depressionssymptomatik</p>
<div class="cell">
<div id="tbl-ett-daten" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ett-daten-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;31.1: Pre- und Post-Intervention BDI Werte
</figcaption>
<div aria-describedby="tbl-ett-daten-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">PreBDI</th>
<th style="text-align: center;">PosBDI</th>
<th style="text-align: center;">dBDI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">29</td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">32</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">28</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">36</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">32</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">28</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">33</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">33</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">33</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">30</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">36</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="even">
<td style="text-align: center;">32</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">6</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Bei der Anwendung eines Einstichproben-T-Tests auf die dBDI Daten dieses Datensatzes nehmen wir also an, dass die <code>dBDI</code> Daten Realisierungen von <span class="math inline">\(n=12\)</span> unabhängig normalverteilten Zufallsvariablen <span class="math inline">\(\upsilon_i \sim N\left(\mu, \sigma^{2}\right)\)</span> sind. Wir nehmen weiterhin an, dass wir daran interessiert sind, unsere Unsicherheit beim inferentiellen Vergleich des wahren, aber unbekannten, Erwartungswertparameters <span class="math inline">\(\mu\)</span> mit einem Vergleichswert <span class="math inline">\(\mu_{0}\)</span> im Sinne eines Hypothesentests zu quantifizieren.</p>
<p>Unabhängig von diesem inferenzstatistischen Vorgehen betrachten wir zunächst die deskriptiven Statistiken der dBDI Daten, wie in <a href="#tbl-ett-deskription" class="quarto-xref">Tabelle&nbsp;<span>31.2</span></a> dargestellt. Es fällt insbesondere auf, dass das Stichprobenmittel im Vergleich zur Standardabweichung relativ klein ist. Im Gruppenmittel unterscheiden sich die PreBDI und PosBDI also zwar in positiver Richtung, was eine Verringerung der Depressionssymptomatik impliziert, allerdings streuen die Daten auch über Patient:innen deutlich, wie auch bereits aus <a href="#tbl-ett-daten" class="quarto-xref">Tabelle&nbsp;<span>31.1</span></a> ersichtlich.</p>
<div class="cell">
<div id="tbl-ett-deskription" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ett-deskription-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;31.2: Deskriptivstatistiken der Pre-Post BDI Differenzwerte
</figcaption>
<div aria-describedby="tbl-ett-deskription-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">n</th>
<th style="text-align: center;">Max</th>
<th style="text-align: center;">Min</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">Var</th>
<th style="text-align: center;">Std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">F2F</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5.17</td>
<td style="text-align: center;">20.88</td>
<td style="text-align: center;">4.57</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="modellformulierung" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="modellformulierung">Modellformulierung</h3>
<p>Wir definieren nun das Einstichproben-T-Test-Modell wie folgt.</p>
<div id="def-einstichproben-t-test-modell" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.1 (Einstichproben-T-Test-Modell)</strong></span> Für <span class="math inline">\(i=1, \ldots, n\)</span> seien <span class="math inline">\(\upsilon_i\)</span> Zufallsvariablen, die die <span class="math inline">\(n\)</span> Datenpunkte eines Einstichproben-T-Test-Szenarios modellieren. Dann hat das Einstichproben-T-Test-Modell die strukturelle Form <span class="math display">\[\begin{equation}
\upsilon_i
= \mu+\varepsilon_{i}
\mbox{ mit } \varepsilon_{i} \sim N\left(0, \sigma^{2}\right)
\mbox{ u.i.v für } i=1, \ldots, n \mbox{ mit } \mu \in \mathbb{R} \mbox{ und } \sigma^{2}&gt;0,
\end{equation}\]</span> die Datenverteilungsform <span class="math display">\[\begin{equation}
\upsilon_i \sim N\left(\mu, \sigma^{2}\right)
\mbox{ u.i.v für } i=1, \ldots, n \mbox{ mit } \mu \in \mathbb{R} \mbox{ und } \sigma^{2}&gt;0,
\end{equation}\]</span> und für den Datenvektor <span class="math inline">\(v=\left(\upsilon_{1}, \ldots, \upsilon_{n}\right)^{T}\)</span> die Designmatrixform <span class="math display">\[\begin{equation}
\upsilon = X\beta+\varepsilon
\mbox{ mit } X:=1_{n} \in \mathbb{R}^{n \times 1},
\beta:=\mu \in \mathbb{R},
\varepsilon \sim N\left(0_{n}, \sigma^{2} I_{n}\right)
\mbox{ und } \sigma^{2}&gt;0.
\end{equation}\]</span></p>
</div>
<p>Das Modell des Einstichproben-T-Tests ist offenbar mit dem dem Modell unabhängiger und identisch normalverteilter Zufallsvariablen identisch (vgl. <a href="403-Modellformulierung.html" class="quarto-xref"><span>Kapitel 27</span></a>). Die Äquivalenz von struktureller, Datenverteilungs- und Designmatrixform des Einstichproben-T-TestModells wurde in <a href="403-Modellformulierung.html" class="quarto-xref"><span>Kapitel 27</span></a> bereits ausführlich diskutiert. Die Simulation von Daten basierend auf dem Einstichproben-T-Test-Modell hat dementsprechend die gleiche Form wie die Simulation unabhängig und identisch normalverteilter Zufallsvariablen. Unterer <strong>R</strong> Code demonstriert dies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># Modellformulierung</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(MASS)                                                         <span class="co"># Multivariate Normalverteilung</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>n      <span class="ot">=</span> <span class="dv">12</span>                                                           <span class="co"># Anzahl von Datenpunkten</span></span>
<span id="cb1-4"><a href="#cb1-4"></a>p      <span class="ot">=</span> <span class="dv">1</span>                                                            <span class="co"># Anzahl von Betaparameter</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>X      <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n), <span class="at">nrow =</span> n)                                   <span class="co"># Designmatrix</span></span>
<span id="cb1-6"><a href="#cb1-6"></a>I_n    <span class="ot">=</span> <span class="fu">diag</span>(n)                                                      <span class="co"># n x n Einheitsmatrix</span></span>
<span id="cb1-7"><a href="#cb1-7"></a>beta   <span class="ot">=</span> <span class="dv">5</span>                                                            <span class="co"># wahrer, aber unbekannter, Betaparameter</span></span>
<span id="cb1-8"><a href="#cb1-8"></a>sigsqr <span class="ot">=</span> <span class="dv">14</span>                                                           <span class="co"># wahrer, aber unbekannter, Varianzparameter</span></span>
<span id="cb1-9"><a href="#cb1-9"></a></span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="co"># Datenrealisierung</span></span>
<span id="cb1-11"><a href="#cb1-11"></a>y      <span class="ot">=</span> <span class="fu">mvrnorm</span>(<span class="dv">1</span>, X <span class="sc">%*%</span> beta, sigsqr<span class="sc">*</span>I_n)                           <span class="co"># eine Realisierung eines n-dimensionalen ZVs</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="modellschätzung" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="modellschätzung">Modellschätzung</h3>
<p>Da die Form des Einstichproben-T-Test-Modells mit dem Szenario unabhängig und identisch normalverteilter Zufallsvariablen identisch ist, trifft dies auch auf die entsprechenden Beta- und Varianzparameterschätzer zu. Es ergibt sich also folgendes Theorem, das bereits in <a href="404-Parameterschätzung.html" class="quarto-xref"><span>Kapitel 28</span></a> bewiesen wurde.</p>
<div id="thm-parameterschaetzer-im-einstichtproben-t-test-modell" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.1 (Parameterschätzer im Einstichproben-T-Test-Modell)</strong></span> Gegeben sei die Designmatrixform des Einstichproben-T-Test-Modells. Dann ergeben sich für den Betaparameterschätzer <span class="math display">\[\begin{equation}
\hat{\beta}=\frac{1}{n} \sum_{i=1}^{n} \upsilon_i=: \bar{\upsilon}
\end{equation}\]</span> und für den Varianzparameterschätzer <span class="math display">\[\begin{equation}
\hat{\sigma}^{2}=\frac{1}{n-1} \sum_{i=1}^{n}\left(\upsilon_i-\bar{\upsilon}\right)^{2}=: s_{\upsilon}^{2}
\end{equation}\]</span> <span class="math inline">\(\bar{\upsilon}\)</span> und <span class="math inline">\(s_{\upsilon}^{2}\)</span> bezeichnen hier also wiederum das Stichprobenmittel und die Stichprobenvarianz der Zufallsvariablen <span class="math inline">\(\upsilon_{1}, \ldots, \upsilon_{n}\)</span>.</p>
</div>
</section>
</section>
<section id="modellevaluation" class="level2" data-number="31.2">
<h2 data-number="31.2" class="anchored" data-anchor-id="modellevaluation"><span class="header-section-number">31.2</span> Modellevaluation</h2>
<p>Basierend auf <a href="405-T-Statistiken.html#def-t-statistik" class="quarto-xref">Definition&nbsp;<span>29.1</span></a> formulieren wir nun die T-Teststatistik für das Einstichproben-T-Test Szenario und geben ihre frequentistische Verteilung an.</p>
<div id="thm-t-teststatistik-des-einstichproben-t-tests" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.2 (T-Teststatistik des Einstichproben-T-Tests)</strong></span> Gegeben sei die Designmatrixform des Einstichproben-T-Test-Modells. Dann ergibt sich für die T-Teststatistik mit <span class="math display">\[\begin{equation}
c:=1 \mbox{ und } c^{T} \beta_{0}=: \mu_{0},
\end{equation}\]</span> dass <span class="math display">\[\begin{equation}
T = \sqrt{n}\left(\frac{\bar{\upsilon}-\mu_{0}}{s_{\upsilon}}\right)
\end{equation}\]</span> und es gilt, dass <span class="math display">\[\begin{equation}
T \sim t(\delta, n-1) \mbox{ mit } \delta=\sqrt{n}\left(\frac{\mu-\mu_{0}}{\sigma}\right).
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Beweis</em>. </span>Mit <a href="405-T-Statistiken.html#thm-frequentistische-verteilung-der-t-statistik" class="quarto-xref">Theorem&nbsp;<span>29.1</span></a> gilt <span class="math display">\[\begin{equation}
T
=\frac{c^{T} \hat{\beta}-c^{T} \beta_{0}}{\sqrt{\hat{\sigma}^{2} c^{T}\left(X^{T} X\right)^{-1} c}}
=\frac{1^{T} \bar{\upsilon}-1^{T} \mu_{0}}{\sqrt{s_{\upsilon}^{2} 1^{T}\left(1_{n}^{T} 1_{n}\right)^{-1} 1}}
=\sqrt{n}\left(\frac{\bar{\upsilon}-\mu_{0}}{s_{\upsilon}}\right) .
\end{equation}\]</span> Weiterhin gilt mit demselben Theorem <span class="math display">\[\begin{equation}
\delta
=\frac{c^{T} \beta-c^{T} \beta_{0}}{\sqrt{\sigma^{2} c^{T}\left(X^{T} X\right)^{-1} c}}
=\frac{1^{T} \mu-1^{T} \mu_{0}}{\sqrt{\sigma^{2} 1^{T}\left(1_{n}^{T} 1_{n}\right)^{-1} 1}}=\sqrt{n}\left(\frac{\mu-\mu_{0}}{\sigma}\right).
\end{equation}\]</span></p>
</div>
<p>Die Formen der T-Teststatistik und ihre Verteilung im Einstichproben-T-Test-Spezialfall des ALMs sind also natürlicherweise mit den entsprechenden Formen im ALM-freien Kontext identisch. Die enstprechende Theorie zu Konfidenzintervallen und der Kontrolle des Testumfangs bei Einstichproben-T-Tests sowie der Gebrauch der Testgütefunktion zur Evaluation der Testtrennschärfe (Power) folgt also analog.</p>
<section id="anwendungsbeispiel-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="anwendungsbeispiel-1">Anwendungsbeispiel</h3>
<p>Folgender <strong>R</strong> Code demonstriert die Evaluation eines 95%-Konfidenzintervalls für den Erwartungswertparameter <span class="math inline">\(\mu\)</span> sowie Durchführung eines zweiseitigen Einstichproben-T-Tests mit einfacher Nullhypothese <span class="math inline">\(\Theta_{0}:=\{0\}\)</span> und Signifikanzlevel <span class="math inline">\(\alpha_{0}:=0.05\)</span> für das oben skizzierte Anwendungsbeispiel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># Datenanalyse</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>D           <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/407-t-tests.csv"</span>)                        <span class="co"># Laden des Datensatzes</span></span>
<span id="cb2-3"><a href="#cb2-3"></a>y           <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>COND <span class="sc">==</span> <span class="st">"F2F"</span>]                                    <span class="co"># Post-Pre Differenzwerte</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>n           <span class="ot">=</span> <span class="fu">length</span>(y)                                                  <span class="co"># Anzahl Datenpunkte</span></span>
<span id="cb2-5"><a href="#cb2-5"></a>p           <span class="ot">=</span> <span class="dv">1</span>                                                          <span class="co"># Anzahl Betaparameter</span></span>
<span id="cb2-6"><a href="#cb2-6"></a>c           <span class="ot">=</span> <span class="dv">1</span>                                                          <span class="co"># Kontrastgewichtsvektor</span></span>
<span id="cb2-7"><a href="#cb2-7"></a>mu_0        <span class="ot">=</span> <span class="dv">0</span>                                                          <span class="co"># Nullhypothesenparameter       </span></span>
<span id="cb2-8"><a href="#cb2-8"></a>delta       <span class="ot">=</span> <span class="fl">0.95</span>                                                       <span class="co"># Konfidenzlevel</span></span>
<span id="cb2-9"><a href="#cb2-9"></a>alpha_0     <span class="ot">=</span> <span class="fl">0.05</span>                                                       <span class="co"># Signifikanzlevel  </span></span>
<span id="cb2-10"><a href="#cb2-10"></a>X           <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n), <span class="at">nrow =</span> n)                                 <span class="co"># Einstichproben-T-Test Designmatrix </span></span>
<span id="cb2-11"><a href="#cb2-11"></a>beta_hat    <span class="ot">=</span> <span class="fu">solve</span>(<span class="fu">t</span>(X)<span class="sc">%*%</span>X)<span class="sc">%*%</span><span class="fu">t</span>(X)<span class="sc">%*%</span>y                                 <span class="co"># Betaparameterschätzer</span></span>
<span id="cb2-12"><a href="#cb2-12"></a>eps_hat     <span class="ot">=</span> y <span class="sc">-</span> X <span class="sc">%*%</span> beta_hat                                         <span class="co"># Residuenvektor </span></span>
<span id="cb2-13"><a href="#cb2-13"></a>sigsqr_hat  <span class="ot">=</span> (<span class="fu">t</span>(eps_hat) <span class="sc">%*%</span> eps_hat)<span class="sc">/</span>(n<span class="sc">-</span>p)                             <span class="co"># Varianzparameterschätzer</span></span>
<span id="cb2-14"><a href="#cb2-14"></a>t_delta     <span class="ot">=</span> <span class="fu">qt</span>((<span class="dv">1</span><span class="sc">+</span>delta)<span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>)                                        <span class="co"># \Psi^{-1}(1+\delta)/2, n-1)</span></span>
<span id="cb2-15"><a href="#cb2-15"></a>lambda      <span class="ot">=</span> <span class="fu">diag</span>(<span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X))                                    <span class="co"># \lambda_j Werte</span></span>
<span id="cb2-16"><a href="#cb2-16"></a>kappa_u     <span class="ot">=</span> beta_hat <span class="sc">-</span> <span class="fu">sqrt</span>(sigsqr_hat<span class="sc">*</span>lambda)<span class="sc">*</span>t_delta                 <span class="co"># untere Konfidenzintervallgrenze</span></span>
<span id="cb2-17"><a href="#cb2-17"></a>kappa_o     <span class="ot">=</span> beta_hat <span class="sc">+</span> <span class="fu">sqrt</span>(sigsqr_hat<span class="sc">*</span>lambda)<span class="sc">*</span>t_delta                 <span class="co"># obere Konfidenzintervallgrenze</span></span>
<span id="cb2-18"><a href="#cb2-18"></a>t_num       <span class="ot">=</span> <span class="fu">t</span>(c) <span class="sc">%*%</span> beta_hat <span class="sc">-</span> mu_0                                   <span class="co"># Zähler der Einstichproben-T-Teststatistik</span></span>
<span id="cb2-19"><a href="#cb2-19"></a>t_den       <span class="ot">=</span> <span class="fu">sqrt</span>(sigsqr_hat <span class="sc">%*%</span> <span class="fu">t</span>(c) <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> c)      <span class="co"># Nenner der Einstichproben-T-Teststatistik</span></span>
<span id="cb2-20"><a href="#cb2-20"></a>t           <span class="ot">=</span> t_num<span class="sc">/</span>t_den                                                <span class="co"># Wert der Einstichproben-T-Teststatistik</span></span>
<span id="cb2-21"><a href="#cb2-21"></a>pval        <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fu">abs</span>(t), n<span class="dv">-1</span>))                                    <span class="co"># p-Wert bei zweiseitigem Einstichproben-T-Test</span></span>
<span id="cb2-22"><a href="#cb2-22"></a>k_alpha_0   <span class="ot">=</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha_0<span class="sc">/</span><span class="dv">2</span>, n<span class="dv">-1</span>)                                       <span class="co"># kritischer Wert </span></span>
<span id="cb2-23"><a href="#cb2-23"></a><span class="cf">if</span>(<span class="fu">abs</span>(t) <span class="sc">&gt;</span> k_alpha_0){phi <span class="ot">=</span> <span class="dv">1</span>} <span class="cf">else</span> {phi <span class="ot">=</span> <span class="dv">0</span>}                           <span class="co"># Einstichproben-T-Test</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Betaparameterschätzer            :  5.17 
95%-Konfidenzintervall          :  2.26 8.07 
Varianzparameterschätzer        :  20.88 
alpha_0                         :  0.05 
Kritischer Wert                 :  2.2 
Einstichproben-T-Teststatistik  :  3.92 
phi                             :  1 
p-Wert                          :  0</code></pre>
</div>
</div>
<p>Die Nullhypothese wird in diesem Fall bei einem einem kritischen Wert von <span class="math inline">\(k_{0.05}=2.20\)</span> und einem Wert der T-Statistik von <span class="math inline">\(T=3.91\)</span> abgelehnt. Das <span class="math inline">\(95/\%\)</span>-Konfidenzintervall für den wahren, aber unbekannten, Erwartungswertparameter ist <span class="math inline">\([2.26, 8.07]\)</span>, überdeckt also den Nullhypothesenparameterwert <span class="math inline">\(\mu_0=0\)</span> nicht.</p>
</section>
</section>
<section id="zweistichproben-t-tests" class="level2" data-number="31.3">
<h2 data-number="31.3" class="anchored" data-anchor-id="zweistichproben-t-tests"><span class="header-section-number">31.3</span> Zweistichproben-T-Tests</h2>
<section id="anwendungsszenario-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="anwendungsszenario-1">Anwendungsszenario</h3>
<p>Das Anwendungsszenario eines Zweistichproben-T-Tests für unabhängige Stichproben ist bekanntlich dadurch gekennzeichnet, dass insgesamt <span class="math inline">\(n\)</span> univariate Datenpunkte zweier Stichproben (Gruppen) randomisierter experimenteller Einheiten betrachtet werden. Es wird dabei insbesondere angenommen, dass die <span class="math inline">\(n_{1}\)</span> univariaten Datenpunkte der ersten Gruppe Realisierungen von <span class="math inline">\(n_{1}\)</span> unabhängigen und identisch normalverteilten Zufallsvariablen mit Erwartungswertparameter <span class="math inline">\(\mu_{1}\)</span> und Varianzparameter <span class="math inline">\(\sigma^{2}\)</span> sind, während weiterhin angenommen wird, dass die <span class="math inline">\(n_{2}\)</span> univariaten Datenpunkte der zweiten Gruppe Realisierungen von <span class="math inline">\(n_{2}\)</span> unabhängigen und identisch normalverteilten Zufallsvariablen mit Erwartungswertparameter <span class="math inline">\(\mu_{2}\)</span> und Varianzparameter <span class="math inline">\(\sigma^{2}\)</span> sind. Es wird also insbesondere angenommen, dass sich die wahren, aber unbekannten, Erwartungswertparameter beider Gruppen von Zufallsvariablen unterscheiden können, die Varianzparameter beider Gruppen dagegen werden als identisch angenommen. Schließlich wird voraussgesetzt, dass ein Interesse am inferentiellen Vergleich der unbekannten Erwartungswertparameter <span class="math inline">\(\mu_{1}\)</span> und <span class="math inline">\(\mu_{2}\)</span> besteht, so zum Beispiel ihrer Gleichheit <span class="math inline">\(\mu_{1}=\mu_{2}\)</span> oder Verschiedenheit <span class="math inline">\(\mu_{1} \neq \mu_{2}\)</span>.</p>
</section>
<section id="anwendungsbeispiel-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="anwendungsbeispiel-2">Anwendungsbeispiel</h3>
<p>Für ein konkretes Anwendungsbeispiel betrachten wird die Analyse von Pre-Post-Interventions-BDI-Differenzwerten zweier Gruppen von je 12 Patient:innen in unterschiedlichen Therapiesettings, wie in <a href="#tbl-ztt-daten" class="quarto-xref">Tabelle&nbsp;<span>31.3</span></a> dargestellt. Die erste Spalte der Tabelle (<code>COND</code>) listet das patientenspezifische Therapiesetting (F2F: face-to-face, ONL: online) auf. Die zweite Spalte der Tabelle (<code>dBDI</code>) listet die entsprechenden patientenspezifischen Pre-Post-Interventions-BDI-Differenzwerte auf. Positive Werte entsprechen hier erneut einer Abnahme der Depressionssymptomatik, negative Werte einer Zunahme der Depressionssymptomatik.</p>
<div class="cell">
<div id="tbl-ztt-daten" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ztt-daten-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;31.3: Pre-Post-BDI Differenzwerte für zwei Stichproben
</figcaption>
<div aria-describedby="tbl-ztt-daten-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">COND</th>
<th style="text-align: center;">dBDI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="even">
<td style="text-align: center;">F2F</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">ONL</td>
<td style="text-align: center;">-2</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Zu Anwendung eines Zweistichproben-T-Tests auf die dBDI Daten nehmen wir an, dass die 12 Datenpunkte der F2F Therapiegruppe Realisierungen von <span class="math inline">\(n_{1}=12\)</span> unabhängig und identisch normalverteilten Zufallsvariablen <span class="math inline">\(\upsilon_{1j} \sim N\left(\mu_{1}, \sigma^{2}\right)\)</span> mit <span class="math inline">\(j=1, \ldots, n_{1}\)</span> sind und dass die 12 Datenpunkte der ONL Therapiegruppe Realisierungen von <span class="math inline">\(n_{2}=12\)</span> unabhängig und identisch normalverteilten Zufallsvariablen <span class="math inline">\(\upsilon_{2j} \sim N\left(\mu_{2}, \sigma^{2}\right)\)</span> mit <span class="math inline">\(j=1, \ldots, n_{2}\)</span> sind.</p>
<p>Unabhängig von dem unten beschriebenen inferenzstatistischen Vorgehen betrachten wir auch hier zunächst die deskriptiven Statistiken der Therapiesetting-spezifischen dBDI Werte. Diese sind in <a href="#tbl-ztt-deskription" class="quarto-xref">Tabelle&nbsp;<span>31.4</span></a> aufgeführt.</p>
<div class="cell">
<div id="tbl-ztt-deskription" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ztt-deskription-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;31.4: Deskriptivstatistiken der Pre-Post BDI Differenzwerte bei unterschiedlichen Therapiesettings
</figcaption>
<div aria-describedby="tbl-ztt-deskription-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">n</th>
<th style="text-align: center;">Max</th>
<th style="text-align: center;">Min</th>
<th style="text-align: center;">Median</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">Var</th>
<th style="text-align: center;">Std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">F2F</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">5.0</td>
<td style="text-align: center;">5.17</td>
<td style="text-align: center;">20.88</td>
<td style="text-align: center;">4.57</td>
</tr>
<tr class="even">
<td style="text-align: left;">ONL</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">-2</td>
<td style="text-align: center;">6.5</td>
<td style="text-align: center;">5.75</td>
<td style="text-align: center;">16.20</td>
<td style="text-align: center;">4.03</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="modellformulierung-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="modellformulierung-1">Modellformulierung</h3>
<p>Mit dem Index <span class="math inline">\(i\)</span> für die Gruppen und dem Index <span class="math inline">\(j\)</span> für die experimentellen Einheiten in jeder Gruppe definieren wir das Zweistichproben-T-Test-Modell wie folgt.</p>
<div id="def-zweistichproben-t-test-modell" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 31.2 (Zweistichproben-T-Test-Modell)</strong></span> Für <span class="math inline">\(i=1,2\)</span> und <span class="math inline">\(j=1,\ldots,n_{i}\)</span> seien <span class="math inline">\(\upsilon_{ij}\)</span> Zufallsvariablen, die die <span class="math inline">\(n=n_{1}+n_{2}\)</span> Datenpunkte eines Zweistichproben-T-Test Szenarios modellieren. Dann hat das Zweistichproben-T-Test-Modell die strukturelle Form <span class="math display">\[\begin{equation}
\upsilon_{ij} = \mu_{i}+\varepsilon_{ij}
\mbox{ mit } \varepsilon_{ij} \sim N\left(0, \sigma^{2}\right)
\mbox{ u.i.v. mit } \mu_{i} \in \mathbb{R} \mbox{ und } \sigma^{2}&gt;0,
\end{equation}\]</span> die Datenverteilungsform <span class="math display">\[\begin{equation}
\upsilon_{ij} \sim N\left(\mu_{i}, \sigma^{2}\right)
\mbox{ u.i.v. mit } \mu_{i} \in \mathbb{R} \mbox{ und } \sigma^{2}&gt;0,
\end{equation}\]</span> und für den <span class="math inline">\(n\)</span>-dimensionalen Datenvektor definiert als <span class="math display">\[\begin{equation}
\upsilon := \left(\upsilon_{11}, \cdots, \upsilon_{1n_{1}},
                  \upsilon_{21}, \cdots, \upsilon_{2n_{2}}\right)^{T}
\end{equation}\]</span> die Designmatrixform <span class="math display">\[\begin{equation}
\upsilon = X\beta+\varepsilon
\end{equation}\]</span> mit <span class="math display">\[\begin{equation}
X:=
\begin{pmatrix}
1_{n_{1}} &amp; 0_{n_{1}} \\
0_{n_{2}} &amp; 1_{n_{2}}
\end{pmatrix} \in \mathbb{R}^{n \times 2},
\beta:=
\begin{pmatrix}
\mu_{1} \\
\mu_{2}
\end{pmatrix} \in \mathbb{R}^{2},
\varepsilon \sim N\left(0_{n}, \sigma^{2} I_{n}\right), \sigma^{2}&gt;0 .
\end{equation}\]</span></p>
</div>
<p>Die hier gewählte Definition des Zweistichproben-T-Test-Modells in Designmatrixform ist nicht die einzig mögliche, jedoch diejenige, unter der sich am klarsten die Äquivalenz zum Zweistichproben-T-Test-Modell im ALM-freien Kontext erkennen lässt. In <a href="408-Einfaktorielle-Varianzanalyse.html" class="quarto-xref"><span>Kapitel 32</span></a> lernen wir eine alternative Parameterisierung auch des Zweistichproben-T-Test-Modells kennen. Wie schon beim Szenario des Einstichproben-T-Tests ergibt sich die Äquivalenz der in <a href="#def-zweistichproben-t-test-modell" class="quarto-xref">Definition&nbsp;<span>31.2</span></a> formulierten Modellformen mit den Ergebnissen in <a href="403-Modellformulierung.html" class="quarto-xref"><span>Kapitel 27</span></a>. Die Simulation von Daten basierend auf dem Zweistichproben-T-Test-Modell ist, bis auf die Definition von Designmatrix und Betaparametervektor mit den bisher bekannten Simulationen von ALM Spezialfällen identisch, wie folgender <strong>R</strong> Code demonstriert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># Modellformulierung</span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="fu">library</span>(MASS)                                <span class="co"># Multivariate Normalverteilung</span></span>
<span id="cb4-3"><a href="#cb4-3"></a>n_1    <span class="ot">=</span> <span class="dv">12</span>                                  <span class="co"># Anzahl von Datenpunkten Gruppe 1</span></span>
<span id="cb4-4"><a href="#cb4-4"></a>n_2    <span class="ot">=</span> <span class="dv">12</span>                                  <span class="co"># Anzahl von Datenpunkten Gruppe 2</span></span>
<span id="cb4-5"><a href="#cb4-5"></a>n      <span class="ot">=</span> n_1 <span class="sc">+</span> n_2                           <span class="co"># Gesamtanzahl Datenpunkte</span></span>
<span id="cb4-6"><a href="#cb4-6"></a>p      <span class="ot">=</span> <span class="dv">2</span>                                   <span class="co"># Anzahl von Betaparameter</span></span>
<span id="cb4-7"><a href="#cb4-7"></a>X      <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n_1), <span class="fu">rep</span>(<span class="dv">0</span>,n_1),    <span class="co"># Designmatrix</span></span>
<span id="cb4-8"><a href="#cb4-8"></a>                  <span class="fu">rep</span>(<span class="dv">0</span>,n_2), <span class="fu">rep</span>(<span class="dv">1</span>,n_2)),</span>
<span id="cb4-9"><a href="#cb4-9"></a>                  <span class="at">nrow  =</span> n)</span>
<span id="cb4-10"><a href="#cb4-10"></a>I_n    <span class="ot">=</span> <span class="fu">diag</span>(n)                             <span class="co"># n x n Einheitsmatrix</span></span>
<span id="cb4-11"><a href="#cb4-11"></a>beta   <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">nrow =</span> p)            <span class="co"># wahrer, aber unbekannter, Betaparameter</span></span>
<span id="cb4-12"><a href="#cb4-12"></a>sigsqr <span class="ot">=</span> <span class="dv">10</span>                                  <span class="co"># wahrer, aber unbekannter, Varianzparameter</span></span>
<span id="cb4-13"><a href="#cb4-13"></a></span>
<span id="cb4-14"><a href="#cb4-14"></a><span class="co"># Datenrealisierung</span></span>
<span id="cb4-15"><a href="#cb4-15"></a>y      <span class="ot">=</span> <span class="fu">mvrnorm</span>(<span class="dv">1</span>, X <span class="sc">%*%</span> beta, sigsqr<span class="sc">*</span>I_n)  <span class="co"># eine Realisierung eines n-dimensionalen ZVs</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="modellschätzung-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="modellschätzung-1">Modellschätzung</h3>
<p>Die beiden Betaparameterkomponenten des Zweistichproben-T-Test-Modells in Designmatrixform werden wenig überraschend durch die entsprechenden Gruppenstichprobenmittel geschätzt. Für den Varianzparameterschätzer ergibt sich die sogenannte <em>gepoolte Stichprobenvarianz</em>. Dies sind die beiden Kernaussagen folgenden Theorems.</p>
<div id="thm-parameterschaetzung-im-zweistichproben-t-test-modell" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.3 (Parameterschätzung im Zweistichproben-T-Test-Modell)</strong></span> Gegeben sei die Designmatrixform des Zweistichproben-T-Test-Modells. Dann ergeben sich für den Betaparameterschätzer <span class="math display">\[\begin{equation}
\hat{\beta}
=\begin{pmatrix}
\frac{1}{n_{1}} \sum_{j=1}^{n_{1}} \upsilon_{1j} \\
\frac{1}{n_{2}} \sum_{j=1}^{n_{2}} \upsilon_{2j}
\end{pmatrix}=:\begin{pmatrix}
\bar{\upsilon}_{1} \\
\bar{\upsilon}_{2}
\end{pmatrix}
\end{equation}\]</span> und für den Varianzparameterschätzer <span class="math display">\[\begin{equation}
\hat{\sigma}^{2}
= \frac{\sum_{j=1}^{n_{1}}\left(\upsilon_{1j}-\bar{\upsilon}_{1}\right)^{2}+\sum_{j=1}^{n_{2}}\left(\upsilon_{2j}-\bar{\upsilon}_{2}\right)^{2}}{n_{1}+n_{2}-2}
=: s_{12}^{2}
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Beweis</em>. </span>Für <span class="math inline">\(i=1,2\)</span> sei <span class="math inline">\(\upsilon_i:=\left(\upsilon_{i1}, \ldots, \upsilon_{i n_{i}}\right)^{T}\)</span>. Dann ergibt sich für den Betaparameterschätzer <span class="math display">\[\begin{align}
\begin{split}
\hat{\beta}
&amp; = \left(X^{T} X\right)^{-1} X^{T} y \\
&amp; =
\left(\begin{pmatrix}
1_{n_{1}} &amp; 0_{n_{2}} \\
0_{n_{1}} &amp; 1_{n_{2}}
\end{pmatrix}
\begin{pmatrix}
1_{n_{1}} &amp; 0_{n_{1}} \\
0_{n_{2}} &amp; 1_{n_{2}}
\end{pmatrix}\right)^{-1}
\begin{pmatrix}
1_{n_{1}} &amp; 0_{n_{2}} \\
0_{n_{1}} &amp; 1_{n_{2}}
\end{pmatrix}
\begin{pmatrix}
\upsilon_{1} \\
\upsilon_{2}
\end{pmatrix} \\
&amp; =
\begin{pmatrix}
n_{1} &amp; 0 \\
0 &amp; n_{2}
\end{pmatrix}^{-1}
\begin{pmatrix}
\sum_{j=1}^{n_{1}} &amp; \upsilon_{1j} \\
\sum_{j=1}^{n_{2}} \upsilon_{2j}
\end{pmatrix} \\
&amp; =
\begin{pmatrix}
n_{1}^{-1} &amp; 0 \\
0 &amp; n_{2}^{-1}
\end{pmatrix}
\begin{pmatrix}
\sum_{j=1}^{n_{1}} &amp; \upsilon_{1j} \\
\sum_{j=1}^{n_{2}} &amp; \upsilon_{2j}
\end{pmatrix} \\
&amp; =
\begin{pmatrix}
\frac{1}{n_{1}} \sum_{j=1}^{n_{1}} \upsilon_{1j} \\
\frac{1}{n_{2}} \sum_{j=1}^{n_{2}} \upsilon_{2j}
\end{pmatrix} \\
&amp; =:
\begin{pmatrix}
\bar{\upsilon}_{1} \\
\bar{\upsilon}_{2}
\end{pmatrix}
\end{split}
\end{align}\]</span> Gleichsam ergibt sich für Varianzparameterschätzer mit <span class="math inline">\(n=n_{1}+n_{2}\)</span> und <span class="math inline">\(p=2\)</span> <span class="math display">\[\begin{align}
\begin{split}
\hat{\sigma}^{2}
&amp; =\frac{(\upsilon - X \hat{\beta})^{T}(\upsilon - X \hat{\beta})}{n-p} \\
&amp; =\frac{1}{n_{1}+n_{2}-2}
\left(
\begin{pmatrix}
\upsilon_{1} \\
\upsilon_{2}
\end{pmatrix}-
\begin{pmatrix}
1_{n_{1}} &amp; 0_{n_{1}} \\
0_{n_{2}} &amp; 1_{n_{2}}
\end{pmatrix}
\begin{pmatrix}
\bar{\upsilon}_{1} \\
\bar{\upsilon}_{2}
\end{pmatrix}\right)^{T}
\left(\begin{pmatrix}
\upsilon_{1} \\
\upsilon_{2}
\end{pmatrix}
-\begin{pmatrix}
1_{n_{1}} &amp; 0_{n_{1}} \\
0_{n_{2}} &amp; 1_{n_{2}}
\end{pmatrix}\begin{pmatrix}
\bar{\upsilon}_{1} \\
\bar{\upsilon}_{2}
\end{pmatrix}\right) \\
&amp; =
\frac{1}{n_{1}+n_{2}-2}
\begin{pmatrix}
\upsilon_{11}-\bar{\upsilon}_{1} \\
\vdots \\
\upsilon_{1 n_{1}}-\bar{\upsilon}_{1} \\
\upsilon_{21}-\bar{\upsilon}_{2} \\
\vdots \\
\upsilon_{2 n_{2}}-\bar{\upsilon}_{2}
\end{pmatrix}\begin{pmatrix}
\upsilon_{11}-\bar{\upsilon}_{1} \\
\vdots \\
\upsilon_{1 n_{1}}-\bar{\upsilon}_{1} \\
\upsilon_{21}-\bar{\upsilon}_{2} \\
\vdots \\
\upsilon_{2 n_{2}}-\bar{\upsilon}_{2}
\end{pmatrix} \\
&amp;
= \frac{\sum_{j=1}^{n_{1}}\left(\upsilon_{1j}-\bar{\upsilon}_{1}\right)^{2}+\sum_{j=1}^{n_{2}}\left(\upsilon_{2j}-\bar{\upsilon}_{2}\right)^{2}}{n_{1}+n_{2}-2} \\
= &amp; : s_{12}^{2} .
\end{split}
\end{align}\]</span></p>
</div>
<p>Man beachte, dass sich die Stichprobenvarianz <span class="math inline">\(s_{\upsilon}^{2}\)</span> der Komponenten von im Allgemeinen von der gepoolten Stichprobenvarianz <span class="math inline">\(s_{12}^{2}\)</span> unterscheidet. Dies ist nicht zuletzt dadurch bedingt, dass die Stichprobenvarianz basierend auf dem Gesamtstichprobenmittel <span class="math inline">\(\bar{\upsilon}\)</span>, die gepoolte Stichprobenvarianz dagegen basierend auf den gruppenspezifischen Stichprobenmittel <span class="math inline">\(\bar{\upsilon}_{1}\)</span> und <span class="math inline">\(\bar{\upsilon}_{2}\)</span> ermittelt wird. Wir wollen das Konzept der gepoolten Stichprobenvarianz hier aber nicht weiter vertiefen.</p>
</section>
<section id="modellevaluation-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="modellevaluation-1">Modellevaluation</h3>
<p>Basierend auf <a href="405-T-Statistiken.html#thm-frequentistische-verteilung-der-t-statistik" class="quarto-xref">Theorem&nbsp;<span>29.1</span></a> formulieren wir nun die T-Teststatistik für das in <a href="#def-zweistichproben-t-test-modell" class="quarto-xref">Definition&nbsp;<span>31.2</span></a> in Designmatrixform definierte Zweistichproben-T-Test-Modell und geben ihre frequentistische Verteilung an.</p>
<div id="thm-t-teststatistik-des-zweistichproben-t-tests" class="theorem">
<p><span class="theorem-title"><strong>Theorem 31.4 (T-Teststatistik des Zweistichproben-T-Tests)</strong></span> Gegeben sei die Designmatrixform des Zweistichproben-T-Tests. Dann ergibt sich für die T-Teststatistik mit <span class="math display">\[\begin{equation}
c:=(1,-1)^{T} \mbox{ und } c^{T} \beta_{0}=: \mu_{0},
\end{equation}\]</span> dass <span class="math display">\[\begin{equation}
T
=\sqrt{\frac{n_{1} n_{2}}{n_{1}+n_{2}}}
\left(\frac{\bar{\upsilon}_{1}-\bar{\upsilon}_{2}-\mu_{0}}{s_{12}}\right)
\end{equation}\]</span> und es gilt <span class="math display">\[\begin{equation}
T \sim t\left(\delta, n_{1}+n_{2}-2\right)
\mbox{ mit } \delta=\sqrt{\frac{n_{1} n_{2}}{n_{1}+n_{2}}}\left(\frac{\mu_{1}-\mu_{2}-\mu_{0}}{\sigma}\right) .
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Beweis</em>. </span>Mit <a href="405-T-Statistiken.html#thm-frequentistische-verteilung-der-t-statistik" class="quarto-xref">Theorem&nbsp;<span>29.1</span></a> gilt zunächst für die Zähler von <span class="math inline">\(T\)</span> und <span class="math inline">\(\delta\)</span>, dass <span class="math display">\[\begin{equation}
c^{T} \hat{\beta}-c^{T} \beta_{0}
=\begin{pmatrix}
1 &amp; -1
\end{pmatrix}
\begin{pmatrix}
\bar{\upsilon}_{1} \\
\bar{\upsilon}_{2}
\end{pmatrix}-\mu_{0}
=\bar{\upsilon}_{1}-\bar{\upsilon}_{2}-\mu_{0}
\end{equation}\]</span> und <span class="math display">\[\begin{equation}
c^{T} \beta-c^{T} \beta_{0}
=\begin{pmatrix}
1 &amp; -1
\end{pmatrix}
\begin{pmatrix}
\mu_{1} \\
\mu_{2}
\end{pmatrix}-\mu_{0}
=\mu_{1}-\mu_{2}-\mu_{0}
\end{equation}\]</span> respektive. Weiterhin gilt für die Nenner von <span class="math inline">\(T\)</span> und <span class="math inline">\(\delta\)</span>, dass <span class="math display">\[\begin{equation}
c^{T}\left(X^{T}X\right)^{-1}c
=
\begin{pmatrix}
1 &amp; -1
\end{pmatrix}
\begin{pmatrix}
n_{1}^{-1} &amp; 0 \\
0 &amp; n_{2}^{-1}
\end{pmatrix}
\begin{pmatrix}
1 \\
-1
\end{pmatrix}
=
\begin{pmatrix}
n_{1}^{-1} &amp; -n_{2}^{-1}
\end{pmatrix}
\begin{pmatrix}
1 \\
-1
\end{pmatrix}
=\frac{1}{n_{1}}+\frac{1}{n_{2}}
\end{equation}\]</span> Außerdem gilt <span class="math display">\[\begin{equation}
\left(\frac{1}{n_{1}}+\frac{1}{n_{2}}\right)^{-\frac{1}{2}}=\left(\frac{n_{2}}{n_{1} n_{2}}+\frac{n_{1}}{n_{1} n_{2}}\right)^{-\frac{1}{2}}=\left(\frac{n_{1}+n_{2}}{n_{1} n_{2}}\right)^{-\frac{1}{2}}=\left(\frac{n_{1} n_{2}}{n_{1}+n_{2}}\right)^{\frac{1}{2}}
\end{equation}\]</span> Zusammengenommen folgt direkt, dass <span class="math display">\[\begin{equation}
T
= \sqrt{\frac{n_{1} n_{2}}{n_{1}+n_{2}}}
\left(\frac{\bar{\upsilon}_{1}-\bar{\upsilon}_{2}-\mu_{0}}{s_{12}}\right)
\mbox{ und }
\delta=\sqrt{\frac{n_{1} n_{2}}{n_{1}+n_{2}}}\left(\frac{\mu_{1}-\mu_{2}-\mu_{0}}{\sigma}\right) .
\end{equation}\]</span></p>
</div>
<p>Die Formen der T-Teststatistik und ihre Verteilung im Zweistichproben-T-Test Modell in Designmatrixform sind also wiederum natürlicherweise mit den entsprechenden Formen im ALM-freien Kontext identisch. Die enstprechende zur Kontrolle des Testumfangs bei Zweistichproben-T-Tests sowie der Gebrauch der Testgütefunktion zur Evaluation der Testtrennschärfe (Power) folgt also analog.</p>
</section>
<section id="anwendungsbeispiel-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="anwendungsbeispiel-3">Anwendungsbeispiel</h3>
<p>Folgender <strong>R</strong> Code demonstriert die Evaluation von 95%-Konfidenzintervallen für die Erwartungswertparameter <span class="math inline">\(\mu_{1}\)</span> und <span class="math inline">\(\mu_{2}\)</span> sowie Durchführung eines zweiseitigen ZweistichprobenT-Tests mit Nullhypothese <span class="math display">\[\begin{equation}
\Theta_{0}
:=
\left\{
\begin{pmatrix}
\mu_{1} \\
\mu_{2}
\end{pmatrix} \in \mathbb{R}^{2} \mid
\mu_{1}=\mu_{2}
\right\}
\end{equation}\]</span> und Signifikanzlevel <span class="math inline">\(\alpha_{0}:=0.05\)</span> für das oben skizzierte Anwendungsbeispiel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Dateneinlesen</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>D           <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/407-t-tests.csv"</span>)               <span class="co"># Dataframe</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>y_1         <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>COND <span class="sc">==</span> <span class="st">"F2F"</span>]                           <span class="co"># BDI Differenzwerte in der F2F Gruppe</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>y_2         <span class="ot">=</span> D<span class="sc">$</span>dBDI[D<span class="sc">$</span>COND <span class="sc">==</span> <span class="st">"ONL"</span>]                           <span class="co"># BDI Differenzwerte in der ONL Gruppe</span></span>
<span id="cb5-5"><a href="#cb5-5"></a></span>
<span id="cb5-6"><a href="#cb5-6"></a><span class="co"># Modellformulierung</span></span>
<span id="cb5-7"><a href="#cb5-7"></a>n_1         <span class="ot">=</span> <span class="fu">length</span>(y_1)                                       <span class="co"># Anzahl Datenpunkte Gruppe 1 (F2F)</span></span>
<span id="cb5-8"><a href="#cb5-8"></a>n_2         <span class="ot">=</span> <span class="fu">length</span>(y_1)                                       <span class="co"># Anzahl Datenpunkte Gruppe 2 (ONL)</span></span>
<span id="cb5-9"><a href="#cb5-9"></a>n           <span class="ot">=</span> n_1 <span class="sc">+</span> n_2                                         <span class="co"># Gesamtanzahl Datenpunkte</span></span>
<span id="cb5-10"><a href="#cb5-10"></a>y           <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(y_1, y_2), <span class="at">nrow =</span> n)                     <span class="co"># Datenvektor</span></span>
<span id="cb5-11"><a href="#cb5-11"></a>p           <span class="ot">=</span> <span class="dv">2</span>                                                 <span class="co"># Anzahl Betaparameter</span></span>
<span id="cb5-12"><a href="#cb5-12"></a>X           <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n_1), <span class="fu">rep</span>(<span class="dv">0</span>,n_2),                  <span class="co"># Zweistichproben-T-Test Designmatrix</span></span>
<span id="cb5-13"><a href="#cb5-13"></a>                       <span class="fu">rep</span>(<span class="dv">0</span>,n_1), <span class="fu">rep</span>(<span class="dv">1</span>,n_2)),</span>
<span id="cb5-14"><a href="#cb5-14"></a>              <span class="at">nrow =</span> n)</span>
<span id="cb5-15"><a href="#cb5-15"></a></span>
<span id="cb5-16"><a href="#cb5-16"></a><span class="co"># Parameterschätzng</span></span>
<span id="cb5-17"><a href="#cb5-17"></a>beta_hat    <span class="ot">=</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y                  <span class="co"># Betaparameterschätzer</span></span>
<span id="cb5-18"><a href="#cb5-18"></a>eps_hat     <span class="ot">=</span> y <span class="sc">-</span> X <span class="sc">%*%</span> beta_hat                                <span class="co"># Residuenvektor</span></span>
<span id="cb5-19"><a href="#cb5-19"></a>sigsqr_hat  <span class="ot">=</span> (<span class="fu">t</span>(eps_hat) <span class="sc">%*%</span> eps_hat) <span class="sc">/</span>(n<span class="sc">-</span>p)                   <span class="co"># Varianzparameterschätzer</span></span>
<span id="cb5-20"><a href="#cb5-20"></a></span>
<span id="cb5-21"><a href="#cb5-21"></a><span class="co"># Konfidenzintervall</span></span>
<span id="cb5-22"><a href="#cb5-22"></a>delta       <span class="ot">=</span> <span class="fl">0.95</span>                                              <span class="co"># Konfidenzbedingung</span></span>
<span id="cb5-23"><a href="#cb5-23"></a>t_delta     <span class="ot">=</span> <span class="fu">qt</span>((<span class="dv">1</span><span class="sc">+</span>delta)<span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>)                               <span class="co"># \Psi^{-1}((1+\delta)/2,n-1)</span></span>
<span id="cb5-24"><a href="#cb5-24"></a>lambda      <span class="ot">=</span> <span class="fu">diag</span>(<span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X))                           <span class="co"># \lambda_j Werte</span></span>
<span id="cb5-25"><a href="#cb5-25"></a>kappa       <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NaN</span>,p<span class="sc">*</span><span class="dv">2</span>), <span class="at">nrow =</span> p)                    <span class="co"># \beta_j Konfidenintervall array</span></span>
<span id="cb5-26"><a href="#cb5-26"></a><span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>p){                                                  <span class="co"># Iteration über \beta_j</span></span>
<span id="cb5-27"><a href="#cb5-27"></a>  kappa[j,<span class="dv">1</span>] <span class="ot">=</span> beta_hat[j]<span class="sc">-</span><span class="fu">sqrt</span>(sigsqr_hat<span class="sc">*</span>lambda[j])<span class="sc">*</span>t_delta   <span class="co"># untere KI Grenze</span></span>
<span id="cb5-28"><a href="#cb5-28"></a>  kappa[j,<span class="dv">2</span>] <span class="ot">=</span> beta_hat[j]<span class="sc">+</span><span class="fu">sqrt</span>(sigsqr_hat<span class="sc">*</span>lambda[j])<span class="sc">*</span>t_delta}  <span class="co"># obere KI Grenze</span></span>
<span id="cb5-29"><a href="#cb5-29"></a></span>
<span id="cb5-30"><a href="#cb5-30"></a><span class="co"># Hypothesentest</span></span>
<span id="cb5-31"><a href="#cb5-31"></a>c           <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>), <span class="at">nrow =</span> <span class="dv">2</span>)                         <span class="co"># Kontrastgewichtsvektor</span></span>
<span id="cb5-32"><a href="#cb5-32"></a>mu_0        <span class="ot">=</span> <span class="dv">0</span>                                                 <span class="co"># Nullhypothese H_0</span></span>
<span id="cb5-33"><a href="#cb5-33"></a>alpha_0     <span class="ot">=</span> <span class="fl">0.05</span>                                              <span class="co"># Signifikanzniveau</span></span>
<span id="cb5-34"><a href="#cb5-34"></a>k_alpha_0   <span class="ot">=</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> (alpha_0<span class="sc">/</span><span class="dv">2</span>), n<span class="dv">-1</span>)                          <span class="co"># kritischer Wert</span></span>
<span id="cb5-35"><a href="#cb5-35"></a>t_num       <span class="ot">=</span> <span class="fu">t</span>(c) <span class="sc">%*%</span> beta_hat <span class="sc">-</span> mu_0                          <span class="co"># T-Teststatistik Zähler</span></span>
<span id="cb5-36"><a href="#cb5-36"></a>t_den       <span class="ot">=</span> <span class="fu">sqrt</span>(sigsqr_hat<span class="sc">*</span><span class="fu">t</span>(c) <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X)<span class="sc">%*%</span>c)   <span class="co"># T-Teststatistik Nenner</span></span>
<span id="cb5-37"><a href="#cb5-37"></a>t           <span class="ot">=</span> t_num<span class="sc">/</span>t_den                                       <span class="co"># T-Teststatistik</span></span>
<span id="cb5-38"><a href="#cb5-38"></a><span class="cf">if</span>(<span class="fu">abs</span>(t) <span class="sc">&gt;=</span> k_alpha_0){phi <span class="ot">=</span> <span class="dv">1</span>} <span class="cf">else</span> {phi <span class="ot">=</span> <span class="dv">0</span>}                 <span class="co"># Test 1_{|T(X) &gt;= k_alpha_0|}</span></span>
<span id="cb5-39"><a href="#cb5-39"></a>pval      <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(<span class="fu">abs</span>(t), n_1<span class="sc">+</span>n_2<span class="dv">-2</span>))                         <span class="co"># p-Wert</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Betaparameterschätzer            :  5.17 5.75 
95%-Konfidenzintervalle         :  2.6 3.18 7.74 8.32 
Varianzparameterschätzer        :  18.54 
alpha_0                         :  0.05 
Kritischer Wert                 :  2.07 
Einstichproben-T-Teststatistik  :  -0.33 
phi                             :  0 
p-Wert                          :  0.74</code></pre>
</div>
</div>
<p>Die Nullhypothese würde in diesem Fall bei einem kritischen Wert von <span class="math inline">\(k_{0.05}=2.07\)</span> und einem Wert der T-Statistik von <span class="math inline">\(T=-033\)</span> nicht verworfen werden. Inferenzstatisch besteht also keine Evidenz dafür, dass sich der wahre, aber unbekannte Erwartungswertparameter im F2F Therapiesetting vom wahren, aber unbekannte Erwartungswertparameter im ONL Therapiesetting unterscheidet. Die 95/%Konfidenzintervalle für die wahren, aber unbekannten, Erwartungswertparameter <span class="math inline">\(\mu_{1}\)</span> und <span class="math inline">\(\mu_{2}\)</span> sind <span class="math inline">\([2.60,7.74]\)</span> und <span class="math inline">\([3.18,8.32]\)</span>, respektive.</p>
</section>
</section>
<section id="literaturhinweise" class="level2" data-number="31.4">
<h2 data-number="31.4" class="anchored" data-anchor-id="literaturhinweise"><span class="header-section-number">31.4</span> Literaturhinweise</h2>
<p>Obwohl die frequentistische Literatur der ersten Hälfte des 20. Jahrhunderts von der Äquivalenz regressions- und varianzanalytischer linearer Modelle durchdrungen ist, fällt es schwer eine definite Quelle anzugeben, die hinsichtlich der Beschreibung von T-Tests als Spezialfälle des ALM Priorität hätte. Es sei hier deshalb eher allgemein auf <span class="citation" data-cites="fisher1925">Fisher (<a href="#ref-fisher1925" role="doc-biblioref">1925</a>)</span> und <span class="citation" data-cites="fisher1935">Fisher (<a href="#ref-fisher1935" role="doc-biblioref">1935</a>)</span> verwiesen.</p>
</section>
<section id="selbstkontrollfragen" class="level2" data-number="31.5">
<h2 data-number="31.5" class="anchored" data-anchor-id="selbstkontrollfragen"><span class="header-section-number">31.5</span> Selbstkontrollfragen</h2>
<ol type="1">
<li>Geben Sie die Definition des Einstichproben-T-Test-Modells wieder.</li>
<li>Geben Sie das Theorem zur Parameterschätzung im Einstichproben-T-Test-Modell wieder.</li>
<li>Geben Sie das Theorem zur T-Teststatistik des Einstichproben-T-Tests wieder.</li>
<li>Geben Sie die Definition des Zweistichproben-T-Test-Modells wieder.</li>
<li>Geben Sie das Theorem zur Parameterschätzung im Zweistichproben-T-Test-Modell wieder.</li>
<li>Geben Sie das Theorem zur T-Teststatistik des Zweistichproben-T-Tests wieder.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-fisher1925" class="csl-entry" role="listitem">
Fisher, R. A. (1925). Theory of <span>Statistical Estimation</span>. <em>Mathematical Proceedings of the Cambridge Philosophical Society</em>, <em>22</em>(5), 700–725. <a href="https://doi.org/10.1017/S0305004100009580">https://doi.org/10.1017/S0305004100009580</a>
</div>
<div id="ref-fisher1935" class="csl-entry" role="listitem">
Fisher, R. A. (1935). <em>The Design of Experiments</em> (1. ed). <span>Hafner Press</span>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./406-F-Statistiken.html" class="pagination-link  aria-label=" &lt;span="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">F-Statistiken</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./408-Einfaktorielle-Varianzanalyse.html" class="pagination-link" aria-label="<span class='chapter-number'>32</span>&nbsp; <span class='chapter-title'>Einfaktorielle Varianzanalyse</span>">
        <span class="nav-page-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Einfaktorielle Varianzanalyse</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages/edit/main/407-T-Tests.qmd" class="toc-action"><i class="bi bi-github"></i>Seite editieren</a></li></ul></div></div></div></footer></body></html>