<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>32&nbsp; Confidence intervals – Probabilistic Data Science for Psychology</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../_part_4/404-Hypothesis-Tests.html" rel="next">
<link href="../_part_4/402-Point-Estimation.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d6825770f4e37b80aa8621686b79c10e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Probabilistic Data Science for Psychology</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dirk-ostwald.github.io/"> 
<span class="menu-text">Deutsch</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Probabilistic-Data-Science-for-Psychology.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_part_4/400-Inference.html">Inference</a></li><li class="breadcrumb-item"><a href="../_part_4/403-Confidence-Intervals.html"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Confidence intervals</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_1/100-Mathematical-Foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mathematical foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/101-Language-and-Logic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Language and logic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/102-Sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Sets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/103-Sums-Products-Powers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sums, products, powers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/104-Functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/105-Sequences-Limits-Continuity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sequences, limits, continuity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/106-Differential-Calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Differential calculus</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/107-Integral-Calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Integral calculus</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/108-Vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/109-Matrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Matrices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_1/110-Descriptive-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_2/200-Imperative-Programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Imperative programming</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/201-Basic-Concepts-of-Computer-Science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Basic concepts of computer science</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/202-Arithmetic-and-Variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Arithmetic and variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/203-Data-Structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Data structures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/204-Vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/205-Matrices-and-Arrays.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Matrices and arrays</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/206-Lists-Dataframes-and-Tibbles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Lists, dataframes, and tibbles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/207-Data-Management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Data management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_2/208-Control-Structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Control structures</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_3/300-Probability-Theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/301-Probability-Spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Probability spaces</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/302-Elementary-Probabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Elementary probabilities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/303-Random-Variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Random variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/304-Random-Vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Random vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/305-Expectations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Expectations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/306-Variances.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Variances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/307-Covariances.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Covariances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/308-Inequalities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inequalities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/309-Limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Limits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/310-Transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Transformations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_3/311-Normal-Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Normal distributions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_4/400-Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/401-Frequentist-Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Frequentist inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/402-Point-Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Point estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/403-Confidence-Intervals.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_4/404-Hypothesis-Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Hypothesis tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_5/500-General-Linear-Model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General linear model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/501-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/502-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/503-Model-Formulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Model formulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/504-Parameter-Estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Parameter estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/505-T-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">T-statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/506-F-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">F-statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/507-T-Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">T-tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/508-One-Way-Analysis-of-Variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">One-way analysis of variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/509-Two-Way-Analysis-of-Variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Two-way analysis of variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/510-Partial-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Partial correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_5/511-Multiple-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../_part_7/700-Multivariate-Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multivariate inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_7/701-Multivariate-Descriptive-Statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Multivariate descriptive statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_7/702-One-Sample-T2-Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">One-sample T<span class="math inline">\(^2\)</span> tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_7/703-One-Way-Analysis-of-Variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">One-way analysis of variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_part_7/704-Canonical-Correlation-Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Canonical correlation analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../References.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-confidence-intervals-definition" id="toc-sec-confidence-intervals-definition" class="nav-link active" data-scroll-target="#sec-confidence-intervals-definition"><span class="header-section-number">32.1</span> Definition</a></li>
  <li><a href="#sec-examples-of-confidence-intervals" id="toc-sec-examples-of-confidence-intervals" class="nav-link" data-scroll-target="#sec-examples-of-confidence-intervals"><span class="header-section-number">32.2</span> Examples of confidence intervals</a>
  <ul class="collapse">
  <li><a href="#confidence-interval-for-the-expectation-parameter-of-the-normal-distribution-model" id="toc-confidence-interval-for-the-expectation-parameter-of-the-normal-distribution-model" class="nav-link" data-scroll-target="#confidence-interval-for-the-expectation-parameter-of-the-normal-distribution-model">Confidence interval for the expectation parameter of the normal distribution model</a></li>
  <li><a href="#confidence-interval-for-the-variance-parameter-of-the-normal-distribution-model" id="toc-confidence-interval-for-the-variance-parameter-of-the-normal-distribution-model" class="nav-link" data-scroll-target="#confidence-interval-for-the-variance-parameter-of-the-normal-distribution-model">Confidence interval for the variance parameter of the normal distribution model</a></li>
  </ul></li>
  <li><a href="#bibliographic-remarks" id="toc-bibliographic-remarks" class="nav-link" data-scroll-target="#bibliographic-remarks"><span class="header-section-number">32.3</span> Bibliographic remarks</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages/edit/main/_part_4/403-Confidence-Intervals.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_part_4/400-Inference.html">Inference</a></li><li class="breadcrumb-item"><a href="../_part_4/403-Confidence-Intervals.html"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Confidence intervals</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-confidence-intervals" class="quarto-section-identifier"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Confidence intervals are interval estimates of true, but unknown, parameters that are constructed so that they are correct in most cases. The gain in certainty about the accuracy of the estimate, compared with point estimation, comes at the cost of a loss in precision. In point estimation, the estimate of a true, but unknown, parameter value, such as <span class="math inline">\(\theta = 2\)</span>, is very precise, for example <span class="math inline">\(\hat{\theta} = 2.14\)</span>. However, against the background of the vanishing probability that a continuous random variable takes exactly <em>one</em> real value, this estimate is almost certainly wrong. Estimating a true, but unknown, parameter by an interval, such as <span class="math inline">\([1.94, 2.34]\)</span>, is coarser. Such an estimate, however, can be constructed so that it is correct with a large desired probability. To express this intuition formally, we first focus in this chapter on one-dimensional parameter spaces. Thus, we consider <span class="math inline">\(\Theta \subseteq \mathbb{R}\)</span> and hence indeed only confidence <em>intervals</em>, that is, subsets of <span class="math inline">\(\mathbb{R}\)</span>. A generalization of the concepts introduced here to higher-dimensional parameter spaces in the sense of confidence <em>sets</em> is, however, possible without major difficulty.</p>
<section id="sec-confidence-intervals-definition" class="level2" data-number="32.1">
<h2 data-number="32.1" class="anchored" data-anchor-id="sec-confidence-intervals-definition"><span class="header-section-number">32.1</span> Definition</h2>
<div id="def-delta-confidence-interval" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 32.1 (<span class="math inline">\(\delta\)</span> confidence interval)</strong></span> Let <span class="math inline">\(y\)</span> be the sample of a frequentist inference model with true, but unknown, parameter <span class="math inline">\(\theta \in \Theta\)</span>, let <span class="math inline">\(\delta \in \,]0,1[\)</span>, and let <span class="math inline">\(G_u(y)\)</span> and <span class="math inline">\(G_o(y)\)</span> be given. Then an interval of the form <span class="math display">\[\begin{equation}
\kappa(y) := [G_u(y), G_o(y)],
\end{equation}\]</span> such that <span class="math display">\[\begin{equation}
\mathbb{P}_\theta\left(\kappa(y) \ni \theta\right) =
\mathbb{P}_\theta\left(G_u(y) \le \theta \le G_o(y) \right) =
\delta \mbox{ for all } \theta \in \Theta
\end{equation}\]</span> holds is called a <em><span class="math inline">\(\delta\)</span> confidence interval for <span class="math inline">\(\theta\)</span></em>. <span class="math inline">\(\delta\)</span> is the coverage probability of <span class="math inline">\(\kappa(y)\)</span> for <span class="math inline">\(\theta\)</span> and is usually called the <em>confidence level</em>. The statistics <span class="math inline">\(G_u(y)\)</span> and <span class="math inline">\(G_o(y)\)</span> are called the <em>lower</em> and the <em>upper bound</em> of the confidence interval, respectively.</p>
</div>
<p>Note that, as in all frequentist inference models, the parameter <span class="math inline">\(\theta\)</span> is a true, but unknown, value here and therefore, in particular, fixed and not random. Because the upper and lower bounds of a confidence interval are random variables as functions of the random sample, however, the confidence interval defined by them is a random interval. The somewhat unusual notation <span class="math inline">\(\kappa(y) \ni \theta\)</span> simply means <span class="math inline">\(\theta \in \kappa(y)\)</span>. Since <span class="math inline">\(\kappa(y)\)</span> is the random entity in the expression <span class="math inline">\(\mathbb{P}_\theta\left(\kappa(y) \ni \theta\right)\)</span>, as just described, <span class="math inline">\(\kappa(y)\)</span> is conventionally written on the left. In this respect, think for example of an expression such as <span class="math inline">\(\mathbb{P}(\xi = x)\)</span>. According to <a href="#def-delta-confidence-interval" class="quarto-xref">Definition&nbsp;<span>32.1</span></a>, a <span class="math inline">\(\delta\)</span> confidence interval covers the true, but unknown, parameter <span class="math inline">\(\theta\)</span> with probability <span class="math inline">\(\delta\)</span>. A high coverage probability of <span class="math inline">\(\delta := 0.95\)</span> is often chosen. In this case, one speaks of a <em><span class="math inline">\(95\%\)</span> confidence interval</em>.</p>
<p>Intuitively, one may interpret <span class="math inline">\(\delta\)</span> confidence intervals in two ways. In the first case, one assumes repeated independent realizations of samples with an identical true, but unknown, parameter <span class="math inline">\(\theta\)</span>. Thus, if one repeatedly realizes data “under the same circumstances”, a <span class="math inline">\(\delta\)</span> confidence interval covers this true, but unknown, parameter in <span class="math inline">\(\delta \cdot 100 \%\)</span> of the realized cases in the long run. Alternatively, however, according to <a href="#def-delta-confidence-interval" class="quarto-xref">Definition&nbsp;<span>32.1</span></a>, this frequentist probability of covering the true, but unknown, parameter also holds for any arbitrary true, but unknown, parameter value <span class="math inline">\(\theta_i, i = 1,2,...\)</span>. Thus, even if one considers different true, but unknown, parameter values <span class="math inline">\(\theta_1,\theta_2,...\)</span> and, in each case, records a sample realization that is independent of the other realizations, the corresponding <span class="math inline">\(\delta\)</span> confidence intervals cover these true, but unknown, parameters in <span class="math inline">\(\delta \cdot 100 \%\)</span> of the cases in the long run. Intuitively, one therefore does not need to repeat “one study”, that is, the investigation of one true, but unknown, parameter value, “infinitely often” under the same circumstances in order to benefit from the coverage probability of a confidence interval. Rather, it is sufficient to determine confidence intervals according to <a href="#def-delta-confidence-interval" class="quarto-xref">Definition&nbsp;<span>32.1</span></a> in “different studies”, that is, investigations of different true, but unknown, parameters. In this case, too, their coverage probability for the true, but unknown, parameters is guaranteed.</p>
<p>To construct <span class="math inline">\(\delta\)</span> confidence intervals for given frequentist inference models by explicitly specifying the statistics <span class="math inline">\(G_u(y)\)</span> and <span class="math inline">\(G_o(y)\)</span>, one proceeds as follows. First, one defines the inference model and thereby fixes the distribution of the sample <span class="math inline">\(y\)</span>. In a second step, one defines a statistic, that is, a function of the sample, that serves as the basis for <span class="math inline">\(G_u(y)\)</span> and <span class="math inline">\(G_o(y)\)</span>, and analyzes its distribution, which is based on the sampling distribution. Once the corresponding distribution has been found, it can be used to guarantee the coverage probability of the true, but unknown, parameter by an appropriately defined confidence interval. We trace this procedure in the development and constructive proofs of the following examples.</p>
</section>
<section id="sec-examples-of-confidence-intervals" class="level2" data-number="32.2">
<h2 data-number="32.2" class="anchored" data-anchor-id="sec-examples-of-confidence-intervals"><span class="header-section-number">32.2</span> Examples of confidence intervals</h2>
<section id="confidence-interval-for-the-expectation-parameter-of-the-normal-distribution-model" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="confidence-interval-for-the-expectation-parameter-of-the-normal-distribution-model">Confidence interval for the expectation parameter of the normal distribution model</h3>
<p>We consider the construction of a <span class="math inline">\(\delta\)</span> confidence interval for the expectation parameter of the normal distribution model. To this end, we first define the following confidence-interval statistic.</p>
<div id="def-t-confidence-interval-statistic" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 32.2 (<span class="math inline">\(T\)</span> confidence-interval statistic)</strong></span> Given the normal distribution model <span class="math display">\[\begin{equation}
y_1,...,y_n \sim N\left(\mu,\sigma^2\right)
\end{equation}\]</span> the statistic defined by the sample mean and the sample standard deviation <span class="math display">\[\begin{equation}
\bar{y} := \frac{1}{n}\sum_{i=1}^n y_i \mbox{ and } S := \sqrt{\frac{1}{n-1}\sum_{i=1}^n(y_i - \bar{y})^2},
\end{equation}\]</span> namely <span class="math display">\[\begin{equation}
T := \sqrt{n}\frac{\bar{y} - \mu}{S}
\end{equation}\]</span> is called the <em><span class="math inline">\(T\)</span> confidence-interval statistic</em>.</p>
</div>
<p>For the distribution of the <span class="math inline">\(T\)</span> confidence-interval statistic, the following theorem holds.</p>
<div id="thm-distribution-of-t-confidence-interval-statistic" class="theorem">
<p><span class="theorem-title"><strong>Theorem 32.1 (Distribution of the <span class="math inline">\(T\)</span> confidence-interval statistic)</strong></span> The <span class="math inline">\(T\)</span> confidence-interval statistic is a <span class="math inline">\(t\)</span>-distributed random variable with parameter <span class="math inline">\(n-1\)</span>; that is, <span class="math display">\[\begin{equation}
T \sim t(n-1)
\end{equation}\]</span></p>
</div>
<p>Note that, according to <a href="#def-t-confidence-interval-statistic" class="quarto-xref">Definition&nbsp;<span>32.2</span></a>, the <span class="math inline">\(T\)</span> confidence-interval statistic is a function of the sample, whereas its distribution according to <a href="#thm-distribution-of-t-confidence-interval-statistic" class="quarto-xref">Theorem&nbsp;<span>32.1</span></a> is independent of the true, but unknown, parameters of the sampling distribution. This is also called the <em>pivot property</em> of the <span class="math inline">\(T\)</span> confidence-interval statistic. For the following developments, recall that we denote the PDF of a <span class="math inline">\(t\)</span>-distributed random variable by <span class="math inline">\(t\)</span>, the CDF of a <span class="math inline">\(t\)</span>-distributed random variable by <span class="math inline">\(\Psi\)</span>, and the inverse CDF of a <span class="math inline">\(t\)</span>-distributed random variable by <span class="math inline">\(\Psi^{-1}\)</span>. The following <strong>R</strong> code first simulates the distribution of the <span class="math inline">\(T\)</span> confidence-interval statistic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># model specification</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>mu       <span class="ot">=</span> <span class="dv">10</span>                                         <span class="co"># true, but unknown, expectation parameter</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>sigsqr   <span class="ot">=</span> <span class="dv">4</span>                                          <span class="co"># true, but unknown, variance parameter</span></span>
<span id="cb1-4"><a href="#cb1-4"></a>n        <span class="ot">=</span> <span class="dv">12</span>                                         <span class="co"># sample size</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>ns       <span class="ot">=</span> <span class="fl">1e4</span>                                        <span class="co"># number of sample realizations</span></span>
<span id="cb1-6"><a href="#cb1-6"></a>res      <span class="ot">=</span> <span class="fl">1e3</span>                                        <span class="co"># outcome-space resolution</span></span>
<span id="cb1-7"><a href="#cb1-7"></a></span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="co"># analytic definitions and results</span></span>
<span id="cb1-9"><a href="#cb1-9"></a>yx       <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">3</span>,<span class="dv">17</span>,<span class="at">len =</span> res)                        <span class="co"># y_i space</span></span>
<span id="cb1-10"><a href="#cb1-10"></a>ssqrx    <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">20</span>,<span class="at">len =</span> res)                        <span class="co"># S^2 space</span></span>
<span id="cb1-11"><a href="#cb1-11"></a>tx       <span class="ot">=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>,<span class="dv">4</span>,<span class="at">len =</span> res)                        <span class="co"># T space</span></span>
<span id="cb1-12"><a href="#cb1-12"></a>p_y_i    <span class="ot">=</span> <span class="fu">dnorm</span>(yx,mu,<span class="fu">sqrt</span>(sigsqr))                  <span class="co"># y_i PDF</span></span>
<span id="cb1-13"><a href="#cb1-13"></a>p_y_bar  <span class="ot">=</span> <span class="fu">dnorm</span>(yx,mu,<span class="fu">sqrt</span>(sigsqr<span class="sc">/</span>n))                <span class="co"># y_bar PDF</span></span>
<span id="cb1-14"><a href="#cb1-14"></a>p_sqr    <span class="ot">=</span> <span class="fu">dchisq</span>(ssqrx,n<span class="dv">-1</span>)                          <span class="co"># S^2 PDF</span></span>
<span id="cb1-15"><a href="#cb1-15"></a>p_t      <span class="ot">=</span> <span class="fu">dt</span>(tx,n<span class="dv">-1</span>)                                 <span class="co"># T PDF</span></span>
<span id="cb1-16"><a href="#cb1-16"></a></span>
<span id="cb1-17"><a href="#cb1-17"></a><span class="co"># simulation</span></span>
<span id="cb1-18"><a href="#cb1-18"></a>y_i      <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                                <span class="co"># y_i array</span></span>
<span id="cb1-19"><a href="#cb1-19"></a>y_bar    <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                                <span class="co"># \bar{y} array</span></span>
<span id="cb1-20"><a href="#cb1-20"></a>S        <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                                <span class="co"># S array</span></span>
<span id="cb1-21"><a href="#cb1-21"></a>TKS      <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                                <span class="co"># T confidence-interval statistic array</span></span>
<span id="cb1-22"><a href="#cb1-22"></a><span class="cf">for</span>(s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ns){                                       <span class="co"># simulation iterations</span></span>
<span id="cb1-23"><a href="#cb1-23"></a>  y         <span class="ot">=</span> <span class="fu">rnorm</span>(n,mu,<span class="fu">sqrt</span>(sigsqr))                <span class="co"># sample realization</span></span>
<span id="cb1-24"><a href="#cb1-24"></a>  y_i[s]    <span class="ot">=</span> y[<span class="dv">1</span>]                                    <span class="co"># sample realization y_i with i = 1</span></span>
<span id="cb1-25"><a href="#cb1-25"></a>  y_bar[s]  <span class="ot">=</span> <span class="fu">mean</span>(y)                                 <span class="co"># sample mean realization</span></span>
<span id="cb1-26"><a href="#cb1-26"></a>  S[s]      <span class="ot">=</span> <span class="fu">sd</span>(y)                                   <span class="co"># sample standard-deviation realization</span></span>
<span id="cb1-27"><a href="#cb1-27"></a>  TKS[s]    <span class="ot">=</span> <span class="fu">sqrt</span>(n)<span class="sc">*</span>((y_bar[s]<span class="sc">-</span>mu)<span class="sc">/</span>S[s])            <span class="co"># T confidence-interval statistic realization</span></span>
<span id="cb1-28"><a href="#cb1-28"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="fig-t-confidence-interval-statistic" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-confidence-interval-statistic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/403-t-confidence-interval-statistic.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-confidence-interval-statistic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.1: Simulation of the distribution of the <span class="math inline">\(T\)</span> confidence-interval statistic and the underlying distributions of the sample variable, the sample mean, and the sample variance.
</figcaption>
</figure>
</div>
<p>In <a href="#fig-t-confidence-interval-statistic" class="quarto-xref">Figure&nbsp;<span>32.1</span></a>, we visualize the distribution of the <span class="math inline">\(T\)</span> confidence-interval statistic as a result of its underlying distributions of the sample variables, the sample mean, and the sample variance (cf. <a href="../_part_3/311-Normal-Distributions.html#thm-t-transformation" class="quarto-xref">Theorem&nbsp;<span>29.13</span></a>). Using the distribution of the <span class="math inline">\(T\)</span> confidence-interval statistic, we can now prove the following theorem on the confidence interval for the expectation parameter of the normal distribution model.</p>
<div id="thm-confidence-interval-for-expectation-parameter-of-normal-distribution-model" class="theorem">
<p><span class="theorem-title"><strong>Theorem 32.2 (Confidence interval for the expectation parameter of the normal distribution model)</strong></span> Given the normal distribution model <span class="math display">\[\begin{equation}
y_1,...,y_n \sim N(\mu,\sigma^2)
\end{equation}\]</span> with true, but unknown, parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span>, let <span class="math inline">\(\delta \in ]0,1[\)</span> and let <span class="math display">\[\begin{equation}
t_\delta := \Psi^{-1}\left(\frac{1+\delta}{2}; n-1\right).
\end{equation}\]</span> where <span class="math inline">\(\Psi^{-1}\)</span> is the inverse CDF of a <span class="math inline">\(t\)</span>-distributed random variable. Then, for the interval <span class="math display">\[\begin{equation}
\kappa(y) :=
\left[\bar{y} - \frac{S}{\sqrt{n}}t_\delta,
\bar{y} + \frac{S}{\sqrt{n}}t_\delta\right],
\end{equation}\]</span> with the sample mean and the sample standard deviation <span class="math display">\[\begin{equation}
\bar{y} := \frac{1}{n}\sum_{i=1}^n y_i \mbox{ and } S := \sqrt{\frac{1}{n-1}\sum_{i=1}^n(y_i - \bar{y})^2},
\end{equation}\]</span> respectively, it holds that <span class="math display">\[\begin{equation}
\mathbb{P}_{\mu}(\kappa(y) \ni \mu) = \delta.
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>For <span class="math inline">\(\delta \in ]0,1[\)</span>, first define <span class="math display">\[\begin{equation}
t_1 := \Psi^{-1}\left(\frac{1 - \delta}{2}; n - 1\right)
\mbox{ and }
t_2 := \Psi^{-1}\left(\frac{1 + \delta}{2}; n-1\right)
\end{equation}\]</span> Then <span class="math display">\[\begin{equation}
\frac{1+\delta}{2} - \frac{1-\delta}{2} = \delta
\end{equation}\]</span> and, by the symmetry of the PDF of the <span class="math inline">\(t\)</span> distribution, also <span class="math display">\[\begin{equation}
t_1 = - t_2.
\end{equation}\]</span> By definition, using <a href="#def-t-confidence-interval-statistic" class="quarto-xref">Definition&nbsp;<span>32.2</span></a> and <a href="#thm-distribution-of-t-confidence-interval-statistic" class="quarto-xref">Theorem&nbsp;<span>32.1</span></a>, it follows that <span class="math display">\[\begin{equation}
\mathbb{P}_\mu\left(-t_{\delta} \le T \le t_{\delta} \right) = \delta.
\end{equation}\]</span> Consequently, we obtain directly <span class="math display">\[\begin{align}
\begin{split}
\delta
&amp; =
\mathbb{P}_\mu\left(-t_\delta \le T \le t_\delta \right)                                                                            \\
&amp; =
\mathbb{P}_\mu\left(-t_\delta \le \frac{\sqrt{n}}{S}(\bar{y} - \mu) \le t_\delta \right)                                        \\
&amp; =
\mathbb{P}_\mu\left(-\frac{S}{\sqrt{n}}t_\delta \le \bar{y} - \mu \le \frac{S}{\sqrt{n}}t_\delta \right)                    \\
&amp; =
\mathbb{P}_\mu\left(-\bar{y} -\frac{S}{\sqrt{n}}t_\delta \le - \mu \le - \bar{y} + \frac{S}{\sqrt{n}}t_\delta \right)   \\
&amp; =
\mathbb{P}_\mu\left(\bar{y} + \frac{S}{\sqrt{n}}t_\delta \ge \mu \ge \bar{y} - \frac{S}{\sqrt{n}}t_\delta \right)       \\
&amp; =
\mathbb{P}_\mu\left(\bar{y} - \frac{S}{\sqrt{n}}t_\delta \le \mu \le \bar{y} + \frac{S}{\sqrt{n}}t_\delta \right)       \\
&amp; =
\mathbb{P}_\mu\left(\left[\bar{y} - \frac{S}{\sqrt{n}}t_\delta, \bar{y} + \frac{S}{\sqrt{n}}t_\delta\right] \ni \mu \right).        \\
&amp; =
\mathbb{P}_\mu\left(\kappa(y) \ni \mu \right).      \\
\end{split}
\end{align}\]</span></p>
</div>
<p>The decisive step for guaranteeing the coverage probability <span class="math inline">\(\delta\)</span> of the true, but unknown, expectation parameter by the confidence interval defined in <a href="#thm-confidence-interval-for-expectation-parameter-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>32.2</span></a> is the definition of <span class="math display">\[\begin{equation}
t_\delta := \Psi^{-1}\left(\frac{1+\delta}{2}; n-1\right).
\end{equation}\]</span> As traced in the proof of <a href="#thm-confidence-interval-for-expectation-parameter-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>32.2</span></a>, the coverage probability of the confidence interval for the true, but unknown, expectation parameter is equivalent to the fact that, when this <span class="math inline">\(t_\delta\)</span> is chosen, the <span class="math inline">\(T\)</span> confidence-interval statistic has probability <span class="math inline">\(\delta\)</span> of taking a value in the interval <span class="math inline">\([-t_\delta, t_\delta]\)</span>. We visualize the choice of <span class="math inline">\(t_\delta\)</span> for the case <span class="math inline">\(\delta := 0.95\)</span> and <span class="math inline">\(n := 5\)</span> in <a href="#fig-t-confidence-condition" class="quarto-xref">Figure&nbsp;<span>32.2</span></a>. In this case, <span class="math display">\[\begin{equation}
-t_\delta = \Psi^{-1}(0.025;4) = -2.57 \mbox{ and }
t_\delta = \Psi^{-1}(0.975;4) = 2.57.
\end{equation}\]</span> <a href="#fig-t-confidence-condition" class="quarto-xref">Figure&nbsp;<span>32.2</span></a> A shows this choice from the perspective of the PDF of the <span class="math inline">\(T\)</span> confidence-interval statistic. The probability mass enclosed by <span class="math inline">\(-t_\delta\)</span> and <span class="math inline">\(t_\delta\)</span> is <span class="math inline">\(\delta\)</span> by construction, so <span class="math inline">\(T\)</span> takes a value between <span class="math inline">\(-t_\delta\)</span> and <span class="math inline">\(t_\delta\)</span> with probability <span class="math inline">\(\delta\)</span>. <a href="#fig-t-confidence-condition" class="quarto-xref">Figure&nbsp;<span>32.2</span></a> B shows the corresponding perspective of the CDF of the <span class="math inline">\(T\)</span> confidence-interval statistic. Based on the specification of <span class="math inline">\(\frac{1-\delta}{2}\)</span> and <span class="math inline">\(\frac{1+\delta}{2}\)</span>, the corresponding values for <span class="math inline">\(-t_\delta\)</span> and <span class="math inline">\(t_\delta\)</span> are determined using the inverse CDF <span class="math inline">\(\Psi^{-1}\)</span>. Note that the centrality of the probability mass given here is not implicit in <a href="#def-delta-confidence-interval" class="quarto-xref">Definition&nbsp;<span>32.1</span></a>, but results from the properties of the distribution of the <span class="math inline">\(T\)</span> confidence-interval statistic, in particular its symmetry around 0.</p>
<div id="fig-t-confidence-condition" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-confidence-condition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/403-t-confidence-condition.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-confidence-condition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.2: Guaranteeing the coverage probability of the confidence interval for the expectation parameter of the normal distribution model for <span class="math inline">\(\delta := 0.95\)</span> and <span class="math inline">\(n := 5\)</span> from the perspective of the PDF (A) and the CDF (B) of the distribution of the <span class="math inline">\(T\)</span> confidence-interval statistic.
</figcaption>
</figure>
</div>
<p>Finally, we want to demonstrate the coverage probability of the confidence interval given by <a href="#thm-confidence-interval-for-expectation-parameter-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>32.2</span></a> using a simulation. We consider only the first interpretation of a confidence interval with a constant true, but unknown, parameter. In this sense, the following <strong>R</strong> code determines the corresponding confidence interval for each sample realization.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># model specification</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)                                        <span class="co"># random-number generator</span></span>
<span id="cb2-3"><a href="#cb2-3"></a>mu      <span class="ot">=</span> <span class="dv">2</span>                                        <span class="co"># true, but unknown, expectation parameter</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>sigsqr  <span class="ot">=</span> <span class="dv">1</span>                                        <span class="co"># true, but unknown, variance parameter</span></span>
<span id="cb2-5"><a href="#cb2-5"></a>sigma   <span class="ot">=</span> <span class="fu">sqrt</span>(sigsqr)                             <span class="co"># true, but unknown, standard-deviation parameter</span></span>
<span id="cb2-6"><a href="#cb2-6"></a>n       <span class="ot">=</span> <span class="dv">12</span>                                       <span class="co"># sample size</span></span>
<span id="cb2-7"><a href="#cb2-7"></a>delta   <span class="ot">=</span> <span class="fl">0.95</span>                                     <span class="co"># confidence condition</span></span>
<span id="cb2-8"><a href="#cb2-8"></a>t_delta <span class="ot">=</span> <span class="fu">qt</span>((<span class="dv">1</span><span class="sc">+</span>delta)<span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>)                      <span class="co"># \Psi^-1((\delta + 1)/2, n-1)</span></span>
<span id="cb2-9"><a href="#cb2-9"></a></span>
<span id="cb2-10"><a href="#cb2-10"></a><span class="co"># sample realizations</span></span>
<span id="cb2-11"><a href="#cb2-11"></a>ns      <span class="ot">=</span> <span class="fl">1e2</span>                                      <span class="co"># number of sample realizations</span></span>
<span id="cb2-12"><a href="#cb2-12"></a>y_bar   <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                              <span class="co"># sample-mean array</span></span>
<span id="cb2-13"><a href="#cb2-13"></a>S       <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                              <span class="co"># standard-deviation array</span></span>
<span id="cb2-14"><a href="#cb2-14"></a>kappa   <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NaN</span>,<span class="dv">2</span><span class="sc">*</span>ns), <span class="at">ncol =</span> <span class="dv">2</span>)          <span class="co"># confidence-interval array</span></span>
<span id="cb2-15"><a href="#cb2-15"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ns){</span>
<span id="cb2-16"><a href="#cb2-16"></a>   y          <span class="ot">=</span> <span class="fu">rnorm</span>(n,mu,sigma)                  <span class="co"># sample realization</span></span>
<span id="cb2-17"><a href="#cb2-17"></a>   y_bar[i]   <span class="ot">=</span> <span class="fu">mean</span>(y)                            <span class="co"># sample mean</span></span>
<span id="cb2-18"><a href="#cb2-18"></a>   S[i]       <span class="ot">=</span> <span class="fu">sd</span>(y)                              <span class="co"># sample standard deviation</span></span>
<span id="cb2-19"><a href="#cb2-19"></a>   kappa[i,<span class="dv">1</span>] <span class="ot">=</span> y_bar[i] <span class="sc">-</span> (S[i]<span class="sc">/</span><span class="fu">sqrt</span>(n))<span class="sc">*</span>t_delta  <span class="co"># lower confidence-interval bound</span></span>
<span id="cb2-20"><a href="#cb2-20"></a>   kappa[i,<span class="dv">2</span>] <span class="ot">=</span> y_bar[i] <span class="sc">+</span> (S[i]<span class="sc">/</span><span class="fu">sqrt</span>(n))<span class="sc">*</span>t_delta  <span class="co"># upper confidence-interval bound</span></span>
<span id="cb2-21"><a href="#cb2-21"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We visualize the results of this simulation in <a href="#fig-ci-expectation-parameter-normal-distribution-1" class="quarto-xref">Figure&nbsp;<span>32.3</span></a>.</p>
<div id="fig-ci-expectation-parameter-normal-distribution-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ci-expectation-parameter-normal-distribution-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/403-ci-expectation-parameter-normal-distribution-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ci-expectation-parameter-normal-distribution-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.3: Simulation of the coverage probability of the confidence interval for the expectation parameter of the normal distribution model with constant true, but unknown, expectation parameter <span class="math inline">\(\mu := 2\)</span> for <span class="math inline">\(\sigma^2 := 2, n := 12\)</span> and a desired coverage probability of <span class="math inline">\(\delta := 0.95\)</span>. The figure shows the confidence interval and the corresponding expectation-parameter estimator for each sample realization. In the present simulation, the confidence intervals cover the identical true, but unknown, expectation parameter <span class="math inline">\(\mu:=2\)</span>, shown as a gray line, in 96 out of 100 cases. The sample realizations for which this is not the case are marked by an orange circle.
</figcaption>
</figure>
</div>
</section>
<section id="confidence-interval-for-the-variance-parameter-of-the-normal-distribution-model" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="confidence-interval-for-the-variance-parameter-of-the-normal-distribution-model">Confidence interval for the variance parameter of the normal distribution model</h3>
<p>We consider the construction of a <span class="math inline">\(\delta\)</span> confidence interval for the variance parameter of the normal distribution model. To this end, we first define the following confidence-interval statistic.</p>
<div id="def-u-confidence-interval-statistic" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 32.3 (<span class="math inline">\(U\)</span> confidence-interval statistic)</strong></span> Given the normal distribution model <span class="math display">\[\begin{equation}
y_1,...,y_n \sim N(\mu,\sigma^2)
\end{equation}\]</span> the statistic defined by the sample variance <span class="math display">\[\begin{equation}
\frac{1}{n-1}\sum_{i=1}^n \left(y_i - \bar{y}\right)^2
\end{equation}\]</span> namely <span class="math display">\[\begin{equation}
U := \frac{n-1}{\sigma^2}S^2
\end{equation}\]</span> is called the <em><span class="math inline">\(U\)</span> confidence-interval statistic</em>.</p>
</div>
<p>For the distribution of the <span class="math inline">\(U\)</span> confidence-interval statistic, the following theorem holds.</p>
<div id="thm-distribution-of-u-confidence-interval-statistic" class="theorem">
<p><span class="theorem-title"><strong>Theorem 32.3 (Distribution of the <span class="math inline">\(U\)</span> confidence-interval statistic)</strong></span> The <span class="math inline">\(U\)</span> confidence-interval statistic is a <span class="math inline">\(\chi^2\)</span>-distributed random variable with parameter <span class="math inline">\(n-1\)</span>; that is, <span class="math display">\[\begin{equation}
U \sim \chi^2(n-1)
\end{equation}\]</span></p>
</div>
<p>For a proof of <a href="#thm-distribution-of-u-confidence-interval-statistic" class="quarto-xref">Theorem&nbsp;<span>32.3</span></a>, we refer to <span class="citation" data-cites="casella2002">Casella &amp; Berger (<a href="#ref-casella2002" role="doc-biblioref">2002</a>)</span>. Like the <span class="math inline">\(T\)</span> confidence-interval statistic, the <span class="math inline">\(U\)</span> confidence-interval statistic has the pivot property because it is a function of the sample, but its distribution according to <a href="#thm-distribution-of-u-confidence-interval-statistic" class="quarto-xref">Theorem&nbsp;<span>32.3</span></a> does not depend on the true, but unknown, distribution parameters of the sample. For the following developments, recall that we denote the PDF of a <span class="math inline">\(\chi^2\)</span>-distributed random variable by <span class="math inline">\(\chi^2\)</span>, the CDF of a <span class="math inline">\(\chi^2\)</span>-distributed random variable by <span class="math inline">\(\Xi\)</span>, and the inverse CDF of a <span class="math inline">\(\chi^2\)</span>-distributed random variable by <span class="math inline">\(\Xi^{-1}\)</span>. The following <strong>R</strong> code first simulates the distribution of the <span class="math inline">\(U\)</span> confidence-interval statistic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># model specification</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>mu      <span class="ot">=</span> <span class="dv">10</span>                                    <span class="co"># true expectation parameter</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>sigsqr  <span class="ot">=</span> <span class="dv">4</span>                                     <span class="co"># true known variance parameter</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>n       <span class="ot">=</span> <span class="dv">12</span>                                    <span class="co"># sample size</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>ns      <span class="ot">=</span> <span class="fl">1e4</span>                                   <span class="co"># number of sample realizations</span></span>
<span id="cb3-6"><a href="#cb3-6"></a>res     <span class="ot">=</span> <span class="fl">1e3</span>                                   <span class="co"># outcome-space resolution</span></span>
<span id="cb3-7"><a href="#cb3-7"></a></span>
<span id="cb3-8"><a href="#cb3-8"></a><span class="co"># analytic definitions and results</span></span>
<span id="cb3-9"><a href="#cb3-9"></a>yx      <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">3</span>,<span class="dv">17</span>,<span class="at">len =</span> res)                   <span class="co"># y_i space</span></span>
<span id="cb3-10"><a href="#cb3-10"></a>ux      <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">30</span>,<span class="at">len =</span> res)                   <span class="co"># U space</span></span>
<span id="cb3-11"><a href="#cb3-11"></a>p_y_i   <span class="ot">=</span> <span class="fu">dnorm</span>(yx,mu,<span class="fu">sqrt</span>(sigsqr))             <span class="co"># y_i PDF</span></span>
<span id="cb3-12"><a href="#cb3-12"></a>p_y_bar <span class="ot">=</span> <span class="fu">dnorm</span>(yx,mu,<span class="fu">sqrt</span>(sigsqr<span class="sc">/</span>n))           <span class="co"># y_bar PDF</span></span>
<span id="cb3-13"><a href="#cb3-13"></a>p_u     <span class="ot">=</span> <span class="fu">dchisq</span>(ux,n<span class="dv">-1</span>)                        <span class="co"># U PDF</span></span>
<span id="cb3-14"><a href="#cb3-14"></a></span>
<span id="cb3-15"><a href="#cb3-15"></a><span class="co"># simulation</span></span>
<span id="cb3-16"><a href="#cb3-16"></a>y_i     <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                           <span class="co"># y_i array</span></span>
<span id="cb3-17"><a href="#cb3-17"></a>y_bar   <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                           <span class="co"># \bar{y} array</span></span>
<span id="cb3-18"><a href="#cb3-18"></a>S_sqr   <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                           <span class="co"># S^2 array</span></span>
<span id="cb3-19"><a href="#cb3-19"></a>UKS     <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                           <span class="co"># U confidence-interval statistic array</span></span>
<span id="cb3-20"><a href="#cb3-20"></a><span class="cf">for</span>(s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ns){                                 <span class="co"># simulation iterations</span></span>
<span id="cb3-21"><a href="#cb3-21"></a>  y         <span class="ot">=</span> <span class="fu">rnorm</span>(n,mu,<span class="fu">sqrt</span>(sigsqr))          <span class="co"># sample realization</span></span>
<span id="cb3-22"><a href="#cb3-22"></a>  y_i[s]    <span class="ot">=</span> y[<span class="dv">1</span>]                              <span class="co"># sample realization y_i with i = 1</span></span>
<span id="cb3-23"><a href="#cb3-23"></a>  y_bar[s]  <span class="ot">=</span> <span class="fu">mean</span>(y)                           <span class="co"># sample-mean realization</span></span>
<span id="cb3-24"><a href="#cb3-24"></a>  S_sqr[s]  <span class="ot">=</span> <span class="fu">var</span>(y)                            <span class="co"># sample-variance realization</span></span>
<span id="cb3-25"><a href="#cb3-25"></a>  UKS[s]    <span class="ot">=</span> ((n<span class="dv">-1</span>)<span class="sc">/</span>sigsqr)<span class="sc">*</span>S_sqr[s]           <span class="co"># U confidence-interval statistic realization</span></span>
<span id="cb3-26"><a href="#cb3-26"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="fig-u-confidence-interval-statistic" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-u-confidence-interval-statistic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/403-u-confidence-interval-statistic.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-u-confidence-interval-statistic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.4: Simulation of the distribution of the <span class="math inline">\(U\)</span> confidence-interval statistic and the underlying distributions of the sample variable, the sample mean, and the sample variance.
</figcaption>
</figure>
</div>
<p>Using the distribution of the <span class="math inline">\(U\)</span> confidence-interval statistic, we can now prove the following theorem on the confidence interval for the variance parameter of the normal distribution model.</p>
<div id="thm-confidence-interval-for-variance-parameter-of-normal-distribution-model" class="theorem">
<p><span class="theorem-title"><strong>Theorem 32.4 (Confidence interval for the variance parameter of the normal distribution model)</strong></span> Given the normal distribution model <span class="math display">\[\begin{equation}
y_1,...,y_n \sim N(\mu,\sigma^2)
\end{equation}\]</span> with true, but unknown, parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span>, let <span class="math inline">\(\delta \in ]0,1[\)</span> and let <span class="math display">\[\begin{equation}
u_{\delta} := \Xi^{-1}\left(\frac{1 - \delta}{2}; n -1  \right)
\mbox{ and }
u_{\delta}' := \Xi^{-1}\left(\frac{1 + \delta}{2};n-1 \right)
\end{equation}\]</span> where <span class="math inline">\(\Xi^{-1}\)</span> is the inverse CDF of a <span class="math inline">\(\chi^2\)</span>-distributed random variable. Then, for the interval <span class="math display">\[\begin{equation}
\kappa(y) := \left[\frac{(n-1)S^2}{u_{\delta}'}, \frac{(n-1)S^2}{u_{\delta}}\right].
\end{equation}\]</span> with the sample variance <span class="math display">\[\begin{equation}
S^2 := \frac{1}{n-1}\sum_{i=1}^n(y_i - \bar{y})^2,
\end{equation}\]</span> it holds that <span class="math display">\[\begin{equation}
\mathbb{P}_{\sigma^2}(\kappa(y) \ni \sigma^2) = \delta.
\end{equation}\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By definition, using <a href="#def-u-confidence-interval-statistic" class="quarto-xref">Definition&nbsp;<span>32.3</span></a> and <a href="#thm-distribution-of-u-confidence-interval-statistic" class="quarto-xref">Theorem&nbsp;<span>32.3</span></a>, we have <span class="math display">\[\begin{equation}
\mathbb{P}_{\sigma^2}\left(u_{\delta} \le U \le u_{\delta}' \right) = \delta.
\end{equation}\]</span> Consequently, it follows directly that <span class="math display">\[\begin{align}
\begin{split}
\delta
&amp; = \mathbb{P}_{\sigma^2}\left(u_{\delta} \le U \le u_{\delta}' \right)                                                                     \\
&amp; = \mathbb{P}_{\sigma^2}\left(u_{\delta} \le \frac{n-1}{\sigma^2}S^2  \le u_{\delta}' \right)                                        \\
&amp; = \mathbb{P}_{\sigma^2}\left(u_{\delta}^{-1} \ge \frac{\sigma^2}{(n-1)S^2} \ge {u_{\delta}'}^{-1} \right)                               \\
&amp; = \mathbb{P}_{\sigma^2}\left(\frac{(n-1)S^2}{u_{\delta}} \ge \sigma^2 \ge \frac{(n-1)S^2}{u_{\delta}'} \right)                   \\
&amp; = \mathbb{P}_{\sigma^2}\left(\frac{(n-1)S^2}{u_{\delta}'} \le \sigma^2 \le \frac{(n-1)S^2}{u_{\delta}} \right)                  \\
&amp; = \mathbb{P}_{\sigma^2}\left(\left[\frac{(n-1)S^2}{u_{\delta}'}, \frac{(n-1)S^2}{u_{\delta}}\right] \ni \sigma^2 \right).     \\
\end{split}
\end{align}\]</span></p>
</div>
<p>As in the case of <a href="#thm-confidence-interval-for-expectation-parameter-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>32.2</span></a>, the decisive step for guaranteeing the coverage probability <span class="math inline">\(\delta\)</span> of the true, but unknown, variance parameter by the confidence interval defined in <a href="#thm-confidence-interval-for-variance-parameter-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>32.4</span></a> is the definition of <span class="math display">\[\begin{equation}
u_{\delta} := \Xi^{-1}\left(\frac{1-\delta}{2}; n-1\right)
\mbox{ and }
u_{\delta}' := \Xi^{-1}\left(\frac{1 + \delta}{2};n-1 \right).
\end{equation}\]</span> As traced in the proof of <a href="#thm-confidence-interval-for-variance-parameter-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>32.4</span></a>, the coverage probability of the confidence interval for the true, but unknown, variance parameter is equivalent to the fact that, when precisely these values of <span class="math inline">\(u_\delta\)</span> and <span class="math inline">\(u_{\delta}'\)</span> are chosen, the <span class="math inline">\(U\)</span> confidence-interval statistic has probability <span class="math inline">\(\delta\)</span> of taking a value in the interval <span class="math inline">\([u_{\delta}, u_{\delta}']\)</span>. We visualize the choice of <span class="math inline">\(u_\delta\)</span> and <span class="math inline">\(u_\delta'\)</span> for the case <span class="math inline">\(\delta := 0.95\)</span> and <span class="math inline">\(n := 10\)</span> in <a href="#fig-u-confidence-condition" class="quarto-xref">Figure&nbsp;<span>32.5</span></a>. In this case, <span class="math display">\[\begin{equation}
u_{\delta}  := \Xi^{-1}\left(0.025;9\right) = 2.70 \mbox{ and }
u_{\delta}' := \Xi^{-1}\left(0.975;9\right) = 19.0.
\end{equation}\]</span> <a href="#fig-u-confidence-condition" class="quarto-xref">Figure&nbsp;<span>32.5</span></a> A shows this choice from the perspective of the PDF of the <span class="math inline">\(U\)</span> confidence-interval statistic. The probability mass enclosed by <span class="math inline">\(u_\delta\)</span> and <span class="math inline">\(u_\delta'\)</span> is <span class="math inline">\(\delta\)</span> by construction, so <span class="math inline">\(U\)</span> takes a value between <span class="math inline">\(u_\delta\)</span> and <span class="math inline">\(u_\delta'\)</span> with probability <span class="math inline">\(\delta\)</span>. <a href="#fig-u-confidence-condition" class="quarto-xref">Figure&nbsp;<span>32.5</span></a> B shows the corresponding perspective of the CDF of the <span class="math inline">\(U\)</span> confidence-interval statistic. Based on the specification of <span class="math inline">\(\frac{1-\delta}{2}\)</span> and <span class="math inline">\(\frac{1+\delta}{2}\)</span>, the corresponding values for <span class="math inline">\(u_\delta\)</span> and <span class="math inline">\(u_\delta'\)</span> are determined using the inverse CDF <span class="math inline">\(\Xi^{-1}\)</span>. Note that in this case the probability mass is located rather arbitrarily with respect to the mode of the distribution of the <span class="math inline">\(U\)</span> confidence-interval statistic. Accordingly, there are more advanced procedures for locating the coverage probability of a confidence-interval statistic in such a way that, for example, it occupies a maximal interval in its outcome space or satisfies a symmetry property around the expectation. We do not pursue these approaches here.</p>
<div id="fig-u-confidence-condition" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-u-confidence-condition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/403-u-confidence-condition.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-u-confidence-condition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.5: Guaranteeing the coverage probability of the confidence interval for the variance parameter of the normal distribution model for <span class="math inline">\(\delta := 0.95\)</span> and <span class="math inline">\(n := 10\)</span> from the perspective of the PDF (A) and the CDF (B) of the distribution of the <span class="math inline">\(U\)</span> confidence-interval statistic.
</figcaption>
</figure>
</div>
<p>Finally, we want to demonstrate the coverage probability of the confidence interval given by <a href="#thm-confidence-interval-for-variance-parameter-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>32.4</span></a> using a simulation. To this end, we first consider the first interpretation of a confidence interval given in <a href="#sec-confidence-intervals-definition" class="quarto-xref"><span>Section 32.1</span></a>, with the same true, but unknown, parameter throughout. In this sense, the following <strong>R</strong> code determines the corresponding confidence interval for each sample realization.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># model specification</span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)                                     <span class="co"># random-number generator</span></span>
<span id="cb4-3"><a href="#cb4-3"></a>mu          <span class="ot">=</span> <span class="dv">2</span>                                 <span class="co"># true, but unknown, expectation parameter</span></span>
<span id="cb4-4"><a href="#cb4-4"></a>sigsqr      <span class="ot">=</span> <span class="dv">2</span>                                 <span class="co"># true, but unknown, variance parameter</span></span>
<span id="cb4-5"><a href="#cb4-5"></a>n           <span class="ot">=</span> <span class="dv">12</span>                                <span class="co"># sample size</span></span>
<span id="cb4-6"><a href="#cb4-6"></a>delta       <span class="ot">=</span> <span class="fl">0.95</span>                              <span class="co"># confidence condition</span></span>
<span id="cb4-7"><a href="#cb4-7"></a>u_delta     <span class="ot">=</span> <span class="fu">qchisq</span>((<span class="dv">1</span><span class="sc">-</span>delta)<span class="sc">/</span><span class="dv">2</span>, n <span class="sc">-</span> <span class="dv">1</span>)        <span class="co"># \Xi^2((1-\delta)/2; n - 1)</span></span>
<span id="cb4-8"><a href="#cb4-8"></a>u_delta_p   <span class="ot">=</span> <span class="fu">qchisq</span>((<span class="dv">1</span><span class="sc">+</span>delta)<span class="sc">/</span><span class="dv">2</span>, n <span class="sc">-</span> <span class="dv">1</span>)        <span class="co"># \Xi^2((1+\delta)/2; n - 1)</span></span>
<span id="cb4-9"><a href="#cb4-9"></a></span>
<span id="cb4-10"><a href="#cb4-10"></a><span class="co"># sample realizations</span></span>
<span id="cb4-11"><a href="#cb4-11"></a>ns          <span class="ot">=</span> <span class="fl">1e2</span>                               <span class="co"># number of simulations</span></span>
<span id="cb4-12"><a href="#cb4-12"></a>y_bar       <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                       <span class="co"># sample-mean array</span></span>
<span id="cb4-13"><a href="#cb4-13"></a>S2          <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NaN</span>,ns)                       <span class="co"># sample-variance array</span></span>
<span id="cb4-14"><a href="#cb4-14"></a>kappa       <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="cn">NaN</span>,<span class="dv">2</span><span class="sc">*</span>ns), <span class="at">ncol =</span> <span class="dv">2</span>)   <span class="co"># confidence-interval array</span></span>
<span id="cb4-15"><a href="#cb4-15"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ns){                                 <span class="co"># simulation iterations</span></span>
<span id="cb4-16"><a href="#cb4-16"></a>   y            <span class="ot">=</span> <span class="fu">rnorm</span>(n,mu,<span class="fu">sqrt</span>(sigsqr))      <span class="co"># sample realization</span></span>
<span id="cb4-17"><a href="#cb4-17"></a>   S2[i]        <span class="ot">=</span> <span class="fu">var</span>(y)                        <span class="co"># sample variance</span></span>
<span id="cb4-18"><a href="#cb4-18"></a>   kappa[i,<span class="dv">1</span>]   <span class="ot">=</span> (n<span class="dv">-1</span>)<span class="sc">*</span>S2[i]<span class="sc">/</span>u_delta_p         <span class="co"># lower confidence-interval bound</span></span>
<span id="cb4-19"><a href="#cb4-19"></a>   kappa[i,<span class="dv">2</span>]   <span class="ot">=</span> (n<span class="dv">-1</span>)<span class="sc">*</span>S2[i]<span class="sc">/</span>u_delta           <span class="co"># upper confidence-interval bound</span></span>
<span id="cb4-20"><a href="#cb4-20"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="fig-ci-variance-parameter-normal-distribution" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ci-variance-parameter-normal-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./_figures/403-ci-variance-parameter-normal-distribution.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ci-variance-parameter-normal-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32.6: Simulation of the coverage probability of the confidence interval for the variance parameter of the normal distribution model with constant true, but unknown, variance parameter <span class="math inline">\(\sigma^2 := 2\)</span> for <span class="math inline">\(\mu := 2, n := 12\)</span> and a desired coverage probability of <span class="math inline">\(\delta := 0.95\)</span>. The figure shows the confidence interval and the corresponding variance-parameter estimator for each sample realization. In the present simulation, the confidence intervals cover the identical true, but unknown, variance parameter <span class="math inline">\(\sigma^2 :=2\)</span>, shown as a gray line, in 95 out of 100 cases. The sample realizations for which this is not the case are marked by an orange circle. Note that the confidence intervals are not arranged symmetrically around the variance-parameter estimator.
</figcaption>
</figure>
</div>
<div id="exm-application-example-confidence-intervals" class="theorem example">
<p><span class="theorem-title"><strong>Example 32.1 (Application example)</strong></span> To conclude this section, we consider the evaluation of confidence intervals for the expectation and variance parameters under normality in the context of <a href="401-Frequentist-Inference.html#exm-application-example" class="quarto-xref">Example&nbsp;<span>30.5</span></a>. To this end, we first evaluate the unbiased point estimators of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span>, that is, the sample mean and the sample variance of the dataset, using the following <strong>R</strong> code.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>D           <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"./_data/bdi-ii-dataset.csv"</span>)        <span class="co"># read dataset</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>y           <span class="ot">=</span> D<span class="sc">$</span>dBDI                                        <span class="co"># select data</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>mu_hat      <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(y),<span class="dv">2</span>)                              <span class="co"># sample mean</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>sigsqr_hat  <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">var</span>(y),<span class="dv">2</span>)                               <span class="co"># sample variance</span></span>
<span id="cb5-5"><a href="#cb5-5"></a><span class="fu">cat</span>(<span class="st">"mu_hat     :"</span>, mu_hat,<span class="st">"</span><span class="sc">\n</span><span class="st">sigsqr_hat :"</span>, sigsqr_hat)    <span class="co"># output</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>mu_hat     : 3.17 
sigsqr_hat : 13.79</code></pre>
</div>
</div>
<p>Based on these estimators and the available <span class="math inline">\(n = 12\)</span> data points, <span class="math display">\[\begin{equation}
\hat{\mu} = 3.17 \mbox{ and } \hat{\sigma}^{2} = 13.8
\end{equation}\]</span> are therefore reasonable guesses for <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span>. In addition to these point estimates, which are very precise but match the true, but unknown, parameters with probability 0, we also determine the <span class="math inline">\(95\%\)</span> confidence-interval estimates for <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span>. The following <strong>R</strong> code determines the <span class="math inline">\(95\%\)</span> confidence interval for the expectation parameter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># confidence interval for the expectation parameter</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>delta    <span class="ot">=</span> <span class="fl">0.95</span>                                    <span class="co"># confidence level</span></span>
<span id="cb7-3"><a href="#cb7-3"></a>n        <span class="ot">=</span> <span class="fu">length</span>(y)                               <span class="co"># number of data points</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>t_delta  <span class="ot">=</span> <span class="fu">qt</span>((<span class="dv">1</span><span class="sc">+</span>delta)<span class="sc">/</span><span class="dv">2</span>,n<span class="dv">-1</span>)                     <span class="co"># \psi^-1((\delta+1)/2,n-1)</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>y_bar    <span class="ot">=</span> <span class="fu">mean</span>(y)                                 <span class="co"># sample mean</span></span>
<span id="cb7-6"><a href="#cb7-6"></a>s        <span class="ot">=</span> <span class="fu">sd</span>(y)                                   <span class="co"># sample standard deviation</span></span>
<span id="cb7-7"><a href="#cb7-7"></a>mu_hat   <span class="ot">=</span> y_bar                                   <span class="co"># expectation-parameter estimator</span></span>
<span id="cb7-8"><a href="#cb7-8"></a>kappa_u  <span class="ot">=</span> y_bar <span class="sc">-</span> (s<span class="sc">/</span><span class="fu">sqrt</span>(n))<span class="sc">*</span>t_delta             <span class="co"># lower confidence-interval bound</span></span>
<span id="cb7-9"><a href="#cb7-9"></a>kappa_o  <span class="ot">=</span> y_bar <span class="sc">+</span> (s<span class="sc">/</span><span class="fu">sqrt</span>(n))<span class="sc">*</span>t_delta             <span class="co"># upper confidence-interval bound</span></span>
<span id="cb7-10"><a href="#cb7-10"></a><span class="fu">cat</span>(<span class="st">"kappa_u:"</span>, kappa_u, <span class="st">"</span><span class="sc">\n</span><span class="st">kappa_o:"</span>, kappa_o)    <span class="co"># output</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>kappa_u: 0.8074098 
kappa_o: 5.525923</code></pre>
</div>
</div>
<p>The 0.95 confidence interval for the expectation parameter is therefore <span class="math display">\[\begin{equation}
\kappa(y) = [0.80,5.52].
\end{equation}\]</span> In the long-run average, a confidence interval calculated in this way covers the true, but unknown, expectation parameter in 95 out of 100 cases. In this sense, the true, but unknown, treatment effect is therefore very likely to lie in an interval between 0.80 and 5.52 BDI-II score pre-post differences.</p>
<p>The following <strong>R</strong> code determines the <span class="math inline">\(95\%\)</span> confidence interval for the variance parameter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># confidence interval for the variance parameter</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>delta       <span class="ot">=</span>  <span class="fl">0.95</span>                                <span class="co"># confidence level</span></span>
<span id="cb9-3"><a href="#cb9-3"></a>n           <span class="ot">=</span> <span class="fu">length</span>(y)                            <span class="co"># number of data points</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>u_delta_u   <span class="ot">=</span> <span class="fu">qchisq</span>((<span class="dv">1</span><span class="sc">-</span>delta)<span class="sc">/</span><span class="dv">2</span>, n <span class="sc">-</span> <span class="dv">1</span>)           <span class="co"># \Xi^2((1-\delta)/2; n - 1)</span></span>
<span id="cb9-5"><a href="#cb9-5"></a>u_delta_o   <span class="ot">=</span> <span class="fu">qchisq</span>((<span class="dv">1</span><span class="sc">+</span>delta)<span class="sc">/</span><span class="dv">2</span>, n <span class="sc">-</span> <span class="dv">1</span>)           <span class="co"># \Xi^2((1+\delta)/2; n - 1)</span></span>
<span id="cb9-6"><a href="#cb9-6"></a>s2          <span class="ot">=</span> <span class="fu">var</span>(y)                               <span class="co"># sample variance</span></span>
<span id="cb9-7"><a href="#cb9-7"></a>sigsqr_hat  <span class="ot">=</span> s2                                   <span class="co"># variance-parameter estimator</span></span>
<span id="cb9-8"><a href="#cb9-8"></a>kappa_u     <span class="ot">=</span> (n<span class="dv">-1</span>)<span class="sc">*</span>s2<span class="sc">/</span>u_delta_o                   <span class="co"># lower confidence-interval bound</span></span>
<span id="cb9-9"><a href="#cb9-9"></a>kappa_o        <span class="ot">=</span> (n<span class="dv">-1</span>)<span class="sc">*</span>s2<span class="sc">/</span>u_delta_u                <span class="co"># upper confidence-interval bound</span></span>
<span id="cb9-10"><a href="#cb9-10"></a><span class="fu">cat</span>(<span class="st">"kappa_u:"</span>, kappa_u, <span class="st">"</span><span class="sc">\n</span><span class="st">kappa_o:"</span>, kappa_o)    <span class="co"># output</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>kappa_u: 6.919084 
kappa_o: 39.74756</code></pre>
</div>
</div>
<p>The 0.95 confidence interval for the variance parameter is therefore <span class="math display">\[\begin{equation}
\kappa(y) = [6.91,39.74].
\end{equation}\]</span> In the long-run average, a confidence interval calculated in this way covers the true, but unknown, variance parameter in 95 out of 100 cases. In this sense, the true, but unknown, treatment-effect dispersion is therefore very likely to lie in an interval between 6.91 and 39.74 squared BDI-II score pre-post differences.</p>
</div>
</section>
</section>
<section id="bibliographic-remarks" class="level2" data-number="32.3">
<h2 data-number="32.3" class="anchored" data-anchor-id="bibliographic-remarks"><span class="header-section-number">32.3</span> Bibliographic remarks</h2>
<p>The results presented in this chapter go back in a very substantial way to <span class="citation" data-cites="neyman1937">Neyman (<a href="#ref-neyman1937" role="doc-biblioref">1937</a>)</span>.</p>
</section>
<section id="study-questions" class="level2 unnumbered unlisted">
<h2 class="unnumbered unlisted anchored" data-anchor-id="study-questions">Study questions</h2>
<ol type="1">
<li>State the definition of the concept of a <span class="math inline">\(\delta\)</span> confidence interval.</li>
<li>Explain the two interpretations of a <span class="math inline">\(\delta\)</span> confidence interval.</li>
<li>Explain the typical steps for constructing a <span class="math inline">\(\delta\)</span> confidence interval.</li>
<li>State the theorem on the confidence interval for the expectation parameter of the normal distribution model.</li>
<li>State the theorem on the confidence interval for the variance parameter of the normal distribution model.</li>
</ol>
</section>
<section id="study-question-answers" class="level2 unnumbered unlisted">
<h2 class="unnumbered unlisted anchored" data-anchor-id="study-question-answers">Study question answers</h2>
<ol type="1">
<li>See <a href="#def-delta-confidence-interval" class="quarto-xref">Definition&nbsp;<span>32.1</span></a>.</li>
<li>See the discussion following <a href="#def-delta-confidence-interval" class="quarto-xref">Definition&nbsp;<span>32.1</span></a>.</li>
<li>See the last paragraph of the discussion following <a href="#def-delta-confidence-interval" class="quarto-xref">Definition&nbsp;<span>32.1</span></a>.</li>
<li>See <a href="#thm-confidence-interval-for-expectation-parameter-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>32.2</span></a>.</li>
<li>See <a href="#thm-confidence-interval-for-variance-parameter-of-normal-distribution-model" class="quarto-xref">Theorem&nbsp;<span>32.4</span></a>.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-casella2002" class="csl-entry" role="listitem">
Casella, G., &amp; Berger, R. (2002). <em>Statistical <span>Inference</span></em> (2nd ed.). Thomson Learning.
</div>
<div id="ref-neyman1937" class="csl-entry" role="listitem">
Neyman, J. (1937). Outline of a <span>Theory</span> of <span>Statistical Estimation Based</span> on the <span>Classical Theory</span> of <span>Probability</span>. <em>Statistical Stimation</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script>
(function () {
  var base = "https://dirk-ostwald.github.io";
  var pageMap = {
    "/": "/en/",
    "/index.html": "/en/",
    "/Referenzen.html": "/en/References.html",
    "/_part_1/100-Mathematische-Grundlagen.html": "/en/_part_1/100-Mathematical-Foundations.html",
    "/_part_1/101-Sprache-und-Logik.html": "/en/_part_1/101-Language-and-Logic.html",
    "/_part_1/102-Mengen.html": "/en/_part_1/102-Sets.html",
    "/_part_1/103-Summen-Produkte-Potenzen.html": "/en/_part_1/103-Sums-Products-Powers.html",
    "/_part_1/104-Funktionen.html": "/en/_part_1/104-Functions.html",
    "/_part_1/105-Folgen-Grenzwerte-Stetigkeit.html": "/en/_part_1/105-Sequences-Limits-Continuity.html",
    "/_part_1/106-Differenzialrechnung.html": "/en/_part_1/106-Differential-Calculus.html",
    "/_part_1/107-Integralrechnung.html": "/en/_part_1/107-Integral-Calculus.html",
    "/_part_1/108-Vektoren.html": "/en/_part_1/108-Vectors.html",
    "/_part_1/109-Matrizen.html": "/en/_part_1/109-Matrices.html",
    "/_part_1/110-Deskriptivstatistiken.html": "/en/_part_1/110-Descriptive-Statistics.html",
    "/_part_2/200-Imperative-Programmierung.html": "/en/_part_2/200-Imperative-Programming.html",
    "/_part_2/201-Informatische-Grundbegriffe.html": "/en/_part_2/201-Basic-Concepts-of-Computer-Science.html",
    "/_part_2/202-Arithmetik-und-Variablen.html": "/en/_part_2/202-Arithmetic-and-Variables.html",
    "/_part_2/203-Datenstrukturen.html": "/en/_part_2/203-Data-Structures.html",
    "/_part_2/204-Vektoren.html": "/en/_part_2/204-Vectors.html",
    "/_part_2/205-Matrizen-und-Arrays.html": "/en/_part_2/205-Matrices-and-Arrays.html",
    "/_part_2/206-Listen-Dataframes-und-Tibbles.html": "/en/_part_2/206-Lists-Dataframes-and-Tibbles.html",
    "/_part_2/207-Datenmanagement.html": "/en/_part_2/207-Data-Management.html",
    "/_part_2/208-Kontrollstrukturen.html": "/en/_part_2/208-Control-Structures.html",
    "/_part_3/300-Wahrscheinlichkeitstheorie.html": "/en/_part_3/300-Probability-Theory.html",
    "/_part_3/301-Wahrscheinlichkeitsräume.html": "/en/_part_3/301-Probability-Spaces.html",
    "/_part_3/302-Elementare-Wahrscheinlichkeiten.html": "/en/_part_3/302-Elementary-Probabilities.html",
    "/_part_3/303-Zufallsvariablen.html": "/en/_part_3/303-Random-Variables.html",
    "/_part_3/304-Zufallsvektoren.html": "/en/_part_3/304-Random-Vectors.html",
    "/_part_3/305-Erwartungswerte.html": "/en/_part_3/305-Expectations.html",
    "/_part_3/306-Varianzen.html": "/en/_part_3/306-Variances.html",
    "/_part_3/307-Kovarianzen.html": "/en/_part_3/307-Covariances.html",
    "/_part_3/308-Ungleichungen.html": "/en/_part_3/308-Inequalities.html",
    "/_part_3/309-Grenzwerte.html": "/en/_part_3/309-Limits.html",
    "/_part_3/310-Transformationen.html": "/en/_part_3/310-Transformations.html",
    "/_part_3/311-Normalverteilungen.html": "/en/_part_3/311-Normal-Distributions.html",
    "/_part_4/400-Inferenz.html": "/en/_part_4/400-Inference.html",
    "/_part_4/401-Frequentistische-Inferenz.html": "/en/_part_4/401-Frequentist-Inference.html",
    "/_part_4/402-Punktschätzung.html": "/en/_part_4/402-Point-Estimation.html",
    "/_part_4/403-Konfidenzintervalle.html": "/en/_part_4/403-Confidence-Intervals.html",
    "/_part_4/404-Hypothesentests.html": "/en/_part_4/404-Hypothesis-Tests.html",
    "/_part_5/500-Allgemeines-Lineares-Modell.html": "/en/_part_5/500-General-Linear-Model.html",
    "/_part_5/501-Regression.html": "/en/_part_5/501-Regression.html",
    "/_part_5/502-Korrelation.html": "/en/_part_5/502-Correlation.html",
    "/_part_5/503-Modellformulierung.html": "/en/_part_5/503-Model-Formulation.html",
    "/_part_5/504-Parameterschätzung.html": "/en/_part_5/504-Parameter-Estimation.html",
    "/_part_5/505-T-Statistiken.html": "/en/_part_5/505-T-Statistics.html",
    "/_part_5/506-F-Statistiken.html": "/en/_part_5/506-F-Statistics.html",
    "/_part_5/507-T-Tests.html": "/en/_part_5/507-T-Tests.html",
    "/_part_5/508-Einfaktorielle-Varianzanalyse.html": "/en/_part_5/508-One-Way-Analysis-of-Variance.html",
    "/_part_5/509-Zweifaktorielle-Varianzanalyse.html": "/en/_part_5/509-Two-Way-Analysis-of-Variance.html",
    "/_part_5/510-Partielle-Korrelation.html": "/en/_part_5/510-Partial-Correlation.html",
    "/_part_5/511-Multiple-Regression.html": "/en/_part_5/511-Multiple-Regression.html",
    "/_part_7/700-Multivariate-Inferenz.html": "/en/_part_7/700-Multivariate-Inference.html",
    "/_part_7/701-Multivariate-Deskriptivstatistiken.html": "/en/_part_7/701-Multivariate-Descriptive-Statistics.html",
    "/_part_7/702-Einstichproben-T2-Tests.html": "/en/_part_7/702-One-Sample-T2-Tests.html",
    "/_part_7/703-Einfaktorielle-Varianzanalyse.html": "/en/_part_7/703-One-Way-Analysis-of-Variance.html",
    "/_part_7/704-Kanonische-Korrelationsanalyse.html": "/en/_part_7/704-Canonical-Correlation-Analysis.html"
  };
  var reversePageMap = {};
  Object.keys(pageMap).forEach(function (key) {
    reversePageMap[pageMap[key]] = key;
  });
  function headings() {
    return Array.prototype.slice.call(document.querySelectorAll("main.content h1[id], main.content h2[id], main.content h3[id], main.content h4[id]"));
  }
  function currentHeadingIndex() {
    var hash = window.location.hash;
    if (!hash) return "";
    var id = hash.slice(1);
    try {
      id = decodeURIComponent(id);
    } catch (error) {}
    var list = headings();
    for (var i = 0; i < list.length; i++) {
      if (list[i].id === id) return String(i);
    }
    return "";
  }
  function scrollToHeadingIndex() {
    var params = new URLSearchParams(window.location.search);
    var value = params.get("h");
    if (value === null) return;
    var index = Number(value);
    var list = headings();
    if (Number.isInteger(index) && index >= 0 && index < list.length) {
      list[index].scrollIntoView();
      if (history.replaceState) {
        history.replaceState(null, "", window.location.pathname + "#" + list[index].id);
      }
    }
  }
  var path = window.location.pathname;
  var target = pageMap[path] || reversePageMap[path];
  if (target) {
    document.querySelectorAll("a.nav-link").forEach(function (link) {
      var text = link.textContent.trim();
      if (text === "English" || text === "Deutsch") {
        var index = currentHeadingIndex();
        link.href = base + target + (index ? "?h=" + index : "");
      }
    });
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", scrollToHeadingIndex);
  } else {
    scrollToHeadingIndex();
  }
}());
</script>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../_part_4/402-Point-Estimation.html" class="pagination-link" aria-label="Point estimation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Point estimation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../_part_4/404-Hypothesis-Tests.html" class="pagination-link" aria-label="Hypothesis tests">
        <span class="nav-page-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Hypothesis tests</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dirk-ostwald/dirk-ostwald.github.io/tree/gh-pages/edit/main/_part_4/403-Confidence-Intervals.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>