# Imperative Programmierung {#sec-imperative-programmierun}
\normalsize

Heutzutage liegen wissenschaftliche Daten in der Regel in digitaler Form vor. 
Um diese digitalen Daten auszuwerten, werden sie mit Hilfe eines Computers analysiert. 
Dazu schreibt man spezielle Computerprogramme, die genau auf die jeweilige Fragestellung
zugeschnitten sind. Solche Programme bezeichnet man als Datenanalyseskripte.

Die computergestützte Datenanalyse folgt dabei einer typischen Struktur. Zunächst 
wird ein digitaler Datensatz eingelesen und bereinigt, um fehlerhafte oder 
unvollständige Daten zu korrigieren und für die Analyse vorzubereiten. Anschließend 
werden meist deskriptive Statistiken berechnet und visualisiert, um einen ersten
Überblick über die Daten zu gewinnen. Darauf folgt häufig ein Schritt der
probabilistischen Modellierung und Inferenz, bei der wahrscheinlichkeitstheorie-
basierte Modelle verwendet werden, um Hypothesen zu testen oder Vorhersagen zu 
treffen. Abschließend werden die Ergebnisse, wiederum mithilfe des Computers,
dokumentiert und anschaulich präsentiert.

Zentrales Element der computergestützten Datenanalyse ist das *Datenanalyseskript*, eine
Textdatei, die alle Schritte vom Rohdatum bis hin zur finalen Datenvisualisierung dokumentiert 
und so Datenanalyseprozesse transparent und nachvollziehbar macht. So ermöglicht 
ein Datenanalyseskript Dritten die Reproduktion wissenschaftlicher Ergebnisse, 
was einen Grundpfeiler guter wissenschaftlicher Praxis darstellt. Datenanalyseskripte 
sind damit unverzichtbare Werkzeuge der täglichen wissenschaftlichen Arbeit und 
essenzielle Bestandteile wissenschaftlicher Publikationen. In den folgenden Abschnitten
wollen wir ausgehend von der Diskussion einiger informatischer Grundbegriffe und 
strukturbildener Elemente der imperativen Programmierung die Entwicklung von 
Datenanalyseskripte in der Programmierumgebung [R](https://www.r-project.org/) 
kennenlernen. 

Zur Analyse psychologischer Daten kommen verschiedene digitale Werkzeuge zum Einsatz. 
Besonders verbreitet sind frei verfügbare Programmiersprachen und Plattformen 
wie [R](https://www.r-project.org/), das häufig in der Datenwissenschaft, Statistik 
und Psychologie genutzt wird, und [Python](https://www.python.org/psf/) mit seinem breiten
Einsatzspektrum in der Datenwissenschaft, dem maschinellen Lernen und der künstlichen
Intelligenz. Eher noch ein Nischendasein führt die eigentlich datenanalytisch
optimierte freie Programmiersprache [Julia](https://julialang.org/), die momentan insbesondere
in industriellen Anwendungen noch keine weite Verbreitung gefunden hat. Freie Programmiersprachen
haben den Vorteil, dass sie häufig von einer breiten Community von Anwendern weiter entwickelt
werden und auf diese Weise eine versatile Infrastruktur entwickeln können.

Daneben kommmen aber auch im Bereich der Psychologie weiterhin kommerzielle Programmierumgebungen,
deren Quellcode nicht einsehbar ist, zum Einsatz. Im Bereich der Neurobildgebung 
sowie in ingenieurstechnischen Anwendungen ist zum Beispiel auch heute noch die 
kommerzielle Programmierumgebung [Matlab](https://de.mathworks.com/) beliebt.
Weiterhin werden auch weiterhin einige aus heutiger Sicht eher altmodische Programme 
verwendet, darunter [SPSS](https://www.ibm.com/de-de/analytics/spss-statistics-software), 
das zur Jahrtausendwende vor allem in den Sozialwissenschaften und in der Psychologie 
sehr verbreitet war, [JMP](https://www.jmp.com/de_de/home.html) mit Einsatzschwerpunkten 
in Biologie und Psychologie und [STATA](https://www.stata.com/), das unter 
anderem in der Medizin und und den Wirtschaftswissenschaften populär war.

Die Popularität digitaler Werkzeuge unterliegt einem stetigen Wandel. Eine Möglichkeit, 
die aktuelle Popularität verschiedener Programmiersprachen und -umgebungen zu messen, 
ist die Quantifizierung von Googlesuchanfragen zu Programmiersprachentutorials. 
Einen Überblick über aktuelle Trends bietet der [PYPL Index](https://pypl.github.io/PYPL.html), 
der auf der Analyse solcher Suchanfragen basiert.

Zusammenfassend lässt sich festhalten, dass die Digitalisierung insbesondere 
auch die Wissenschaft nachhaltig prägt. Ein effektives Forschungsdatenmanagement 
stellt dabei eine akute Herausforderung dar, der sich Forschende stellen müssen.
Programmierung entwickelt sich zunehmend zu einem zentralen Handwerkszeug 
wissenschaftlicher Arbeit, und grundlegende Informatikkenntnisse sind in der 
modernen Arbeitswelt unverzichtbar geworden. Dies gilt nicht zuletzt auch für 
Psychotherapeut:innen, etwa im Kontext von Online-Interventionen, digital gestützten 
Behandlungsangeboten oder der Psychotherapieforschung.

