# Kovarianzen {#sec-kovarianzen}
\normalsize

Mit der *Kovarianz* zweier Zufallsvariablen und ihrer standardisierten Form, der
*Korrelation*, führen wir in diesem Kapitel skalare Maßzahlen für die linear-affine
Abhängigkeit von Zufallsvariablen ein.

## Definitionen {#sec-kovarianzen-definitionen}

:::{#def-kovarianz-und-korrelation-zweier-zufallsvariablen}
## Kovarianz und Korrelation zweier Zufallsvariablen
Die *Kovarianz* zweier Zufallsvariablen $\xi_1$ und $\xi_2$ ist definiert als
\begin{equation}
\mathbb{C}(\xi_1,\xi_2) :=
\mathbb{E}\left((\xi_1-\mathbb{E}(\xi_1))(\xi_2-\mathbb{E}(\xi_2))\right).
\end{equation}
Die *Korrelation* zweier Zufallsvariablen $\xi_1$ und $\xi_2$ mit $\mathbb{S}(\xi_1) > 0$
und $\mathbb{S}(\xi_2) > 0$ ist definiert als
\begin{equation}
\rho(\xi_1,\xi_2)
:= \frac{\mathbb{C}(\xi_1,\xi_2)}{\mathbb{S}(\xi_1)\mathbb{S}(\xi_2)}.
\end{equation}
:::

Die Kovarianz einer Zufallsvariable mit sich selbst ist ihre Varianz,
denn es gilt
\begin{equation}
\mathbb{C}(\xi_1,\xi_2)
= \mathbb{E}\left((\xi_1-\mathbb{E}(\xi_1))(\xi_1-\mathbb{E}(\xi_1))\right)
= \mathbb{E}\left((\xi_1-\mathbb{E}(\xi_1))^2\right)
= \mathbb{V}(\xi_1).
\end{equation}
Die Zahl $\rho(\xi_1,\xi_2)$ wird auch *Korrelationskoeffizient von $\xi_1$ und $\xi_2$*
genannt. Wenn $\rho(\xi_1,\xi_2) = 0$ gilt, so werden $\xi_1$ und $\xi_2$ *unkorreliert*
genannt. In @sec-ungleichungen zeigen wir in @thm-korrelationsungleichung, dass
\begin{equation}
-1 \le \rho(\xi_1,\xi_2) \le 1.
\end{equation}
Die Definition der Kovarianz nach @def-kovarianz-und-korrelation-zweier-zufallsvariablen
lässt implizit, dass die in ihr auftauchenden Erwartungswerte unterschiedlicher Natur sind. Dabei geht die
Definition der Kovarianz zunächst einmal davon aus, dass $\xi_1$ und $\xi_2$
die Komponenten eines Zufallsvektors $\xi := (\xi_1,\xi_2)$ mit Ergebnisraum
$\mathcal{X}_1 \times \mathcal{X}_2$, gemeinsamer Verteilung $\mathbb{P}(\xi_1,\xi_2)$
und marginalen Verteilungen $\mathbb{P}(\xi_1)$ und $\mathbb{P}(\xi_2)$ sind. Bei den
Erwartungswerten $\mathbb{E}(\xi_1)$ und $\mathbb{E}(\xi_2)$ handelt es sich um
die Erwartungswerte der Komponenten $\xi_1$ und $\xi_2$ bezüglich dieser
Marginalverteilungen. Die Kovarianz selbst ist dann der Erwartungswert der Funktion
$$
f : \mathcal{X}_1 \times \mathcal{X}_2 \to \mathcal{Z},
(x_1,x_2) \mapsto f(x_1,x_2) := (x_1 - \mathbb{E}(\xi_1))(x_2 - \mathbb{E}(\xi_2))
$$ {#eq-f}
bezüglich der gemeinsamen Verteilung $\mathbb{P}(\xi_1,\xi_2)$. Wir wollen
dies am Beispiel eines diskreten Zufallsvektors verdeutlichen.

:::{#exm-kovarianz-zweier-diskreter-zufallsvariablen}
## Kovarianz zweier diskreter Zufallsvariablen.

Es $\xi := (\xi_1,\xi_2)$ ein diskreter Zufallsvektor mit Ergebnisraum
$\mathcal{X} := \{1,2\} \times \{1,2,3\}$ und der in @tbl-wmf dargestellten
gemeinsamen WMF $p(x_1,x_2)$ und marginalen WMFen $p(x_1)$ und $p(x_2)$.


| $p(x_1,x_2)$  | $x_2 = 1$  | $x_2 = 2$  | $x_2 = 3$  | $p(x_1)$  |
|:-------------:|:----------:|:----------:|:----------:|:---------:|
| $x_1 = 1$     | $0.10$     | $0.05$     | $0.15$     | $0.30$    |
| $x_1 = 2$     | $0.60$     | $0.05$     | $0.05$     | $0.70$    |
| $p(x_2)$      | $0.70$     | $0.10$     | $0.20$     |           |

: Gemeinsame und marginale WMFen des Zufallsvektors $\xi$ {#tbl-wmf}

Mit der Definition der Kovarianz von $\xi_1$ und $\xi_2$ gilt dann unter Beachtung
von @eq-f
\begin{align}
\begin{split}
\mathbb{C}(\xi_1,\xi_2)
& = \mathbb{E}(f(\xi_1,\xi_2)) 																		\\
& = \sum_{x_1 = 1}^2  \sum_{x_2 = 1}^3 f(x_1, x_2)p(x_1,x_2)										\\
& = \sum_{x_1 =  1}^2 \sum_{x_2 =  1}^3 (x_1-\mathbb{E}(\xi_1))(x_2-\mathbb{E}(\xi_2))p(x_1,x_2)	\\
\end{split}
\end{align}
Einsetzen der Werte aus @tbl-wmf ergibt dann zunächst
\begin{equation}
\mathbb{E}(\xi_1) = \sum_{x_1 = 1}^2 x_1 p(x_1) = 1\cdot 0.3 + 2\cdot 0.7 = 1.7
\end{equation}
und
\begin{equation}
\mathbb{E}(\xi_2) = \sum_{x_2=1}^3 x_2 p(x_2) = 1\cdot 0.7 + 2\cdot 0.1 + 3\cdot 0.2 = 1.5.
\end{equation}
und damit dann schließlich
\footnotesize
\begin{align}
\begin{split}
\mathbb{C}(\xi_1,\xi_2)
& = \sum_{x_1 =  1}^2 \sum_{x_2 =  1}^3 \left(x_1-1.7\right)\left(x_2-1.5\right)p(x_1,x_2)						\\
& = \sum_{x_1 =  1}^2 (x_1 -1.7)(1 - 1.5)p(x_1,1) + (x_1 -1.7)(2 - 1.5)p(x_1,2) + (x_1 -1.7)(3 - 1.5)p(x_1,3) 	\\
& =	\quad        (1 - 1.7)(1 - 1.5)p(1,1) + (1 - 1.7)(2 - 1.5)p(1,2) +	(1 - 1.7)(3 - 1.5)p(1,3)				\\
& \quad\quad\,\, (2 - 1.7)(1 - 1.5)p(2,1) + (2 - 1.7)(2 - 1.5)p(2,2) + (2 - 1.7)(3 - 1.5)p(2,3) 				\\
& = (-0.7)\cdot(-0.5)\cdot 0.10+ (-0.7)\cdot 0.5\cdot 0.05 + (-0.7)\cdot 1.5\cdot 0.15 							\\
& \quad\,\,  + 0.3\cdot(-0.5)\cdot 0.60 \,\, + 0.3\cdot 0.5\cdot 0.05 \quad\,\, + 0.3\cdot 1.5\cdot 0.05			\\
& = 0.035- 0.0175- 0.1575 - 0.09+ 0.0075+ 0.0225																\\
& = - 0.2.
\end{split}
\end{align}
\normalsize
Die Kovarianz der Zufallsvariablen $\xi_1$ und $\xi_2$ mit der in obiger Tabelle
festgelegter Verteilung ist also $\mathbb{C}(\xi_1,\xi_2) = -0.2$. Im Gegensatz
zur Varianz kann die Kovarianz also offenbar auch negative Werte annehmen.
:::

\normalsize

## Eigenschaften {#sec-kovarianzen-eigenschaften}

Wir betrachten im Folgenden einige grundlegende Eigenschaften der Kovarianz.

:::{#thm-symmetrie-von-kovarianz-und-korrelation}
## Symmetrie von Kovarianz und Korrelation
$\xi_1$ und $\xi_2$ seien zwei Zufallsvariablen. Dann gelten
\begin{equation}
\mathbb{C}(\xi_1,\xi_2) = \mathbb{C}(\xi_2,\xi_1)
\mbox{ und }
\rho(\xi_1,\xi_2) = \rho(\xi_2,\xi_1).
\end{equation}
:::

:::{.proof}
Mit der Kommutativität der Multiplikation gilt zunächst
\begin{equation}
\mathbb{C}(\xi_1,\xi_2)
= \mathbb{E}\left((\xi_1-\mathbb{E}(\xi_1))(\xi_2-\mathbb{E}(\xi_2))\right)
= \mathbb{E}\left((\xi_2-\mathbb{E}(\xi_2))(\xi_1-\mathbb{E}(\xi_1))\right)
= \mathbb{C}(\xi_2,\xi_1)
\end{equation}
Weiterhin gilt dann
\begin{equation}
\rho(\xi_1,\xi_2)
= \frac{\mathbb{C}(\xi_1,\xi_2)}{\mathbb{S}(\xi_1)\mathbb{S}(\xi_2)}
= \frac{\mathbb{C}(\xi_2,\xi_1)}{\mathbb{S}(\xi_2)\mathbb{S}(\xi_1)}
= \rho(\xi_2,\xi_1)
\end{equation}
:::


Wie das Berechnen von Varianzen wird auch das Berechnen von Kovarianzen manchmal
durch folgendes Theorem erleichtert.

:::{#thm-kovarianzverschiebungssatz}
## Kovarianzverschiebungssatz
$\xi_1$ und $\xi_2$ seien Zufallsvariablen. Dann gilt
\begin{equation}
\mathbb{C}(\xi_1,\xi_2) = \mathbb{E}(\xi_1\xi_2) - \mathbb{E}(\xi_1)\mathbb{E}(\xi_2).
\end{equation}
:::

:::{.proof}
Mit @def-kovarianz-und-korrelation-zweier-zufallsvariablen gilt
\begin{align}
\begin{split}
\mathbb{C}(\xi_1,\xi_2)
& = \mathbb{E}\left((\xi_1-\mathbb{E}(\xi_1))(\xi_2-\mathbb{E}(\xi_2))\right) 															\\
& = \mathbb{E}\left(\xi_1\xi_2-\xi_1\mathbb{E}(\xi_2)-\mathbb{E}(\xi_1)\xi_2+\mathbb{E}(\xi_1)\mathbb{E}(\xi_2)\right) 					\\
& = \mathbb{E}(\xi_1\xi_2)-\mathbb{E}(\xi_1)\mathbb{E}(\xi_2)-\mathbb{E}(\xi_1)\mathbb{E}(\xi_2)+\mathbb{E}(\xi_1)\mathbb{E}(\xi_2)		\\
& = \mathbb{E}(\xi_1\xi_2)-\mathbb{E}(\xi_1)\mathbb{E}(\xi_2).
\end{split}
\end{align}
:::

Natürlich ist @thm-kovarianzverschiebungssatz nur dann wirklich nützlich, wenn
$\mathbb{E}(\xi_1\xi_2)$ leicht zu berechnen sind. Der Varianzverschiebungssatz
nach @thm-varianzverschiebungssatz ergibt sich aus @thm-kovarianzverschiebungssatz
für den Fall $\xi_1 = \xi_2 := \xi$ anhand von
\begin{equation}
\mathbb{V}(\xi)
= \mathbb{C}(\xi,\xi)
= \mathbb{E}(\xi\xi) - \mathbb{E}(\xi)\mathbb{E}(\xi)
= \mathbb{E}(\xi^2) - \mathbb{E}(\xi)\mathbb{E}(\xi).
\end{equation}

Auch in Hinblick auf die Kovarianz  $\mathbb{C}(\xi_1,\xi_2)$ ist man daran interessiert,
wie sich diese unter Anwendung linear-affiner Transformationen auf $\xi_2$ und
$\xi_2$ verhält. Folgendes Resultat zeigt, dass die Kovarianz zweier Zufallsvariablen
von ihrem Maßstab abhängt, die Korrelation dagegen nicht. Dies motiviert den häufigen
Einsatz der Korrelation als allgemeines, zwischen verschiedenen Anwendungsszenarien
vergleichbares Zusammenhangsmaß.

:::{#thm-kovarianz-und-korrelation-bei-linear-affiner-transformation}
## Kovarianz und Korrelation bei linear-affinen Transformation
$\xi_1$ und $\xi_2$ seien Zufallsvariablen mit gemeinsamen Ergebnisraum $\mathcal{X}_1 \times \mathcal{X}_2$
und es seien
\begin{align}
\begin{split}
f_1 : \mathcal{X}_1 \to \mathcal{Z}_1, x_1 \mapsto f(x_1) := ax_1 + b \\
f_2 : \mathcal{X}_2 \to \mathcal{Z}_2, x_2 \mapsto f(x_2) := cx_2 + d
\end{split}
\end{align}
für $a,b,c,d\in \mathbb{R}$ zwei linear-affine Funktionen. Dann gelten
\begin{equation}
\mathbb{C}(f_1(\xi_1), f(\xi_2)) = \mathbb{C}(a\xi_1 + b, c\xi_2 + d) = ac\mathbb{C}(\xi_1,\xi_2).
\end{equation}
und
\begin{equation}
\rho(f_1(\xi_1), f(\xi_2)) = \rho(a\xi_1 + b, c\xi_2 + d) = \rho(\xi_1,\xi_2).
\end{equation}
:::


:::{.proof}
Es gilt zunächst
\begin{align}
\begin{split}
\mathbb{C}(a\xi_1+b,c\xi_2+d)
& = \mathbb{E}((a\xi_1+b-\mathbb{E}(a\xi_1+b))(c\xi_2+d-\mathbb{E}(c\xi_2+d)))    	\\
& = \mathbb{E}((a\xi_1+b-a\mathbb{E}(\xi_1)-b)(c\xi_2+d-c\mathbb{E}(\xi_2)-d))   	\\
& = \mathbb{E}(a(\xi_1-\mathbb{E}(\xi_1))(c(\xi_2 -c\mathbb{E}(\xi_2)))             \\
& = \mathbb{E}(ac((\xi_1-\mathbb{E}(\xi_1))(\xi_2 -c\mathbb{E}(\xi_2))))            \\
&  = ac\mathbb{C}(\xi_1,\xi_2).
\end{split}
\end{align}
Also folgt
\begin{align}
\begin{split}
\rho(a\xi_1 + b, c\xi_2 + d)
& = \frac{\mathbb{C}(a\xi_1+b,c\xi_2+d)}{\sqrt{\mathbb{V}(a\xi_1+b)}\sqrt{\mathbb{V}(c\xi_2+d)}}	\\
& = \frac{ac\mathbb{C}(\xi_1,\xi_2)}{\sqrt{a^2\mathbb{V}(\xi_1)}\sqrt{c^2\mathbb{V}(\xi_2)}}        \\
& = \frac{ac\mathbb{C}(\xi_1,\xi_2)}{a\mathbb{S}(\xi_1)c\mathbb{S}(\xi_2)}                          \\
& = \frac{\mathbb{C}(\xi_1,\xi_2)}{\mathbb{S}(\xi_1)\mathbb{S}(\xi_2)}                              \\
& = \rho(\xi_1,\xi_2).
\end{split}
\end{align}

:::

Mithilfe des Begriffes des Kovarianz ist es möglich, weitgreifenderer Aussagen
über die Varianzen von Summen und Differenzen von Zufallsvariablen zu treffen
als es in @sec-varianzen der Fall war, wo lediglich die Varianzen von Summen
unabhängiger Zufallsvariablen betrachtetet wurden. Mit dem folgenden Theorem untersuchen wir
zunächst den sehr allgemeinen Fall der Kovarianz zweier Zufallsvariablen, die sich
als Linearkombinationen von $n$ Zufallsvariablen $\xi_1,...,\xi_n$ und $m$ Zufallsvariablen
$\zeta_1,...,\zeta_m$ unter Addition reeller Konstanten ergeben. Hieraus ergeben
sich dann eine Reihe von in der Anwendung, insbesondere in der Klassischen Testtheorie,
wichtiger Spezialfälle.

:::{#thm-kovarianz-von-linearkombinationen-von-zufallsvariablen}
## Kovarianz von Linearkombinationen von Zufallsvariablen
Gegeben seien $n$ Zufallsvariablen  $\xi_1,...,\xi_n$  und $n+1$ reelle Konstanten
$a_0,a_1,...,a_n$ sowie $m$ Zufallsvariablen $\zeta_1,...,\zeta_m$ und $m + 1$ reelle
Konstanten $b_0,b_1,...,b_m$. Dann gilt
\begin{equation}
\mathbb{C}\left(a_0 + \sum_{i=1}^n a_i \xi_i, b_0 + \sum_{j=1}^m b_j \zeta_j\right)
= \sum_{i=1}^n \sum_{j=1}^m a_ib_j\mathbb{C}(\xi_i, \zeta_j).
\end{equation}
:::

:::{.proof}
\begin{align*}
\begin{split}
& \mathbb{C}\left(a_0 + \sum_{i=1}^n a_i \xi_i, b_0 + \sum_{j=1}^m b_j \zeta_j \right) \\
& = \mathbb{E}\left(
	\left(a_0 + \sum_{i=1}^n a_i \xi_i  - \mathbb{E}\left(a_0 + \sum_{i=1}^n a_i \xi_i\right)\right)
	\left(b_0 + \sum_{j=1}^m b_j \zeta_j - \mathbb{E}\left(b_0 + \sum_{j=1}^m b_j \zeta_j \right)\right)
	\right)
\\
& = \mathbb{E}\left(
	\left(a_0 + \sum_{i=1}^n a_i \xi_i  - a_0 - \mathbb{E}\left(\sum_{i=1}^n a_i \xi_i\right)\right)
	\left(b_0 + \sum_{j=1}^m b_j \zeta_j - b_0 - \mathbb{E}\left(\sum_{j=1}^m b_j \zeta_j \right)\right)
	\right)
\\
& = \mathbb{E}\left(
	\left(\sum_{i=1}^n a_i \xi_i  - \sum_{i=1}^n a_i \mathbb{E}(\xi_i) \right)
	\left(\sum_{j=1}^m b_j \zeta_j - \sum_{j=1}^m b_j \mathbb{E}(\zeta_j)\right)
	\right)
\\
& = \mathbb{E}
	\left(
	\sum_{i=1}^n a_i \xi_i\sum_{j=1}^m b_j \zeta_j  - \sum_{i=1}^n a_i \xi_i \sum_{j=1}^m b_j \mathbb{E}(\zeta_j)
	- \sum_{i=1}^n a_i \mathbb{E}(\xi_i)\sum_{j=1}^m b_j \zeta_j +  \sum_{i=1}^n a_i \mathbb{E}(\xi_i) \sum_{j=1}^m b_j \mathbb{E}(\zeta_j)
	\right)
\\
& = \mathbb{E}\left(\sum_{i=1}^n a_i \xi_i\sum_{j=1}^m b_j \zeta_j\right)
    - \mathbb{E}\left(\sum_{i=1}^n a_i \xi_i \sum_{j=1}^m b_j \mathbb{E}(\zeta_j)\right)
	- \mathbb{E}\left(\sum_{i=1}^n a_i \mathbb{E}(\xi_i)\sum_{j=1}^m b_j \zeta_j\right)
	+ \mathbb{E}\left(\sum_{i=1}^n a_i \mathbb{E}(\xi_i) \sum_{j=1}^m b_j \mathbb{E}(\zeta_j)\right)
\\
& =  \sum_{i=1}^n \sum_{j=1}^m a_ib_j \mathbb{E}(\xi_i\zeta_j)
    - 2\sum_{i=1}^n \sum_{j=1}^m a_i  b_j \mathbb{E}(\xi_i)\mathbb{E}(\zeta_j)
	+ \sum_{i=1}^n\sum_{j=1}^m a_ib_j \mathbb{E}(\xi_i) \mathbb{E}(\zeta_j)
\\
& =  \sum_{i=1}^n \sum_{j=1}^m a_ib_j \left(\mathbb{E}(\xi_i\zeta_j) -  2 \mathbb{E}(\xi_i)\mathbb{E}(\zeta_j) +\mathbb{E}(\xi_i)\mathbb{E}(\zeta_j)\right)
\\
& =  \sum_{i=1}^n \sum_{j=1}^m a_ib_j
     \mathbb{E}\left((\xi_i -  \mathbb{E}(\xi_i))(\zeta_j - \mathbb{E}(\zeta_j))\right)
\\
& = \sum_{i=1}^n \sum_{j=1}^m a_ib_j\mathbb{C}(\xi_i, \zeta_j)
\end{split}
\end{align*}
:::

Mit folgenden Theorem betrachten wir nun einen ersten Spezialfall von
@thm-kovarianz-von-linearkombinationen-von-zufallsvariablen.

:::{#thm-kovarianz-bei-paarweiser-addition-von-zufallsvariablen}
## Kovarianz bei paarweiser Addition von Zufallsvariablen
$\xi_1,\xi_2,\zeta_1,\zeta_2$ seien vier Zufallsvariablen. Dann gilt
\begin{equation}
\mathbb{C}(\xi_1 + \xi_2, \zeta_1 + \zeta_2)
= \mathbb{C}(\xi_1,\zeta_1) + \mathbb{C}(\xi_1,\zeta_2) + \mathbb{C}(\xi_2,\zeta_1) + \mathbb{C}(\xi_2,\zeta_2).
\end{equation}
:::

:::{.proof}
Es seien $n := 2, m := 2, a_0 = b_0 := 0$ und $a_i = b_i := 1$ für $i = 1,2$.
Dann gilt mit @thm-kovarianz-von-linearkombinationen-von-zufallsvariablen
\begin{align}
\begin{split}
\mathbb{C}\left(\xi_1 +\xi_2, \zeta_1 + \zeta_2 \right)
& = \mathbb{C}\left(a_0 + \sum_{i=1}^2 a_i \xi_i, b_0 + \sum_{j=1}^2 b_j \zeta_j \right) \\
& = \sum_{i=1}^2 \sum_{j=1}^2 a_i b_j\mathbb{C}\left(\xi_i, \zeta_j \right) \\
& = \sum_{i=1}^2 \sum_{j=1}^2 \mathbb{C}\left(\xi_i, \zeta_j \right) \\
& = \mathbb{C}\left(\xi_1, \zeta_1\right) + \mathbb{C}\left(\xi_1, \zeta_2 \right) + \mathbb{C}\left(\xi_2, \zeta_1\right) + \mathbb{C}\left(\xi_2, \zeta_2 \right).
\end{split}
\end{align}
:::

Folgendes Theorem besagt nun, wie man im Allgemeinen die Varianz einer Linearkombinationen
von Zufallsvariablen unter Addition einer Konstante bestimmt werden kann.

:::{#thm-varianz-einer-linearkombination-von-zufallsvariablen}
## Varianz einer Linearkombination von Zufallsvariablen
Gegeben seien $n$ Zufallsvariablen $\xi_1,...,\xi_n$ und $n+1$ reelle Konstanten
$a_0,a_1,...,a_n$.
Dann gilt
\begin{equation}
\mathbb{V}\left(a_0 + \sum_{i=1}^n a_i \xi_i \right)
= \sum_{i=1}^n a_i^2 \mathbb{V}(\xi_i) + 2 \sum_{i=1}^{n-1}\sum_{j=i+1}^n a_ia_j\mathbb{C}(\xi_i,\xi_j).
\end{equation}
:::

:::{.proof}
Mit $\mathbb{V}(\xi) = \mathbb{C}(\xi,\xi)$ und @thm-kovarianz-von-linearkombinationen-von-zufallsvariablen
gilt zunächst
\begin{align}
\begin{split}
\mathbb{V}\left(a_0 + \sum_{i=1}^n a_i\xi_i\right)
& = \mathbb{C}\left(a_0 + \sum_{i=1}^n a_i\xi_i, a_0 + \sum_{i=1}^n a_i\xi_i\right) 																				\\
& = \mathbb{C}\left(a_0 + \sum_{i=1}^n a_i\xi_i, a_0 + \sum_{j=1}^n a_j \xi_j \right)																					\\
& = \sum_{i=1}^n \sum_{j=1}^n a_ia_j \mathbb{C}(\xi_i,\xi_j) 																										\\
& = \sum_{i=1}^n\sum_{\substack{j=1 \\ j = i}}^n a_ia_j \mathbb{C}(\xi_i,\xi_j)  + \sum_{i=1}^n \sum_{\substack{j=1 \\ j \neq i}}^n a_ia_j \mathbb{C}(\xi_i,\xi_j) 	\\
& = \sum_{i=1}^n a_i a_i\mathbb{C}(\xi_i,\xi_i)  + \sum_{i=1}^n \sum_{\substack{j=1 \\ j \neq i}}^n a_ia_j \mathbb{C}(\xi_i,\xi_j) 									\\
& = \sum_{i=1}^n a_i^2\mathbb{V}(\xi_i)  + \sum_{i=1}^n \sum_{\substack{j=1 \\ j \neq i}}^n a_ia_j \mathbb{C}(\xi_i,\xi_j)											\\
& = \sum_{i=1}^n a_i^2\mathbb{V}(\xi_i)  + 2 \sum_{i=1}^{n-1}\sum_{j=i+1}^na_ia_j \mathbb{C}(\xi_i,\xi_j),
\end{split}
\end{align}
Dabei wurde in der vierten Gleichung die Doppelsumme in solche Terme aufgespalten
für die $i = j$ und für die $i \neq j$ und in siebten Gleichung ausgenutzt, dass
\begin{equation}
a_ia_j\mathbb{C}(\xi_i,\xi_j) = a_ja_i\mathbb{C}(\xi_j,\xi_i).
\end{equation}
Wir verdeutlichen die daraus folgende Identität
\begin{equation}
\sum_{i=1}^n \sum_{\substack{j=1 \\ j \neq i}}^n a_ia_j \mathbb{C}(\xi_i,\xi_j)
= 2 \sum_{i=1}^{n-1}\sum_{j=i+1}^na_ia_j \mathbb{C}(\xi_i,\xi_j),
\end{equation}
am Beispiel $n = 3$ untenstehend. Analog mag man sich vorstellen, über alle
Elemente außer der Diagonalelemente der $i = 1,...,n$ Zeilen und $j = 1,...,n$
Spalten einer symmetrischen Matrix mit Einträgen $a_ia_j\mathbb{C}(\xi_i,\xi_j)$
zu summieren. Die linke Seite oberer Gleichung entspricht dann dem zeilenweisen
Vorgehen der Summationsbildung für alle Spalteneinträge außer dem, der in der
Spalte der jeweils betrachteten Zeile steht, d.h. dem Diagonaleintrag. Die rechte
Seite der obigen Gleichung entspricht dann dem Vorgehen, die Symmetrie der Matrix
auszunutzen, also die Tatsache zu berücksichtigen, dass die Einträge der Matrix rechts
oberhalb und links unterhalb der Diagonalen identisch sind, so dass es genügt,
die Einträge der oberen linken Hälfte aufzuaddieren und zu verdoppeln. Dabei werden
für jede Zeile $i = 1,...,n$ nur gerade die Spalten $j = i+1,...,n$ betrachtet,
die rechts von der Diagonale stehen und ihre Einträge aufsummiert. In der letzten
Zeile steht dabei nur ein Diagonalelement, das nicht zur Summe gehört, weshalb
der Index der äußeren Summe nur bis $n-1$ läuft. Konkret ergibt sich für $n := 3$
\begin{align}
\begin{split}
& \sum_{i=1}^3\sum_{\substack{j=1 \\ j \neq i}}^3 a_ia_j \mathbb{C}(\xi_i,\xi_j) \\
& = \sum_{\substack{j=1 \\ j \neq 1}}^3 a_1a_j\mathbb{C}(\xi_1,\xi_j) +
    \sum_{\substack{j=1 \\ j \neq 2}}^3 a_2a_j\mathbb{C}(\xi_2,\xi_j) +
	\sum_{\substack{j=1 \\ j \neq 3}}^3 a_3a_j\mathbb{C}(\xi_3,\xi_j)\\
& = a_1a_2\mathbb{C}(\xi_1,\xi_2) + a_1a_3\mathbb{C}(\xi_1,\xi_3) + a_2a_1\mathbb{C}(\xi_2,\xi_1) + a_2a_3\mathbb{C}(\xi_2,\xi_3)  + a_3a_1\mathbb{C}(\xi_3,\xi_1) + a_3a_2\mathbb{C}(\xi_3,\xi_2)\\
& = a_1a_2\mathbb{C}(\xi_1,\xi_2) + a_2a_1\mathbb{C}(\xi_2,\xi_1) + a_1a_3\mathbb{C}(\xi_1,\xi_3) + a_3a_1\mathbb{C}(\xi_3,\xi_1) + a_2a_3\mathbb{C}(\xi_2,\xi_3) + a_3a_2\mathbb{C}(\xi_3,\xi_2)\\
& = 2a_1a_2\mathbb{C}(\xi_1,\xi_2) + 2a_1a_3\mathbb{C}(\xi_1,\xi_3) + 2a_2a_3\mathbb{C}(\xi_2,\xi_3)\\
& = 2\left(a_1a_2\mathbb{C}(\xi_1,\xi_2) + a_1a_3\mathbb{C}(\xi_1,\xi_3) + a_2a_3\mathbb{C}(\xi_2,\xi_3)\right)\\
& = 2\left(\sum_{j=2}^3 a_1a_j\mathbb{C}(\xi_1,\xi_j) + \sum_{j=3}^3 a_2a_j\mathbb{C}(\xi_2,\xi_j)\right)\\
& = 2\left(\sum_{j=1+1}^3 a_1a_j\mathbb{C}(\xi_1,\xi_j) + \sum_{j=2+1}^3 a_2a_j\mathbb{C}(\xi_2,\xi_j)\right)\\
& = 2\sum_{i=1}^{2}\sum_{j=i+1}^3 a_ia_j\mathbb{C}(\xi_i,\xi_j).
\end{split}
\end{align}
:::

:::{#thm-varianzen-spezieller-linearkombinationen-von-zufallsvariablen}
## Varianzen spezieller Linearkombinationen von Zufallsvariablen
\vspace{1mm}

\noindent (1) (Varianz bei Addition zweier Zufallsvariablen). Gegeben seien zwei Zufallsvariablen $\xi$ und $\zeta$. Dann gilt
\begin{equation}
\mathbb{V}(\xi + \zeta)
= \mathbb{V}(\xi) + \mathbb{V}(\zeta) + 2\mathbb{C}(\xi,\zeta)
\end{equation}
\noindent (2) (Varianz bei Subtraktion zweier Zufallsvariablen). Gegeben seien  zwei Zufallsvariablen $\xi$ und $\zeta$. Dann gilt
\begin{equation}
\mathbb{V}(\xi - \zeta)
= \mathbb{V}(\xi) + \mathbb{V}(\zeta) - 2\mathbb{C}(\xi,\zeta)
\end{equation}
:::

:::{.proof}

Es seien $n := 2$, $\xi_1 := \xi$, $\xi_2 := \zeta$, $a_0 := 0$, $a_1 := 1$ und $a_2 := 1$. Dann gilt mit @thm-varianz-einer-linearkombination-von-zufallsvariablen
\begin{align}
\begin{split}
\mathbb{V}(\xi + \zeta)
& = \mathbb{V}(a_0 + a_1\xi_1 + a_2\xi_2) 																					\\
& = \mathbb{V}\left(a_0 + \sum_{i=1}^2 a_i \xi_i \right) 																	\\
& = \sum_{i=1}^2 a_i^2 \mathbb{V}(\xi_i) + 2 \sum_{i=1}^{2-1}\sum_{j = i+ 1}^2 a_i a_j\mathbb{C}(\xi_i,\xi_j)				\\
& = \sum_{i=1}^2 a_i^2 \mathbb{V}(\xi_i) + 2 \sum_{i=1}^{1}\sum_{j = i + 1}^2 a_ia_j \mathbb{C}(\xi_i,\xi_j)				\\
& = \sum_{i=1}^2 a_i^2 \mathbb{V}(\xi_i) + 2 \sum_{j = 1 + 1}^2 a_ia_j \mathbb{C}(\xi_1,\xi_j)								\\
& = \sum_{i=1}^2 a_i^2 \mathbb{V}(\xi_i) + 2 \sum_{j = 2}^2 a_1a_j\mathbb{C}(\xi_1,\xi_j)									\\
& = a_1^2\mathbb{V}(\xi_1) + a_2^2\mathbb{V}(\xi_2) + 2 a_1a_2\mathbb{C}(\xi_1,\xi_2)										\\
& = 1^2 \cdot \mathbb{V}(\xi)   +  1^2 \cdot \mathbb{V}(\zeta) + 2 \cdot  1 \cdot 1 \cdot  \mathbb{C}(\xi,\zeta) 			\\
& = \mathbb{V}(\xi) + \mathbb{V}(\zeta) + 2 \mathbb{C}(\xi,\zeta).															\\
\end{split}
\end{align}
Es seien nun $n := 2$, $\xi_1 := \xi$, $\xi_2 := \zeta$, $a_0 := 0$, $a_1 := 1$ und $a_2 := -1$. Dann gilt mit dem @thm-varianz-einer-linearkombination-von-zufallsvariablen
\begin{align}
\begin{split}
\mathbb{V}(\xi - \zeta)
& = \mathbb{V}(a_0 + a_1\xi_1 + a_2\xi_2) 																					\\
& = \mathbb{V}\left(a_0 + \sum_{i=1}^2 a_i \xi_i \right) 																	\\
& = \sum_{i=1}^2 a_i^2 \mathbb{V}(\xi_i) + 2 \sum_{i=1}^{2-1}\sum_{j = i+ 1}^2 a_i a_j\mathbb{C}(\xi_i,\xi_j)				\\
& = \sum_{i=1}^2 a_i^2 \mathbb{V}(\xi_i) + 2 \sum_{i=1}^{1}\sum_{j = i + 1}^2 a_ia_j \mathbb{C}(\xi_i,\xi_j)				\\
& = \sum_{i=1}^2 a_i^2 \mathbb{V}(\xi_i) + 2 \sum_{j = 1 + 1}^2 a_ia_j \mathbb{C}(\xi_1,\xi_j)								\\
& = \sum_{i=1}^2 a_i^2 \mathbb{V}(\xi_i) + 2 \sum_{j = 2}^2 a_1a_j\mathbb{C}(\xi_1,\xi_j)									\\
& = a_1^2\mathbb{V}(\xi_1) + a_2^2\mathbb{V}(\xi_2) + 2 a_1a_2\mathbb{C}(\xi_1,\xi_2)										\\
& = 1^2\cdot \mathbb{V}(\xi)   +  (-1)^2 \cdot \mathbb{V}(\zeta) + 2 \cdot  1 \cdot (-1)\cdot  \mathbb{C}(\xi,\zeta) \\
& = \mathbb{V}(\xi) + \mathbb{V}(\zeta) - 2 \mathbb{C}(\xi,\zeta).																\\
\end{split}
\end{align}
Alternativ gilt ohne Rückgriff auf @thm-varianz-einer-linearkombination-von-zufallsvariablen
und mit @thm-erwartungswert-bei-linear-affiner-kombination-von-zufallsvariablen, dass
\begin{align}
\begin{split}
& \mathbb{V}(a\xi + b\zeta + c)																	\\
& = \mathbb{E}\left((a\xi + b\zeta + c - a\mathbb{E}(\xi) - b\mathbb{E}(\zeta) - c)^2\right) 	\\
& = \mathbb{E}\left((a(\xi  - \mathbb{E}(\xi)) + b(\zeta  - \mathbb{E}(\zeta)))^2\right) 		\\
& = \mathbb{E}\left(a^2(\xi - \mathbb{E}(\xi))^2
				  + 2ab(\xi - \mathbb{E}(\xi))(\zeta - \mathbb{E}(\zeta)))
				  + b^2(\zeta - \mathbb{E}(\zeta))^2\right) 									\\
& = a^2\mathbb{E}\left((\xi - \mathbb{E}(\xi))^2\right) +
    b^2\mathbb{E}\left((\zeta - \mathbb{E}(\zeta))^2\right) +
	2ab\mathbb{E}\left((\xi - \mathbb{E}(\xi))(\zeta - \mathbb{E}(\zeta))\right) 				\\
& = a^2\mathbb{V}(\xi)+ b^2\mathbb{V}(\zeta) + 2ab\mathbb{C}(\xi,\zeta).
\end{split}
\end{align}
Die Spezialfälle folgen dann direkt mit $a := b := 1$ und $a := 1, b := -1$, respektive.
:::

Schließlich wollen wir mit Theorem 13.12 einen ersten Eindruck zum Zusammenhang
von Kovarianz und Korrelation mit dem Begriff der Unabhängigkeit von Zufallsvariablen
erlangen. Es zeigt sich, dass Kovarianz und Korrelation lediglich für bestimmte
Formen der Abhängigkeit von Zufallsvariablen sensitiv sind und insbesondere,
dass von einer Kovarianz von null nicht auf die Unabhängigkeit der Zufallsvariablen
geschlossen werden kann. Anderseits impliziert die Unabhängigkeit zweier Zufallsvariablen
immer, dass ihre Kovarianz null und sie damit unkorreliert sind. Abhängigkeit und
Unabhängigkeit von Zufallsvariablen sind also sehr viel allgemeinere Begrifflichkeiten
zur Beschreibung des Zusammenhangs von Zufallsvariablen als Kovarianz und Korrelation.

:::{#thm-korrelation-und-unabhängigkeit-von-zufallsvariablen}
## Korrelation und Unabhängigkeit von Zufallsvariablen

$\xi_1$ und $\xi_2$ seien zwei Zufallsvariablen. Wenn $\xi_1$ und $\xi_2$
unabhängig sind, dann ist $\mathbb{C}(\xi_1,\xi_2) = 0$ und $\xi_1$ und $\xi_2$
sind folglich unkorreliert. Ist dagegen $\mathbb{C}(\xi_1,\xi_2) = 0$ und sind
$\xi_1$ und $\xi_2$ somit unkorreliert, dann sind $\xi_1$ und $\xi_2$ nicht
notwendigerweise unabhängig.

:::

:::{.proof}

Wir zeigen in einem ersten Schritt, dass aus der Unabhängigkeit von $\xi_1$ und $\xi_2$
$\mathbb{C}(\xi_1,\xi_2) = 0$ folgt. Wir zeigen dann durch Angabe eines Beispiels,
dass die Kovarianz von abhängigen Zufallsvariablen $\xi_1$ und $\xi_2$ durchaus
null sein kann.

\noindent (1) Wir zeigen, dass aus der Unabhängigkeit von $\xi_1$ und $\xi_2$
$\mathbb{C}(\xi_1,\xi_2) = 0$ folgt. Hierzu halten wir als erstes fest, dass für
unabhängige Zufallsvariablen gilt, dass
\begin{equation}
\mathbb{E}(\xi_1\xi_2) = \mathbb{E}(\xi_1)\mathbb{E}(\xi_2).
\end{equation}
Mit dem Kovarianzverschiebungssatz folgt dann
\begin{equation}
\mathbb{C}(\xi_1,\xi_2)
= \mathbb{E}(\xi_1\xi_2) - \mathbb{E}(\xi_1)\mathbb{E}(\xi_2)
= \mathbb{E}(\xi_1)\mathbb{E}(\xi_2) - \mathbb{E}(\xi_1)\mathbb{E}(\xi_2)
= 0.
\end{equation}
Mit der Definition des Korrelationskoeffizienten folgt dann, dass $\rho(\xi_1,\xi_2) = 0$
ist und $\xi_1$ und $\xi_2$ somit unkorreliert sind.

\noindent (2) Wir zeigen nun durch Angabe eines Beispiels, dass die Kovarianz
von abhängigen Zufallsvariablen $\xi_1$ und $\xi_2$ null sein kann. Zu diesem Zweck
betrachten wir den Fall zweier diskreter Zufallsvariablen $\xi_1$ und $\xi_2$ mit
Ergebnisräumen $\mathcal{X}_1 = \{-1,0,1\}$ und $\mathcal{X}_2 = \{0,1\}$, marginaler WMF von
$\xi_1$ gegeben durch $p(x_1) := \frac{1}{3}$ für alle  $x_1 \in \mathcal{X}_1$ und der Definition von
\begin{equation}
\xi_2 := \xi_1^2.
\end{equation}
Die Definition von $\xi_2$ impliziert dann die in @tbl-bedingte-wmf-beweis gezeigte bedingte WMF.

| $p(x_2|x_1)$  | $x_1 = -1$ | $x_1 = 0$  | $x_1 = 1$  |
|:-------------:|:----------:|:----------:|:----------:|
| $x_2 = 0$     | $0$        | $1$     	  | $0$        |
| $x_2 = 1$     | $1$        | $0$   	  | $1$    	   |

: Bedingte WMF zum Beweis von @thm-korrelation-und-unabhängigkeit-von-zufallsvariablen {#tbl-bedingte-wmf-beweis}

Die marginale WMF $p(x_1)$ und die bedingte WMF $p(x_2|x_1)$ implizieren dann die
in @tbl-gemeinsame-wmf-beweis gezeigte gemeinsame  WMF.


| $p(x_1,x_2)$	| $x_1 = -1$ | $x_1 = 0$  |	$x_1 = 1$  | $p(x_2)$	|
|:-------------:|:----------:|:----------:|:----------:|:----------:|
| $x_2 = 0$		| $0$		 | $1/3$	  |	$0$		   | $1/3$		|
| $x_2 = 1$		| $1/3$		 | $0$	 	  |	$1/3$	   | $2/3$	    |
| $p(x_1)$ 		| $1/3$	 	 | $1/3$	  | $1/3$      |            |

: Gemeinsame WMF zum Beweis von @thm-korrelation-und-unabhängigkeit-von-zufallsvariablen {#tbl-gemeinsame-wmf-beweis}

Anhand von @tbl-gemeinsame-wmf-beweis gilt also zum Beispiel
\begin{equation}
p(-1,0) = 0 \neq \frac{1}{9} = \frac{1}{3} \cdot \frac{1}{3} = p(-1)p(0).
\end{equation}
Die gemeinsame WMF von $\xi_1$ und $\xi_2$ faktorisiert also nicht und
$\xi_1$ und $\xi_2$ sind damit nicht unabhängig. Allerdings folgt mit
\begin{equation}
\mathbb{E}(\xi_1)
= \sum_{x_1 \in \mathcal{X}_1} x_1 p(x_1)
= -1 \cdot \frac{1}{3} + 0\cdot \frac{1}{3} + 1\cdot\frac{1}{3}
= 0
\end{equation}
und
\begin{equation}
\mathbb{E}(\xi_1\xi_2)
= \mathbb{E}(\xi_1\xi_1^2)
= \mathbb{E}(\xi_1^3)
= \sum_{x_1 \in \mathcal{X}_1} x_1^3 p(x_1)
= -1^3 \cdot \frac{1}{3} + 0^3\cdot \frac{1}{3} + 1^3\cdot\frac{1}{3}
= 0,
\end{equation}
sowie dem Kovarianzverschiebungssatz, dass
\begin{equation}
\mathbb{C}(\xi_1,\xi_2)
= \mathbb{E}(\xi_1\xi_2) - \mathbb{E}(\xi_1)\mathbb{E}(\xi_2)
= \mathbb{E}(\xi_1^3) - \mathbb{E}(\xi_1)\mathbb{E}(\xi_2)
= 0 - 0\cdot \mathbb{E}(\xi_2)
= 0.
\end{equation}
Die Kovarianz von $\xi_1$ und $\xi_2$ ist also null und $\xi_1$ und $\xi_2$
damit unkorreliert, obwohl $\xi_1$ und $\xi_2$ nicht unabhängig sind.

:::

## Bedingte Kovarianz {#sec-bedingte-kovarianz}

Wie den Erwartungswert und die Varianz kann man auch die Kovarianz in einer
bedingten gemeinsamen Verteilung zweier Zufallsvariablen betrachten. Dies führt
auf den Begriff der *bedingten Kovarianz*.

:::{#def-bedingte-kovarianz}
## Bedingte Kovarianz
Gegeben sei ein Zufallsvektor $\xi := (\xi_1,\xi_2,\xi_3)$ mit Ergebnisraum
$\mathcal{X} := \mathcal{X}_1 \times \mathcal{X}_2\times \mathcal{X}_3$ und WMF oder WDF $p(x_1,x_2,x_3)$
und bedingter WMF oder WDF $p(x_1,x_2|x_3)$ für alle $x_3 \in \mathcal{X}_3$. Dann ist die
bedingte Kovarianz von $\xi_1$ und $\xi_2$ gegeben $\xi_3 = x_3$ definiert als
\begin{equation}
\mathbb{C}(\xi_1,\xi_2|\xi_3 = x_3)
= \mathbb{E}
  \left(
  \left(\xi_1 - \mathbb{E}\left(\xi_1|\xi_3 = x_3\right)\right)
  \left(\xi_2 - \mathbb{E}\left(\xi_2|\xi_3 = x_3\right)\right)|\xi_3 = x_3
  \right)
\end{equation}
:::

Die bedingte Kovarianz ist also im Sinne des bedingten Erwartungswerts des
Zufallsvektors $(\xi_1,\xi_2)$ definiert und ist, wie der bedingte Erwartungswert
und die bedingte Varianz im Allgemeinen eine Zufallsvariable dar. Schließlich halten
wir fest, dass auch für die bedingte Kovarianz der Kovarianzverschiebungssatz gilt.

:::{#thm-bedingte-kovarianzverschiebungssatz}
## Verschiebungssatz der bedingten Kovarianz
Gegeben sei ein Zufallsvektor $\xi := (\xi_1,\xi_2,\xi_3)$. Dann gilt
\begin{equation}
\mathbb{C}(\xi_1, \xi_2|\xi_3)
= \mathbb{E}\left(\xi_1\xi_2|\xi_3\right) - \mathbb{E}\left(\xi_1|\xi_3\right)\mathbb{E}\left(\xi_2|\xi_3\right).
\end{equation}
:::

:::{.proof}
Ein Beweis ergibt sich durch die Ersetzung der entsprechenden Erwartungswerte
im Beweis von @thm-kovarianzverschiebungssatz durch die entsprechenden bedingten
Erwartungswerte.
:::

## Kovarianzmatrizen {#sec-kovarianzmatrizen}

Das multivariate Analogon der Varianz einer Zufallsvariable ist die *Kovarianzmatrix
eines Zufallsvektors*. Diese enkodiert neben den Varianzen der Komponenten des Zufallsvektors
auch ihre paarweisen Kovarianzen und ist wie folgt definiert.

:::{#def-kovarianzmatrix-eines-zufallsvektors}
## Kovarianzmatrix eines Zufallsvektors
$\xi$ sei ein $n$-dimensionaler Zufallsvektor. Dann ist die *Kovarianzmatrix* von
$\xi$ definiert als die $n \times n$ Matrix
\begin{equation}
\mathbb{C}(\xi) := \mathbb{E}\left((\xi - \mathbb{E}(\xi))(\xi - \mathbb{E}(\xi))^T \right).
\end{equation}
:::

Die Kovarianzmatrix ist in @def-kovarianzmatrix-eines-zufallsvektors
formal analog zur Kovarianz zweier Zufallsvariablen definiert. Eine direkte Rückführung
des Begriffs der Kovarianzmatrix eines Zufallsvektors auf den Begriff aus dem
univariaten Kontext bekannten Begriff der Kovarianz zweier Zufallsvariablen
erlaubt folgendesTheorem.

:::{#thm-eigenschaften-der-kovarianzmatrix}
## Eigenschaften der Kovarianzmatrix
$\xi$ sei ein $m$-dimensionaler Zufallsvektor und $\mathbb{C}(\xi)$ sei seine Kovarianzmatrix.
Dann gelten

\noindent (1) (Elemente) Die Elemente von $\mathbb{C}(\xi)$ sind die Kovarianzen der Komponenten von $\xi$,
\begin{equation}
\mathbb{C}(\xi) = \left(\mathbb{C}(\xi_i,\xi_j)\right)_{1 \le i,j \le m}.
\end{equation}

\noindent (2) (Kovarianzmatrixverschiebungssatz) Es gilt
\begin{equation}
\mathbb{C}(\xi) = \mathbb{E}\left(\xi\xi^T\right) -  \mathbb{E}(\xi)\mathbb{E}(\xi)^T.
\end{equation}
\noindent (3) (Linear-affine Transformation) Für $A \in \mathbb{R}^{n \times m}$ und $b \in \mathbb{R}^n$ gilt
\begin{equation}
\mathbb{C}(A\xi +b) = A\mathbb{C}(\xi)A^T.
\end{equation}
\noindent (4) (Matrixeigenschaften) $\mathbb{C}(\xi)$ ist symmetrisch und positiv-semidefinit.
:::

:::{.proof}

\noindent (1) Es gilt
\begin{align}
\begin{split}
\mathbb{C}(\xi)
& := \mathbb{E}\left((\xi - \mathbb{E}(\xi))(\xi - \mathbb{E}(\xi))^T \right) \\
& =
\mathbb{E}
\left(
\left(
\begin{pmatrix}
\xi_1 \\
\vdots \\
\xi_n
\end{pmatrix}
-
\begin{pmatrix}
\mathbb{E}(\xi_1) \\
\vdots \\
\mathbb{E}(\xi_n)
\end{pmatrix}
\right)
\left(
\begin{pmatrix}
\xi_1 \\
\vdots \\
\xi_n
\end{pmatrix}
-
\begin{pmatrix}
\mathbb{E}(\xi_1) \\
\vdots \\
\mathbb{E}(\xi_n)
\end{pmatrix}
\right)^T
\right)
\\
& =
\mathbb{E}
\left(
\begin{pmatrix}
\xi_1 - \mathbb{E}(\xi_1) \\
\vdots \\
\xi_n - \mathbb{E}(\xi_n)
\end{pmatrix}
\begin{pmatrix}
\xi_1 - \mathbb{E}(\xi_1)\\
\vdots \\
\xi_n - \mathbb{E}(\xi_n)
\end{pmatrix}^T
\right)
\\
& =
\mathbb{E}
\left(
\begin{pmatrix}
\xi_1 - \mathbb{E}(\xi_1) \\
\vdots \\
\xi_n - \mathbb{E}(\xi_n)
\end{pmatrix}
\begin{pmatrix}
\xi_1 - \mathbb{E}(\xi_1)
& \dots
& \xi_n - \mathbb{E}(\xi_n)
\end{pmatrix}
\right) \\
& =
\mathbb{E}
\begin{pmatrix}
  (\xi_1 - \mathbb{E}(\xi_1))(\xi_1 - \mathbb{E}(\xi_1))
& \dots
& (\xi_1 - \mathbb{E}(\xi_1))(\xi_n - \mathbb{E}(\xi_n)
\\
\vdots
& \ddots
& \vdots
\\
  (\xi_n - \mathbb{E}(\xi_n))(\xi_1 - \mathbb{E}(\xi_1))
& \dots
& (\xi_n - \mathbb{E}(\xi_n))(\xi_n - \mathbb{E}(\xi_n))
\\
\end{pmatrix}
\\
& =
\left(\mathbb{E}\left((\xi_i - \mathbb{E}(\xi_i))(\xi_j - \mathbb{E}(\xi_j)) \right) \right)_{1 \le i,j \le n} \\
& =
\left(\mathbb{C}(\xi_i,\xi_j)\right)_{1 \le i,j \le n}. \\
\end{split}
\end{align}

\noindent (2) Mit den Eigenschaften von Erwartungswerten  gilt
\begin{align}
\begin{split}
\mathbb{C}(\xi)
& = \mathbb{E}\left((\xi - \mathbb{E}(\xi))(\xi - \mathbb{E}(\xi))^T \right)                                          \\
& = \mathbb{E}\left(\xi\xi^T - \xi\mathbb{E}(\xi)^T - \mathbb{E}(\xi)\xi^T + \mathbb{E}(\xi)\mathbb{E}(\xi)^T  \right) \\
& = \mathbb{E}\left(\xi\xi^T\right) - \mathbb{E}(\xi)\mathbb{E}(\xi)^T - \mathbb{E}(\xi)\mathbb{E}(\xi)^T + \mathbb{E}(\xi)\mathbb{E}(\xi)^T  \\
& = \mathbb{E}\left(\xi\xi^T\right) - \mathbb{E}(\xi)\mathbb{E}(\xi)^T.  \\
\end{split}
\end{align}

\noindent (3) Mit den Eigenschaften von Erwartungswerten gilt
\begin{align}
\begin{split}
\mathbb{C}(A\xi+b)
& = \mathbb{E}\left((A\xi+b-\mathbb{E}(A\xi+b))(A\xi+b-\mathbb{E}(A\xi+b))^T \right)  \\
& = \mathbb{E}\left((A\xi+b-A\mathbb{E}(\xi)-b)(A\xi+b-A\mathbb{E}(\xi)-b)^T \right)  \\
& = \mathbb{E}\left((A(\xi-\mathbb{E}(\xi)))(A(\xi-\mathbb{E}(\xi)))^T \right)        \\
& = \mathbb{E}\left(A(\xi-\mathbb{E}(\xi))(\xi-\mathbb{E}(\xi))^T A^T\right)          \\
& = A\mathbb{E}\left((\xi-\mathbb{E}(\xi))(\xi-\mathbb{E}(\xi))^T\right)A^T           \\
& = A\mathbb{C}(\xi)A^T.                                                               \\
\end{split}
\end{align}


\noindent (4) Die Symmetrie von $\mathbb{C}(\xi)$ folgt aus der Symmetrie der Kovarianz einer Zufallsvariable mit
\begin{equation}
\mathbb{C}(\xi_i,\xi_j) = \mathbb{C}(\xi_j, \xi_i) \mbox{ für alle } i = 1,...,m, j = 1,...,m.
\end{equation}
Um die positive Semidefinitheit von $\mathbb{C}(\xi)$ nachzuweisen, ist zu zeigen, dass
$a^T\mathbb{C}(\xi)a \ge 0$ für alle $a\in \mathbb{R}^m$ mit $a \neq 0_m$. Sei also
$a \in \mathbb{R}^m$ mit $a\neq 0$. Dann gilt mit Aussage (3) für $A := a^T \in \mathbb{R}^{1\times m}$,
dass
\begin{equation}
a^T\mathbb{C}(\xi)a = \mathbb{C}(a^T\xi).
\end{equation}
Weiterhin gilt mit der Definition der Kovarianzmatrix aber, dass
\begin{equation}
\mathbb{C}(a^T\xi)
= \mathbb{E}\left(\left(a^T\xi-\mathbb{E}(a^T\xi)\right)^2\right)
= \mathbb{V}\left(a^T\xi\right).
\end{equation}
Da mit den Eigenschaften der Varianz die Varianz der Zufallsvariable $a^T\xi$ aber immer nichtnegativ ist, folgt
\begin{equation}
a^T\mathbb{C}(\xi)a = \mathbb{V}(a^T\xi)\ge 0
\end{equation}
und damit die positive Semidefinitheit von $\mathbb{C}(\xi)$.
:::



Die Diagonalelemente von $\mathbb{C}(\xi)$ sind die Varianzen der Komponenten von $\xi$, da
\begin{equation}
\mathbb{V}(\xi_i) = \mathbb{C}(\xi_i,\xi_i) \mbox{ für } i = 1,...m.
\end{equation}
Eigenschaften (2) und (3) sind im Wesentlichen analog zu den Eigenschaften der Varianz.



Die Kovarianzmatrix eines Zufallsvektors $\xi$ ist also die Matrix der Kovarianzen
der Komponenten von $\xi$. Damit ist auch die Kovarianzmatrix direkt im Sinne
des Begriffs der Kovarianz von Zufallsvektoren gegeben. Da die Kovarianz einer
Zufallsvariable mit sich selbst bekanntlich ihre Varianz ist, enthält die
Kovarianzmatrix auf ihrer Diagonalen die Varianzen der Komponenten von $\xi$.

Folgendes Theorem dokumentiert eine Schreibweise für die Kovarianzmatrix eines
partitionierten Zufallsvektors im Sinne von Erwartungswerten von Zufallsvektorprodukten
an, die zum Beispiel im Rahmen der Kanonischen Korrelationsanalyse hilfreich ist.

:::{#thm-kovarianzmatrizen-von-zufallsvektoren}
## Kovarianzmatrizen von Zufallsvektoren

Es seien
\begin{equation}
\zeta = \begin{pmatrix} \xi \\ \upsilon \end{pmatrix}
\mbox{ mit }
\mathbb{E}(\zeta)  := 0_m
\end{equation}
ein $m_\xi + m_\upsilon$-dimensionaler Zufallsvektor und sein Erwartungswertvektor,
respektive. Dann kann die $m \times m$ Kovarianzmatrix von $\zeta$ geschrieben werden als
\begin{equation}
\mathbb{C}(\zeta) =
\begin{pmatrix}
\Sigma_{\xi\xi} & \Sigma_{\xi_1\xi_2} \\
\Sigma_{\upsilon\xi} & \Sigma_{\upsilon\upsilon} \\
\end{pmatrix}
\in \mathbb{R}^{m \times m}
\end{equation}
wobei
\begin{align}
\begin{split}
\Sigma_{\xi\xi}   & := \mathbb{E}\left(\xi\xi^T  \right) \in \mathbb{R}^{m_\xi  \times m_\xi}\\
\Sigma_{\xi_1\xi_2}  & := \mathbb{E}\left(\xi_1\xi_2^T \right) \in \mathbb{R}^{m_\xi  \times m_\upsilon}\\
\Sigma_{\upsilon\xi}  & := \mathbb{E}\left(\upsilon\xi^T \right) \in \mathbb{R}^{m_\upsilon \times m_\xi}\\
\Sigma_{\upsilon\upsilon} & := \mathbb{E}\left(\upsilon\upsilon^T\right) \in \mathbb{R}^{m_\xi  \times m_\upsilon}
\end{split}
\end{align}
:::

:::{.proof}
Nach Definition der Kovarianzmatrix eines Zufallsvektors gilt
\begin{align}
\begin{split}
\mathbb{C}(z)
& = \mathbb{E}\left((\zeta - \mathbb{E}(\zeta))(\zeta - \mathbb{E}(\zeta))^T \right) \\
& = \mathbb{E}\left((\zeta - 0_m)(\zeta - 0_m)^T \right) \\
& = \mathbb{E}\left(\zeta\zeta^T\right)\\
& = \mathbb{E}\left(\begin{pmatrix} \xi \\ \upsilon \end{pmatrix} \begin{pmatrix} \xi^T & \upsilon^T \end{pmatrix} \right) \\
& = \mathbb{E}\left(\begin{pmatrix} \xi\xi^T & \xi_1\xi_2^T \\ \upsilon\xi^T & \upsilon\upsilon^T \end{pmatrix}\right)
\\
& =
\begin{pmatrix}
\mathbb{E}\left(\xi\xi^T\right)   & \mathbb{E}\left(\xi_1\xi_2^T\right) \\
\mathbb{E}\left(\upsilon\xi^T\right)  & \mathbb{E}\left(\upsilon\upsilon^T\right)
\end{pmatrix}
\\
& =
\begin{pmatrix}
\Sigma_{\xi\xi}   & \Sigma_{\xi_1\xi_2}  \\
\Sigma_{\upsilon\xi}  & \Sigma_{\upsilon\upsilon} \\
\end{pmatrix}
\end{split}
\end{align}
:::

Schließlich ist man in manchen Anwendungen an einer normalisierten, maßstabsunabhängigen
Repräsentation der Kovarianzen eines Zufallsvektors interessiert. Wie im univariaten
Fall bietet sich hierfür die Normalisierung der Kovarianz zweier Zufallsvariablen
mithilfe ihrer jeweiligen Varianzen im Sinne einer Korrelation an. Diese Überlegung
führt auf den Begriff der *Korrelationsmatrix* eines Zufallsvektors.

:::{#def-korrelationsmatrix}
## Korrelationsmatrix
$\xi$ sei ein $n$-dimensionaler Zufallsvektor. Dann ist die *Korrelationsmatrix*
von $\xi$ definiert als die $n \times n$ Matrix
\begin{equation}
\mathbb{R}(\xi)
:= \left(\rho_{ij} \right)_{1 \le i,j\le n}
 = \left(\frac{\mathbb{C}(\xi_i,\xi_j)}{\sqrt{\mathbb{V}(\xi_i)}\sqrt{\mathbb{V}(\xi_j)}}\right)_{1 \le i,j\le n}.
\end{equation}
:::

Da es sich bei den Varianzen der Komponenten von $\xi$ um die Diagonalelemente
der Kovarianzmatrix von $\xi$ handelt, ist die Korrelationsmatrix natürlich in
der Kovarianzmatrix implizit. Weiterhin gelten, wie immer für Korrelationen, für
die Einträge $\rho_{ij}, 1 \le i,j \le n$ der Korrelationsmatrix, dass
\begin{equation}
\rho_{ij} \in [-1,1] \mbox{ für } 1 \le i,j \in n \mbox{ und } \rho_{ii} = 1 \mbox{ für } 1 \le i \le n.
\end{equation}


## Selbstkontrollfragen {.unnumbered .unlisted}
\footnotesize

1. Geben Sie die Definition von Kovarianz und Korrelation zweier Zufallsvariablen wieder.
1. Erläutern Sie die Definition von Kovarianz und Korrelation zweier Zufallsvariablen.
1. Geben Sie das Theorem zur Symmetrie von Kovarianz und Korrelation wieder.
1. Geben Sie das Theorem zur Kovarianz und Korrelation bei linear-affinen Transformation wieder.
1. Erläutern Sie das Theorem zur Kovarianz und Korrelation bei linear-affinen Transformation.
1. Geben Sie das Theorem zu den Varianzen spezieller Linearkombinationen von Zufallsvariablen wieder.
1. Geben Sie das Theorem zur Korrelation und Unabhängigkeit von Zufallsvariablen wieder.

## Lösungen {.unnumbered .unlisted}

1. Siehe @def-kovarianz-und-korrelation-zweier-zufallsvariablen.
1. Siehe Erläuterungen zu @def-kovarianz-und-korrelation-zweier-zufallsvariablen und @exm-kovarianz-zweier-diskreter-zufallsvariablen.
1. Siehe @thm-symmetrie-von-kovarianz-und-korrelation.
1. Siehe @thm-kovarianz-und-korrelation-bei-linear-affiner-transformation.
1. Siehe Erläuterungen zu @thm-kovarianz-und-korrelation-bei-linear-affiner-transformation.
1. Siehe @thm-varianzen-spezieller-linearkombinationen-von-zufallsvariablen.
1. Siehe @thm-korrelation-und-unabhängigkeit-von-zufallsvariablen.